package modules

import (
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/accessorialchargerepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/accountingcontrolrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/accountsreceivablerepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/accounttyperepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/ailogrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/apikeyrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/assignmentrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/auditdlqrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/auditrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/billingcontrolrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/billingqueuefilterpresetrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/billingqueuerepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/commodityrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/customerpaymentrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/customerrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/customfieldrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/customfieldvaluerepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/databasesessionrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/dataentrycontrolrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/datarententionrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/dispatchcontrolrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/distanceoverriderepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/documentaiextractionrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/documentcontentrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/documentcontrolrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/documentpacketrulerepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/documentparsingrulerepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/documentrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/documentsearchprojectionrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/documentshipmentdraftrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/documenttyperepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/documentuploadrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/dothazmatreferencerepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/equipmentcontinuityrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/equipmentmanufacturerrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/equipmenttyperepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/fiscalperiodrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/fiscalyearrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/fleetcoderepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/formulatemplaterepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/formulatemplateversionrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/glaccountrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/glbalancerepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/hazardousmaterialrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/hazmatsegregationrulerepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/holdreasonrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/integrationrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/invoiceadjustmentcontrolrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/invoiceadjustmentrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/invoicerepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/journalentryrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/journalpostingrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/journalreversalrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/journalsourcerepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/locationcategoryrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/locationrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/m2msync"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/manualjournalrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/notificationrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/organizationrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/pagefavoriterepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/roleassignmentrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/rolerepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/sequenceconfigrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/servicetyperepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/shipmentadditionalchargerepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/shipmentcommentrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/shipmentcommodityrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/shipmentcontrolrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/shipmentholdrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/shipmentimportchatrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/shipmentmoverepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/shipmentrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/shipmenttyperepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/ssoconfigrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/tableconfigurationrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/tcaallowlistrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/tcasubscriptionrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/tractorrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/trailerrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/userrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/usstaterepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/workerptorepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/workerrepository"
	"github.com/emoss08/trenova/pkg/seqgen"
	"go.uber.org/fx"
)

var PostgresRepositoryModule = fx.Module("postgres-repositories", fx.Provide(
	m2msync.NewSyncer,
	organizationrepository.New,
	ssoconfigrepository.New,
	userrepository.New,
	formulatemplaterepository.New,
	formulatemplateversionrepository.New,
	tableconfigurationrepository.New,
	pagefavoriterepository.New,
	billingqueuefilterpresetrepository.New,
	equipmentmanufacturerrepository.New,
	equipmenttyperepository.New,
	equipmentcontinuityrepository.New,
	fleetcoderepository.New,
	glbalancerepository.New,
	tractorrepository.New,
	trailerrepository.New,
	workerrepository.New,
	workerptorepository.New,
	auditdlqrepository.New,
	auditrepository.New,
	dataentrycontrolrepository.New,
	datarententionrepository.New,
	dispatchcontrolrepository.New,
	documentcontrolrepository.New,
	documentparsingrulerepository.New,
	documentpacketrulerepository.New,
	rolerepository.New,
	roleassignmentrepository.New,
	usstaterepository.New,
	customfieldrepository.New,
	customfieldvaluerepository.New,
	databasesessionrepository.New,
	documentrepository.New,
	documentaiextractionrepository.New,
	documentcontentrepository.New,
	documentsearchprojectionrepository.New,
	documentshipmentdraftrepository.New,
	documentuploadrepository.New,
	accessorialchargerepository.New,
	assignmentrepository.New,
	servicetyperepository.New,
	sequenceconfigrepository.New,
	shipmentcontrolrepository.New,
	shipmentadditionalchargerepository.New,
	shipmentcommodityrepository.New,
	shipmentcommentrepository.New,
	shipmentholdrepository.New,
	shipmentimportchatrepository.New,
	shipmentmoverepository.New,
	seqgen.NewSequenceStore,
	seqgen.NewFormatProvider,
	seqgen.NewGenerator,
	shipmentrepository.New,
	shipmenttyperepository.New,
	hazardousmaterialrepository.New,
	hazmatsegregationrulerepository.New,
	dothazmatreferencerepository.New,
	commodityrepository.New,
	customerpaymentrepository.New,
	customerrepository.New,
	accountingcontrolrepository.New,
	accountsreceivablerepository.New,
	accounttyperepository.New,
	apikeyrepository.New,
	glaccountrepository.New,
	fiscalyearrepository.New,
	fiscalperiodrepository.New,
	locationcategoryrepository.New,
	locationrepository.New,
	documenttyperepository.New,
	holdreasonrepository.New,
	integrationrepository.New,
	invoiceadjustmentcontrolrepository.New,
	invoiceadjustmentrepository.New,
	invoicerepository.New,
	journalentryrepository.New,
	journalpostingrepository.New,
	journalreversalrepository.New,
	journalsourcerepository.New,
	manualjournalrepository.New,
	billingcontrolrepository.New,
	billingqueuerepository.New,
	distanceoverriderepository.New,
	tcasubscriptionrepository.New,
	tcaallowlistrepository.New,
	notificationrepository.New,
	ailogrepository.New,
))
