package modules

import (
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/accessorialchargerepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/accountingcontrolrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/accountsreceivablerepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/accounttyperepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/ailogrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/apikeyrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/assignmentrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/auditdlqrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/auditrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/bankreceiptbatchrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/bankreceiptrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/bankreceiptworkitemrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/billingcontrolrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/billingqueuefilterpresetrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/billingqueuerepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/commodityrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/costingrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/customerledgerrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/customerpaymentrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/customerrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/customfieldrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/customfieldvaluerepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/databasesessionrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/dataentrycontrolrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/datarententionrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/dispatchcontrolrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/distancecalculationrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/distancecontrolrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/distanceoverriderepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/distanceprofilerepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/documentaiextractionrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/documentcontentrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/documentcontrolrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/documentpacketrulerepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/documentparsingrulerepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/documentrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/documentsearchprojectionrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/documentshipmentdraftrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/documenttyperepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/documentuploadrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/dothazmatreferencerepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/edicarrierinvoicerepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/edicommunicationprofilerepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/ediconnectionrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/edicontrolnumberrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/edidocumenttyperepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/ediinboundfilerepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/edimappingprofilerepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/edimessagerepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/edipartnerdocumentprofilerepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/edipartnerrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/edipartnersettingrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/edishipmentlinkrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/edisourcecontextrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/editemplaterepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/editenderchangerepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/editenderrecipientrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/editestcaserepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/editransferchangerepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/editransferrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/emailrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/equipmentcontinuityrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/equipmentmanufacturerrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/equipmenttyperepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/exchangeraterepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/fiscalperiodrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/fiscalyearrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/fleetcoderepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/formulatemplaterepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/formulatemplateversionrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/fuelsurchargerepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/glaccountrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/glbalancerepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/hazardousmaterialrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/hazmatsegregationrulerepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/holdreasonrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/iamrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/integrationrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/invoiceadjustmentcontrolrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/invoiceadjustmentrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/invoicerepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/journalentryrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/journalpostingrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/journalreversalrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/journalsourcerepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/locationcategoryrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/locationrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/m2msync"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/manualjournalrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/notificationrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/orderrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/organizationrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/pagefavoriterepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/ratetablerepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/rbacrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/reportrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/roleassignmentrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/rolerepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/sequenceconfigrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/servicefailurereasoncoderepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/servicefailurerepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/servicetyperepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/shipmentadditionalchargerepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/shipmentcommentrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/shipmentcommodityrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/shipmentcontrolrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/shipmenteventrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/shipmentholdrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/shipmentimportchatrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/shipmentmoverepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/shipmentrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/shipmenttyperepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/sidebarpreferencerepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/ssoconfigrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/storedmileagerepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/tableconfigurationrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/tcaallowlistrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/tcasubscriptionrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/tenantprovisioningrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/tenantsyncrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/tractorrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/trailerrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/userrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/usstaterepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/weatheralertrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/workerptorepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/workerrepository"
	"github.com/emoss08/trenova/pkg/seqgen"
	"go.uber.org/fx"
)

var PostgresRepositoryModule = fx.Module("postgres-repositories", fx.Provide(
	m2msync.NewSyncer,
	tenantsyncrepository.New,
	tenantprovisioningrepository.New,
	organizationrepository.New,
	iamrepository.New,
	ssoconfigrepository.New,
	userrepository.New,
	formulatemplaterepository.New,
	formulatemplateversionrepository.New,
	ratetablerepository.New,
	tableconfigurationrepository.New,
	pagefavoriterepository.New,
	reportrepository.NewDefinitionRepository,
	reportrepository.NewRunRepository,
	reportrepository.NewScheduleRepository,
	sidebarpreferencerepository.New,
	billingqueuefilterpresetrepository.New,
	equipmentmanufacturerrepository.New,
	equipmenttyperepository.New,
	equipmentcontinuityrepository.New,
	fleetcoderepository.New,
	glbalancerepository.New,
	tractorrepository.New,
	trailerrepository.New,
	workerrepository.New,
	weatheralertrepository.New,
	workerptorepository.New,
	auditdlqrepository.New,
	auditrepository.New,
	dataentrycontrolrepository.New,
	datarententionrepository.New,
	dispatchcontrolrepository.New,
	documentcontrolrepository.New,
	documentparsingrulerepository.New,
	documentpacketrulerepository.New,
	rbacrepository.New,
	rolerepository.New,
	roleassignmentrepository.New,
	usstaterepository.New,
	customfieldrepository.New,
	customfieldvaluerepository.New,
	databasesessionrepository.New,
	documentrepository.New,
	documentaiextractionrepository.New,
	documentcontentrepository.New,
	documentsearchprojectionrepository.New,
	documentshipmentdraftrepository.New,
	documentuploadrepository.New,
	accessorialchargerepository.New,
	assignmentrepository.New,
	bankreceiptrepository.New,
	bankreceiptbatchrepository.New,
	bankreceiptworkitemrepository.New,
	servicetyperepository.New,
	orderrepository.New,
	servicefailurereasoncoderepository.New,
	servicefailurerepository.New,
	sequenceconfigrepository.New,
	shipmentcontrolrepository.New,
	shipmentadditionalchargerepository.New,
	shipmentcommodityrepository.New,
	shipmentcommentrepository.New,
	shipmenteventrepository.New,
	shipmentholdrepository.New,
	shipmentimportchatrepository.New,
	shipmentmoverepository.New,
	seqgen.NewSequenceStore,
	seqgen.NewFormatProvider,
	seqgen.NewGenerator,
	shipmentrepository.New,
	shipmenttyperepository.New,
	hazardousmaterialrepository.New,
	hazmatsegregationrulerepository.New,
	dothazmatreferencerepository.New,
	edipartnerrepository.New,
	edimappingprofilerepository.New,
	editransferrepository.New,
	ediconnectionrepository.New,
	edicommunicationprofilerepository.New,
	edishipmentlinkrepository.New,
	editransferchangerepository.New,
	editenderrecipientrepository.New,
	editenderchangerepository.New,
	edidocumenttyperepository.New,
	edisourcecontextrepository.New,
	edipartnersettingrepository.New,
	editemplaterepository.New,
	edipartnerdocumentprofilerepository.New,
	edicontrolnumberrepository.New,
	edimessagerepository.New,
	editestcaserepository.New,
	ediinboundfilerepository.New,
	edicarrierinvoicerepository.New,
	commodityrepository.New,
	customerpaymentrepository.New,
	customerledgerrepository.New,
	customerrepository.New,
	accountingcontrolrepository.New,
	accountsreceivablerepository.New,
	accountsreceivablerepository.NewAnalytics,
	accounttyperepository.New,
	apikeyrepository.New,
	glaccountrepository.New,
	fiscalyearrepository.New,
	fiscalperiodrepository.New,
	locationcategoryrepository.New,
	locationrepository.New,
	documenttyperepository.New,
	holdreasonrepository.New,
	integrationrepository.New,
	emailrepository.New,
	invoiceadjustmentcontrolrepository.New,
	invoiceadjustmentrepository.New,
	invoicerepository.New,
	journalentryrepository.New,
	journalpostingrepository.New,
	journalreversalrepository.New,
	journalsourcerepository.New,
	manualjournalrepository.New,
	billingcontrolrepository.New,
	costingrepository.New,
	costingrepository.NewActuals,
	billingqueuerepository.New,
	distancecalculationrepository.New,
	distancecontrolrepository.New,
	distanceoverriderepository.New,
	distanceprofilerepository.New,
	storedmileagerepository.New,
	exchangeraterepository.New,
	fuelsurchargerepository.NewIndexRepository,
	fuelsurchargerepository.NewPriceRepository,
	fuelsurchargerepository.NewProgramRepository,
	tcasubscriptionrepository.New,
	tcaallowlistrepository.New,
	notificationrepository.New,
	ailogrepository.New,
))
