CREATE TABLE "invoices"(
    "id" varchar(100) NOT NULL,
    "organization_id" varchar(100) NOT NULL,
    "business_unit_id" varchar(100) NOT NULL,
    "billing_queue_item_id" varchar(100) NOT NULL,
    "shipment_id" varchar(100) NOT NULL,
    "customer_id" varchar(100) NOT NULL,
    "number" varchar(100) NOT NULL,
    "bill_type" varchar(50) NOT NULL,
    "status" varchar(50) NOT NULL DEFAULT 'Draft',
    "payment_term" varchar(50) NOT NULL,
    "currency_code" varchar(3) NOT NULL DEFAULT 'USD',
    "invoice_date" bigint NOT NULL,
    "due_date" bigint,
    "posted_at" bigint,
    "shipment_pro_number" varchar(100),
    "shipment_bol" varchar(100),
    "service_date" bigint,
    "bill_to_name" varchar(255) NOT NULL,
    "bill_to_code" varchar(50),
    "bill_to_address_line_1" varchar(255),
    "bill_to_address_line_2" varchar(255),
    "bill_to_city" varchar(100),
    "bill_to_state" varchar(100),
    "bill_to_postal_code" varchar(20),
    "bill_to_country" varchar(100),
    "subtotal_amount" numeric(19,4) NOT NULL DEFAULT 0,
    "other_amount" numeric(19,4) NOT NULL DEFAULT 0,
    "total_amount" numeric(19,4) NOT NULL DEFAULT 0,
    "version" bigint NOT NULL DEFAULT 0,
    "created_at" bigint NOT NULL DEFAULT extract(epoch from current_timestamp)::bigint,
    "updated_at" bigint NOT NULL DEFAULT extract(epoch from current_timestamp)::bigint,
    CONSTRAINT "pk_invoices" PRIMARY KEY ("id", "organization_id", "business_unit_id"),
    CONSTRAINT "fk_invoices_organization" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE,
    CONSTRAINT "fk_invoices_business_unit" FOREIGN KEY ("business_unit_id") REFERENCES "business_units"("id") ON DELETE CASCADE,
    CONSTRAINT "fk_invoices_billing_queue_item" FOREIGN KEY ("billing_queue_item_id", "organization_id", "business_unit_id") REFERENCES "billing_queue_items"("id", "organization_id", "business_unit_id") ON DELETE RESTRICT,
    CONSTRAINT "fk_invoices_shipment" FOREIGN KEY ("shipment_id", "organization_id", "business_unit_id") REFERENCES "shipments"("id", "organization_id", "business_unit_id") ON DELETE RESTRICT,
    CONSTRAINT "fk_invoices_customer" FOREIGN KEY ("customer_id", "organization_id", "business_unit_id") REFERENCES "customers"("id", "organization_id", "business_unit_id") ON DELETE RESTRICT,
    CONSTRAINT "uk_invoices_billing_queue_item" UNIQUE ("billing_queue_item_id", "organization_id", "business_unit_id"),
    CONSTRAINT "uk_invoices_number" UNIQUE ("organization_id", "business_unit_id", "number")
);

CREATE TABLE "invoice_lines"(
    "id" varchar(100) NOT NULL,
    "organization_id" varchar(100) NOT NULL,
    "business_unit_id" varchar(100) NOT NULL,
    "invoice_id" varchar(100) NOT NULL,
    "line_number" integer NOT NULL,
    "type" varchar(50) NOT NULL,
    "description" text NOT NULL,
    "quantity" numeric(19,4) NOT NULL DEFAULT 0,
    "unit_price" numeric(19,4) NOT NULL DEFAULT 0,
    "amount" numeric(19,4) NOT NULL DEFAULT 0,
    "version" bigint NOT NULL DEFAULT 0,
    "created_at" bigint NOT NULL DEFAULT extract(epoch from current_timestamp)::bigint,
    "updated_at" bigint NOT NULL DEFAULT extract(epoch from current_timestamp)::bigint,
    CONSTRAINT "pk_invoice_lines" PRIMARY KEY ("id", "organization_id", "business_unit_id"),
    CONSTRAINT "fk_invoice_lines_invoice" FOREIGN KEY ("invoice_id", "organization_id", "business_unit_id") REFERENCES "invoices"("id", "organization_id", "business_unit_id") ON DELETE CASCADE,
    CONSTRAINT "uk_invoice_lines_number" UNIQUE ("invoice_id", "organization_id", "business_unit_id", "line_number")
);

CREATE INDEX "idx_invoices_tenant_status" ON "invoices"("organization_id", "business_unit_id", "status");
CREATE INDEX "idx_invoices_shipment" ON "invoices"("organization_id", "business_unit_id", "shipment_id");
CREATE INDEX "idx_invoice_lines_invoice" ON "invoice_lines"("invoice_id", "organization_id", "business_unit_id");
