# Generated by Django 4.1.7 on 2023-02-18 16:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("location", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="locationcontact",
            new_name="location_co_name_e20d46_idx",
            old_name="location_lo_name_81e740_idx",
        ),
        migrations.AlterModelTable(
            name="location",
            table="location",
        ),
        migrations.AlterModelTable(
            name="locationcategory",
            table="location_category",
        ),
        migrations.AlterModelTable(
            name="locationcomment",
            table="location_comment",
        ),
        migrations.AlterModelTable(
            name="locationcontact",
            table="location_contact",
        ),
    ]
