# Generated by Django 4.1.2 on 2022-11-03 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("control_file", "0003_commenttype"),
        ("location", "0002_alter_location_depot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="locationcomment",
            name="comment_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="location_comments",
                related_query_name="location_comment",
                to="control_file.commenttype",
                verbose_name="Comment Type",
            ),
        ),
        migrations.DeleteModel(
            name="LocationCommentType",
        ),
    ]
