// Code generated by buncolgen. DO NOT EDIT.
//
// This file contains type-safe database helpers for Bun ORM entities.
// All column expressions are pre-computed at init time — method calls are
// zero-allocation string returns. See [Column] for the full method reference.

package buncolgen

import (
	"github.com/emoss08/trenova/pkg/dbtype"
	"github.com/emoss08/trenova/pkg/domaintypes"
	"github.com/emoss08/trenova/pkg/pagination"
	"github.com/uptrace/bun"
)

// Ensure imports are used.
var (
	_ dbtype.Operator
	_ domaintypes.FieldFilter
	_ pagination.TenantInfo
	_ *bun.SelectQuery
	_ *bun.UpdateQuery
	_ *bun.DeleteQuery
)

// ---------------------------------------------------------------------------
// AccountType — table "account_types", alias "at"
// ---------------------------------------------------------------------------

// AccountTypeTable holds the table name, alias, and primary key columns
// for the "account_types" table. The alias "at" is used in all generated
// SQL fragments (e.g. "at.id = ?").
var AccountTypeTable = TableInfo{
	Name:       "account_types",
	Alias:      "at",
	PrimaryKey: []string{"id", "business_unit_id", "organization_id"},
}

// AccountTypeColumns provides type-safe column references for the "account_types" table.
// Each field is a [Column] whose methods return pre-computed SQL fragments.
//
// Use String() when Bun manages the alias (model-aware queries):
//
//	q.Column(AccountTypeColumns.ID.String())
//	// SELECT at.id FROM account_types AS at
//
// Use expression helpers for raw WHERE/ORDER BY clauses:
//
//	q.Where(AccountTypeColumns.ID.Eq(), id)           // WHERE at.id = ?
//	q.Order(AccountTypeColumns.CreatedAt.OrderDesc())  // ORDER BY at.created_at DESC
var AccountTypeColumns = struct {
	ID             Column // "id" → qualified: "at.id"
	BusinessUnitID Column // "business_unit_id" → qualified: "at.business_unit_id"
	OrganizationID Column // "organization_id" → qualified: "at.organization_id"
	Status         Column // "status" → qualified: "at.status"
	Code           Column // "code" → qualified: "at.code"
	Name           Column // "name" → qualified: "at.name"
	Description    Column // "description" → qualified: "at.description"
	Category       Column // "category" → qualified: "at.category"
	Color          Column // "color" → qualified: "at.color"
	IsSystem       Column // "is_system" → qualified: "at.is_system"
	Version        Column // "version" → qualified: "at.version"
	CreatedAt      Column // "created_at" → qualified: "at.created_at"
	UpdatedAt      Column // "updated_at" → qualified: "at.updated_at"
	SearchVector   Column // "search_vector" → qualified: "at.search_vector"
	Rank           Column // "rank" → qualified: "at.rank"
}{
	ID:             NewColumn("id", "at"),
	BusinessUnitID: NewColumn("business_unit_id", "at"),
	OrganizationID: NewColumn("organization_id", "at"),
	Status:         NewColumn("status", "at"),
	Code:           NewColumn("code", "at"),
	Name:           NewColumn("name", "at"),
	Description:    NewColumn("description", "at"),
	Category:       NewColumn("category", "at"),
	Color:          NewColumn("color", "at"),
	IsSystem:       NewColumn("is_system", "at"),
	Version:        NewColumn("version", "at"),
	CreatedAt:      NewColumn("created_at", "at"),
	UpdatedAt:      NewColumn("updated_at", "at"),
	SearchVector:   NewColumn("search_vector", "at"),
	Rank:           NewColumn("rank", "at"),
}

// AccountTypeFieldMap maps JSON API field names to database column names.
// The QueryBuilder uses this to translate filter/sort requests from the frontend
// (e.g. "firstName") into SQL column references (e.g. "first_name") without reflection.
// This is returned by AccountType.GetStaticFieldMap().
var AccountTypeFieldMap = map[string]string{
	"id":             "id",
	"businessUnitId": "business_unit_id",
	"organizationId": "organization_id",
	"status":         "status",
	"code":           "code",
	"name":           "name",
	"description":    "description",
	"category":       "category",
	"color":          "color",
	"isSystem":       "is_system",
	"version":        "version",
	"createdAt":      "created_at",
	"updatedAt":      "updated_at",
}

// AccountTypeInsertableColumns lists column names suitable for INSERT statements on the "account_types" table.
// Excludes scanonly columns (e.g. search_vector, rank) that are computed by PostgreSQL.
var AccountTypeInsertableColumns = []string{
	"id",
	"business_unit_id",
	"organization_id",
	"status",
	"code",
	"name",
	"description",
	"category",
	"color",
	"is_system",
	"version",
	"created_at",
	"updated_at",
}

// AccountTypeRelations provides type-safe names for Bun eager-loading.
// Use these instead of string literals in .Relation() calls to get compile-time safety.
//
//	q.Relation(AccountTypeRelations.BusinessUnit)
//	// Bun eager-loads the BusinessUnit association via a separate query
var AccountTypeRelations = struct {
	BusinessUnit string
	Organization string
}{
	BusinessUnit: "BusinessUnit",
	Organization: "Organization",
}

// AccountTypeScopeTenant restricts a query to a single tenant by adding:
//
//	WHERE at.organization_id = ? AND at.business_unit_id = ?
//
// Returns the same *bun.SelectQuery so it can be chained fluently:
//
//	buncolgen.AccountTypeScopeTenant(sq, ti).
//		Where(buncolgen.AccountTypeColumns.ID.Eq(), id)
func AccountTypeScopeTenant(q *bun.SelectQuery, ti pagination.TenantInfo) *bun.SelectQuery {
	return ScopeTenant(q, AccountTypeColumns.OrganizationID, AccountTypeColumns.BusinessUnitID, ti)
}

// AccountTypeScopeTenantUpdate restricts an update query to a single tenant.
// Use this inside UpdateQuery.WhereGroup callbacks:
//
//	WhereGroup(" AND ", func(uq *bun.UpdateQuery) *bun.UpdateQuery {
//		return buncolgen.AccountTypeScopeTenantUpdate(uq, req.TenantInfo).
//			Where(buncolgen.AccountTypeColumns.ID.In(), bun.List(ids))
//	})
func AccountTypeScopeTenantUpdate(q *bun.UpdateQuery, ti pagination.TenantInfo) *bun.UpdateQuery {
	return ScopeTenantUpdate(q, AccountTypeColumns.OrganizationID, AccountTypeColumns.BusinessUnitID, ti)
}

// AccountTypeScopeTenantDelete restricts a delete query to a single tenant.
// Use this inside DeleteQuery.WhereGroup callbacks:
//
//	WhereGroup(" AND ", func(dq *bun.DeleteQuery) *bun.DeleteQuery {
//		return buncolgen.AccountTypeScopeTenantDelete(dq, req.TenantInfo).
//			Where(buncolgen.AccountTypeColumns.ID.Eq(), id)
//	})
func AccountTypeScopeTenantDelete(q *bun.DeleteQuery, ti pagination.TenantInfo) *bun.DeleteQuery {
	return ScopeTenantDelete(q, AccountTypeColumns.OrganizationID, AccountTypeColumns.BusinessUnitID, ti)
}

// AccountTypeApplyTenant returns a closure for SelectQuery.Apply() that scopes to a single tenant.
// Use this instead of wrapping ScopeTenant in an anonymous function:
//
//	q.Apply(buncolgen.AccountTypeApplyTenant(tenantInfo))
func AccountTypeApplyTenant(ti pagination.TenantInfo) func(*bun.SelectQuery) *bun.SelectQuery {
	return ApplyTenant(AccountTypeColumns.OrganizationID, AccountTypeColumns.BusinessUnitID, ti)
}

// AccountTypeFilter builds [domaintypes.FieldFilter] values using the correct JSON
// field names for the "account_types" table. Pass these to the QueryBuilder's ApplyFilters.
//
// The JSON field name is baked in — you only provide the operator and value:
//
//	AccountTypeFilter.ID(dbtype.OpEq, value)
//	// produces FieldFilter{Field: "id", Operator: "eq", Value: value}
var AccountTypeFilter = struct {
	ID             func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "id" → DB: "id"
	BusinessUnitID func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "businessUnitId" → DB: "business_unit_id"
	OrganizationID func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "organizationId" → DB: "organization_id"
	Status         func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "status" → DB: "status"
	Code           func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "code" → DB: "code"
	Name           func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "name" → DB: "name"
	Description    func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "description" → DB: "description"
	Category       func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "category" → DB: "category"
	Color          func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "color" → DB: "color"
	IsSystem       func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "isSystem" → DB: "is_system"
	Version        func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "version" → DB: "version"
	CreatedAt      func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "createdAt" → DB: "created_at"
	UpdatedAt      func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "updatedAt" → DB: "updated_at"
}{
	ID: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("id", op, value)
	},
	BusinessUnitID: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("businessUnitId", op, value)
	},
	OrganizationID: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("organizationId", op, value)
	},
	Status: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("status", op, value)
	},
	Code: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("code", op, value)
	},
	Name: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("name", op, value)
	},
	Description: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("description", op, value)
	},
	Category: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("category", op, value)
	},
	Color: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("color", op, value)
	},
	IsSystem: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("isSystem", op, value)
	},
	Version: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("version", op, value)
	},
	CreatedAt: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("createdAt", op, value)
	},
	UpdatedAt: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("updatedAt", op, value)
	},
}
