// Code generated by buncolgen. DO NOT EDIT.
//
// This file contains type-safe database helpers for Bun ORM entities.
// All column expressions are pre-computed at init time — method calls are
// zero-allocation string returns. See [Column] for the full method reference.

package buncolgen

import (
	"github.com/emoss08/trenova/pkg/dbtype"
	"github.com/emoss08/trenova/pkg/domaintypes"
	"github.com/emoss08/trenova/pkg/pagination"
	"github.com/uptrace/bun"
)

// Ensure imports are used.
var (
	_ dbtype.Operator
	_ domaintypes.FieldFilter
	_ pagination.TenantInfo
	_ *bun.SelectQuery
	_ *bun.UpdateQuery
	_ *bun.DeleteQuery
)

// ---------------------------------------------------------------------------
// Reversal — table "journal_reversals", alias "jr"
// ---------------------------------------------------------------------------

// ReversalTable holds the table name, alias, and primary key columns
// for the "journal_reversals" table. The alias "jr" is used in all generated
// SQL fragments (e.g. "jr.id = ?").
var ReversalTable = TableInfo{
	Name:       "journal_reversals",
	Alias:      "jr",
	PrimaryKey: []string{"id", "organization_id", "business_unit_id"},
}

// ReversalColumns provides type-safe column references for the "journal_reversals" table.
// Each field is a [Column] whose methods return pre-computed SQL fragments.
//
// Use String() when Bun manages the alias (model-aware queries):
//
//	q.Column(ReversalColumns.ID.String())
//	// SELECT jr.id FROM journal_reversals AS jr
//
// Use expression helpers for raw WHERE/ORDER BY clauses:
//
//	q.Where(ReversalColumns.ID.Eq(), id)           // WHERE jr.id = ?
//	q.Order(ReversalColumns.CreatedAt.OrderDesc())  // ORDER BY jr.created_at DESC
var ReversalColumns = struct {
	ID                      Column // "id" → qualified: "jr.id"
	OrganizationID          Column // "organization_id" → qualified: "jr.organization_id"
	BusinessUnitID          Column // "business_unit_id" → qualified: "jr.business_unit_id"
	OriginalJournalEntryID  Column // "original_journal_entry_id" → qualified: "jr.original_journal_entry_id"
	ReversalJournalEntryID  Column // "reversal_journal_entry_id" → qualified: "jr.reversal_journal_entry_id"
	PostedBatchID           Column // "posted_batch_id" → qualified: "jr.posted_batch_id"
	Status                  Column // "status" → qualified: "jr.status"
	RequestedAccountingDate Column // "requested_accounting_date" → qualified: "jr.requested_accounting_date"
	ResolvedFiscalYearID    Column // "resolved_fiscal_year_id" → qualified: "jr.resolved_fiscal_year_id"
	ResolvedFiscalPeriodID  Column // "resolved_fiscal_period_id" → qualified: "jr.resolved_fiscal_period_id"
	ReasonCode              Column // "reason_code" → qualified: "jr.reason_code"
	ReasonText              Column // "reason_text" → qualified: "jr.reason_text"
	RequestedByID           Column // "requested_by_id" → qualified: "jr.requested_by_id"
	ApprovedByID            Column // "approved_by_id" → qualified: "jr.approved_by_id"
	ApprovedAt              Column // "approved_at" → qualified: "jr.approved_at"
	RejectedByID            Column // "rejected_by_id" → qualified: "jr.rejected_by_id"
	RejectedAt              Column // "rejected_at" → qualified: "jr.rejected_at"
	RejectionReason         Column // "rejection_reason" → qualified: "jr.rejection_reason"
	CancelledByID           Column // "cancelled_by_id" → qualified: "jr.cancelled_by_id"
	CancelledAt             Column // "cancelled_at" → qualified: "jr.cancelled_at"
	CancelReason            Column // "cancel_reason" → qualified: "jr.cancel_reason"
	PostedByID              Column // "posted_by_id" → qualified: "jr.posted_by_id"
	PostedAt                Column // "posted_at" → qualified: "jr.posted_at"
	CreatedAt               Column // "created_at" → qualified: "jr.created_at"
	UpdatedAt               Column // "updated_at" → qualified: "jr.updated_at"
	Version                 Column // "version" → qualified: "jr.version"
}{
	ID:                      NewColumn("id", "jr"),
	OrganizationID:          NewColumn("organization_id", "jr"),
	BusinessUnitID:          NewColumn("business_unit_id", "jr"),
	OriginalJournalEntryID:  NewColumn("original_journal_entry_id", "jr"),
	ReversalJournalEntryID:  NewColumn("reversal_journal_entry_id", "jr"),
	PostedBatchID:           NewColumn("posted_batch_id", "jr"),
	Status:                  NewColumn("status", "jr"),
	RequestedAccountingDate: NewColumn("requested_accounting_date", "jr"),
	ResolvedFiscalYearID:    NewColumn("resolved_fiscal_year_id", "jr"),
	ResolvedFiscalPeriodID:  NewColumn("resolved_fiscal_period_id", "jr"),
	ReasonCode:              NewColumn("reason_code", "jr"),
	ReasonText:              NewColumn("reason_text", "jr"),
	RequestedByID:           NewColumn("requested_by_id", "jr"),
	ApprovedByID:            NewColumn("approved_by_id", "jr"),
	ApprovedAt:              NewColumn("approved_at", "jr"),
	RejectedByID:            NewColumn("rejected_by_id", "jr"),
	RejectedAt:              NewColumn("rejected_at", "jr"),
	RejectionReason:         NewColumn("rejection_reason", "jr"),
	CancelledByID:           NewColumn("cancelled_by_id", "jr"),
	CancelledAt:             NewColumn("cancelled_at", "jr"),
	CancelReason:            NewColumn("cancel_reason", "jr"),
	PostedByID:              NewColumn("posted_by_id", "jr"),
	PostedAt:                NewColumn("posted_at", "jr"),
	CreatedAt:               NewColumn("created_at", "jr"),
	UpdatedAt:               NewColumn("updated_at", "jr"),
	Version:                 NewColumn("version", "jr"),
}

// ReversalFieldMap maps JSON API field names to database column names.
// The QueryBuilder uses this to translate filter/sort requests from the frontend
// (e.g. "firstName") into SQL column references (e.g. "first_name") without reflection.
// This is returned by Reversal.GetStaticFieldMap().
var ReversalFieldMap = map[string]string{
	"id":                      "id",
	"organizationId":          "organization_id",
	"businessUnitId":          "business_unit_id",
	"originalJournalEntryId":  "original_journal_entry_id",
	"reversalJournalEntryId":  "reversal_journal_entry_id",
	"postedBatchId":           "posted_batch_id",
	"status":                  "status",
	"requestedAccountingDate": "requested_accounting_date",
	"resolvedFiscalYearId":    "resolved_fiscal_year_id",
	"resolvedFiscalPeriodId":  "resolved_fiscal_period_id",
	"reasonCode":              "reason_code",
	"reasonText":              "reason_text",
	"requestedById":           "requested_by_id",
	"approvedById":            "approved_by_id",
	"approvedAt":              "approved_at",
	"rejectedById":            "rejected_by_id",
	"rejectedAt":              "rejected_at",
	"rejectionReason":         "rejection_reason",
	"cancelledById":           "cancelled_by_id",
	"cancelledAt":             "cancelled_at",
	"cancelReason":            "cancel_reason",
	"postedById":              "posted_by_id",
	"postedAt":                "posted_at",
	"createdAt":               "created_at",
	"updatedAt":               "updated_at",
	"version":                 "version",
}

// ReversalInsertableColumns lists column names suitable for INSERT statements on the "journal_reversals" table.
// Excludes scanonly columns (e.g. search_vector, rank) that are computed by PostgreSQL.
var ReversalInsertableColumns = []string{
	"id",
	"organization_id",
	"business_unit_id",
	"original_journal_entry_id",
	"reversal_journal_entry_id",
	"posted_batch_id",
	"status",
	"requested_accounting_date",
	"resolved_fiscal_year_id",
	"resolved_fiscal_period_id",
	"reason_code",
	"reason_text",
	"requested_by_id",
	"approved_by_id",
	"approved_at",
	"rejected_by_id",
	"rejected_at",
	"rejection_reason",
	"cancelled_by_id",
	"cancelled_at",
	"cancel_reason",
	"posted_by_id",
	"posted_at",
	"created_at",
	"updated_at",
	"version",
}

// ReversalScopeTenant restricts a query to a single tenant by adding:
//
//	WHERE jr.organization_id = ? AND jr.business_unit_id = ?
//
// Returns the same *bun.SelectQuery so it can be chained fluently:
//
//	buncolgen.ReversalScopeTenant(sq, ti).
//		Where(buncolgen.ReversalColumns.ID.Eq(), id)
func ReversalScopeTenant(q *bun.SelectQuery, ti pagination.TenantInfo) *bun.SelectQuery {
	return ScopeTenant(q, ReversalColumns.OrganizationID, ReversalColumns.BusinessUnitID, ti)
}

// ReversalScopeTenantUpdate restricts an update query to a single tenant.
// Use this inside UpdateQuery.WhereGroup callbacks:
//
//	WhereGroup(" AND ", func(uq *bun.UpdateQuery) *bun.UpdateQuery {
//		return buncolgen.ReversalScopeTenantUpdate(uq, req.TenantInfo).
//			Where(buncolgen.ReversalColumns.ID.In(), bun.List(ids))
//	})
func ReversalScopeTenantUpdate(q *bun.UpdateQuery, ti pagination.TenantInfo) *bun.UpdateQuery {
	return ScopeTenantUpdate(q, ReversalColumns.OrganizationID, ReversalColumns.BusinessUnitID, ti)
}

// ReversalScopeTenantDelete restricts a delete query to a single tenant.
// Use this inside DeleteQuery.WhereGroup callbacks:
//
//	WhereGroup(" AND ", func(dq *bun.DeleteQuery) *bun.DeleteQuery {
//		return buncolgen.ReversalScopeTenantDelete(dq, req.TenantInfo).
//			Where(buncolgen.ReversalColumns.ID.Eq(), id)
//	})
func ReversalScopeTenantDelete(q *bun.DeleteQuery, ti pagination.TenantInfo) *bun.DeleteQuery {
	return ScopeTenantDelete(q, ReversalColumns.OrganizationID, ReversalColumns.BusinessUnitID, ti)
}

// ReversalApplyTenant returns a closure for SelectQuery.Apply() that scopes to a single tenant.
// Use this instead of wrapping ScopeTenant in an anonymous function:
//
//	q.Apply(buncolgen.ReversalApplyTenant(tenantInfo))
func ReversalApplyTenant(ti pagination.TenantInfo) func(*bun.SelectQuery) *bun.SelectQuery {
	return ApplyTenant(ReversalColumns.OrganizationID, ReversalColumns.BusinessUnitID, ti)
}

// ReversalFilter builds [domaintypes.FieldFilter] values using the correct JSON
// field names for the "journal_reversals" table. Pass these to the QueryBuilder's ApplyFilters.
//
// The JSON field name is baked in — you only provide the operator and value:
//
//	ReversalFilter.ID(dbtype.OpEq, value)
//	// produces FieldFilter{Field: "id", Operator: "eq", Value: value}
var ReversalFilter = struct {
	ID                      func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "id" → DB: "id"
	OrganizationID          func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "organizationId" → DB: "organization_id"
	BusinessUnitID          func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "businessUnitId" → DB: "business_unit_id"
	OriginalJournalEntryID  func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "originalJournalEntryId" → DB: "original_journal_entry_id"
	ReversalJournalEntryID  func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "reversalJournalEntryId" → DB: "reversal_journal_entry_id"
	PostedBatchID           func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "postedBatchId" → DB: "posted_batch_id"
	Status                  func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "status" → DB: "status"
	RequestedAccountingDate func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "requestedAccountingDate" → DB: "requested_accounting_date"
	ResolvedFiscalYearID    func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "resolvedFiscalYearId" → DB: "resolved_fiscal_year_id"
	ResolvedFiscalPeriodID  func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "resolvedFiscalPeriodId" → DB: "resolved_fiscal_period_id"
	ReasonCode              func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "reasonCode" → DB: "reason_code"
	ReasonText              func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "reasonText" → DB: "reason_text"
	RequestedByID           func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "requestedById" → DB: "requested_by_id"
	ApprovedByID            func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "approvedById" → DB: "approved_by_id"
	ApprovedAt              func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "approvedAt" → DB: "approved_at"
	RejectedByID            func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "rejectedById" → DB: "rejected_by_id"
	RejectedAt              func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "rejectedAt" → DB: "rejected_at"
	RejectionReason         func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "rejectionReason" → DB: "rejection_reason"
	CancelledByID           func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "cancelledById" → DB: "cancelled_by_id"
	CancelledAt             func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "cancelledAt" → DB: "cancelled_at"
	CancelReason            func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "cancelReason" → DB: "cancel_reason"
	PostedByID              func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "postedById" → DB: "posted_by_id"
	PostedAt                func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "postedAt" → DB: "posted_at"
	CreatedAt               func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "createdAt" → DB: "created_at"
	UpdatedAt               func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "updatedAt" → DB: "updated_at"
	Version                 func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "version" → DB: "version"
}{
	ID: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("id", op, value)
	},
	OrganizationID: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("organizationId", op, value)
	},
	BusinessUnitID: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("businessUnitId", op, value)
	},
	OriginalJournalEntryID: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("originalJournalEntryId", op, value)
	},
	ReversalJournalEntryID: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("reversalJournalEntryId", op, value)
	},
	PostedBatchID: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("postedBatchId", op, value)
	},
	Status: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("status", op, value)
	},
	RequestedAccountingDate: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("requestedAccountingDate", op, value)
	},
	ResolvedFiscalYearID: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("resolvedFiscalYearId", op, value)
	},
	ResolvedFiscalPeriodID: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("resolvedFiscalPeriodId", op, value)
	},
	ReasonCode: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("reasonCode", op, value)
	},
	ReasonText: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("reasonText", op, value)
	},
	RequestedByID: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("requestedById", op, value)
	},
	ApprovedByID: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("approvedById", op, value)
	},
	ApprovedAt: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("approvedAt", op, value)
	},
	RejectedByID: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("rejectedById", op, value)
	},
	RejectedAt: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("rejectedAt", op, value)
	},
	RejectionReason: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("rejectionReason", op, value)
	},
	CancelledByID: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("cancelledById", op, value)
	},
	CancelledAt: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("cancelledAt", op, value)
	},
	CancelReason: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("cancelReason", op, value)
	},
	PostedByID: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("postedById", op, value)
	},
	PostedAt: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("postedAt", op, value)
	},
	CreatedAt: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("createdAt", op, value)
	},
	UpdatedAt: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("updatedAt", op, value)
	},
	Version: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("version", op, value)
	},
}
