// Code generated by buncolgen. DO NOT EDIT.
//
// This file contains type-safe database helpers for Bun ORM entities.
// All column expressions are pre-computed at init time — method calls are
// zero-allocation string returns. See [Column] for the full method reference.

package buncolgen

import (
	"github.com/emoss08/trenova/pkg/dbtype"
	"github.com/emoss08/trenova/pkg/domaintypes"
	"github.com/emoss08/trenova/pkg/pagination"
	"github.com/uptrace/bun"
)

// Ensure imports are used.
var (
	_ dbtype.Operator
	_ domaintypes.FieldFilter
	_ pagination.TenantInfo
	_ *bun.SelectQuery
	_ *bun.UpdateQuery
	_ *bun.DeleteQuery
)

// ---------------------------------------------------------------------------
// UsState — table "us_states", alias "ust"
// ---------------------------------------------------------------------------

// UsStateTable holds the table name, alias, and primary key columns
// for the "us_states" table. The alias "ust" is used in all generated
// SQL fragments (e.g. "ust.id = ?").
var UsStateTable = TableInfo{
	Name:       "us_states",
	Alias:      "ust",
	PrimaryKey: []string{"id"},
}

// UsStateColumns provides type-safe column references for the "us_states" table.
// Each field is a [Column] whose methods return pre-computed SQL fragments.
//
// Use String() when Bun manages the alias (model-aware queries):
//
//	q.Column(UsStateColumns.ID.String())
//	// SELECT ust.id FROM us_states AS ust
//
// Use expression helpers for raw WHERE/ORDER BY clauses:
//
//	q.Where(UsStateColumns.ID.Eq(), id)           // WHERE ust.id = ?
//	q.Order(UsStateColumns.CreatedAt.OrderDesc())  // ORDER BY ust.created_at DESC
var UsStateColumns = struct {
	ID           Column // "id" → qualified: "ust.id"
	Name         Column // "name" → qualified: "ust.name"
	Abbreviation Column // "abbreviation" → qualified: "ust.abbreviation"
	CountryName  Column // "country_name" → qualified: "ust.country_name"
	CountryIso3  Column // "country_iso3" → qualified: "ust.country_iso3"
	CreatedAt    Column // "created_at" → qualified: "ust.created_at"
	UpdatedAt    Column // "updated_at" → qualified: "ust.updated_at"
}{
	ID:           NewColumn("id", "ust"),
	Name:         NewColumn("name", "ust"),
	Abbreviation: NewColumn("abbreviation", "ust"),
	CountryName:  NewColumn("country_name", "ust"),
	CountryIso3:  NewColumn("country_iso3", "ust"),
	CreatedAt:    NewColumn("created_at", "ust"),
	UpdatedAt:    NewColumn("updated_at", "ust"),
}

// UsStateFieldMap maps JSON API field names to database column names.
// The QueryBuilder uses this to translate filter/sort requests from the frontend
// (e.g. "firstName") into SQL column references (e.g. "first_name") without reflection.
// This is returned by UsState.GetStaticFieldMap().
var UsStateFieldMap = map[string]string{
	"id":           "id",
	"name":         "name",
	"abbreviation": "abbreviation",
	"countryName":  "country_name",
	"countryIso3":  "country_iso3",
	"createdAt":    "created_at",
	"updatedAt":    "updated_at",
}

// UsStateInsertableColumns lists column names suitable for INSERT statements on the "us_states" table.
// Excludes scanonly columns (e.g. search_vector, rank) that are computed by PostgreSQL.
var UsStateInsertableColumns = []string{
	"id",
	"name",
	"abbreviation",
	"country_name",
	"country_iso3",
	"created_at",
	"updated_at",
}

// UsStateFilter builds [domaintypes.FieldFilter] values using the correct JSON
// field names for the "us_states" table. Pass these to the QueryBuilder's ApplyFilters.
//
// The JSON field name is baked in — you only provide the operator and value:
//
//	UsStateFilter.ID(dbtype.OpEq, value)
//	// produces FieldFilter{Field: "id", Operator: "eq", Value: value}
var UsStateFilter = struct {
	ID           func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "id" → DB: "id"
	Name         func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "name" → DB: "name"
	Abbreviation func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "abbreviation" → DB: "abbreviation"
	CountryName  func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "countryName" → DB: "country_name"
	CountryIso3  func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "countryIso3" → DB: "country_iso3"
	CreatedAt    func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "createdAt" → DB: "created_at"
	UpdatedAt    func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "updatedAt" → DB: "updated_at"
}{
	ID: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("id", op, value)
	},
	Name: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("name", op, value)
	},
	Abbreviation: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("abbreviation", op, value)
	},
	CountryName: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("countryName", op, value)
	},
	CountryIso3: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("countryIso3", op, value)
	},
	CreatedAt: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("createdAt", op, value)
	},
	UpdatedAt: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("updatedAt", op, value)
	},
}
