// Code generated by buncolgen. DO NOT EDIT.
//
// This file contains type-safe database helpers for Bun ORM entities.
// All column expressions are pre-computed at init time — method calls are
// zero-allocation string returns. See [Column] for the full method reference.

package buncolgen

import (
	"github.com/emoss08/trenova/pkg/dbtype"
	"github.com/emoss08/trenova/pkg/domaintypes"
	"github.com/emoss08/trenova/pkg/pagination"
	"github.com/uptrace/bun"
)

// Ensure imports are used.
var (
	_ dbtype.Operator
	_ domaintypes.FieldFilter
	_ pagination.TenantInfo
	_ *bun.SelectQuery
	_ *bun.UpdateQuery
	_ *bun.DeleteQuery
)

// ---------------------------------------------------------------------------
// Activity — table "weather_alert_activities", alias "waa"
// ---------------------------------------------------------------------------

// ActivityTable holds the table name, alias, and primary key columns
// for the "weather_alert_activities" table. The alias "waa" is used in all generated
// SQL fragments (e.g. "waa.id = ?").
var ActivityTable = TableInfo{
	Name:       "weather_alert_activities",
	Alias:      "waa",
	PrimaryKey: []string{"id", "organization_id", "business_unit_id"},
}

// ActivityColumns provides type-safe column references for the "weather_alert_activities" table.
// Each field is a [Column] whose methods return pre-computed SQL fragments.
//
// Use String() when Bun manages the alias (model-aware queries):
//
//	q.Column(ActivityColumns.ID.String())
//	// SELECT waa.id FROM weather_alert_activities AS waa
//
// Use expression helpers for raw WHERE/ORDER BY clauses:
//
//	q.Where(ActivityColumns.ID.Eq(), id)           // WHERE waa.id = ?
//	q.Order(ActivityColumns.CreatedAt.OrderDesc())  // ORDER BY waa.created_at DESC
var ActivityColumns = struct {
	ID             Column // "id" → qualified: "waa.id"
	OrganizationID Column // "organization_id" → qualified: "waa.organization_id"
	BusinessUnitID Column // "business_unit_id" → qualified: "waa.business_unit_id"
	WeatherAlertID Column // "weather_alert_id" → qualified: "waa.weather_alert_id"
	ActivityType   Column // "activity_type" → qualified: "waa.activity_type"
	Timestamp      Column // "timestamp" → qualified: "waa.timestamp"
	Details        Column // "details" → qualified: "waa.details"
	CreatedAt      Column // "created_at" → qualified: "waa.created_at"
	UpdatedAt      Column // "updated_at" → qualified: "waa.updated_at"
}{
	ID:             NewColumn("id", "waa"),
	OrganizationID: NewColumn("organization_id", "waa"),
	BusinessUnitID: NewColumn("business_unit_id", "waa"),
	WeatherAlertID: NewColumn("weather_alert_id", "waa"),
	ActivityType:   NewColumn("activity_type", "waa"),
	Timestamp:      NewColumn("timestamp", "waa"),
	Details:        NewColumn("details", "waa"),
	CreatedAt:      NewColumn("created_at", "waa"),
	UpdatedAt:      NewColumn("updated_at", "waa"),
}

// ActivityFieldMap maps JSON API field names to database column names.
// The QueryBuilder uses this to translate filter/sort requests from the frontend
// (e.g. "firstName") into SQL column references (e.g. "first_name") without reflection.
// This is returned by Activity.GetStaticFieldMap().
var ActivityFieldMap = map[string]string{
	"id":             "id",
	"organizationId": "organization_id",
	"businessUnitId": "business_unit_id",
	"weatherAlertId": "weather_alert_id",
	"activityType":   "activity_type",
	"timestamp":      "timestamp",
	"details":        "details",
	"createdAt":      "created_at",
	"updatedAt":      "updated_at",
}

// ActivityInsertableColumns lists column names suitable for INSERT statements on the "weather_alert_activities" table.
// Excludes scanonly columns (e.g. search_vector, rank) that are computed by PostgreSQL.
var ActivityInsertableColumns = []string{
	"id",
	"organization_id",
	"business_unit_id",
	"weather_alert_id",
	"activity_type",
	"timestamp",
	"details",
	"created_at",
	"updated_at",
}

// ActivityScopeTenant restricts a query to a single tenant by adding:
//
//	WHERE waa.organization_id = ? AND waa.business_unit_id = ?
//
// Returns the same *bun.SelectQuery so it can be chained fluently:
//
//	buncolgen.ActivityScopeTenant(sq, ti).
//		Where(buncolgen.ActivityColumns.ID.Eq(), id)
func ActivityScopeTenant(q *bun.SelectQuery, ti pagination.TenantInfo) *bun.SelectQuery {
	return ScopeTenant(q, ActivityColumns.OrganizationID, ActivityColumns.BusinessUnitID, ti)
}

// ActivityScopeTenantUpdate restricts an update query to a single tenant.
// Use this inside UpdateQuery.WhereGroup callbacks:
//
//	WhereGroup(" AND ", func(uq *bun.UpdateQuery) *bun.UpdateQuery {
//		return buncolgen.ActivityScopeTenantUpdate(uq, req.TenantInfo).
//			Where(buncolgen.ActivityColumns.ID.In(), bun.List(ids))
//	})
func ActivityScopeTenantUpdate(q *bun.UpdateQuery, ti pagination.TenantInfo) *bun.UpdateQuery {
	return ScopeTenantUpdate(q, ActivityColumns.OrganizationID, ActivityColumns.BusinessUnitID, ti)
}

// ActivityScopeTenantDelete restricts a delete query to a single tenant.
// Use this inside DeleteQuery.WhereGroup callbacks:
//
//	WhereGroup(" AND ", func(dq *bun.DeleteQuery) *bun.DeleteQuery {
//		return buncolgen.ActivityScopeTenantDelete(dq, req.TenantInfo).
//			Where(buncolgen.ActivityColumns.ID.Eq(), id)
//	})
func ActivityScopeTenantDelete(q *bun.DeleteQuery, ti pagination.TenantInfo) *bun.DeleteQuery {
	return ScopeTenantDelete(q, ActivityColumns.OrganizationID, ActivityColumns.BusinessUnitID, ti)
}

// ActivityApplyTenant returns a closure for SelectQuery.Apply() that scopes to a single tenant.
// Use this instead of wrapping ScopeTenant in an anonymous function:
//
//	q.Apply(buncolgen.ActivityApplyTenant(tenantInfo))
func ActivityApplyTenant(ti pagination.TenantInfo) func(*bun.SelectQuery) *bun.SelectQuery {
	return ApplyTenant(ActivityColumns.OrganizationID, ActivityColumns.BusinessUnitID, ti)
}

// ActivityFilter builds [domaintypes.FieldFilter] values using the correct JSON
// field names for the "weather_alert_activities" table. Pass these to the QueryBuilder's ApplyFilters.
//
// The JSON field name is baked in — you only provide the operator and value:
//
//	ActivityFilter.ID(dbtype.OpEq, value)
//	// produces FieldFilter{Field: "id", Operator: "eq", Value: value}
var ActivityFilter = struct {
	ID             func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "id" → DB: "id"
	OrganizationID func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "organizationId" → DB: "organization_id"
	BusinessUnitID func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "businessUnitId" → DB: "business_unit_id"
	WeatherAlertID func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "weatherAlertId" → DB: "weather_alert_id"
	ActivityType   func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "activityType" → DB: "activity_type"
	Timestamp      func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "timestamp" → DB: "timestamp"
	Details        func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "details" → DB: "details"
	CreatedAt      func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "createdAt" → DB: "created_at"
	UpdatedAt      func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "updatedAt" → DB: "updated_at"
}{
	ID: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("id", op, value)
	},
	OrganizationID: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("organizationId", op, value)
	},
	BusinessUnitID: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("businessUnitId", op, value)
	},
	WeatherAlertID: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("weatherAlertId", op, value)
	},
	ActivityType: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("activityType", op, value)
	},
	Timestamp: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("timestamp", op, value)
	},
	Details: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("details", op, value)
	},
	CreatedAt: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("createdAt", op, value)
	},
	UpdatedAt: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("updatedAt", op, value)
	},
}

// ---------------------------------------------------------------------------
// WeatherAlert — table "weather_alerts", alias "wa"
// ---------------------------------------------------------------------------

// WeatherAlertTable holds the table name, alias, and primary key columns
// for the "weather_alerts" table. The alias "wa" is used in all generated
// SQL fragments (e.g. "wa.id = ?").
var WeatherAlertTable = TableInfo{
	Name:       "weather_alerts",
	Alias:      "wa",
	PrimaryKey: []string{"id", "organization_id", "business_unit_id"},
}

// WeatherAlertColumns provides type-safe column references for the "weather_alerts" table.
// Each field is a [Column] whose methods return pre-computed SQL fragments.
//
// Use String() when Bun manages the alias (model-aware queries):
//
//	q.Column(WeatherAlertColumns.ID.String())
//	// SELECT wa.id FROM weather_alerts AS wa
//
// Use expression helpers for raw WHERE/ORDER BY clauses:
//
//	q.Where(WeatherAlertColumns.ID.Eq(), id)           // WHERE wa.id = ?
//	q.Order(WeatherAlertColumns.CreatedAt.OrderDesc())  // ORDER BY wa.created_at DESC
var WeatherAlertColumns = struct {
	ID             Column // "id" → qualified: "wa.id"
	OrganizationID Column // "organization_id" → qualified: "wa.organization_id"
	BusinessUnitID Column // "business_unit_id" → qualified: "wa.business_unit_id"
	NWSID          Column // "nws_id" → qualified: "wa.nws_id"
	Event          Column // "event" → qualified: "wa.event"
	Severity       Column // "severity" → qualified: "wa.severity"
	Urgency        Column // "urgency" → qualified: "wa.urgency"
	Certainty      Column // "certainty" → qualified: "wa.certainty"
	Headline       Column // "headline" → qualified: "wa.headline"
	Description    Column // "description" → qualified: "wa.description"
	Instruction    Column // "instruction" → qualified: "wa.instruction"
	AreaDesc       Column // "area_desc" → qualified: "wa.area_desc"
	Effective      Column // "effective" → qualified: "wa.effective"
	Expires        Column // "expires" → qualified: "wa.expires"
	Onset          Column // "onset" → qualified: "wa.onset"
	Ends           Column // "ends" → qualified: "wa.ends"
	Status         Column // "status" → qualified: "wa.status"
	MessageType    Column // "message_type" → qualified: "wa.message_type"
	SenderName     Column // "sender_name" → qualified: "wa.sender_name"
	Response       Column // "response" → qualified: "wa.response"
	Category       Column // "category" → qualified: "wa.category"
	AlertCategory  Column // "alert_category" → qualified: "wa.alert_category"
	Geometry       Column // "geometry" → qualified: "wa.geometry"
	FirstSeenAt    Column // "first_seen_at" → qualified: "wa.first_seen_at"
	LastUpdatedAt  Column // "last_updated_at" → qualified: "wa.last_updated_at"
	ExpiredAt      Column // "expired_at" → qualified: "wa.expired_at"
	Version        Column // "version" → qualified: "wa.version"
	CreatedAt      Column // "created_at" → qualified: "wa.created_at"
	UpdatedAt      Column // "updated_at" → qualified: "wa.updated_at"
}{
	ID:             NewColumn("id", "wa"),
	OrganizationID: NewColumn("organization_id", "wa"),
	BusinessUnitID: NewColumn("business_unit_id", "wa"),
	NWSID:          NewColumn("nws_id", "wa"),
	Event:          NewColumn("event", "wa"),
	Severity:       NewColumn("severity", "wa"),
	Urgency:        NewColumn("urgency", "wa"),
	Certainty:      NewColumn("certainty", "wa"),
	Headline:       NewColumn("headline", "wa"),
	Description:    NewColumn("description", "wa"),
	Instruction:    NewColumn("instruction", "wa"),
	AreaDesc:       NewColumn("area_desc", "wa"),
	Effective:      NewColumn("effective", "wa"),
	Expires:        NewColumn("expires", "wa"),
	Onset:          NewColumn("onset", "wa"),
	Ends:           NewColumn("ends", "wa"),
	Status:         NewColumn("status", "wa"),
	MessageType:    NewColumn("message_type", "wa"),
	SenderName:     NewColumn("sender_name", "wa"),
	Response:       NewColumn("response", "wa"),
	Category:       NewColumn("category", "wa"),
	AlertCategory:  NewColumn("alert_category", "wa"),
	Geometry:       NewColumn("geometry", "wa"),
	FirstSeenAt:    NewColumn("first_seen_at", "wa"),
	LastUpdatedAt:  NewColumn("last_updated_at", "wa"),
	ExpiredAt:      NewColumn("expired_at", "wa"),
	Version:        NewColumn("version", "wa"),
	CreatedAt:      NewColumn("created_at", "wa"),
	UpdatedAt:      NewColumn("updated_at", "wa"),
}

// WeatherAlertFieldMap maps JSON API field names to database column names.
// The QueryBuilder uses this to translate filter/sort requests from the frontend
// (e.g. "firstName") into SQL column references (e.g. "first_name") without reflection.
// This is returned by WeatherAlert.GetStaticFieldMap().
var WeatherAlertFieldMap = map[string]string{
	"id":             "id",
	"organizationId": "organization_id",
	"businessUnitId": "business_unit_id",
	"nwsId":          "nws_id",
	"event":          "event",
	"severity":       "severity",
	"urgency":        "urgency",
	"certainty":      "certainty",
	"headline":       "headline",
	"description":    "description",
	"instruction":    "instruction",
	"areaDesc":       "area_desc",
	"effective":      "effective",
	"expires":        "expires",
	"onset":          "onset",
	"ends":           "ends",
	"status":         "status",
	"messageType":    "message_type",
	"senderName":     "sender_name",
	"response":       "response",
	"category":       "category",
	"alertCategory":  "alert_category",
	"firstSeenAt":    "first_seen_at",
	"lastUpdatedAt":  "last_updated_at",
	"expiredAt":      "expired_at",
	"version":        "version",
	"createdAt":      "created_at",
	"updatedAt":      "updated_at",
}

// WeatherAlertInsertableColumns lists column names suitable for INSERT statements on the "weather_alerts" table.
// Excludes scanonly columns (e.g. search_vector, rank) that are computed by PostgreSQL.
var WeatherAlertInsertableColumns = []string{
	"id",
	"organization_id",
	"business_unit_id",
	"nws_id",
	"event",
	"severity",
	"urgency",
	"certainty",
	"headline",
	"description",
	"instruction",
	"area_desc",
	"effective",
	"expires",
	"onset",
	"ends",
	"status",
	"message_type",
	"sender_name",
	"response",
	"category",
	"alert_category",
	"first_seen_at",
	"last_updated_at",
	"expired_at",
	"version",
	"created_at",
	"updated_at",
}

// WeatherAlertScopeTenant restricts a query to a single tenant by adding:
//
//	WHERE wa.organization_id = ? AND wa.business_unit_id = ?
//
// Returns the same *bun.SelectQuery so it can be chained fluently:
//
//	buncolgen.WeatherAlertScopeTenant(sq, ti).
//		Where(buncolgen.WeatherAlertColumns.ID.Eq(), id)
func WeatherAlertScopeTenant(q *bun.SelectQuery, ti pagination.TenantInfo) *bun.SelectQuery {
	return ScopeTenant(q, WeatherAlertColumns.OrganizationID, WeatherAlertColumns.BusinessUnitID, ti)
}

// WeatherAlertScopeTenantUpdate restricts an update query to a single tenant.
// Use this inside UpdateQuery.WhereGroup callbacks:
//
//	WhereGroup(" AND ", func(uq *bun.UpdateQuery) *bun.UpdateQuery {
//		return buncolgen.WeatherAlertScopeTenantUpdate(uq, req.TenantInfo).
//			Where(buncolgen.WeatherAlertColumns.ID.In(), bun.List(ids))
//	})
func WeatherAlertScopeTenantUpdate(q *bun.UpdateQuery, ti pagination.TenantInfo) *bun.UpdateQuery {
	return ScopeTenantUpdate(q, WeatherAlertColumns.OrganizationID, WeatherAlertColumns.BusinessUnitID, ti)
}

// WeatherAlertScopeTenantDelete restricts a delete query to a single tenant.
// Use this inside DeleteQuery.WhereGroup callbacks:
//
//	WhereGroup(" AND ", func(dq *bun.DeleteQuery) *bun.DeleteQuery {
//		return buncolgen.WeatherAlertScopeTenantDelete(dq, req.TenantInfo).
//			Where(buncolgen.WeatherAlertColumns.ID.Eq(), id)
//	})
func WeatherAlertScopeTenantDelete(q *bun.DeleteQuery, ti pagination.TenantInfo) *bun.DeleteQuery {
	return ScopeTenantDelete(q, WeatherAlertColumns.OrganizationID, WeatherAlertColumns.BusinessUnitID, ti)
}

// WeatherAlertApplyTenant returns a closure for SelectQuery.Apply() that scopes to a single tenant.
// Use this instead of wrapping ScopeTenant in an anonymous function:
//
//	q.Apply(buncolgen.WeatherAlertApplyTenant(tenantInfo))
func WeatherAlertApplyTenant(ti pagination.TenantInfo) func(*bun.SelectQuery) *bun.SelectQuery {
	return ApplyTenant(WeatherAlertColumns.OrganizationID, WeatherAlertColumns.BusinessUnitID, ti)
}

// WeatherAlertFilter builds [domaintypes.FieldFilter] values using the correct JSON
// field names for the "weather_alerts" table. Pass these to the QueryBuilder's ApplyFilters.
//
// The JSON field name is baked in — you only provide the operator and value:
//
//	WeatherAlertFilter.ID(dbtype.OpEq, value)
//	// produces FieldFilter{Field: "id", Operator: "eq", Value: value}
var WeatherAlertFilter = struct {
	ID             func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "id" → DB: "id"
	OrganizationID func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "organizationId" → DB: "organization_id"
	BusinessUnitID func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "businessUnitId" → DB: "business_unit_id"
	NWSID          func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "nwsId" → DB: "nws_id"
	Event          func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "event" → DB: "event"
	Severity       func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "severity" → DB: "severity"
	Urgency        func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "urgency" → DB: "urgency"
	Certainty      func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "certainty" → DB: "certainty"
	Headline       func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "headline" → DB: "headline"
	Description    func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "description" → DB: "description"
	Instruction    func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "instruction" → DB: "instruction"
	AreaDesc       func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "areaDesc" → DB: "area_desc"
	Effective      func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "effective" → DB: "effective"
	Expires        func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "expires" → DB: "expires"
	Onset          func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "onset" → DB: "onset"
	Ends           func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "ends" → DB: "ends"
	Status         func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "status" → DB: "status"
	MessageType    func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "messageType" → DB: "message_type"
	SenderName     func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "senderName" → DB: "sender_name"
	Response       func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "response" → DB: "response"
	Category       func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "category" → DB: "category"
	AlertCategory  func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "alertCategory" → DB: "alert_category"
	FirstSeenAt    func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "firstSeenAt" → DB: "first_seen_at"
	LastUpdatedAt  func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "lastUpdatedAt" → DB: "last_updated_at"
	ExpiredAt      func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "expiredAt" → DB: "expired_at"
	Version        func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "version" → DB: "version"
	CreatedAt      func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "createdAt" → DB: "created_at"
	UpdatedAt      func(op dbtype.Operator, value any) domaintypes.FieldFilter // JSON: "updatedAt" → DB: "updated_at"
}{
	ID: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("id", op, value)
	},
	OrganizationID: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("organizationId", op, value)
	},
	BusinessUnitID: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("businessUnitId", op, value)
	},
	NWSID: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("nwsId", op, value)
	},
	Event: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("event", op, value)
	},
	Severity: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("severity", op, value)
	},
	Urgency: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("urgency", op, value)
	},
	Certainty: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("certainty", op, value)
	},
	Headline: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("headline", op, value)
	},
	Description: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("description", op, value)
	},
	Instruction: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("instruction", op, value)
	},
	AreaDesc: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("areaDesc", op, value)
	},
	Effective: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("effective", op, value)
	},
	Expires: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("expires", op, value)
	},
	Onset: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("onset", op, value)
	},
	Ends: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("ends", op, value)
	},
	Status: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("status", op, value)
	},
	MessageType: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("messageType", op, value)
	},
	SenderName: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("senderName", op, value)
	},
	Response: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("response", op, value)
	},
	Category: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("category", op, value)
	},
	AlertCategory: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("alertCategory", op, value)
	},
	FirstSeenAt: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("firstSeenAt", op, value)
	},
	LastUpdatedAt: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("lastUpdatedAt", op, value)
	},
	ExpiredAt: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("expiredAt", op, value)
	},
	Version: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("version", op, value)
	},
	CreatedAt: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("createdAt", op, value)
	},
	UpdatedAt: func(op dbtype.Operator, value any) domaintypes.FieldFilter {
		return NewFieldFilter("updatedAt", op, value)
	},
}
