# Generated by Django 4.1.4 on 2022-12-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0002_alter_chargetype_description_alter_chargetype_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentclassification",
            name="name",
            field=models.CharField(
                help_text="Document classification name",
                max_length=150,
                verbose_name="Name",
            ),
        ),
    ]
