# Generated by Django 4.1.6 on 2023-02-12 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_alter_billingcontrol_invoice_number_prefix"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingcontrol",
            name="invoice_due_after_days",
            field=models.PositiveIntegerField(
                default=30,
                help_text="Define the number of days after invoice date that an invoice is due.",
                verbose_name="Invoice Due After Days",
            ),
        ),
    ]
