# Generated by Django 4.1.5 on 2023-01-28 16:51

from django.db import migrations
import utils.models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0011_rename_auto_bill_order_billingcontrol_auto_bill_orders"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingcontrol",
            name="order_transfer_criteria",
            field=utils.models.ChoiceField(
                choices=[
                    ("READY_AND_COMPLETED", "Ready to bill & Completed"),
                    ("COMPLETED", "Completed"),
                    ("READY_TO_BILL", "Ready to bill"),
                ],
                default="READY_AND_COMPLETED",
                help_text="Define when an order can be transferred to billing.",
                max_length=19,
                verbose_name="Order Transfer Criteria",
            ),
        ),
    ]
