// Code generated by buncolgen. DO NOT EDIT.

package permission

import "github.com/emoss08/trenova/pkg/buncolgen"

// GetStaticFieldMap returns the pre-computed JSON→database column mapping for [ResourcePermission].
// This implements [querybuilder.StaticFieldMapper], allowing the QueryBuilder to use
// the generated [buncolgen.ResourcePermissionFieldMap] instead of parsing struct tags via reflection.
func (e *ResourcePermission) GetStaticFieldMap() map[string]string {
	return buncolgen.ResourcePermissionFieldMap
}

// GetStaticFieldMap returns the pre-computed JSON→database column mapping for [Role].
// This implements [querybuilder.StaticFieldMapper], allowing the QueryBuilder to use
// the generated [buncolgen.RoleFieldMap] instead of parsing struct tags via reflection.
func (e *Role) GetStaticFieldMap() map[string]string {
	return buncolgen.RoleFieldMap
}

// GetStaticFieldMap returns the pre-computed JSON→database column mapping for [RoleConstraint].
// This implements [querybuilder.StaticFieldMapper], allowing the QueryBuilder to use
// the generated [buncolgen.RoleConstraintFieldMap] instead of parsing struct tags via reflection.
func (e *RoleConstraint) GetStaticFieldMap() map[string]string {
	return buncolgen.RoleConstraintFieldMap
}

// GetStaticFieldMap returns the pre-computed JSON→database column mapping for [RoleConstraintRole].
// This implements [querybuilder.StaticFieldMapper], allowing the QueryBuilder to use
// the generated [buncolgen.RoleConstraintRoleFieldMap] instead of parsing struct tags via reflection.
func (e *RoleConstraintRole) GetStaticFieldMap() map[string]string {
	return buncolgen.RoleConstraintRoleFieldMap
}

// GetStaticFieldMap returns the pre-computed JSON→database column mapping for [RoleHierarchyEdge].
// This implements [querybuilder.StaticFieldMapper], allowing the QueryBuilder to use
// the generated [buncolgen.RoleHierarchyEdgeFieldMap] instead of parsing struct tags via reflection.
func (e *RoleHierarchyEdge) GetStaticFieldMap() map[string]string {
	return buncolgen.RoleHierarchyEdgeFieldMap
}

// GetStaticFieldMap returns the pre-computed JSON→database column mapping for [UserRoleAssignment].
// This implements [querybuilder.StaticFieldMapper], allowing the QueryBuilder to use
// the generated [buncolgen.UserRoleAssignmentFieldMap] instead of parsing struct tags via reflection.
func (e *UserRoleAssignment) GetStaticFieldMap() map[string]string {
	return buncolgen.UserRoleAssignmentFieldMap
}
