package permission

func (r *Registry) registerAccountingResources() {
	_ = r.Register(&ResourceDefinition{
		Resource:           ResourceAccountingControl.String(),
		DisplayName:        "Accounting Control",
		Description:        "Accounting policy and posting control configuration",
		Category:           "Accounting",
		Operations:         standardOps,
		DefaultSensitivity: SensitivityRestricted,
	})

	_ = r.Register(&ResourceDefinition{
		Resource:    ResourceAccountingIntegration.String(),
		DisplayName: "Accounting Integration",
		Description: "The connection to the organization's accounting system and how Trenova maps to it",
		Category:    "Accounting",
		Operations: []OperationDefinition{
			{
				Operation:   OpRead,
				DisplayName: "Read",
				Description: "View the accounting connection, its health and its mappings",
			},
			{
				Operation:   OpUpdate,
				DisplayName: "Update",
				Description: "Change sync settings and mappings",
			},
			{
				Operation:   OpManage,
				DisplayName: "Manage",
				Description: "Connect or disconnect the accounting system",
			},
		},
		DefaultSensitivity: SensitivityRestricted,
		FieldSensitivities: map[string]FieldSensitivity{
			"id":                  SensitivityInternal,
			"businessUnitId":      SensitivityInternal,
			"organizationId":      SensitivityInternal,
			"integrationType":     SensitivityInternal,
			"status":              SensitivityInternal,
			"externalCompanyName": SensitivityInternal,
			"lastSuccessAt":       SensitivityInternal,
			"lastCheckedAt":       SensitivityInternal,
			"createdAt":           SensitivityInternal,
			"updatedAt":           SensitivityInternal,
		},
	})

	_ = r.Register(&ResourceDefinition{
		Resource:    ResourceAccountingSync.String(),
		DisplayName: "Accounting Sync",
		Description: "What has been sent to the accounting system, what failed and where the two disagree",
		Category:    "Accounting",
		Operations: []OperationDefinition{
			{
				Operation:   OpRead,
				DisplayName: "Read",
				Description: "View sync status, records and differences",
			},
			{
				Operation:   OpUpdate,
				DisplayName: "Update",
				Description: "Retry, skip and resolve sync records and differences",
			},
			{Operation: OpExport, DisplayName: "Export", Description: "Export sync records"},
		},
		DefaultSensitivity: SensitivityInternal,
	})

	_ = r.Register(&ResourceDefinition{
		Resource:           ResourceBillingControl.String(),
		DisplayName:        "Billing Control",
		Description:        "Billing policy and workflow control configuration",
		Category:           "Accounting",
		Operations:         standardOps,
		DefaultSensitivity: SensitivityRestricted,
	})

	_ = r.Register(&ResourceDefinition{
		Resource:           ResourceCostingControl.String(),
		DisplayName:        "Costing Control",
		Description:        "Cost per mile and shipment profitability estimation configuration",
		Category:           "Accounting",
		Operations:         standardOps,
		DefaultSensitivity: SensitivityRestricted,
	})

	_ = r.Register(&ResourceDefinition{
		Resource:           ResourceInvoiceAdjustmentControl.String(),
		DisplayName:        "Invoice Adjustment Control",
		Description:        "Invoice adjustment policy and approval control configuration",
		Category:           "Accounting",
		Operations:         standardOps,
		DefaultSensitivity: SensitivityRestricted,
	})

	_ = r.Register(&ResourceDefinition{
		Resource:           ResourceAccountType.String(),
		DisplayName:        "Account Type",
		Description:        "Chart of accounts type definitions",
		Category:           "Accounting",
		Operations:         standardOps,
		DefaultSensitivity: SensitivityInternal,
	})

	_ = r.Register(&ResourceDefinition{
		Resource:           ResourceGeneralLedgerAccount.String(),
		DisplayName:        "General Ledger Account",
		Description:        "GL account management",
		Category:           "Accounting",
		Operations:         standardOpsWithDelete,
		DefaultSensitivity: SensitivityRestricted,
		FieldSensitivities: map[string]FieldSensitivity{
			"accountCode":    SensitivityInternal,
			"accountTypeId":  SensitivityInternal,
			"allowManualJe":  SensitivityInternal,
			"businessUnitId": SensitivityInternal,
			"createdAt":      SensitivityInternal,
			"description":    SensitivityInternal,
			"id":             SensitivityInternal,
			"isSystem":       SensitivityInternal,
			"name":           SensitivityInternal,
			"organizationId": SensitivityInternal,
			"parentId":       SensitivityInternal,
			"requireProject": SensitivityInternal,
			"status":         SensitivityInternal,
			"updatedAt":      SensitivityInternal,
			"version":        SensitivityInternal,
			"creditBalance":  SensitivityRestricted,
			"currentBalance": SensitivityRestricted,
			"debitBalance":   SensitivityRestricted,
		},
	})

	_ = r.Register(&ResourceDefinition{
		Resource:           ResourceDivisionCode.String(),
		DisplayName:        "Division Code",
		Description:        "Division code definitions",
		Category:           "Accounting",
		Operations:         standardOps,
		DefaultSensitivity: SensitivityInternal,
	})

	_ = r.Register(&ResourceDefinition{
		Resource:    ResourceFiscalYear.String(),
		DisplayName: "Fiscal Year",
		Description: "Fiscal year management",
		Category:    "Accounting",
		Operations: []OperationDefinition{
			{Operation: OpRead, DisplayName: "Read", Description: "View fiscal years"},
			{Operation: OpCreate, DisplayName: "Create", Description: "Create fiscal years"},
			{Operation: OpUpdate, DisplayName: "Update", Description: "Modify fiscal years"},
			{Operation: OpDelete, DisplayName: "Delete", Description: "Delete fiscal years"},
			{Operation: OpClose, DisplayName: "Close", Description: "Close fiscal years"},
			{
				Operation:   OpReopen,
				DisplayName: "Reopen",
				Description: "Reopen closed fiscal years and reverse their closing entries",
			},
			{Operation: OpLock, DisplayName: "Lock", Description: "Lock fiscal years"},
			{Operation: OpUnlock, DisplayName: "Unlock", Description: "Unlock fiscal years"},
			{Operation: OpActivate, DisplayName: "Activate", Description: "Activate fiscal years"},
			{
				Operation:   OpExport,
				DisplayName: "Export",
				Description: "Export fiscal calendar data",
			},
		},
		DefaultSensitivity: SensitivityRestricted,
		FieldSensitivities: map[string]FieldSensitivity{
			"allowAdjustingEntries": SensitivityInternal,
			"businessUnitId":        SensitivityInternal,
			"closedAt":              SensitivityInternal,
			"closedById":            SensitivityInternal,
			"createdAt":             SensitivityInternal,
			"description":           SensitivityInternal,
			"endDate":               SensitivityInternal,
			"id":                    SensitivityInternal,
			"isCalendarYear":        SensitivityInternal,
			"isCurrent":             SensitivityInternal,
			"lockedAt":              SensitivityInternal,
			"lockedById":            SensitivityInternal,
			"name":                  SensitivityInternal,
			"organizationId":        SensitivityInternal,
			"reopenedAt":            SensitivityInternal,
			"reopenedById":          SensitivityInternal,
			"startDate":             SensitivityInternal,
			"status":                SensitivityInternal,
			"updatedAt":             SensitivityInternal,
			"version":               SensitivityInternal,
			"year":                  SensitivityInternal,
			"reopenReason":          SensitivityRestricted,
		},
	})

	_ = r.Register(&ResourceDefinition{
		Resource:    ResourceFiscalPeriod.String(),
		DisplayName: "Fiscal Period",
		Description: "Fiscal period management",
		Category:    "Accounting",
		Operations: []OperationDefinition{
			{Operation: OpRead, DisplayName: "Read", Description: "View fiscal periods"},
			{Operation: OpCreate, DisplayName: "Create", Description: "Create fiscal periods"},
			{Operation: OpUpdate, DisplayName: "Update", Description: "Modify fiscal periods"},
			{Operation: OpDelete, DisplayName: "Delete", Description: "Delete fiscal periods"},
			{Operation: OpClose, DisplayName: "Close", Description: "Close fiscal periods"},
			{Operation: OpReopen, DisplayName: "Reopen", Description: "Reopen fiscal periods"},
			{Operation: OpLock, DisplayName: "Lock", Description: "Lock fiscal periods"},
			{Operation: OpUnlock, DisplayName: "Unlock", Description: "Unlock fiscal periods"},
			{
				Operation:   OpActivate,
				DisplayName: "Open",
				Description: "Open inactive fiscal periods",
			},
			{
				Operation:   OpExport,
				DisplayName: "Export",
				Description: "Export fiscal calendar data",
			},
		},
		DefaultSensitivity: SensitivityRestricted,
		FieldSensitivities: map[string]FieldSensitivity{
			"adjustmentDeadline":    SensitivityInternal,
			"allowAdjustingEntries": SensitivityInternal,
			"businessUnitId":        SensitivityInternal,
			"closedAt":              SensitivityInternal,
			"closedById":            SensitivityInternal,
			"createdAt":             SensitivityInternal,
			"endDate":               SensitivityInternal,
			"fiscalYearId":          SensitivityInternal,
			"id":                    SensitivityInternal,
			"isAdjusting":           SensitivityInternal,
			"lockedAt":              SensitivityInternal,
			"lockedById":            SensitivityInternal,
			"name":                  SensitivityInternal,
			"organizationId":        SensitivityInternal,
			"periodNumber":          SensitivityInternal,
			"periodType":            SensitivityInternal,
			"reopenedAt":            SensitivityInternal,
			"reopenedById":          SensitivityInternal,
			"startDate":             SensitivityInternal,
			"status":                SensitivityInternal,
			"updatedAt":             SensitivityInternal,
			"version":               SensitivityInternal,
			"reopenReason":          SensitivityRestricted,
		},
	})

	_ = r.Register(&ResourceDefinition{
		Resource:    ResourceManualJournal.String(),
		DisplayName: "Manual Journal",
		Description: "Manual journal request workflow and approvals",
		Category:    "Accounting",
		Operations: []OperationDefinition{
			{Operation: OpRead, DisplayName: "Read", Description: "View manual journals"},
			{
				Operation:   OpCreate,
				DisplayName: "Create",
				Description: "Create manual journal drafts",
			},
			{Operation: OpUpdate, DisplayName: "Update", Description: "Edit manual journal drafts"},
			{Operation: OpApprove, DisplayName: "Approve", Description: "Approve manual journals"},
			{Operation: OpReject, DisplayName: "Reject", Description: "Reject manual journals"},
			{
				Operation:   OpSubmit,
				DisplayName: "Submit",
				Description: "Submit manual journals for approval",
			},
			{Operation: OpCancel, DisplayName: "Cancel", Description: "Cancel manual journals"},
		},
		DefaultSensitivity: SensitivityRestricted,
		FieldSensitivities: map[string]FieldSensitivity{
			"accountingDate":          SensitivityInternal,
			"approvedAt":              SensitivityInternal,
			"approvedById":            SensitivityInternal,
			"businessUnitId":          SensitivityInternal,
			"cancelledAt":             SensitivityInternal,
			"cancelledById":           SensitivityInternal,
			"createdAt":               SensitivityInternal,
			"createdById":             SensitivityInternal,
			"currencyCode":            SensitivityInternal,
			"description":             SensitivityInternal,
			fieldGLAccountID:          SensitivityInternal,
			"id":                      SensitivityInternal,
			"lineNumber":              SensitivityInternal,
			"organizationId":          SensitivityInternal,
			fieldPostedBatchID:        SensitivityInternal,
			"rejectedAt":              SensitivityInternal,
			"rejectedById":            SensitivityInternal,
			"requestNumber":           SensitivityInternal,
			"requestedFiscalPeriodId": SensitivityInternal,
			"requestedFiscalYearId":   SensitivityInternal,
			"status":                  SensitivityInternal,
			"updatedAt":               SensitivityInternal,
			fieldUpdatedByID:          SensitivityInternal,
			"version":                 SensitivityInternal,
		},
	})

	_ = r.Register(&ResourceDefinition{
		Resource:    ResourceJournalReversal.String(),
		DisplayName: "Journal Reversal",
		Description: "Journal reversal workflow and posting",
		Category:    "Accounting",
		Operations: []OperationDefinition{
			{Operation: OpRead, DisplayName: "Read", Description: "View journal reversals"},
			{
				Operation:   OpCreate,
				DisplayName: "Create",
				Description: "Create journal reversal requests",
			},
			{
				Operation:   OpApprove,
				DisplayName: "Approve",
				Description: "Approve journal reversals",
			},
			{Operation: OpReject, DisplayName: "Reject", Description: "Reject journal reversals"},
			{Operation: OpCancel, DisplayName: "Cancel", Description: "Cancel journal reversals"},
		},
		DefaultSensitivity: SensitivityRestricted,
		FieldSensitivities: map[string]FieldSensitivity{
			"approvedAt":              SensitivityInternal,
			"approvedById":            SensitivityInternal,
			"businessUnitId":          SensitivityInternal,
			"cancelledAt":             SensitivityInternal,
			"cancelledById":           SensitivityInternal,
			"createdAt":               SensitivityInternal,
			"id":                      SensitivityInternal,
			"organizationId":          SensitivityInternal,
			"originalJournalEntryId":  SensitivityInternal,
			"postedAt":                SensitivityInternal,
			fieldPostedBatchID:        SensitivityInternal,
			"postedById":              SensitivityInternal,
			"reasonCode":              SensitivityInternal,
			"rejectedAt":              SensitivityInternal,
			"rejectedById":            SensitivityInternal,
			"requestedAccountingDate": SensitivityInternal,
			"requestedById":           SensitivityInternal,
			"resolvedFiscalPeriodId":  SensitivityInternal,
			"resolvedFiscalYearId":    SensitivityInternal,
			"reversalJournalEntryId":  SensitivityInternal,
			"status":                  SensitivityInternal,
			"updatedAt":               SensitivityInternal,
			"version":                 SensitivityInternal,
		},
	})

	_ = r.Register(&ResourceDefinition{
		Resource:    ResourceJournalEntry.String(),
		DisplayName: "Journal Entry",
		Description: "Journal entry details and source drill-down",
		Category:    "Accounting",
		Operations: []OperationDefinition{
			{
				Operation:   OpRead,
				DisplayName: "Read",
				Description: "View journal entry details and accounting sources",
			},
			{
				Operation:   OpExport,
				DisplayName: "Export",
				Description: "Export journal entries and their lines",
			},
			{
				Operation:   OpApprove,
				DisplayName: "Approve and post",
				Description: "Approve journal entries awaiting review and post them to the general ledger",
			},
		},
		DefaultSensitivity: SensitivityRestricted,
		FieldSensitivities: map[string]FieldSensitivity{
			"accountingDate":       SensitivityInternal,
			"approvedAt":           SensitivityInternal,
			"approvedById":         SensitivityInternal,
			"batchId":              SensitivityInternal,
			"batchNumber":          SensitivityInternal,
			"batchType":            SensitivityInternal,
			"businessUnitId":       SensitivityInternal,
			"createdAt":            SensitivityInternal,
			"createdById":          SensitivityInternal,
			"customerId":           SensitivityInternal,
			"departmentId":         SensitivityInternal,
			"description":          SensitivityInternal,
			"entryCount":           SensitivityInternal,
			"entryDate":            SensitivityInternal,
			"entryNumber":          SensitivityInternal,
			"entryType":            SensitivityInternal,
			"fiscalPeriodId":       SensitivityInternal,
			"fiscalYearId":         SensitivityInternal,
			fieldGLAccountID:       SensitivityInternal,
			"id":                   SensitivityInternal,
			"isApproved":           SensitivityInternal,
			"isAutoGenerated":      SensitivityInternal,
			"isPosted":             SensitivityInternal,
			"isReconciled":         SensitivityInternal,
			"isRejected":           SensitivityInternal,
			"isReversal":           SensitivityInternal,
			"isTaxLine":            SensitivityInternal,
			"journalBatchId":       SensitivityInternal,
			"journalEntryId":       SensitivityInternal,
			"lineNumber":           SensitivityInternal,
			"locationId":           SensitivityInternal,
			"organizationId":       SensitivityInternal,
			"postedAt":             SensitivityInternal,
			"postedById":           SensitivityInternal,
			"projectId":            SensitivityInternal,
			"reconciledAt":         SensitivityInternal,
			"reconciledById":       SensitivityInternal,
			"referenceId":          SensitivityInternal,
			"referenceNumber":      SensitivityInternal,
			"referenceType":        SensitivityInternal,
			"rejectedAt":           SensitivityInternal,
			"rejectedById":         SensitivityInternal,
			"requiresApproval":     SensitivityInternal,
			"reversalDate":         SensitivityInternal,
			"reversalOfId":         SensitivityInternal,
			"reversedById":         SensitivityInternal,
			"sourceDocumentNumber": SensitivityInternal,
			"sourceEventType":      SensitivityInternal,
			"sourceObjectId":       SensitivityInternal,
			"sourceObjectType":     SensitivityInternal,
			"status":               SensitivityInternal,
			"taxCode":              SensitivityInternal,
			"updatedAt":            SensitivityInternal,
			fieldUpdatedByID:       SensitivityInternal,
			"vendorId":             SensitivityInternal,
			"version":              SensitivityInternal,
			"approvalNotes":        SensitivityRestricted,
			"creditAmount":         SensitivityRestricted,
			"debitAmount":          SensitivityRestricted,
			"netAmount":            SensitivityRestricted,
			"rejectionReason":      SensitivityRestricted,
			"reversalReason":       SensitivityRestricted,
			"taxAmount":            SensitivityRestricted,
			"totalCredit":          SensitivityRestricted,
			"totalDebit":           SensitivityRestricted,
		},
	})

	_ = r.Register(&ResourceDefinition{
		Resource:    ResourceCustomerPayment.String(),
		DisplayName: "Customer Payment",
		Description: "Customer payment posting and applications",
		Category:    "Accounting",
		Operations: []OperationDefinition{
			{Operation: OpRead, DisplayName: "Read", Description: "View customer payments"},
			{Operation: OpCreate, DisplayName: "Create", Description: "Post customer payments"},
			{
				Operation:   OpUpdate,
				DisplayName: "Update",
				Description: "Apply and reverse customer payments",
			},
			{
				Operation:   OpExport,
				DisplayName: "Export",
				Description: "Export customer payments and their applications",
			},
		},
		DefaultSensitivity: SensitivityRestricted,
		FieldSensitivities: map[string]FieldSensitivity{
			"accountingDate":       SensitivityInternal,
			"businessUnitId":       SensitivityInternal,
			"createdAt":            SensitivityInternal,
			"createdById":          SensitivityInternal,
			"currencyCode":         SensitivityInternal,
			"customerId":           SensitivityInternal,
			"customerPaymentId":    SensitivityInternal,
			"id":                   SensitivityInternal,
			"invoiceId":            SensitivityInternal,
			"lineNumber":           SensitivityInternal,
			"organizationId":       SensitivityInternal,
			"paymentDate":          SensitivityInternal,
			"paymentMethod":        SensitivityInternal,
			fieldPostedBatchID:     SensitivityInternal,
			"referenceNumber":      SensitivityInternal,
			"reversalBatchId":      SensitivityInternal,
			"reversedAt":           SensitivityInternal,
			"reversedById":         SensitivityInternal,
			"status":               SensitivityInternal,
			"updatedAt":            SensitivityInternal,
			fieldUpdatedByID:       SensitivityInternal,
			"version":              SensitivityInternal,
			"amountMinor":          SensitivityRestricted,
			"appliedAmountMinor":   SensitivityRestricted,
			"memo":                 SensitivityRestricted,
			"reversalReason":       SensitivityRestricted,
			"shortPayAmountMinor":  SensitivityRestricted,
			"unappliedAmountMinor": SensitivityRestricted,
		},
	})

	_ = r.Register(&ResourceDefinition{
		Resource:    ResourceAccountsReceivable.String(),
		DisplayName: "Accounts Receivable",
		Description: "AR ledger and aging reporting",
		Category:    "Accounting",
		Operations: []OperationDefinition{
			{Operation: OpRead, DisplayName: "Read", Description: "View AR ledger and aging"},
			{Operation: OpExport, DisplayName: "Export", Description: "Export the AR subledger"},
		},
		DefaultSensitivity: SensitivityRestricted,
		FieldSensitivities: map[string]FieldSensitivity{
			"businessUnitId":   SensitivityInternal,
			"createdAt":        SensitivityInternal,
			"createdById":      SensitivityInternal,
			"customerId":       SensitivityInternal,
			"documentNumber":   SensitivityInternal,
			"id":               SensitivityInternal,
			"lineNumber":       SensitivityInternal,
			"organizationId":   SensitivityInternal,
			"relatedInvoiceId": SensitivityInternal,
			"sourceEventType":  SensitivityInternal,
			"sourceObjectId":   SensitivityInternal,
			"sourceObjectType": SensitivityInternal,
			"transactionDate":  SensitivityInternal,
			"amountMinor":      SensitivityRestricted,
		},
	})

	_ = r.Register(&ResourceDefinition{
		Resource:    ResourceBankReceipt.String(),
		DisplayName: "Bank Receipt",
		Description: "Imported bank receipts and payment matching",
		Category:    "Accounting",
		Operations: []OperationDefinition{
			{Operation: OpRead, DisplayName: "Read", Description: "View bank receipts"},
			{Operation: OpCreate, DisplayName: "Create", Description: "Import bank receipts"},
			{
				Operation:   OpUpdate,
				DisplayName: "Update",
				Description: "Match bank receipts to payments",
			},
			{
				Operation:   OpExport,
				DisplayName: "Export",
				Description: "Export bank receipts and their match state",
			},
		},
		DefaultSensitivity: SensitivityRestricted,
		FieldSensitivities: map[string]FieldSensitivity{
			"businessUnitId":           SensitivityInternal,
			"createdAt":                SensitivityInternal,
			"createdById":              SensitivityInternal,
			"id":                       SensitivityInternal,
			"importBatchId":            SensitivityInternal,
			"matchedAt":                SensitivityInternal,
			"matchedById":              SensitivityInternal,
			"matchedCustomerPaymentId": SensitivityInternal,
			"organizationId":           SensitivityInternal,
			"receiptDate":              SensitivityInternal,
			"referenceNumber":          SensitivityInternal,
			"status":                   SensitivityInternal,
			"updatedAt":                SensitivityInternal,
			fieldUpdatedByID:           SensitivityInternal,
			"version":                  SensitivityInternal,
			"amountMinor":              SensitivityRestricted,
			"exceptionReason":          SensitivityRestricted,
			"memo":                     SensitivityConfidential,
		},
	})

	_ = r.Register(&ResourceDefinition{
		Resource:    ResourceAccountingReport.String(),
		DisplayName: "Accounting Report",
		Description: "Trial balance, income statement, and balance sheet reporting",
		Category:    "Accounting",
		Operations: []OperationDefinition{
			{Operation: OpRead, DisplayName: "Read", Description: "View accounting reports"},
			{Operation: OpExport, DisplayName: "Export", Description: "Export accounting reports"},
		},
		DefaultSensitivity: SensitivityRestricted,
		FieldSensitivities: map[string]FieldSensitivity{
			"businessUnitId":     SensitivityInternal,
			"createdAt":          SensitivityInternal,
			"fiscalPeriodId":     SensitivityInternal,
			"fiscalYearId":       SensitivityInternal,
			fieldGLAccountID:     SensitivityInternal,
			"lastJournalEntryId": SensitivityInternal,
			"organizationId":     SensitivityInternal,
			"updatedAt":          SensitivityInternal,
			"netChangeMinor":     SensitivityRestricted,
			"periodCreditMinor":  SensitivityRestricted,
			"periodDebitMinor":   SensitivityRestricted,
		},
	})

	_ = r.Register(&ResourceDefinition{
		Resource:    ResourceBankReceiptWorkItem.String(),
		DisplayName: "Bank Receipt Work Item",
		Description: "Reconciliation exception queue for bank receipts",
		Category:    "Accounting",
		Operations: []OperationDefinition{
			{Operation: OpRead, DisplayName: "Read", Description: "View bank receipt work queue"},
			{
				Operation:   OpUpdate,
				DisplayName: "Update",
				Description: "Assign and resolve bank receipt work items",
			},
		},
		DefaultSensitivity: SensitivityRestricted,
	})
}
