package permission

import (
	"slices"
)

func (r *Registry) registerSettlementResources() {
	_ = r.Register(&ResourceDefinition{
		Resource:    ResourceDriverPayProfile.String(),
		DisplayName: "Driver Pay Profile",
		Description: "Driver pay package configuration and worker pay assignments",
		Category:    "Payroll",
		Operations: append(slices.Clone(standardOpsWithDelete),
			OperationDefinition{
				Operation:   OpAssign,
				DisplayName: "Assign",
				Description: "Assign pay profiles to workers",
			},
		),
		DefaultSensitivity: SensitivityRestricted,
	})

	_ = r.Register(&ResourceDefinition{
		Resource:           ResourceRecurringDeduction.String(),
		DisplayName:        "Recurring Deduction",
		Description:        "Recurring driver deduction schedules",
		Category:           "Payroll",
		Operations:         standardOpsWithDelete,
		DefaultSensitivity: SensitivityRestricted,
		FieldSensitivities: map[string]FieldSensitivity{
			"businessUnitId":      SensitivityInternal,
			"createdAt":           SensitivityInternal,
			"createdById":         SensitivityInternal,
			"currencyCode":        SensitivityInternal,
			"description":         SensitivityInternal,
			"endDate":             SensitivityInternal,
			"escrowAccountId":     SensitivityInternal,
			"frequency":           SensitivityInternal,
			"id":                  SensitivityInternal,
			"kind":                SensitivityInternal,
			"organizationId":      SensitivityInternal,
			"payCodeId":           SensitivityInternal,
			"priority":            SensitivityInternal,
			"startDate":           SensitivityInternal,
			"status":              SensitivityInternal,
			"updatedAt":           SensitivityInternal,
			"version":             SensitivityInternal,
			"workerId":            SensitivityInternal,
			"amountMinor":         SensitivityRestricted,
			"deductedToDateMinor": SensitivityRestricted,
			"totalCapMinor":       SensitivityRestricted,
			"caseNumber":          SensitivityConfidential,
			"courtOrderNumber":    SensitivityConfidential,
			"issuingAgency":       SensitivityConfidential,
		},
	})

	r.registerRecurringEarningResource()

	_ = r.Register(&ResourceDefinition{
		Resource:    ResourcePayAdvance.String(),
		DisplayName: "Pay Advance",
		Description: "Driver cash and money-code advances",
		Category:    "Payroll",
		Operations: append(slices.Clone(standardOps),
			OperationDefinition{
				Operation:   OpCancel,
				DisplayName: "Write Off",
				Description: "Write off unrecoverable advances",
			},
		),
		DefaultSensitivity: SensitivityRestricted,
		FieldSensitivities: map[string]FieldSensitivity{
			"businessUnitId":  SensitivityInternal,
			"createdAt":       SensitivityInternal,
			"createdById":     SensitivityInternal,
			"currencyCode":    SensitivityInternal,
			"id":              SensitivityInternal,
			"issuedDate":      SensitivityInternal,
			"organizationId":  SensitivityInternal,
			"reference":       SensitivityInternal,
			"source":          SensitivityInternal,
			"status":          SensitivityInternal,
			"updatedAt":       SensitivityInternal,
			"version":         SensitivityInternal,
			"workerId":        SensitivityInternal,
			"writtenOffAt":    SensitivityInternal,
			"writtenOffById":  SensitivityInternal,
			"amountMinor":     SensitivityRestricted,
			"notes":           SensitivityRestricted,
			"recoveredMinor":  SensitivityRestricted,
			"writeOffReason":  SensitivityRestricted,
			"writtenOffMinor": SensitivityRestricted,
		},
	})

	_ = r.Register(&ResourceDefinition{
		Resource:    ResourceEscrowAccount.String(),
		DisplayName: "Escrow Account",
		Description: "Owner-operator escrow accounts and ledgers",
		Category:    "Payroll",
		Operations: append(slices.Clone(standardOps),
			OperationDefinition{
				Operation:   OpClose,
				DisplayName: "Close",
				Description: "Close escrow accounts and refund balances",
			},
		),
		DefaultSensitivity: SensitivityRestricted,
		FieldSensitivities: map[string]FieldSensitivity{
			"businessUnitId":          SensitivityInternal,
			"closedDate":              SensitivityInternal,
			"createdAt":               SensitivityInternal,
			"createdById":             SensitivityInternal,
			"currencyCode":            SensitivityInternal,
			"description":             SensitivityInternal,
			"escrowAccountId":         SensitivityInternal,
			"id":                      SensitivityInternal,
			"lastInterestAccrualDate": SensitivityInternal,
			"occurredDate":            SensitivityInternal,
			"openedDate":              SensitivityInternal,
			"organizationId":          SensitivityInternal,
			"settlementId":            SensitivityInternal,
			"status":                  SensitivityInternal,
			"type":                    SensitivityInternal,
			"updatedAt":               SensitivityInternal,
			"version":                 SensitivityInternal,
			"workerId":                SensitivityInternal,
			"amountMinor":             SensitivityRestricted,
			"annualInterestRate":      SensitivityRestricted,
			"balanceAfterMinor":       SensitivityRestricted,
			"balanceMinor":            SensitivityRestricted,
			"targetAmountMinor":       SensitivityRestricted,
		},
	})

	_ = r.Register(&ResourceDefinition{
		Resource:    ResourceDriverSettlement.String(),
		DisplayName: "Driver Settlement",
		Description: "Driver and owner-operator settlement statements and batches",
		Category:    "Payroll",
		Operations: append(slices.Clone(standardOps),
			OperationDefinition{
				Operation:   OpSubmit,
				DisplayName: "Submit",
				Description: "Submit settlements for approval",
			},
			OperationDefinition{
				Operation:   OpApprove,
				DisplayName: "Approve",
				Description: "Approve and post settlements",
			},
			OperationDefinition{
				Operation:   OpReject,
				DisplayName: "Reject",
				Description: "Send settlements back to draft",
			},
			OperationDefinition{
				Operation:   OpCancel,
				DisplayName: "Void",
				Description: "Void settlements",
			},
		),
		DefaultSensitivity: SensitivityRestricted,
		FieldSensitivities: map[string]FieldSensitivity{
			"advanceId":            SensitivityInternal,
			"approvedAt":           SensitivityInternal,
			"approvedById":         SensitivityInternal,
			"assignmentId":         SensitivityInternal,
			"batchId":              SensitivityInternal,
			"businessUnitId":       SensitivityInternal,
			"canceledAt":           SensitivityInternal,
			"canceledById":         SensitivityInternal,
			"category":             SensitivityInternal,
			"classification":       SensitivityInternal,
			"completedAt":          SensitivityInternal,
			"componentKind":        SensitivityInternal,
			"createdAt":            SensitivityInternal,
			"currencyCode":         SensitivityInternal,
			"description":          SensitivityInternal,
			"escrowAccountId":      SensitivityInternal,
			"eventDate":            SensitivityInternal,
			"exceptionCount":       SensitivityInternal,
			"generatedAt":          SensitivityInternal,
			"generatedById":        SensitivityInternal,
			"hasExceptions":        SensitivityInternal,
			"id":                   SensitivityInternal,
			"lineNumber":           SensitivityInternal,
			"method":               SensitivityInternal,
			"moveId":               SensitivityInternal,
			"name":                 SensitivityInternal,
			"onHold":               SensitivityInternal,
			"organizationId":       SensitivityInternal,
			"paidAt":               SensitivityInternal,
			"paidById":             SensitivityInternal,
			"payCodeId":            SensitivityInternal,
			"payDate":              SensitivityInternal,
			"payEventId":           SensitivityInternal,
			"payProfileId":         SensitivityInternal,
			"payProfileName":       SensitivityInternal,
			"paymentMethod":        SensitivityInternal,
			"periodEnd":            SensitivityInternal,
			"periodStart":          SensitivityInternal,
			"postedAt":             SensitivityInternal,
			"postedById":           SensitivityInternal,
			"postedJournalBatchId": SensitivityInternal,
			"proNumber":            SensitivityInternal,
			"recurringDeductionId": SensitivityInternal,
			"recurringEarningId":   SensitivityInternal,
			"settlementCount":      SensitivityInternal,
			"settlementId":         SensitivityInternal,
			"settlementLineId":     SensitivityInternal,
			"settlementNumber":     SensitivityInternal,
			"shipmentCount":        SensitivityInternal,
			"shipmentId":           SensitivityInternal,
			"status":               SensitivityInternal,
			"submittedAt":          SensitivityInternal,
			"submittedById":        SensitivityInternal,
			"updatedAt":            SensitivityInternal,
			"version":              SensitivityInternal,
			"voidJournalBatchId":   SensitivityInternal,
			"voidedAt":             SensitivityInternal,
			"voidedById":           SensitivityInternal,
			"workerId":             SensitivityInternal,
			"amountMinor":          SensitivityRestricted,
			"carryForwardInMinor":  SensitivityRestricted,
			"carryForwardOutMinor": SensitivityRestricted,
			"deductionsMinor":      SensitivityRestricted,
			"grossAmountMinor":     SensitivityRestricted,
			"grossEarningsMinor":   SensitivityRestricted,
			"holdReason":           SensitivityRestricted,
			"netPayMinor":          SensitivityRestricted,
			"notes":                SensitivityRestricted,
			"quantity":             SensitivityRestricted,
			"rate":                 SensitivityRestricted,
			"reimbursementsMinor":  SensitivityRestricted,
			"totalGrossMinor":      SensitivityRestricted,
			"totalMiles":           SensitivityRestricted,
			"totalNetMinor":        SensitivityRestricted,
			"voidReason":           SensitivityRestricted,
			"paymentReference":     SensitivityConfidential,
		},
	})

	_ = r.Register(&ResourceDefinition{
		Resource:           ResourceSettlementControl.String(),
		DisplayName:        "Settlement Control",
		Description:        "Settlement pay period, trigger, and exception policy configuration",
		Category:           "Payroll",
		Operations:         standardOps,
		DefaultSensitivity: SensitivityRestricted,
	})

	_ = r.Register(&ResourceDefinition{
		Resource:    ResourceSettlementDispute.String(),
		DisplayName: "Settlement Dispute",
		Description: "Driver-submitted settlement disputes and their resolution",
		Category:    "Payroll",
		Operations: append(slices.Clone(standardOps),
			OperationDefinition{
				Operation:   OpApprove,
				DisplayName: "Resolve",
				Description: "Resolve or deny settlement disputes",
			},
		),
		ParentResource:     ResourceDriverSettlement.String(),
		DefaultSensitivity: SensitivityRestricted,
	})

	_ = r.Register(&ResourceDefinition{
		Resource:    ResourceDriverExpense.String(),
		DisplayName: "Driver Expense",
		Description: "Driver-submitted expenses pending reimbursement review",
		Category:    "Payroll",
		Operations: append(slices.Clone(standardOps),
			OperationDefinition{
				Operation:   OpApprove,
				DisplayName: "Review",
				Description: "Approve or reject driver expenses",
			},
		),
		ParentResource:     ResourceDriverSettlement.String(),
		DefaultSensitivity: SensitivityRestricted,
	})

	_ = r.Register(&ResourceDefinition{
		Resource:           ResourceDashControl.String(),
		DisplayName:        "Dash Control",
		Description:        "Driver portal (Dash) feature toggles — what drivers can see and do",
		Category:           "Payroll",
		Operations:         standardOps,
		DefaultSensitivity: SensitivityRestricted,
	})

	_ = r.Register(&ResourceDefinition{
		Resource:    ResourceDriverPortal.String(),
		DisplayName: "Driver Portal",
		Description: "Driver portal (Dash) access management and invitations",
		Category:    "Payroll",
		Operations: append(slices.Clone(standardOps),
			OperationDefinition{
				Operation:   OpCancel,
				DisplayName: "Revoke",
				Description: "Revoke a driver's portal access",
			},
		),
		ParentResource:     ResourceWorker.String(),
		DefaultSensitivity: SensitivityRestricted,
	})
}
