package permission

import (
	"slices"
)

func (r *Registry) registerRateResources() {
	_ = r.Register(&ResourceDefinition{
		Resource:    ResourceRateAgreement.String(),
		DisplayName: "Rate Agreement",
		Description: "Customer and carrier rate agreements, their lane rules, accessorial schedules, and versions",
		Category:    "Billing",
		Operations: append(
			slices.Clone(standardOpsWithDelete),
			OperationDefinition{
				Operation:   OpSubmit,
				DisplayName: "Submit",
				Description: "Send a draft rate agreement for approval",
			},
			OperationDefinition{
				Operation:   OpArchive,
				DisplayName: "Archive",
				Description: "Retire a rate agreement so it no longer prices shipments",
			},
			OperationDefinition{
				Operation:   OpApprove,
				DisplayName: "Approve",
				Description: "Activate a rate agreement so it prices shipments",
			},
			OperationDefinition{
				Operation:   OpReject,
				DisplayName: "Reject",
				Description: "Send a rate agreement back for revision",
			},
			OperationDefinition{
				Operation:   OpDuplicate,
				DisplayName: "Duplicate",
				Description: "Copy a rate agreement as the basis for a new one",
			},
		),
		// A rate agreement is the negotiated price, which is exactly what a
		// competitor would want and what a customer would object to seeing.
		DefaultSensitivity: SensitivityConfidential,
		FieldSensitivities: map[string]FieldSensitivity{
			"accessorialChargeId":     SensitivityInternal,
			"accessorialTerms":        SensitivityInternal,
			"agreementEffectiveFrom":  SensitivityInternal,
			"agreementEffectiveTo":    SensitivityInternal,
			"agreementType":           SensitivityInternal,
			"allowDeficitRating":      SensitivityInternal,
			"approvedAt":              SensitivityInternal,
			"approvedById":            SensitivityInternal,
			"autoApply":               SensitivityInternal,
			"autoRenew":               SensitivityInternal,
			"billToCustomerId":        SensitivityInternal,
			"businessUnitId":          SensitivityInternal,
			"carrierId":               SensitivityInternal,
			"changeSummary":           SensitivityInternal,
			"code":                    SensitivityInternal,
			"commodityIds":            SensitivityInternal,
			"contractRef":             SensitivityInternal,
			"createdAt":               SensitivityInternal,
			"createdById":             SensitivityInternal,
			"currency":                SensitivityInternal,
			"currentVersionNumber":    SensitivityInternal,
			"customerId":              SensitivityInternal,
			"daysOfWeek":              SensitivityInternal,
			"densityScaleId":          SensitivityInternal,
			"description":             SensitivityInternal,
			"destinationCity":         SensitivityInternal,
			"destinationLatitude":     SensitivityInternal,
			"destinationLongitude":    SensitivityInternal,
			"destinationRadiusMeters": SensitivityInternal,
			"destinationScopeType":    SensitivityInternal,
			"destinationScopeValue":   SensitivityInternal,
			"direction":               SensitivityInternal,
			"documentId":              SensitivityInternal,
			"effectiveFrom":           SensitivityInternal,
			"effectiveTo":             SensitivityInternal,
			"equipmentClasses":        SensitivityInternal,
			"fixedFreightClass":       SensitivityInternal,
			"formulaTemplateId":       SensitivityInternal,
			"freeUnits":               SensitivityInternal,
			"freightClassSource":      SensitivityInternal,
			"freightClasses":          SensitivityInternal,
			"fromWeight":              SensitivityInternal,
			"fuelTerms":               SensitivityInternal,
			"hazmatOnly":              SensitivityInternal,
			"id":                      SensitivityInternal,
			"label":                   SensitivityInternal,
			"laneKey":                 SensitivityInternal,
			"maxDistance":             SensitivityInternal,
			"maxStops":                SensitivityInternal,
			"maxWeight":               SensitivityInternal,
			"method":                  SensitivityInternal,
			"minBillableDistance":     SensitivityInternal,
			"minDistance":             SensitivityInternal,
			"minStops":                SensitivityInternal,
			"minWeight":               SensitivityInternal,
			"name":                    SensitivityInternal,
			"organizationId":          SensitivityInternal,
			"originCity":              SensitivityInternal,
			"originLatitude":          SensitivityInternal,
			"originLongitude":         SensitivityInternal,
			"originRadiusMeters":      SensitivityInternal,
			"originScopeType":         SensitivityInternal,
			"originScopeValue":        SensitivityInternal,
			"partyId":                 SensitivityInternal,
			"partyType":               SensitivityInternal,
			"priority":                SensitivityInternal,
			"rateAgreementId":         SensitivityInternal,
			"rateAgreementRuleId":     SensitivityInternal,
			"rateMatrixId":            SensitivityInternal,
			"rateUnit":                SensitivityInternal,
			"renewalNoticeDays":       SensitivityInternal,
			"roundingMode":            SensitivityInternal,
			"roundingPrecision":       SensitivityInternal,
			"serviceModels":           SensitivityInternal,
			"serviceTypeIds":          SensitivityInternal,
			"shipmentTypeIds":         SensitivityInternal,
			"sortOrder":               SensitivityInternal,
			"sourceImportRowId":       SensitivityInternal,
			"specificityScore":        SensitivityInternal,
			"status":                  SensitivityInternal,
			"submittedAt":             SensitivityInternal,
			"submittedById":           SensitivityInternal,
			"supersedesRuleId":        SensitivityInternal,
			"tempControlOnly":         SensitivityInternal,
			"toWeight":                SensitivityInternal,
			"tractorTypeIds":          SensitivityInternal,
			"trailerTypeIds":          SensitivityInternal,
			"updatedAt":               SensitivityInternal,
			"version":                 SensitivityInternal,
			"versionNumber":           SensitivityInternal,
			"waived":                  SensitivityInternal,
			"absoluteMinCharge":       SensitivityRestricted,
			"amount":                  SensitivityRestricted,
			"applyCondition":          SensitivityRestricted,
			"changeMessage":           SensitivityRestricted,
			"defaultMaxCharge":        SensitivityRestricted,
			"defaultMinCharge":        SensitivityRestricted,
			"discountPercent":         SensitivityRestricted,
			"maxAmount":               SensitivityRestricted,
			"maxCharge":               SensitivityRestricted,
			"minCharge":               SensitivityRestricted,
			"rate":                    SensitivityRestricted,
			"reviewComment":           SensitivityRestricted,
			"marginFloorPercent":      SensitivityConfidential,
			"maxPayPercentOfSell":     SensitivityConfidential,
		},
	})

	_ = r.Register(&ResourceDefinition{
		Resource:           ResourceRateZone.String(),
		DisplayName:        "Rate Zone",
		Description:        "Named groupings of geography that lane rules and rate matrices are written against",
		Category:           "Billing",
		Operations:         standardOpsWithDelete,
		DefaultSensitivity: SensitivityInternal,
	})

	_ = r.Register(&ResourceDefinition{
		Resource:           ResourceRateMatrix.String(),
		DisplayName:        "Rate Matrix",
		Description:        "Multi-dimensional rate tables, their axes, cells, and density classification scales",
		Category:           "Billing",
		Operations:         standardOpsWithDelete,
		DefaultSensitivity: SensitivityConfidential,
		FieldSensitivities: map[string]FieldSensitivity{
			"businessUnitId":    SensitivityInternal,
			"code":              SensitivityInternal,
			"createdAt":         SensitivityInternal,
			"currency":          SensitivityInternal,
			"d0Key":             SensitivityInternal,
			"d0Max":             SensitivityInternal,
			"d0Min":             SensitivityInternal,
			"d1Key":             SensitivityInternal,
			"d1Max":             SensitivityInternal,
			"d1Min":             SensitivityInternal,
			"d2Key":             SensitivityInternal,
			"d2Max":             SensitivityInternal,
			"d2Min":             SensitivityInternal,
			"d3Key":             SensitivityInternal,
			"d3Max":             SensitivityInternal,
			"d3Min":             SensitivityInternal,
			"deficitEligible":   SensitivityInternal,
			"description":       SensitivityInternal,
			"formulaTemplateId": SensitivityInternal,
			"id":                SensitivityInternal,
			"keyNormalization":  SensitivityInternal,
			"kind":              SensitivityInternal,
			"label":             SensitivityInternal,
			"matchMode":         SensitivityInternal,
			"name":              SensitivityInternal,
			"organizationId":    SensitivityInternal,
			"position":          SensitivityInternal,
			"rangeOverflow":     SensitivityInternal,
			"rateMatrixId":      SensitivityInternal,
			"roundingMode":      SensitivityInternal,
			"roundingPrecision": SensitivityInternal,
			"status":            SensitivityInternal,
			"updatedAt":         SensitivityInternal,
			"version":           SensitivityInternal,
			"minCharge":         SensitivityRestricted,
			"value":             SensitivityRestricted,
		},
	})

	_ = r.Register(&ResourceDefinition{
		Resource:    ResourceRateSimulation.String(),
		DisplayName: "Rate Simulation",
		Description: "Replays of a proposed contract against freight that already moved, and what it would have charged",
		Category:    "Billing",
		// A simulation is run and read; its results are produced by the engine
		// and never edited, so there is nothing to update.
		Operations: []OperationDefinition{
			{
				Operation:   OpRead,
				DisplayName: "Read",
				Description: "View simulations and their results",
			},
			{
				Operation:   OpCreate,
				DisplayName: "Create",
				Description: "Run a simulation against historical shipments",
			},
			{
				Operation:   OpDelete,
				DisplayName: "Delete",
				Description: "Remove a simulation and its results",
			},
		},
		DefaultSensitivity: SensitivityConfidential,
	})

	_ = r.Register(&ResourceDefinition{
		Resource:    ResourceRateQuote.String(),
		DisplayName: "Rate Quote",
		Description: "The record of how each shipment was priced, including every rate considered and why it lost",
		Category:    "Billing",
		// Quotes are written by the rating engine and never edited: correcting
		// one means re-rating, which produces a new quote and supersedes the old.
		Operations: []OperationDefinition{
			{
				Operation:   OpRead,
				DisplayName: "Read",
				Description: "View rate quotes and their explanations",
			},
			{
				Operation:   OpExport,
				DisplayName: "Export",
				Description: "Export rate quotes and margin detail",
			},
		},
		DefaultSensitivity: SensitivityConfidential,
		FieldSensitivities: map[string]FieldSensitivity{
			"agreementVersionNumber": SensitivityInternal,
			"asOf":                   SensitivityInternal,
			"billingCurrency":        SensitivityInternal,
			"businessUnitId":         SensitivityInternal,
			"createdAt":              SensitivityInternal,
			"currency":               SensitivityInternal,
			"engineVersion":          SensitivityInternal,
			"exchangeRateId":         SensitivityInternal,
			"formulaTemplateId":      SensitivityInternal,
			"id":                     SensitivityInternal,
			"organizationId":         SensitivityInternal,
			"outcome":                SensitivityInternal,
			"partyId":                SensitivityInternal,
			"partyType":              SensitivityInternal,
			"purpose":                SensitivityInternal,
			"rateAgreementId":        SensitivityInternal,
			"rateAgreementRuleId":    SensitivityInternal,
			"ratedAt":                SensitivityInternal,
			"ratedById":              SensitivityInternal,
			"shipmentId":             SensitivityInternal,
			"shipmentMoveId":         SensitivityInternal,
			"specificityScore":       SensitivityInternal,
			"status":                 SensitivityInternal,
			"accessorialAmount":      SensitivityRestricted,
			"billingAmount":          SensitivityRestricted,
			"costAmount":             SensitivityRestricted,
			"foregoneAmount":         SensitivityRestricted,
			"fuelAmount":             SensitivityRestricted,
			"fxRate":                 SensitivityRestricted,
			"linehaulAmount":         SensitivityRestricted,
			"marginAmount":           SensitivityRestricted,
			"marginPercent":          SensitivityRestricted,
			"overrideReason":         SensitivityRestricted,
			"totalAmount":            SensitivityRestricted,
		},
	})
}
