# Generated by Django 4.1.7 on 2023-03-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commodities", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commodity",
            name="name",
            field=models.CharField(
                help_text="Name of the Commodity", max_length=255, verbose_name="Name"
            ),
        ),
        migrations.AddConstraint(
            model_name="commodity",
            constraint=models.UniqueConstraint(
                fields=("name", "organization"),
                name="unique_commodity_name_organization",
            ),
        ),
    ]
