# Generated by Django 4.1.7 on 2023-02-18 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commodities", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="commodity",
            table="commodity",
        ),
        migrations.AlterModelTable(
            name="hazardousmaterial",
            table="hazardous_material",
        ),
    ]
