// Code generated by buncolgen. DO NOT EDIT.

package invoicerun

import "github.com/emoss08/trenova/pkg/buncolgen"

// GetStaticFieldMap returns the pre-computed JSON→database column mapping for [InvoiceRun].
// This implements [querybuilder.StaticFieldMapper], allowing the QueryBuilder to use
// the generated [buncolgen.InvoiceRunFieldMap] instead of parsing struct tags via reflection.
func (e *InvoiceRun) GetStaticFieldMap() map[string]string {
	return buncolgen.InvoiceRunFieldMap
}

// GetStaticFieldMap returns the pre-computed JSON→database column mapping for [InvoiceRunGroup].
// This implements [querybuilder.StaticFieldMapper], allowing the QueryBuilder to use
// the generated [buncolgen.InvoiceRunGroupFieldMap] instead of parsing struct tags via reflection.
func (e *InvoiceRunGroup) GetStaticFieldMap() map[string]string {
	return buncolgen.InvoiceRunGroupFieldMap
}

// GetStaticFieldMap returns the pre-computed JSON→database column mapping for [InvoiceRunGroupItem].
// This implements [querybuilder.StaticFieldMapper], allowing the QueryBuilder to use
// the generated [buncolgen.InvoiceRunGroupItemFieldMap] instead of parsing struct tags via reflection.
func (e *InvoiceRunGroupItem) GetStaticFieldMap() map[string]string {
	return buncolgen.InvoiceRunGroupItemFieldMap
}
