import {
  AlertCircleIcon,
  AlertTriangleIcon,
  ArrowDownIcon,
  ArrowRightIcon,
  ArrowUpIcon,
  Award01Icon,
  BankNote01Icon,
  BarChart10Icon,
  Beaker01Icon,
  Bell01Icon,
  BookmarkIcon,
  BrainIcon,
  CalendarIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ClockIcon,
  Cloud01Icon,
  Columns01Icon,
  Copy01Icon,
  CornerDownLeftIcon,
  Database01Icon,
  Diamond01Icon,
  DotsGridIcon,
  DotsHorizontalIcon,
  Download01Icon,
  Droplets01Icon,
  Edit02Icon,
  EyeOffIcon,
  FilterLinesIcon,
  FlipBackwardIcon,
  HandIcon,
  HeadsetIcon,
  HelpCircleIcon,
  Inbox01Icon,
  Key01Icon,
  Keyboard01Icon,
  LayersThree01Icon,
  LayoutLeftIcon,
  LayoutRightIcon,
  Link01Icon,
  LinkExternal01Icon,
  Lock01Icon,
  Map01Icon,
  MessageChatSquareIcon,
  PackageIcon,
  PauseIcon,
  PlayIcon,
  PlugIcon,
  PlusIcon,
  ReceiptTextIcon,
  RefreshCw01Icon,
  Repeat01Icon,
  RouteIcon,
  SearchMdIcon,
  Send01Icon,
  Server01Icon,
  Settings01Icon,
  Settings02Icon,
  ShieldTickIcon,
  SlashCircle01Icon,
  Snowflake01Icon,
  Speedometer03Icon,
  Star01Icon,
  SunIcon,
  SwitchHorizontal01Icon,
  SwitchVertical01Icon,
  TableIcon,
  Tool01Icon,
  Trash01Icon,
  Truck01Icon,
  Upload01Icon,
  User01Icon,
  Users01Icon,
  VolumeXIcon,
  Wallet01Icon,
  XCloseIcon,
  ZapIcon,
  type IconComponent,
} from "@trenova/shared/components/icons";
import { AssistMark } from "@trenova/shared/components/ui/assist-mark";

/** The design's icon names, drawn from Trenova's icon set. */
const ICONS = {
  plus: PlusIcon,
  search: SearchMdIcon,
  x: XCloseIcon,
  check: CheckIcon,
  arrowR: ArrowRightIcon,
  chevR: ChevronRightIcon,
  chevD: ChevronDownIcon,
  chevL: ChevronLeftIcon,
  upDown: SwitchVertical01Icon,
  up: ArrowUpIcon,
  down: ArrowDownIcon,
  refresh: RefreshCw01Icon,
  bell: Bell01Icon,
  star: Star01Icon,
  filter: FilterLinesIcon,
  columns: Columns01Icon,
  table: TableIcon,
  map: Map01Icon,
  timeline: BarChart10Icon,
  truck: Truck01Icon,
  box: PackageIcon,
  repeat: Repeat01Icon,
  receipt: ReceiptTextIcon,
  alert: AlertCircleIcon,
  warn: AlertTriangleIcon,
  clock: ClockIcon,
  gear: Settings02Icon,
  cog: Settings01Icon,
  more: DotsHorizontalIcon,
  ext: LinkExternal01Icon,
  chat: MessageChatSquareIcon,
  diamond: Diamond01Icon,
  user: User01Icon,
  users: Users01Icon,
  hand: HandIcon,
  snow: Snowflake01Icon,
  cloud: Cloud01Icon,
  download: Download01Icon,
  upload: Upload01Icon,
  mute: VolumeXIcon,
  bookmark: BookmarkIcon,
  panel: LayoutRightIcon,
  sidebar: LayoutLeftIcon,
  sparkle: AssistMark,
  layers: LayersThree01Icon,
  plug: PlugIcon,
  send: Send01Icon,
  route: RouteIcon,
  enter: CornerDownLeftIcon,
  edit: Edit02Icon,
  undo: FlipBackwardIcon,
  flask: Beaker01Icon,
  copy: Copy01Icon,
  swap: SwitchHorizontal01Icon,
  ban: SlashCircle01Icon,
  link: Link01Icon,
  pause: PauseIcon,
  play: PlayIcon,
  eyeOff: EyeOffIcon,
  lock: Lock01Icon,
  tool: Tool01Icon,
  calendar: CalendarIcon,
  bolt: ZapIcon,
  inbox: Inbox01Icon,
  key: Key01Icon,
  server: Server01Icon,
  trash: Trash01Icon,
  grip: DotsGridIcon,
  shield: ShieldTickIcon,
  fuel: Droplets01Icon,
  dollar: BankNote01Icon,
  chart: BarChart10Icon,
  wallet: Wallet01Icon,
  headset: HeadsetIcon,
  sun: SunIcon,
  database: Database01Icon,
  help: HelpCircleIcon,
  brain: BrainIcon,
  gauge: Speedometer03Icon,
  award: Award01Icon,
  keyboard: Keyboard01Icon,
} as const satisfies Record<string, IconComponent>;

export type IcName = keyof typeof ICONS;

type IcProps = {
  n: IcName;
  /** Size in pixels. */
  s?: number;
  /** Stroke width. */
  w?: number;
  className?: string;
};

/** An icon at the design's size and stroke: 14px, 1.7. */
export function Ic({ n, s = 14, w = 1.7, className }: IcProps) {
  const Icon = ICONS[n];
  return <Icon size={s} strokeWidth={w} className={className} />;
}
