# .air.toml
root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./cmd/api/main.go"
bin = "./tmp/main"
delay = 100
exclude_dir = ["assets", "tmp", "vendor", "ui", "platform"]
include_ext = ["go", "tpl", "tmpl", "html", "yaml"]
exclude_regex = ["_test\\.go"]
send_interrupt = false
stop_on_error = true
