# # Copyright 2023-2025 Eric Moss
# # Licensed under FSL-1.1-ALv2 (Functional Source License 1.1, Apache 2.0 Future)
# # Full license: https://github.com/emoss08/trenova/blob/main/LICENSE.md

# Docker Compose override file for testing with read replicas
# Usage: docker-compose -f docker-compose-local.yml -f docker-compose-replicas.yml up

# This file only contains the replica services to be added to the base compose file
# The primary database configuration remains in docker-compose-local.yml

services:
  # Standard PostgreSQL setup for simpler local testing
  db:
    image: postgres:latest
    environment:
      POSTGRES_INITDB_ARGS: "--data-checksums"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    command: >
      postgres
      -c wal_level=replica
      -c hot_standby=on
      -c max_wal_senders=10
      -c max_replication_slots=10
      -c hot_standby_feedback=on
      -c wal_keep_size=128MB
      
  # Read replica using standard PostgreSQL
  db-replica1:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      PGUSER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    volumes:
      - pg_replica1_data:/var/lib/postgresql/data
    command: >
      bash -c '
      until PGPASSWORD=${DB_PASSWORD:-postgres} pg_basebackup --pgdata=/var/lib/postgresql/data -R --slot=replication_slot_1 --host=db --port=5432 --username=${DB_USER:-postgres}
      do
        echo "Waiting for primary to be ready..."
        sleep 2s
      done
      chmod 0700 /var/lib/postgresql/data
      postgres
      '
    depends_on:
      - db
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 512M
          
  db-replica2:
    image: postgres:latest
    ports:
      - "5434:5432"
    environment:
      PGUSER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    volumes:
      - pg_replica2_data:/var/lib/postgresql/data
    command: >
      bash -c '
      until PGPASSWORD=${DB_PASSWORD:-postgres} pg_basebackup --pgdata=/var/lib/postgresql/data -R --slot=replication_slot_2 --host=db --port=5432 --username=${DB_USER:-postgres}
      do
        echo "Waiting for primary to be ready..."
        sleep 2s
      done
      chmod 0700 /var/lib/postgresql/data
      postgres
      '
    depends_on:
      - db
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 512M