x-build-args: &build-args
  DOCKER_BUILDKIT: 1
  GO_VERSION: 1.24
  ALPINE_VERSION: latest

name: trenova-prod
services:
  tren-db:
    container_name: tren-db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_DB: ${DB_NAME:-trenova_go_db}
      POSTGRES_INITDB_ARGS: "--data-checksums"
      POSTGRES_MULTIPLE_EXTENSIONS: "pg_stat_statements,pg_trgm,btree_gin,btree_gist"
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements,pg_buffercache"
      - "-c"
      - "pg_stat_statements.track=all"
      - "-c"
      - "max_replication_slots=1"
      - "-c"
      - "max_connections=100"
      - "-c"
      - "shared_buffers=128MB" # 25% of container memory
      - "-c"
      - "effective_cache_size=384MB" # 75% of container memory
      - "-c"
      - "maintenance_work_mem=64MB"
      - "-c"
      - "checkpoint_completion_target=0.9"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "effective_io_concurrency=200"
      - "-c"
      - "work_mem=4MB"
      - "-c"
      - "min_wal_size=1GB"
      - "-c"
      - "max_wal_size=4GB"
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "1"
        reservations:
          memory: 256M
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-trenova_go_db}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s # Allow time for initial startup

  tren-pgbouncer:
    container_name: tren-pgbouncer
    image: edoburu/pgbouncer:latest # Using a pre-built image for simplicity
    environment:
      - DATABASE_URL=postgres://postgres:postgres@tren-db:5432/trenova_go_db?sslmode=disable
    volumes:
      - ./config/production/pgbouncer/pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini:ro
      - ./config/production/pgbouncer/userlist.txt:/etc/pgbouncer/userlist.txt:ro
    ports:
      - "6432:6432"
    depends_on:
      tren-db:
        condition: service_healthy
    restart: always
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h localhost -p 6432 -U ${DB_USER:-postgres} -d ${DB_NAME:-trenova_go_db}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  tren-redis:
    container_name: tren-redis
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes # This will be overridden by the command
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 1G
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  tren-minio:
    container_name: tren-minio
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minioadmin}
    volumes:
      - minio_data:/data
    ports:
      - 9000:9000 # API
      - 9001:9001 # Console
    restart: always
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 512M
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  tren-rabbitmq:
    container_name: tren-rabbitmq
    image: "rabbitmq:3-management"
    ports:
      - "5674:5672" # RabbitMQ
      - "15674:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - "rabbitmq_data:/var/lib/rabbitmq"
      - "rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf" # Configuration file mount
    restart: always
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 30s
      timeout: 10s
      retries: 10
    networks:
      - app-network

  tren-api:
    container_name: tren-api
    build:
      context: .
      dockerfile: Dockerfile
      args:
        <<: *build-args
    ports:
      - "3001:3001"
    environment:
      - TRENOVA_APP_ENVIRONMENT=production
      - TRENOVA_SERVER_SECRET_KEY=${SERVER_SECRET_KEY:-secretKey}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-yourStrongRedisPassword}
      - DB_HOST=tren-pgbouncer
      - DB_PORT=6432
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_NAME=${DB_NAME:-postgres}
    depends_on:
      tren-pgbouncer:
        condition: service_healthy
      tren-redis:
        condition: service_healthy
      tren-minio:
        condition: service_healthy
      tren-rabbitmq:
        condition: service_healthy
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "1"
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:8080/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: always

  tren-client:
    container_name: tren-client
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - app-network
    depends_on:
      - tren-api
    environment:
      - VITE_API_URL=https://trenova.local/api/v1
    restart: always
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.5"

  tren-caddy:
    container_name: tren-caddy
    build:
      context: .
      dockerfile: Dockerfile.caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./logs/caddy:/var/log/caddy
    environment:
      - ACME_AGREE=true
    networks:
      - app-network
    depends_on:
      - tren-api
      - tren-client
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: "0.5"

volumes:
  pg_data: {}
  redis_data: {}
  minio_data: {}
  caddy_data: {}
  caddy_config: {}
  rabbitmq_data: {}
  rabbitmq.conf: {}

networks:
  app-network:
    driver: bridge
