version: "3"

tasks:
  run:
    cmd: go run ./cmd/api/main.go serve
  reset:
    cmds:
      - task: db-reset
      - task: redis-flushall
      - task: db-init
      - task: db-migrate
      - task: db-seed
  check:
    cmds:
      - task: test-pretty
      - task: lint
      - task: format
      - task: critic
      - task: security
  swag:
    cmds:
      - task: swag-fmt
      - task: swag-init
  test:
    cmd: go test ./... -v
  test-pretty:
    cmd: |
      if ! command -v tparse &> /dev/null
      then
        echo "tparse could not be found, installing..."
        go install github.com/mfridman/tparse@latest
      fi
      set -o pipefail && go test ./... -json | tparse -all
    silent: true
  update-go-deps:
    cmd: go get -u ./... && go mod tidy
  run-client:
    dir: ui
    cmd: pnpm run dev
  lint:
    cmd: golangci-lint run --timeout 5m
  nilcheck:
    cmd: nilaway ./...
  format:
    cmd: go fmt ./...
  format-sql:
    cmd: |
      if ! command -v pg_format &> /dev/null
      then
        echo "pg_format could not be found, please install pgFormatter..."
        echo "Visit https://github.com/darold/pgFormatter for installation instructions"
        exit 1
      fi
      find internal/infrastructure/database/postgres/migrations/ -name "*.sql" -type f -exec pg_format -i {} \;
    desc: Format all SQL files in the migrations directory using pgFormatter
  critic:
    cmd: |
      if ! command -v gocritic &> /dev/null
      then
        echo "gocritic could not be found, installing..."
        go install github.com/go-critic/go-critic/cmd/gocritic@latest
      fi
      gocritic check -enableAll -disable=sloppyReassign,unnamedResult,importShadow,paramTypeCombine,whyNoLint,commentedOutCode ./...
  security:
    cmd: gosec ./...
  tidy:
    cmd: go mod tidy
  bump-deps:
    cmd: go get -u ./... && go mod tidy
  db-reset:
    cmd: go run cmd/db/main.go db reset
  db-init:
    cmd: go run cmd/db/main.go db init
  db-migrate:
    cmd: go run cmd/db/main.go db migrate
  db-seed:
    cmd: go run cmd/db/main.go db seed
  redis-flushall:
    cmd: go run cmd/db/main.go redis flushall
  swag-init:
    cmd: swag init --parseDependency --parseInternal --parseDepth 1
  swag-fmt:
    cmd: swag fmt
