# -*- coding: utf-8 -*-
# Generated by Django 4.1.2 on 2022-10-30 02:30

from django.db import migrations, models
import organization.validators


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="timezone",
            field=models.CharField(
                default="America/New_York",
                help_text="The timezone of the organization",
                max_length=255,
                validators=[organization.validators.validate_org_timezone],
                verbose_name="Timezone",
            ),
        ),
    ]
