# Generated by Django 4.1.7 on 2023-02-16 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0007_tablechangealert_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tablechangealert",
            options={
                "ordering": ["name"],
                "verbose_name": "Table Change Alert",
                "verbose_name_plural": "Table Change Alerts",
            },
        ),
        migrations.AddField(
            model_name="tablechangealert",
            name="database_action",
            field=models.CharField(
                choices=[("INSERT", "Insert"), ("UPDATE", "Update"), ("BOTH", "BOTH")],
                default="INSERT",
                help_text="The database action that the table change alert is for.",
                max_length=50,
                verbose_name="Database Action",
            ),
        ),
    ]
