# Generated by Django 4.1.3 on 2022-12-04 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("order", "0001_initial"),
        ("customer", "0001_initial"),
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerfuelprofile",
            name="order_type",
            field=models.ForeignKey(
                help_text="Order Type",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_fuel_profiles",
                related_query_name="customer_fuel_profile",
                to="order.ordertype",
                verbose_name="Order Type",
            ),
        ),
        migrations.AddField(
            model_name="customerfuelprofile",
            name="organization",
            field=models.ForeignKey(
                help_text="Organization",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                related_query_name="%(class)s",
                to="organization.organization",
                verbose_name="Organization",
            ),
        ),
        migrations.AddField(
            model_name="customeremailprofile",
            name="organization",
            field=models.ForeignKey(
                help_text="Organization",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                related_query_name="%(class)s",
                to="organization.organization",
                verbose_name="Organization",
            ),
        ),
        migrations.AddField(
            model_name="customercontact",
            name="customer",
            field=models.ForeignKey(
                help_text="Customer",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                related_query_name="contact",
                to="customer.customer",
                verbose_name="Customer",
            ),
        ),
        migrations.AddField(
            model_name="customercontact",
            name="organization",
            field=models.ForeignKey(
                help_text="Organization",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                related_query_name="%(class)s",
                to="organization.organization",
                verbose_name="Organization",
            ),
        ),
        migrations.AddField(
            model_name="customerbillingprofile",
            name="customer",
            field=models.OneToOneField(
                help_text="Customer",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="billing_profile",
                related_query_name="billing_profiles",
                to="customer.customer",
                verbose_name="Customer",
            ),
        ),
        migrations.AddField(
            model_name="customerbillingprofile",
            name="email_profile",
            field=models.ForeignKey(
                blank=True,
                help_text="Customer Email Profile",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="billing_profiles",
                related_query_name="billing_profiles",
                to="customer.customeremailprofile",
                verbose_name="Customer Email Profile",
            ),
        ),
        migrations.AddField(
            model_name="customerbillingprofile",
            name="organization",
            field=models.ForeignKey(
                help_text="Organization",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                related_query_name="%(class)s",
                to="organization.organization",
                verbose_name="Organization",
            ),
        ),
        migrations.AddField(
            model_name="customerbillingprofile",
            name="rule_profile",
            field=models.ForeignKey(
                blank=True,
                help_text="Rule Profile",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="billing_profiles",
                related_query_name="billing_profile",
                to="customer.customerruleprofile",
                verbose_name="Rule Profile",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="organization",
            field=models.ForeignKey(
                help_text="Organization",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                related_query_name="%(class)s",
                to="organization.organization",
                verbose_name="Organization",
            ),
        ),
    ]
