CREATE TABLE IF NOT EXISTS casbin_rule
(
    id    BIGSERIAL PRIMARY KEY,
    ptype VARCHAR(255) NOT NULL,
    v0    VARCHAR(255) NOT NULL,
    v1    VARCHAR(255) NOT NULL,
    v2    VARCHAR(255) NOT NULL,
    v3    VARCHAR(255) NOT NULL,
    v4    VARCHAR(255) NOT NULL,
    v5    VARCHAR(255) NOT NULL
);