-- # Copyright 2023-2025 Eric Moss
-- # Licensed under FSL-1.1-ALv2 (Functional Source License 1.1, Apache 2.0 Future)
-- # Full license: https://github.com/emoss08/trenova/blob/main/LICENSE.md

-- Trenova - (c) 2024 Eric Moss
-- Licensed under the Business Source License 1.1 (BSL 1.1)
--
-- You may use this software for non-production purposes only.
-- For full license text, see the LICENSE file in the project root.
--
-- This software will be licensed under GPLv2 or later on 2026-11-16.
-- For alternative licensing options, email: eric@trenova.app
-- Nothing need to be done
