package validators

import (
	"github.com/emoss08/trenova/internal/pkg/validator/accessorialchargevalidator"
	"github.com/emoss08/trenova/internal/pkg/validator/assignmentvalidator"
	"github.com/emoss08/trenova/internal/pkg/validator/billingcontrolvalidator"
	"github.com/emoss08/trenova/internal/pkg/validator/commodityvalidator"
	"github.com/emoss08/trenova/internal/pkg/validator/compliancevalidator"
	"github.com/emoss08/trenova/internal/pkg/validator/customervalidator"
	"github.com/emoss08/trenova/internal/pkg/validator/documenttypevalidator"
	"github.com/emoss08/trenova/internal/pkg/validator/equipmentmanufacturervalidator"
	"github.com/emoss08/trenova/internal/pkg/validator/equipmenttypevalidator"
	"github.com/emoss08/trenova/internal/pkg/validator/fleetcodevalidator"
	"github.com/emoss08/trenova/internal/pkg/validator/framework"
	"github.com/emoss08/trenova/internal/pkg/validator/hazardousmaterialvalidator"
	"github.com/emoss08/trenova/internal/pkg/validator/hazmatsegreationrulevalidator"
	"github.com/emoss08/trenova/internal/pkg/validator/locationvalidator"
	"github.com/emoss08/trenova/internal/pkg/validator/servicetypevalidator"
	"github.com/emoss08/trenova/internal/pkg/validator/shipmentcontrolvalidator"
	"github.com/emoss08/trenova/internal/pkg/validator/shipmenttypevalidator"
	"github.com/emoss08/trenova/internal/pkg/validator/shipmentvalidator"
	"github.com/emoss08/trenova/internal/pkg/validator/tractorvalidator"
	"github.com/emoss08/trenova/internal/pkg/validator/trailervalidator"
	"github.com/emoss08/trenova/internal/pkg/validator/workervalidator"
	"go.uber.org/fx"
)

var Module = fx.Module("validators",
	fx.Provide(
		compliancevalidator.NewValidator,
		workervalidator.NewWorkerProfileValidator,
		workervalidator.NewWorkerPTOValidator,
		workervalidator.NewValidator,
		fleetcodevalidator.NewValidator,
		equipmenttypevalidator.NewValidator,
		equipmentmanufacturervalidator.NewValidator,
		shipmenttypevalidator.NewValidator,
		servicetypevalidator.NewValidator,
		hazardousmaterialvalidator.NewValidator,
		commodityvalidator.NewValidator,
		locationvalidator.NewLocationCategoryValidator,
		locationvalidator.NewValidator,
		tractorvalidator.NewValidator,
		trailervalidator.NewValidator,
		customervalidator.NewValidator,
		hazmatsegreationrulevalidator.NewValidator,
		shipmentvalidator.NewStopValidator,
		shipmentvalidator.NewMoveValidator,
		shipmentvalidator.NewValidator,
		assignmentvalidator.NewValidator,
		shipmentcontrolvalidator.NewValidator,
		billingcontrolvalidator.NewValidator,
		accessorialchargevalidator.NewValidator,
		documenttypevalidator.NewValidator,
		framework.ProvideValidationEngineFactory,
		framework.ProvideLifecycle,
	),
	fx.Options(
		framework.Module,
	),
)
