version: 2.1

jobs:
  test-and-lint:
    docker:
      - image: cimg/python:3.11.1
      - image: cimg/postgres:14.1
        environment:
          POSTGRES_USER: example
    steps:
      - checkout
      - run:
          name: install dependencies
          command: pip install -r requirements.txt
      - run:
          name: run tests
          command: python manage.py test
      - store_test_results:
          path: test_results
workflows:
  build-and-test-workflow:
    jobs:
      - test-and-lint