version: 2.1

jobs:
  test-and-lint:
    docker:
      - image: cimg/python:3.11.1
        environment:
          TEST_DATABASE_URL: postgresql://postgres@localhost/circle_test
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference


      - image: cimg/postgres:14.1
        environment:
          TEST_DATABASE_URL: postgresql://postgres@localhost/circle_test
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference

      - image: cimg/redis:6.2.6
    steps:
      - checkout
      - run:
          name: install dependencies
          command: pip install -r requirements.txt
      - run:
          name: run lint
          command: mypy .
      - run:
          name: run tests
          command: python -m pytest -s
      - store_test_results:
          path: test_results
workflows:
  build-and-test-workflow:
    jobs:
      - test-and-lint