version: 2.1

jobs:
  test-and-lint:
    docker:
      - image: cimg/python:3.11.1

      - image: cimg/postgres:14.1
        environment:
          DATABASE_NAME: circle_test
          DATABASE_USER: root
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
          DATABASE_PASSWORD: ''
          DATABASE_PORT: 5432
          DATABASE_HOST: localhost

      - image: cimg/redis:6.2.6
    steps:
      - checkout
      - run:
          name: install dependencies
          command: pip install -r requirements.txt
      - run:
          name: run lint
          command: mypy .
      - run:
          name: run tests
          command: python -m pytest -s
      - store_test_results:
          path: test_results
workflows:
  build-and-test-workflow:
    jobs:
      - test-and-lint