services:
  app:
    image: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@trenova-db/trenova_app_db
    networks:
      - trenova-net

networks:
  trenova-net:
    external: true
