import type { SidebarLink } from "@/components/sidebar-nav";
import { OrganizationCapability } from "@trenova/shared/types/organization-capability";
import { Operation, Resource } from "@trenova/shared/types/permission";
import {
  BarChart3Icon,
  CalculatorIcon,
  ContainerIcon,
  FileSlidersIcon,
  FuelIcon,
  HandshakeIcon,
  HomeIcon,
  InboxIcon,
  MessagesSquareIcon,
  Package,
  ReceiptTextIcon,
  RouteIcon,
  SettingsIcon,
  TimerIcon,
  TruckIcon,
  UsersIcon,
  WalletIcon,
} from "lucide-react";
import type { ModuleId, NavigationConfig, NavModule } from "./navigation.types";

interface AppModuleGroup {
  id: string;
  label: string;
  moduleIds: ModuleId[];
}

const homeModule: NavModule = {
  id: "home",
  label: "Home",
  icon: HomeIcon,
  description: "Your work, your numbers, and where to go next",
  basePath: "/",
  hideSecondarySidebar: true,
  navigation: [],
};
const deskModule: NavModule = {
  id: "desk",
  label: "Desk",
  icon: MessagesSquareIcon,
  description:
    "Your conversations with the agents, what they produced, and what they ask you to decide",
  basePath: "/desk",
  routePrefixes: ["/desk"],
  hideSecondarySidebar: true,
  resource: Resource.Assistant,
  navigation: [],
};

// The inbox is its own module rather than a page under the Desk. What arrives
// by email is work coming in from outside, which is a different thing from the
// conversations and decisions the Desk holds, and a dispatcher opens one
// without wanting the other.
const inboxModule: NavModule = {
  id: "inbox",
  label: "Inbox",
  icon: InboxIcon,
  description: "Mail that arrived on a monitored address, and what was made of it",
  basePath: "/inbox",
  routePrefixes: ["/inbox"],
  hideSecondarySidebar: true,
  resource: Resource.InboundMessage,
  navigation: [],
};

const adminModule: NavModule = {
  id: "admin",
  label: "Organization settings",
  shortLabel: "Settings",
  icon: SettingsIcon,
  description: "System administration",
  basePath: "/admin/organization-settings",
  routePrefixes: ["/admin", "/organization"],
  hideSecondarySidebar: true,
  resource: Resource.Organization,
  navigation: [],
};

const shipmentManagementModule: NavModule = {
  id: "shipment",
  label: "Shipment management",
  shortLabel: "Shipments",
  icon: TruckIcon,
  description: "Shipments and related configuration",
  basePath: "#",
  routePrefixes: ["/shipment-management"],
  navigation: [
    {
      id: "shipments",
      label: "Shipments",
      path: "/shipment-management/shipments",
      icon: Package,
      resource: Resource.Shipment,
    },
    {
      id: "recurring-shipments",
      label: "Recurring shipments",
      path: "/shipment-management/recurring-shipments",
      resource: Resource.RecurringShipment,
    },
    {
      id: "orders",
      label: "Orders",
      path: "/shipment-management/orders",
      resource: Resource.Order,
    },
    {
      id: "service-failures",
      label: "Service failures",
      path: "/shipment-management/service-failures",
      resource: Resource.ServiceFailure,
    },
    {
      id: "config-files-group",
      label: "Configuration files",
      kind: "configuration",
      defaultOpen: false,
      items: [
        {
          id: "shipment-types",
          label: "Shipment types",
          path: "/shipment-management/configuration-files/shipment-types",
          resource: Resource.ShipmentType,
        },
        {
          id: "service-types",
          label: "Service types",
          path: "/shipment-management/configuration-files/service-types",
          resource: Resource.ServiceType,
        },
        {
          id: "hazardous-materials",
          label: "Hazardous materials",
          path: "/shipment-management/configuration-files/hazardous-materials",
          resource: Resource.HazardousMaterial,
        },
        {
          id: "commodities",
          label: "Commodities",
          path: "/shipment-management/configuration-files/commodities",
          resource: Resource.Commodity,
        },
      ],
    },
  ],
};

const dispatchModule: NavModule = {
  id: "dispatch",
  label: "Dispatch management",
  shortLabel: "Dispatch",
  icon: RouteIcon,
  description: "The board, the lanes, and the carriers that run them",
  basePath: "/dispatch",
  navigation: [
    {
      id: "dispatch-console",
      label: "Console",
      path: "/dispatch/console",
      resource: Resource.ShipmentMove,
    },
    {
      id: "locations",
      label: "Locations",
      path: "/dispatch/locations",
      resource: Resource.Location,
    },
    {
      id: "carriers",
      label: "Carriers",
      path: "/dispatch/carriers",
      resource: Resource.Carrier,
      capability: OrganizationCapability.Brokerage,
    },
    {
      id: "carrier-monitoring",
      label: "Carrier monitoring",
      path: "/dispatch/carrier-monitoring",
      resource: Resource.CarrierIntelligence,
    },
    {
      id: "carrier-sourcing",
      label: "Carrier sourcing",
      path: "/dispatch/carrier-sourcing",
      resource: Resource.CarrierSourcing,
      capability: OrganizationCapability.Brokerage,
    },
    {
      id: "routing-guides",
      label: "Routing guides",
      path: "/dispatch/routing-guides",
      resource: Resource.RoutingGuide,
      capability: OrganizationCapability.Brokerage,
    },
    {
      id: "dispatch-config-group",
      label: "Configuration files",
      kind: "configuration",
      defaultOpen: false,
      items: [
        {
          id: "location-categories",
          label: "Location categories",
          path: "/dispatch/configuration-files/location-categories",
          resource: Resource.LocationCategory,
        },
        {
          id: "fleet-codes",
          label: "Fleet codes",
          path: "/dispatch/configuration-files/fleet-codes",
          resource: Resource.FleetCode,
          capability: OrganizationCapability.AssetOperations,
        },
      ],
    },
  ],
};

/**
 * Everything about the people who work here: the employee record and the
 * catalogs the record is measured against. Dispatch keeps the board; this
 * keeps the file.
 */
const humanResourcesModule: NavModule = {
  id: "hr",
  label: "Human resource management",
  shortLabel: "People",
  icon: UsersIcon,
  description: "Employee records, qualifications, time off, and performance",
  basePath: "/hr",
  capability: OrganizationCapability.AssetOperations,
  navigation: [
    {
      id: "workers",
      label: "Workers",
      path: "/hr/workers",
      resource: Resource.Worker,
      capability: OrganizationCapability.AssetOperations,
    },
    {
      id: "my-team",
      label: "My team",
      path: "/hr/my-team",
      resource: Resource.Worker,
      capability: OrganizationCapability.AssetOperations,
    },
    {
      id: "hr-config-group",
      label: "Configuration files",
      kind: "configuration",
      defaultOpen: false,
      items: [
        {
          id: "credential-types",
          label: "Credential types",
          path: "/hr/credential-types",
          resource: Resource.WorkerCredentialType,
          capability: OrganizationCapability.AssetOperations,
        },
        {
          id: "training-courses",
          label: "Training courses",
          path: "/hr/training-courses",
          resource: Resource.TrainingCourse,
          capability: OrganizationCapability.AssetOperations,
        },
        {
          id: "checklist-templates",
          label: "Checklist templates",
          path: "/hr/checklist-templates",
          resource: Resource.WorkerChecklistTemplate,
          capability: OrganizationCapability.AssetOperations,
        },
        {
          id: "review-templates",
          label: "Review templates",
          path: "/hr/review-templates",
          resource: Resource.PerformanceReviewTemplate,
          capability: OrganizationCapability.AssetOperations,
        },
        {
          id: "leave-settings",
          label: "Leave settings",
          path: "/hr/leave-settings",
          resource: Resource.WorkerLeave,
          capability: OrganizationCapability.AssetOperations,
        },
        {
          id: "policies",
          label: "Policies",
          path: "/hr/policies",
          resource: Resource.WorkerPolicy,
          capability: OrganizationCapability.AssetOperations,
        },
        {
          id: "time-attendance",
          label: "Time & attendance",
          path: "/hr/time-attendance",
          resource: Resource.Timesheet,
          capability: OrganizationCapability.AssetOperations,
        },
        {
          id: "scheduling",
          label: "Scheduling",
          path: "/hr/scheduling",
          resource: Resource.WorkerSchedule,
          capability: OrganizationCapability.AssetOperations,
        },
        {
          id: "benefits",
          label: "Benefits",
          path: "/hr/benefits",
          resource: Resource.BenefitPlan,
          capability: OrganizationCapability.AssetOperations,
        },
        {
          id: "org-structure",
          label: "Org structure",
          path: "/hr/org-structure",
          resource: Resource.JobPosition,
          capability: OrganizationCapability.AssetOperations,
        },
        {
          id: "fleet-safety",
          label: "Fleet safety",
          path: "/hr/fleet-safety",
          resource: Resource.WorkerSafetyEvent,
          capability: OrganizationCapability.AssetOperations,
        },
        {
          id: "osha-log",
          label: "OSHA 300 log",
          path: "/hr/osha-log",
          resource: Resource.WorkerInjury,
          capability: OrganizationCapability.AssetOperations,
        },
        {
          id: "random-testing",
          label: "Random testing",
          path: "/hr/random-testing",
          resource: Resource.DOTRandomPool,
          capability: OrganizationCapability.AssetOperations,
        },
        {
          id: "pto-policies",
          label: "PTO policies",
          path: "/hr/pto-policies",
          resource: Resource.PTOPolicy,
          capability: OrganizationCapability.AssetOperations,
        },
        {
          id: "holidays",
          label: "Holiday calendar",
          path: "/hr/holidays",
          resource: Resource.OrgHoliday,
          capability: OrganizationCapability.AssetOperations,
        },
      ],
    },
  ],
};

const equipmentModule: NavModule = {
  id: "fleet",
  label: "Equipment management",
  shortLabel: "Equipment",
  icon: ContainerIcon,
  description: "Tractors, trailers, and equipment",
  basePath: "/equipment",
  navigation: [
    {
      id: "tractors",
      label: "Tractors",
      path: "/equipment/tractors",
      resource: Resource.Tractor,
      capability: OrganizationCapability.AssetOperations,
    },
    {
      id: "trailers",
      label: "Trailers",
      path: "/equipment/trailers",
      resource: Resource.Trailer,
      capability: OrganizationCapability.AssetOperations,
    },
    {
      id: "equipment-config-group",
      label: "Configuration files",
      kind: "configuration",
      defaultOpen: false,
      items: [
        {
          id: "equipment-manufacturers",
          label: "Equipment manufacturers",
          path: "/equipment/configuration-files/equipment-manufacturers",
          resource: Resource.EquipmentManufacturer,
        },
        {
          id: "equipment-types",
          label: "Equipment types",
          path: "/equipment/configuration-files/equipment-types",
          resource: Resource.EquipmentType,
        },
      ],
    },
  ],
};

const fuelModule: NavModule = {
  id: "fuel",
  label: "Fuel & tax",
  shortLabel: "Fuel",
  icon: FuelIcon,
  description: "Fuel spend, surcharge pricing, and IFTA",
  basePath: "/fuel",
  navigation: [
    {
      id: "fuel-purchases",
      label: "Fuel purchases",
      path: "/fuel/purchases",
      resource: Resource.FuelPurchase,
      capability: OrganizationCapability.AssetOperations,
    },
    {
      id: "feed-runs",
      label: "Feed runs",
      path: "/fuel/feed-runs",
      resource: Resource.FuelPurchaseImport,
      capability: OrganizationCapability.AssetOperations,
    },
    {
      id: "unassigned-cards",
      label: "Unassigned cards",
      path: "/fuel/unassigned-cards",
      resource: Resource.FuelCard,
      capability: OrganizationCapability.AssetOperations,
    },
    {
      id: "jurisdiction-mileage",
      label: "Jurisdiction mileage",
      path: "/fuel/jurisdiction-mileage",
      resource: Resource.IFTAJurisdictionMileage,
      capability: OrganizationCapability.AssetOperations,
    },
    {
      id: "ifta-returns",
      label: "IFTA returns",
      path: "/fuel/ifta-returns",
      resource: Resource.IFTAReturn,
      capability: OrganizationCapability.AssetOperations,
    },
    {
      id: "fuel-config-group",
      label: "Configuration files",
      kind: "configuration",
      defaultOpen: false,
      items: [
        {
          id: "fuel-cards",
          label: "Fuel cards",
          path: "/fuel/configuration-files/fuel-cards",
          resource: Resource.FuelCard,
          capability: OrganizationCapability.AssetOperations,
        },
        {
          id: "ifta-tax-rates",
          label: "IFTA tax rates",
          path: "/fuel/configuration-files/ifta-tax-rates",
          resource: Resource.IFTATaxRate,
          capability: OrganizationCapability.AssetOperations,
        },
        {
          id: "fuel-surcharge",
          label: "Fuel surcharge",
          path: "/fuel/configuration-files/surcharge",
          resource: Resource.FuelSurchargeProgram,
        },
      ],
    },
  ],
};

const billingModule: NavModule = {
  id: "billing",
  label: "Billing management",
  shortLabel: "Billing",
  icon: ReceiptTextIcon,
  description: "Invoicing and financial management",
  basePath: "/billing",
  navigation: [
    {
      id: "billing-queue",
      label: "Billing queue",
      path: "/billing/queue",
      resource: Resource.BillingQueue,
    },
    {
      id: "invoices",
      label: "Invoices",
      path: "/billing/invoices",
      resource: Resource.Invoice,
    },
    {
      id: "pending-approvals",
      label: "Pending approvals",
      path: "/billing/pending-approvals",
      resource: Resource.Invoice,
    },
    {
      id: "reconciliation-exceptions",
      label: "Reconciliation exceptions",
      path: "/billing/reconciliation-exceptions",
      resource: Resource.Invoice,
    },
    {
      id: "adjustment-batches",
      label: "Batch monitor",
      path: "/billing/adjustment-batches",
      resource: Resource.Invoice,
    },
    {
      id: "rate-agreements",
      label: "Rate agreements",
      path: "/billing/rate-agreements",
      resource: Resource.RateAgreement,
      includeBetaTag: true,
    },
    {
      id: "billing-config-group",
      label: "Configuration files",
      kind: "configuration",
      defaultOpen: false,
      items: [
        {
          id: "accessorial-charges",
          label: "Accessorial charges",
          path: "/billing/configuration-files/accessorial-charges",
          resource: Resource.AccessorialCharge,
        },
        {
          id: "formula-templates",
          label: "Formula templates",
          path: "/billing/configuration-files/formula-templates",
          resource: Resource.FormulaTemplate,
        },
        {
          id: "rate-zones",
          label: "Rate zones",
          path: "/billing/configuration-files/rate-zones",
          resource: Resource.RateZone,
          includeBetaTag: true,
        },
        {
          id: "rate-matrices",
          label: "Rate matrices",
          path: "/billing/configuration-files/rate-matrices",
          resource: Resource.RateMatrix,
          includeBetaTag: true,
        },
        {
          id: "customers",
          label: "Customers",
          path: "/billing/configuration-files/customers",
          resource: Resource.Customer,
        },
        {
          id: "document-types",
          label: "Document types",
          path: "/billing/configuration-files/document-types",
          resource: Resource.DocumentType,
        },
        {
          id: "document-packet-rules",
          label: "Packet rules",
          path: "/billing/configuration-files/document-packet-rules",
          resource: Resource.DocumentType,
        },
      ],
    },
  ],
};

const detentionModule: NavModule = {
  id: "detention",
  label: "Detention management",
  shortLabel: "Detention",
  icon: TimerIcon,
  description: "Live dwell clocks, detention billing, and contract terms",
  basePath: "/detention",
  navigation: [
    {
      id: "detention-desk",
      label: "Desk",
      path: "/detention/desk",
      resource: Resource.DetentionPolicy,
    },
    {
      id: "detention-intelligence",
      label: "Intelligence",
      path: "/detention/intelligence",
      resource: Resource.DetentionPolicy,
    },
    {
      id: "detention-config-group",
      label: "Configuration files",
      kind: "configuration",
      defaultOpen: false,
      items: [
        {
          id: "detention-policies",
          label: "Detention policies",
          path: "/detention/configuration-files/detention-policies",
          resource: Resource.DetentionPolicy,
        },
      ],
    },
  ],
};

const payrollModule: NavModule = {
  id: "payroll",
  label: "Payroll & settlements",
  shortLabel: "Payroll",
  icon: WalletIcon,
  description: "Driver and owner-operator pay",
  basePath: "/payroll",
  capability: OrganizationCapability.AssetOperations,
  navigation: [
    {
      id: "settlement-workspace",
      label: "Workspace",
      path: "/payroll/workspace",
      resource: Resource.DriverSettlement,
    },
    {
      id: "driver-settlements",
      label: "Settlement history",
      path: "/payroll/settlements",
      resource: Resource.DriverSettlement,
    },
    {
      id: "settlement-disputes",
      label: "Disputes",
      path: "/payroll/disputes",
      resource: Resource.SettlementDispute,
    },
    {
      id: "driver-expenses",
      label: "Driver expenses",
      path: "/payroll/expenses",
      resource: Resource.DriverExpense,
    },
    {
      id: "settlement-batches",
      label: "Settlement batches",
      path: "/payroll/settlement-batches",
      resource: Resource.DriverSettlement,
    },
    {
      id: "pay-events",
      label: "Pay events",
      path: "/payroll/pay-events",
      resource: Resource.DriverSettlement,
    },
    {
      id: "payroll-config-group",
      label: "Configuration files",
      kind: "configuration",
      defaultOpen: false,
      items: [
        {
          id: "pay-profiles",
          label: "Pay profiles",
          path: "/payroll/pay-profiles",
          resource: Resource.DriverPayProfile,
        },
        {
          id: "recurring-deductions",
          label: "Recurring deductions",
          path: "/payroll/deductions",
          resource: Resource.RecurringDeduction,
        },
        {
          id: "recurring-earnings",
          label: "Recurring earnings",
          path: "/payroll/earnings",
          resource: Resource.RecurringEarning,
        },
        {
          id: "pay-codes",
          label: "Pay codes",
          path: "/payroll/pay-codes",
          resource: Resource.PayCode,
        },
        {
          id: "pay-advances",
          label: "Pay advances",
          path: "/payroll/advances",
          resource: Resource.PayAdvance,
        },
        {
          id: "escrow-accounts",
          label: "Escrow accounts",
          path: "/payroll/escrow-accounts",
          resource: Resource.EscrowAccount,
        },
      ],
    },
  ],
};

const carrierSettlementsModule: NavModule = {
  id: "carrier-settlements",
  label: "Carrier settlements",
  icon: HandshakeIcon,
  description: "Carrier payables and invoice reconciliation",
  basePath: "/carrier-settlements",
  capability: OrganizationCapability.Brokerage,
  navigation: [
    {
      id: "carrier-settlement-workspace",
      label: "Workspace",
      path: "/carrier-settlements/workspace",
      resource: Resource.CarrierSettlement,
    },
    {
      id: "carrier-settlements-history",
      label: "Settlement history",
      path: "/carrier-settlements/settlements",
      resource: Resource.CarrierSettlement,
    },
    {
      id: "carrier-settlement-batches",
      label: "Settlement batches",
      path: "/carrier-settlements/batches",
      resource: Resource.CarrierSettlement,
    },
    {
      id: "carrier-cost-events",
      label: "Cost events",
      path: "/carrier-settlements/cost-events",
      resource: Resource.CarrierSettlement,
    },
    {
      id: "carrier-invoice-matching",
      label: "Invoice matching",
      path: "/carrier-settlements/invoice-matching",
      resource: Resource.CarrierInvoiceMatch,
    },
  ],
};

const ediModule: NavModule = {
  id: "edi",
  label: "EDI",
  icon: FileSlidersIcon,
  description: "Internal partner exchange and load tender workflow",
  basePath: "/edi/overview",
  routePrefixes: ["/edi"],
  navigation: [
    {
      id: "edi-overview",
      label: "Overview",
      path: "/edi/overview",
      resource: Resource.EDI,
      badge: "edi-attention",
    },
    {
      id: "edi-designer",
      label: "Template designer",
      path: "/edi/designer",
      resource: Resource.EDI,
    },
    {
      id: "edi-inbound",
      label: "Inbound transfers",
      path: "/edi/transfers/inbound",
      resource: Resource.EDI,
    },
    {
      id: "edi-outbound",
      label: "Outbound transfers",
      path: "/edi/transfers/outbound",
      resource: Resource.EDI,
    },
    {
      id: "edi-messages",
      label: "Messages",
      path: "/edi/messages",
      resource: Resource.EDI,
    },
    {
      id: "edi-inbound-files",
      label: "Inbound files",
      path: "/edi/inbound-files",
      resource: Resource.EDI,
    },
    {
      id: "edi-test-cases",
      label: "Test cases",
      path: "/edi/test-cases",
      resource: Resource.EDI,
    },
    {
      id: "edi-config-group",
      label: "Configuration files",
      kind: "configuration",
      defaultOpen: false,
      items: [
        {
          id: "edi-partners",
          label: "Partners",
          path: "/edi/partners",
          resource: Resource.EDI,
        },
        {
          id: "edi-communication-profiles",
          label: "Communication profiles",
          path: "/edi/communication-profiles",
          resource: Resource.EDI,
        },
        {
          id: "edi-mapping-profiles",
          label: "Mapping profiles",
          path: "/edi/mapping-profiles",
          resource: Resource.EDI,
        },
      ],
    },
  ],
};

const accountingModule: NavModule = {
  id: "accounting",
  label: "Accounting management",
  shortLabel: "Accounting",
  icon: CalculatorIcon,
  description: "Accounting management",
  basePath: "/accounting",
  navigation: [
    {
      id: "accounting-dashboard",
      label: "Accounting dashboard",
      path: "/accounting",
    },
    {
      id: "manual-journals",
      label: "Manual journals",
      path: "/accounting/manual-journals",
      resource: Resource.ManualJournal,
    },
    {
      id: "journal-reversals",
      label: "Journal reversals",
      path: "/accounting/journal-reversals",
      resource: Resource.JournalReversal,
    },
    {
      id: "reports-group",
      label: "Reports",
      defaultOpen: false,
      items: [
        {
          id: "trial-balance",
          label: "Trial balance",
          path: "/accounting/reports/trial-balance",
          resource: Resource.AccountingReport,
        },
        {
          id: "income-statement",
          label: "Income Statement",
          path: "/accounting/reports/income-statement",
          resource: Resource.AccountingReport,
        },
        {
          id: "balance-sheet",
          label: "Balance sheet",
          path: "/accounting/reports/balance-sheet",
          resource: Resource.AccountingReport,
        },
      ],
    },
    {
      id: "ar-group",
      label: "Accounts receivable",
      defaultOpen: false,
      items: [
        {
          id: "ar-aging",
          label: "AR aging",
          path: "/accounting/ar/aging",
        },
        {
          id: "customer-ledger",
          label: "Customer ledger",
          path: "/accounting/ar/customer-ledger",
        },
        {
          id: "ar-open-items",
          label: "Open items",
          path: "/accounting/ar/open-items",
        },
        {
          id: "invoice-register",
          label: "Invoice register",
          path: "/accounting/ar/invoices",
          resource: Resource.Invoice,
        },
        {
          id: "late-charges",
          label: "Late charges",
          path: "/accounting/ar/late-charges",
          resource: Resource.AccountsReceivable,
        },
        {
          id: "customer-payments",
          label: "Customer payments",
          path: "/accounting/ar/payments",
        },
      ],
    },
    {
      id: "reconciliation-group",
      label: "Bank reconciliation",
      defaultOpen: false,
      items: [
        {
          id: "bank-receipts",
          label: "Bank receipts",
          path: "/accounting/reconciliation/bank-receipts",
          resource: Resource.BankReceipt,
        },
        {
          id: "work-queue",
          label: "Work queue",
          path: "/accounting/reconciliation/work-queue",
          resource: Resource.BankReceiptWorkItem,
        },
        {
          id: "reconciliation-summary",
          label: "Summary",
          path: "/accounting/reconciliation/summary",
          resource: Resource.BankReceipt,
        },
        {
          id: "import-batches",
          label: "Import batches",
          path: "/accounting/reconciliation/import-batches",
          resource: Resource.BankReceipt,
        },
      ],
    },
    {
      id: "accounting-sync-group",
      label: "Accounting sync",
      defaultOpen: false,
      items: [
        {
          id: "accounting-mappings",
          label: "Mappings",
          path: "/accounting/sync/mappings",
          resource: Resource.AccountingIntegration,
        },
      ],
    },
    {
      id: "configuration-files-group",
      label: "Configuration files",
      kind: "configuration",
      defaultOpen: false,
      items: [
        {
          id: "account-types",
          label: "Account types",
          path: "/accounting/configuration-files/account-types",
          resource: Resource.AccountType,
        },
        {
          id: "fiscal-years",
          label: "Fiscal years",
          path: "/accounting/configuration-files/fiscal-years",
          resource: Resource.FiscalYear,
        },
      ],
    },
  ],
};

const reportsModule: NavModule = {
  id: "reports",
  label: "Reports",
  icon: BarChart3Icon,
  description: "Analytics and reporting",
  basePath: "/reports",
  routePrefixes: ["/reports", "/insights"],
  navigation: [
    {
      id: "reports-library",
      label: "Report library",
      path: "/reports",
      resource: Resource.Report,
    },
    {
      id: "reports-run-history",
      label: "Run history",
      path: "/reports/runs",
      resource: Resource.Report,
    },
    {
      id: "reports-insights",
      label: "Insights",
      path: "/insights",
      resource: Resource.Insight,
    },
  ],
};

export const navigationConfig: NavigationConfig = {
  modules: [
    homeModule,
    deskModule,
    inboxModule,
    shipmentManagementModule,
    dispatchModule,
    humanResourcesModule,
    equipmentModule,
    fuelModule,
    billingModule,
    detentionModule,
    payrollModule,
    carrierSettlementsModule,
    ediModule,
    reportsModule,
    accountingModule,
    adminModule,
  ],
  quickActions: [
    {
      id: "create-shipment",
      label: "New shipment",
      description: "Add a new shipment",
      path: "/shipment-management/shipments",
      resource: Resource.Shipment,
      requiredOperation: Operation.Create,
      query: { panelType: "create" },
      keywords: ["shipment"],
    },
    {
      id: "create-shipment-type",
      label: "New shipment type",
      description: "Add a new shipment type",
      path: "/shipment-management/configuration-files/shipment-types",
      resource: Resource.ShipmentType,
      requiredOperation: Operation.Create,
      query: { panelType: "create" },
      keywords: ["shipment", "type"],
    },
    {
      id: "create-service-type",
      label: "New service type",
      description: "Add a new service type",
      path: "/shipment-management/configuration-files/service-types",
      resource: Resource.ServiceType,
      requiredOperation: Operation.Create,
      query: { panelType: "create" },
      keywords: ["service", "type"],
    },
    {
      id: "create-hazardous-material",
      label: "New hazardous material",
      description: "Add a new hazardous material",
      path: "/shipment-management/configuration-files/hazardous-materials",
      resource: Resource.HazardousMaterial,
      requiredOperation: Operation.Create,
      query: { panelType: "create" },
      keywords: ["hazmat", "dangerous goods", "material"],
    },
    {
      id: "create-commodity",
      label: "New commodity",
      description: "Add a new commodity",
      path: "/shipment-management/configuration-files/commodities",
      resource: Resource.Commodity,
      requiredOperation: Operation.Create,
      query: { panelType: "create" },
      keywords: ["commodity"],
    },
    {
      id: "create-accessorial-charge",
      label: "New accessorial charge",
      description: "Add a new accessorial charge",
      path: "/billing/configuration-files/accessorial-charges",
      resource: Resource.AccessorialCharge,
      requiredOperation: Operation.Create,
      query: { panelType: "create" },
      keywords: ["accessorial", "charge"],
    },
    {
      id: "create-customer",
      label: "New customer",
      description: "Add a new customer",
      path: "/billing/configuration-files/customers",
      resource: Resource.Customer,
      requiredOperation: Operation.Create,
      query: { panelType: "create" },
      keywords: ["customer"],
    },
    {
      id: "create-document-type",
      label: "New document type",
      description: "Add a new document type",
      path: "/billing/configuration-files/document-types",
      resource: Resource.DocumentType,
      requiredOperation: Operation.Create,
      query: { panelType: "create" },
      keywords: ["document", "type"],
    },
    {
      id: "create-formula-template",
      label: "New formula template",
      description: "Open the Formula Studio and start a new template",
      path: "/billing/configuration-files/formula-templates/new",
      resource: Resource.FormulaTemplate,
      requiredOperation: Operation.Create,
      keywords: ["formula", "template", "studio"],
    },
    {
      id: "create-rate-agreement",
      label: "New rate agreement",
      description: "Write a customer or carrier contract",
      path: "/billing/rate-agreements",
      resource: Resource.RateAgreement,
      requiredOperation: Operation.Create,
      query: { panelType: "create" },
      keywords: ["rate", "agreement", "contract", "tariff", "lane"],
    },
    {
      id: "create-rate-zone",
      label: "New rate zone",
      description: "Name a market area contracts can be priced against",
      path: "/billing/configuration-files/rate-zones",
      resource: Resource.RateZone,
      requiredOperation: Operation.Create,
      query: { panelType: "create" },
      keywords: ["rate", "zone", "region", "market", "geography"],
    },
    {
      id: "create-rate-matrix",
      label: "New rate matrix",
      description: "Enter a published tariff as the grid it was published as",
      path: "/billing/configuration-files/rate-matrices",
      resource: Resource.RateMatrix,
      requiredOperation: Operation.Create,
      query: { panelType: "create" },
      keywords: ["rate", "matrix", "tariff", "grid", "weight break", "class", "ltl"],
    },
    {
      id: "create-detention-policy",
      label: "New detention policy",
      description: "Encode a contract's detention terms",
      path: "/detention/configuration-files/detention-policies",
      resource: Resource.DetentionPolicy,
      requiredOperation: Operation.Create,
      query: { panelType: "create" },
      keywords: ["detention", "policy", "demurrage", "free time", "dwell"],
    },
    {
      id: "create-fuel-surcharge-program",
      label: "New fuel surcharge program",
      description: "Add a new fuel surcharge program",
      path: "/fuel/configuration-files/surcharge",
      resource: Resource.FuelSurchargeProgram,
      requiredOperation: Operation.Create,
      query: { tab: "programs" },
      keywords: ["fuel", "surcharge", "fsc", "doe", "diesel"],
    },
    {
      id: "create-account-type",
      label: "New account type",
      description: "Add a new account type",
      path: "/accounting/configuration-files/account-types",
      resource: Resource.AccountType,
      requiredOperation: Operation.Create,
      query: { panelType: "create" },
      keywords: ["account", "type"],
    },
    {
      id: "create-fiscal-year",
      label: "New fiscal year",
      description: "Add a new fiscal year",
      path: "/accounting/configuration-files/fiscal-years",
      resource: Resource.FiscalYear,
      requiredOperation: Operation.Create,
      query: { panelType: "create" },
      keywords: ["fiscal", "year"],
    },
    {
      id: "create-tractor",
      label: "New tractor",
      description: "Add a new tractor",
      path: "/equipment/tractors",
      resource: Resource.Tractor,
      requiredOperation: Operation.Create,
      query: { panelType: "create" },
      keywords: ["tractor", "equipment"],
      capability: OrganizationCapability.AssetOperations,
    },
    {
      id: "record-fuel-purchase",
      label: "Record fuel purchase",
      description: "Key a fuel receipt against a tractor",
      path: "/fuel/purchases",
      resource: Resource.FuelPurchase,
      requiredOperation: Operation.Create,
      query: { panelType: "create" },
      keywords: ["fuel", "purchase", "diesel", "ifta", "receipt"],
      capability: OrganizationCapability.AssetOperations,
    },
    {
      id: "import-fuel-card-statement",
      label: "Import fuel card statement",
      description: "Stage a Comdata, EFS or WEX statement for review",
      path: "/fuel/purchases",
      resource: Resource.FuelPurchaseImport,
      requiredOperation: Operation.Create,
      query: { import: "fuel-card" },
      keywords: ["fuel", "card", "statement", "import", "comdata", "efs", "wex"],
      capability: OrganizationCapability.AssetOperations,
    },
    {
      id: "create-trailer",
      label: "New trailer",
      description: "Add a new trailer",
      path: "/equipment/trailers",
      resource: Resource.Trailer,
      requiredOperation: Operation.Create,
      query: { panelType: "create" },
      keywords: ["trailer", "equipment"],
      capability: OrganizationCapability.AssetOperations,
    },
    {
      id: "create-equipment-type",
      label: "New equipment type",
      description: "Add a new equipment type",
      path: "/equipment/configuration-files/equipment-types",
      resource: Resource.EquipmentType,
      requiredOperation: Operation.Create,
      query: { panelType: "create" },
      keywords: ["equipment", "type"],
    },
    {
      id: "create-equipment-manufacturer",
      label: "New equipment manufacturer",
      description: "Add a new equipment manufacturer",
      path: "/equipment/configuration-files/equipment-manufacturers",
      resource: Resource.EquipmentManufacturer,
      requiredOperation: Operation.Create,
      query: { panelType: "create" },
      keywords: ["equipment", "manufacturer"],
    },
    {
      id: "create-location",
      label: "New location",
      description: "Add a new location",
      path: "/dispatch/locations",
      resource: Resource.Location,
      requiredOperation: Operation.Create,
      query: { panelType: "create" },
      keywords: ["location"],
    },
    {
      id: "create-worker",
      label: "New worker",
      description: "Add a new worker",
      path: "/hr/workers",
      resource: Resource.Worker,
      requiredOperation: Operation.Create,
      query: { pageTab: "workers", panelType: "create" },
      keywords: ["worker", "driver", "employee"],
      capability: OrganizationCapability.AssetOperations,
    },
    {
      id: "request-worker-pto",
      label: "Request worker PTO",
      description: "Request time off on behalf of a worker",
      path: "/hr/workers",
      resource: Resource.WorkerPTO,
      requiredOperation: Operation.Create,
      query: { pageTab: "pto", panelType: "create" },
      keywords: ["pto", "time off", "vacation", "leave", "worker"],
      capability: OrganizationCapability.AssetOperations,
    },
    {
      id: "create-location-category",
      label: "New location category",
      description: "Add a new location category",
      path: "/dispatch/configuration-files/location-categories",
      resource: Resource.LocationCategory,
      requiredOperation: Operation.Create,
      query: { panelType: "create" },
      keywords: ["location", "category"],
    },
    {
      id: "create-fleet-code",
      label: "New fleet code",
      description: "Add a new fleet code",
      path: "/dispatch/configuration-files/fleet-codes",
      resource: Resource.FleetCode,
      requiredOperation: Operation.Create,
      query: { panelType: "create" },
      keywords: ["fleet", "code"],
      capability: OrganizationCapability.AssetOperations,
    },
    {
      id: "create-hold-reason",
      label: "New hold reason",
      description: "Add a new hold reason",
      path: "/admin/hold-reasons",
      resource: Resource.HoldReason,
      requiredOperation: Operation.Create,
      query: { panelType: "create" },
      keywords: ["hold", "reason"],
    },
    {
      id: "create-jurisdiction-rule",
      label: "New jurisdiction rule",
      description: "Add oversize limits for a state",
      path: "/admin/jurisdiction-rules",
      resource: Resource.JurisdictionRule,
      requiredOperation: Operation.Create,
      query: { panelType: "create" },
      keywords: ["jurisdiction", "oversize", "permit", "state", "limits"],
    },
    {
      id: "create-jurisdiction-rule-override",
      label: "New carrier override",
      description: "Hold this fleet to a stricter limit than a state requires",
      path: "/admin/jurisdiction-rule-overrides",
      resource: Resource.JurisdictionRuleOverride,
      requiredOperation: Operation.Create,
      query: { panelType: "create" },
      keywords: ["override", "carrier", "jurisdiction", "stricter", "limits"],
    },
    {
      id: "create-service-failure-reason-code",
      label: "New service failure reason",
      description: "Add a service failure reason code",
      path: "/admin/service-failure-reason-codes",
      resource: Resource.ServiceFailureReasonCode,
      requiredOperation: Operation.Create,
      query: { panelType: "create" },
      keywords: ["service", "failure", "reason"],
    },
    {
      id: "create-hazmat-segregation-rule",
      label: "New hazmat segregation rule",
      description: "Add a new hazmat segregation rule",
      path: "/admin/hazmat-segregation-rules",
      resource: Resource.HazmatSegregationRule,
      requiredOperation: Operation.Create,
      query: { panelType: "create" },
      keywords: ["hazmat", "segregation", "rule"],
    },
    {
      id: "create-distance-override",
      label: "New distance override",
      description: "Add a new distance override",
      path: "/admin/distance-overrides",
      resource: Resource.DistanceOverride,
      requiredOperation: Operation.Create,
      query: { panelType: "create" },
      keywords: ["distance", "override"],
    },
    {
      id: "create-distance-profile",
      label: "New distance profile",
      description: "Add a new distance routing profile",
      path: "/admin/distance-profiles",
      resource: Resource.DistanceProfile,
      requiredOperation: Operation.Create,
      query: { panelType: "create" },
      keywords: ["distance", "profile", "routing"],
    },
    {
      id: "create-user",
      label: "New user",
      description: "Add a new user",
      path: "/admin/users",
      resource: Resource.User,
      requiredOperation: Operation.Create,
      query: { panelType: "create" },
      keywords: ["user"],
    },
    {
      id: "open-insights",
      label: "Operational insights",
      description: "Findings computed from your own records",
      path: "/insights",
      resource: Resource.Insight,
      requiredOperation: Operation.Read,
      keywords: ["insight", "insights", "findings", "ai", "detention", "unbilled", "on-time"],
    },
    {
      id: "open-assistant",
      label: "Open assistant",
      description: "Ask about shipments, drivers and billing, or propose a change",
      path: "/assistant",
      action: "open-assistant",
      resource: Resource.Assistant,
      requiredOperation: Operation.Read,
      keywords: ["assistant", "chat", "ai", "agent", "ask"],
    },
    {
      id: "create-home-layout",
      label: "New home screen",
      description: "Author a home screen and assign it to roles",
      path: "/admin/home-layouts/new",
      resource: Resource.HomeLayoutPreset,
      requiredOperation: Operation.Create,
      keywords: ["home", "layout", "dashboard", "widget"],
    },
    {
      id: "create-role",
      label: "New role",
      description: "Add a new role",
      path: "/admin/roles/new",
      resource: Resource.Role,
      requiredOperation: Operation.Create,
      keywords: ["role", "permissions"],
    },
    {
      id: "create-custom-field",
      label: "New custom field",
      description: "Add a new custom field",
      path: "/admin/custom-fields",
      resource: Resource.CustomFieldDefinition,
      requiredOperation: Operation.Create,
      query: { panelType: "create" },
      keywords: ["custom", "field"],
    },
  ],
};

export const appModuleGroups: AppModuleGroup[] = [
  {
    id: "core",
    label: "Core",
    moduleIds: ["home", "desk", "inbox"],
  },
  {
    id: "operations",
    label: "Operations",
    moduleIds: ["shipment", "dispatch", "fleet", "fuel", "edi"],
  },
  {
    id: "people",
    label: "People",
    moduleIds: ["hr", "payroll"],
  },
  {
    id: "finance",
    label: "Finance",
    moduleIds: ["billing", "detention", "carrier-settlements", "accounting", "reports"],
  },
  {
    id: "admin",
    label: "Admin",
    moduleIds: ["admin"],
  },
];

export const adminLinks: SidebarLink[] = [
  {
    href: "/admin/organization-settings",
    title: "Organization settings",
    group: "Organization",
    resource: Resource.Organization,
    requiredOperation: Operation.Read,
  },
  {
    href: "/admin/accounting-control",
    title: "Accounting controls",
    group: "Organization",
    resource: Resource.AccountingControl,
    requiredOperation: Operation.Read,
  },
  {
    href: "/admin/settlement-control",
    title: "Settlement control",
    group: "Organization",
    resource: Resource.SettlementControl,
    requiredOperation: Operation.Read,
    capability: OrganizationCapability.AssetOperations,
  },
  {
    href: "/admin/carrier-settlement-control",
    title: "Carrier settlement control",
    group: "Organization",
    resource: Resource.CarrierSettlementControl,
    requiredOperation: Operation.Read,
    capability: OrganizationCapability.Brokerage,
  },
  {
    href: "/admin/dash-control",
    title: "Dash control",
    group: "Organization",
    resource: Resource.DashControl,
    requiredOperation: Operation.Read,
    capability: OrganizationCapability.AssetOperations,
  },
  {
    href: "/admin/cost-control",
    title: "Cost control",
    group: "Organization",
    resource: Resource.CostingControl,
    requiredOperation: Operation.Read,
  },
  {
    href: "/admin/billing-controls/",
    title: "Billing controls",
    group: "Organization",
    resource: Resource.BillingControl,
  },
  {
    href: "/admin/invoice-adjustment-controls/",
    title: "Invoice adjustment controls",
    group: "Organization",
    resource: Resource.InvoiceAdjustmentControl,
    requiredOperation: Operation.Read,
  },
  {
    href: "/admin/data-entry-controls/",
    title: "Data entry controls",
    group: "Organization",
    resource: Resource.DataEntryControl,
    requiredOperation: Operation.Read,
  },
  {
    href: "/admin/dispatch-controls/",
    title: "Dispatch controls",
    group: "Organization",
    resource: Resource.DispatchControl,
    requiredOperation: Operation.Read,
  },
  {
    href: "/admin/shipment-controls",
    title: "Shipment controls",
    group: "Organization",
    resource: Resource.ShipmentControl,
    requiredOperation: Operation.Read,
  },
  {
    href: "/admin/agent-control",
    title: "AI control",
    group: "AI & Automation",
    resource: Resource.AgentControl,
    requiredOperation: Operation.Read,
  },
  {
    href: "/admin/document-intelligence",
    title: "Document intelligence",
    group: "AI & Automation",
    resource: Resource.DocumentControl,
    requiredOperation: Operation.Read,
  },
  {
    href: "/admin/document-parsing-rules",
    title: "Parsing rules",
    group: "Document Management",
    resource: Resource.DocumentParsingRule,
    requiredOperation: Operation.Read,
  },
  {
    href: "/admin/sequence-configs",
    title: "Sequence configuration",
    group: "Organization",
    resource: Resource.SequenceConfig,
    requiredOperation: Operation.Read,
  },
  {
    href: "/admin/distance-controls/",
    title: "Distance controls",
    group: "Organization",
    resource: Resource.DistanceControl,
    requiredOperation: Operation.Read,
  },
  {
    href: "/admin/distance-overrides/",
    title: "Distance overrides",
    group: "Organization",
    resource: Resource.DistanceOverride,
    requiredOperation: Operation.Read,
  },
  {
    href: "/admin/distance-profiles/",
    title: "Distance profiles",
    group: "Organization",
    resource: Resource.DistanceProfile,
    requiredOperation: Operation.Read,
  },
  {
    href: "/admin/stored-mileages/",
    title: "Stored mileages",
    group: "Organization",
    resource: Resource.StoredMileage,
    requiredOperation: Operation.Read,
  },
  {
    href: "/organization/consolidation-settings/",
    title: "Consolidation settings",
    group: "Organization",
    disabled: true,
  },
  {
    href: "/organization/route-controls/",
    title: "Route controls",
    group: "Organization",
    disabled: true,
  },
  {
    href: "/organization/feasibility-controls/",
    title: "Feasibility controls",
    group: "Organization",
    disabled: true,
  },
  {
    href: "/admin/hazmat-segregation-rules",
    title: "Hazmat seg. rules",
    group: "Organization",
    resource: Resource.HazmatSegregationRule,
    requiredOperation: Operation.Read,
  },
  {
    href: "/admin/hold-reasons/",
    title: "Hold reasons",
    group: "Organization",
    resource: Resource.HoldReason,
    requiredOperation: Operation.Read,
  },
  {
    href: "/admin/jurisdiction-rules/",
    title: "Jurisdiction rules",
    group: "Organization",
    resource: Resource.JurisdictionRule,
    requiredOperation: Operation.Read,
  },
  {
    href: "/admin/jurisdiction-rule-overrides/",
    title: "Carrier overrides",
    group: "Organization",
    resource: Resource.JurisdictionRuleOverride,
    requiredOperation: Operation.Read,
  },
  {
    href: "/admin/service-failure-reason-codes/",
    title: "Service failure reasons",
    group: "Organization",
    resource: Resource.ServiceFailureReasonCode,
    requiredOperation: Operation.Read,
  },
  {
    href: "/admin/users/",
    title: "Users & roles",
    group: "Organization",
    resource: Resource.User,
    requiredOperation: Operation.Read,
  },
  {
    href: "#",
    title: "Custom reports",
    group: "Reporting & Analytics",
    disabled: true,
  },
  {
    href: "#",
    title: "Scheduled reports",
    group: "Reporting & Analytics",
    disabled: true,
  },
  {
    href: "/organization/email-controls/",
    title: "Email controls",
    group: "Email & SMS",
    disabled: true,
  },
  {
    href: "/organization/email-logs/",
    title: "Email logs",
    group: "Email & SMS",
    resource: Resource.EmailLog,
    requiredOperation: Operation.Read,
  },
  {
    href: "/organization/email-profiles/",
    title: "Email Profile(s)",
    group: "Email & SMS",
    resource: Resource.EmailProfile,
    requiredOperation: Operation.Read,
  },
  {
    href: "#",
    title: "Notification types",
    group: "Notifications",
    disabled: true,
  },
  {
    href: "/admin/audit-logs",
    title: "Audit entries",
    includeBetaTag: true,
    group: "Data & Integrations",
    resource: Resource.AuditLog,
    requiredOperation: Operation.Read,
  },
  {
    href: "/admin/database-sessions",
    title: "DB sessions",
    group: "Data & Integrations",
    resource: Resource.DatabaseSession,
    requiredOperation: Operation.Read,
  },
  {
    href: "/admin/graphql-explorer",
    title: "GraphQL explorer",
    group: "Data & Integrations",
    resource: Resource.Organization,
    requiredOperation: Operation.Read,
  },
  {
    href: "/organization/ai-logs/",
    title: "AI logs",
    group: "Data & Integrations",
    disabled: true,
  },
  {
    href: "/admin/integrations",
    title: "Integrations",
    group: "Data & Integrations",
    resource: Resource.Integration,
    requiredOperation: Operation.Read,
  },
  {
    href: "/admin/inbound-mailboxes",
    title: "Inbound mailboxes",
    group: "Data & Integrations",
    resource: Resource.InboundMailbox,
    requiredOperation: Operation.Read,
  },
  {
    href: "/admin/api-keys",
    title: "API keys",
    group: "Data & Integrations",
    resource: Resource.APIKey,
    requiredOperation: Operation.Read,
  },
  {
    href: "/organization/pattern-config/",
    title: "Pattern detection",
    group: "Data & Integrations",
    disabled: true,
  },
  {
    href: "/admin/custom-fields",
    title: "Custom fields",
    group: "Data & Integrations",
    resource: Resource.CustomFieldDefinition,
    requiredOperation: Operation.Read,
  },
  {
    href: "/organization/data-retention/",
    title: "Data retention",
    group: "Data & Integrations",
    resource: Resource.Organization,
    requiredOperation: Operation.Read,
  },
  {
    href: "/organization/docker/",
    title: "Docker management",
    group: "Data & Integrations",
    disabled: true,
  },
  {
    href: "/organization/resource-editor/",
    title: "Resource editor",
    group: "Data & Integrations",
    disabled: true,
  },
  {
    href: "/admin/table-change-alerts/",
    title: "Table change alerts",
    group: "Data & Integrations",
    resource: Resource.TableChangeAlert,
    requiredOperation: Operation.Read,
  },
  {
    href: "/admin/document-operations",
    title: "Document operations",
    group: "Document Management",
    resource: Resource.DocumentOperation,
    requiredOperation: Operation.Read,
  },
  {
    href: "/organization/document-templates/",
    title: "Document templates",
    group: "Document Management",
    disabled: true,
  },
];
