import {
  AlertTriangleIcon,
  Beaker02Icon,
  BoxesIcon,
  Building07Icon,
  CalendarRangeIcon,
  ClockStopwatchIcon,
  Dataflow02Icon,
  FactoryIcon,
  File06Icon,
  FileSpreadsheetIcon,
  FuelIcon,
  Grid01Icon,
  Hash01Icon,
  type IconComponent,
  Map01Icon,
  MarkerPin01Icon,
  PackageIcon,
  PauseCircleIcon,
  ReceiptIcon,
  RouteIcon,
  SemiTruckIcon,
  Settings02Icon,
  ShieldAlertIcon,
  ShieldTickIcon,
  ShippingContainerIcon,
  SigmaIcon,
  Sliders01Icon,
  Tool01Icon,
  Truck01Icon,
  UserPlus01Icon,
  Users01Icon,
  Wallet02Icon,
} from "@trenova/shared/components/icons";

export const QUICK_ACTION_ICONS: Record<string, IconComponent> = {
  "create-home-layout": Grid01Icon,
  "create-shipment": Truck01Icon,
  "create-shipment-type": BoxesIcon,
  "create-service-type": Tool01Icon,
  "create-hazardous-material": Beaker02Icon,
  "create-commodity": PackageIcon,
  "create-accessorial-charge": ReceiptIcon,
  "create-customer": Building07Icon,
  "create-document-type": File06Icon,
  "create-formula-template": SigmaIcon,
  "create-detention-policy": ClockStopwatchIcon,
  "create-account-type": Wallet02Icon,
  "create-fiscal-year": CalendarRangeIcon,
  "create-tractor": SemiTruckIcon,
  "record-fuel-purchase": FuelIcon,
  "import-fuel-card-statement": FileSpreadsheetIcon,
  "create-trailer": ShippingContainerIcon,
  "create-equipment-type": Settings02Icon,
  "create-equipment-manufacturer": FactoryIcon,
  "create-location": MarkerPin01Icon,
  "create-worker": Users01Icon,
  "create-location-category": Dataflow02Icon,
  "create-fleet-code": Hash01Icon,
  "create-hold-reason": PauseCircleIcon,
  "create-service-failure-reason-code": AlertTriangleIcon,
  "create-hazmat-segregation-rule": ShieldAlertIcon,
  "create-distance-override": RouteIcon,
  "create-distance-profile": Map01Icon,
  "create-user": UserPlus01Icon,
  "create-role": ShieldTickIcon,
  "create-custom-field": Sliders01Icon,
};
