import type { LucideIcon } from "lucide-react";
import {
  Building2Icon,
  BoxesIcon,
  CalendarRangeIcon,
  CirclePauseIcon,
  CogIcon,
  ContainerIcon,
  FactoryIcon,
  FileTextIcon,
  FlaskConicalIcon,
  FolderTreeIcon,
  HashIcon,
  MapIcon,
  MapPinIcon,
  PackageIcon,
  ReceiptIcon,
  RouteIcon,
  ShieldAlertIcon,
  ShieldCheckIcon,
  SigmaIcon,
  SlidersHorizontalIcon,
  TableIcon,
  TractorIcon,
  TriangleAlertIcon,
  TruckIcon,
  UserPlusIcon,
  UsersIcon,
  WalletIcon,
  WrenchIcon,
} from "lucide-react";

export const QUICK_ACTION_ICONS: Record<string, LucideIcon> = {
  "create-shipment": TruckIcon,
  "create-shipment-type": BoxesIcon,
  "create-service-type": WrenchIcon,
  "create-hazardous-material": FlaskConicalIcon,
  "create-commodity": PackageIcon,
  "create-accessorial-charge": ReceiptIcon,
  "create-customer": Building2Icon,
  "create-document-type": FileTextIcon,
  "create-formula-template": SigmaIcon,
  "create-rate-table": TableIcon,
  "create-account-type": WalletIcon,
  "create-fiscal-year": CalendarRangeIcon,
  "create-tractor": TractorIcon,
  "create-trailer": ContainerIcon,
  "create-equipment-type": CogIcon,
  "create-equipment-manufacturer": FactoryIcon,
  "create-location": MapPinIcon,
  "create-worker": UsersIcon,
  "create-location-category": FolderTreeIcon,
  "create-fleet-code": HashIcon,
  "create-hold-reason": CirclePauseIcon,
  "create-service-failure-reason-code": TriangleAlertIcon,
  "create-hazmat-segregation-rule": ShieldAlertIcon,
  "create-distance-override": RouteIcon,
  "create-distance-profile": MapIcon,
  "create-user": UserPlusIcon,
  "create-role": ShieldCheckIcon,
  "create-custom-field": SlidersHorizontalIcon,
};
