package validators

import (
	"github.com/emoss08/trenova/pkg/validator/accessorialchargevalidator"
	"github.com/emoss08/trenova/pkg/validator/accountingcontrolvalidator"
	"github.com/emoss08/trenova/pkg/validator/accounttypevalidator"
	"github.com/emoss08/trenova/pkg/validator/billingcontrolvalidator"
	"github.com/emoss08/trenova/pkg/validator/commodityvalidator"
	"github.com/emoss08/trenova/pkg/validator/customervalidator"
	"github.com/emoss08/trenova/pkg/validator/dispatchcontrolvalidator"
	"github.com/emoss08/trenova/pkg/validator/distanceoverridevalidator"
	"github.com/emoss08/trenova/pkg/validator/documenttypevalidator"
	"github.com/emoss08/trenova/pkg/validator/emailvalidator"
	"github.com/emoss08/trenova/pkg/validator/equipmentmanufacturervalidator"
	"github.com/emoss08/trenova/pkg/validator/equipmenttypevalidator"
	"github.com/emoss08/trenova/pkg/validator/fiscalperiodvalidator"
	"github.com/emoss08/trenova/pkg/validator/fiscalyearvalidator"
	"github.com/emoss08/trenova/pkg/validator/fleetcodevalidator"
	"github.com/emoss08/trenova/pkg/validator/framework"
	"github.com/emoss08/trenova/pkg/validator/glaccountvalidator"
	"github.com/emoss08/trenova/pkg/validator/hazardousmaterialvalidator"
	"github.com/emoss08/trenova/pkg/validator/hazmatsegregationrulevalidator"
	"github.com/emoss08/trenova/pkg/validator/holdreasonvalidator"
	"github.com/emoss08/trenova/pkg/validator/journalentryvalidator"
	"github.com/emoss08/trenova/pkg/validator/locationcategoryvalidator"
	"github.com/emoss08/trenova/pkg/validator/locationvalidator"
	"github.com/emoss08/trenova/pkg/validator/organizationvalidator"
	"github.com/emoss08/trenova/pkg/validator/servicetypevalidator"
	"github.com/emoss08/trenova/pkg/validator/shipmentcontrolvalidator"
	"github.com/emoss08/trenova/pkg/validator/shipmenttypevalidator"
	"github.com/emoss08/trenova/pkg/validator/tractorvalidator"
	"github.com/emoss08/trenova/pkg/validator/trailervalidator"
	"github.com/emoss08/trenova/pkg/validator/workervalidator"
	"go.uber.org/fx"
)

var Module = fx.Module("validators",
	fx.Provide(
		holdreasonvalidator.NewValidator,
		hazardousmaterialvalidator.NewValidator,
		hazmatsegregationrulevalidator.NewValidator,
		billingcontrolvalidator.NewValidator,
		shipmentcontrolvalidator.NewValidator,
		locationcategoryvalidator.NewValidator,
		locationvalidator.NewValidator,
		fleetcodevalidator.NewValidator,
		emailvalidator.NewEmailProfileValidator,
		documenttypevalidator.NewValidator,
		equipmenttypevalidator.NewValidator,
		equipmentmanufacturervalidator.NewValidator,
		workervalidator.NewWorkerProfileValidator,
		workervalidator.NewWorkerPTOValidator,
		workervalidator.NewValidator,
		shipmenttypevalidator.NewValidator,
		servicetypevalidator.NewValidator,
		tractorvalidator.NewValidator,
		trailervalidator.NewValidator,
		commodityvalidator.NewValidator,
		customervalidator.NewValidator,
		accessorialchargevalidator.NewValidator,
		dispatchcontrolvalidator.NewValidator,
		organizationvalidator.NewValidator,
		distanceoverridevalidator.NewValidator,
		accounttypevalidator.NewValidator,
		fiscalyearvalidator.NewValidator,
		fiscalperiodvalidator.NewValidator,
		glaccountvalidator.NewValidator,
		accountingcontrolvalidator.NewValidator,
		journalentryvalidator.NewValidator,
	),
	fx.Options(
		framework.Module,
	),
)
