package services

import (
	"github.com/emoss08/trenova/internal/core/services/accessorialcharge"
	"github.com/emoss08/trenova/internal/core/services/accountingcontrol"
	"github.com/emoss08/trenova/internal/core/services/accounttype"
	"github.com/emoss08/trenova/internal/core/services/ailog"
	"github.com/emoss08/trenova/internal/core/services/audit"
	"github.com/emoss08/trenova/internal/core/services/auth"
	"github.com/emoss08/trenova/internal/core/services/billingcontrol"
	"github.com/emoss08/trenova/internal/core/services/classification"
	"github.com/emoss08/trenova/internal/core/services/commodity"
	"github.com/emoss08/trenova/internal/core/services/customer"
	"github.com/emoss08/trenova/internal/core/services/dataretention"
	"github.com/emoss08/trenova/internal/core/services/dedicatedlane"
	"github.com/emoss08/trenova/internal/core/services/dispatchcontrol"
	"github.com/emoss08/trenova/internal/core/services/distancecalculator"
	"github.com/emoss08/trenova/internal/core/services/distanceoverride"
	"github.com/emoss08/trenova/internal/core/services/dlsuggestion"
	"github.com/emoss08/trenova/internal/core/services/documenttype"
	"github.com/emoss08/trenova/internal/core/services/emailprofile"
	"github.com/emoss08/trenova/internal/core/services/encryption"
	"github.com/emoss08/trenova/internal/core/services/equipmentmanufacturer"
	"github.com/emoss08/trenova/internal/core/services/equipmenttype"
	"github.com/emoss08/trenova/internal/core/services/fiscalperiod"
	"github.com/emoss08/trenova/internal/core/services/fiscalyear"
	"github.com/emoss08/trenova/internal/core/services/fleetcode"
	"github.com/emoss08/trenova/internal/core/services/formulatemplate"
	"github.com/emoss08/trenova/internal/core/services/glaccount"
	"github.com/emoss08/trenova/internal/core/services/hazardousmaterial"
	"github.com/emoss08/trenova/internal/core/services/hazmatsegregationrule"
	"github.com/emoss08/trenova/internal/core/services/holdreason"
	"github.com/emoss08/trenova/internal/core/services/journalentry"
	"github.com/emoss08/trenova/internal/core/services/location"
	"github.com/emoss08/trenova/internal/core/services/locationcategory"
	"github.com/emoss08/trenova/internal/core/services/moderation"
	"github.com/emoss08/trenova/internal/core/services/notification"
	"github.com/emoss08/trenova/internal/core/services/organization"
	"github.com/emoss08/trenova/internal/core/services/pagefavorite"
	"github.com/emoss08/trenova/internal/core/services/patternconfig"
	"github.com/emoss08/trenova/internal/core/services/servicetype"
	"github.com/emoss08/trenova/internal/core/services/shipment"
	"github.com/emoss08/trenova/internal/core/services/shipmentcomment"
	"github.com/emoss08/trenova/internal/core/services/shipmentcontrol"
	"github.com/emoss08/trenova/internal/core/services/shipmenttype"
	"github.com/emoss08/trenova/internal/core/services/tableconfiguration"
	"github.com/emoss08/trenova/internal/core/services/tractor"
	"github.com/emoss08/trenova/internal/core/services/trailer"
	"github.com/emoss08/trenova/internal/core/services/user"
	"github.com/emoss08/trenova/internal/core/services/usstate"
	"github.com/emoss08/trenova/internal/core/services/variable"
	"github.com/emoss08/trenova/internal/core/services/websocket"
	"github.com/emoss08/trenova/internal/core/services/worker"
	"go.uber.org/fx"
)

var Module = fx.Module(
	"services",
	fx.Provide(
		audit.NewService,
		auth.NewService,
		encryption.NewService,
		organization.NewService,
		user.NewService,
		usstate.NewService,
		websocket.NewService,
		notification.NewService,
		pagefavorite.NewService,
		tableconfiguration.NewService,
		holdreason.NewService,
		hazardousmaterial.NewService,
		hazmatsegregationrule.NewService,
		billingcontrol.NewService,
		shipmentcontrol.NewService,
		dataretention.NewService,
		locationcategory.NewService,
		location.NewService,
		fleetcode.NewService,
		emailprofile.NewService,
		documenttype.NewService,
		equipmenttype.NewService,
		equipmentmanufacturer.NewService,
		worker.NewService,
		shipmenttype.NewService,
		servicetype.NewService,
		tractor.NewService,
		trailer.NewService,
		commodity.NewService,
		classification.NewService,
		moderation.NewService,
		ailog.NewService,
		customer.NewService,
		variable.NewQueryValidator,
		variable.NewFormatSQLValidator,
		variable.NewService,
		variable.NewResolverService,
		accessorialcharge.NewService,
		formulatemplate.NewService,
		shipment.NewService,
		shipmentcomment.NewService,
		dedicatedlane.NewService,
		dlsuggestion.NewService,
		patternconfig.NewService,
		dispatchcontrol.NewService,
		distanceoverride.NewService,
		distancecalculator.NewService,
		accounttype.NewService,
		fiscalperiod.NewService,
		fiscalyear.NewService,
		glaccount.NewService,
		journalentry.NewService,
		accountingcontrol.NewService,
	),
)
