package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"

	"github.com/emoss08/trenova/internal/api/actorutil"
	"github.com/emoss08/trenova/internal/api/graphql/gqlmodel"
	"github.com/emoss08/trenova/internal/core/domain/permission"
	"github.com/emoss08/trenova/internal/core/ports/services"
	"github.com/emoss08/trenova/shared/pulid"
)

// UpdateBillingQueueStatus is the resolver for the updateBillingQueueStatus field.
func (r *mutationResolver) UpdateBillingQueueStatus(ctx context.Context, id string, input gqlmodel.BillingQueueUpdateStatusInput) (*gqlmodel.BillingQueueItem, error) {
	authCtx, err := r.requirePermission(ctx, permission.ResourceBillingQueue, permission.OpUpdate)
	if err != nil {
		return nil, err
	}

	itemID, err := pulid.MustParse(id)
	if err != nil {
		return nil, err
	}

	item, err := r.billingQueueService.UpdateStatus(ctx, &services.UpdateBillingQueueStatusRequest{
		ItemID:              itemID,
		NewStatus:           input.Status,
		ExceptionReasonCode: input.ExceptionReasonCode,
		ExceptionNotes:      stringValue(input.ExceptionNotes),
		ReviewNotes:         stringValue(input.ReviewNotes),
		CancelReason:        stringValue(input.CancelReason),
		TenantInfo:          tenantInfo(authCtx),
	}, actorutil.FromAuthContext(authCtx))
	if err != nil {
		return nil, err
	}

	return requiredBillingQueueItemToModel(item)
}

// AssignBillingQueueBiller is the resolver for the assignBillingQueueBiller field.
func (r *mutationResolver) AssignBillingQueueBiller(ctx context.Context, id string, input gqlmodel.BillingQueueAssignInput) (*gqlmodel.BillingQueueItem, error) {
	authCtx, err := r.requirePermission(ctx, permission.ResourceBillingQueue, permission.OpAssign)
	if err != nil {
		return nil, err
	}

	itemID, err := pulid.MustParse(id)
	if err != nil {
		return nil, err
	}

	billerID, err := pulid.MustParse(input.BillerID)
	if err != nil {
		return nil, err
	}

	item, err := r.billingQueueService.AssignBiller(ctx, &services.AssignBillerRequest{
		ItemID:     itemID,
		BillerID:   billerID,
		TenantInfo: tenantInfo(authCtx),
	}, actorutil.FromAuthContext(authCtx))
	if err != nil {
		return nil, err
	}

	return requiredBillingQueueItemToModel(item)
}
