package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"

	"github.com/emoss08/trenova/internal/api/graphql/generated"
	"github.com/emoss08/trenova/internal/api/graphql/gqlmodel"
	"github.com/emoss08/trenova/internal/core/domain/distanceprofile"
	"github.com/emoss08/trenova/internal/core/domain/permission"
	"github.com/emoss08/trenova/internal/core/ports/repositories"
	"github.com/emoss08/trenova/shared/pulid"
)

// Provider is the resolver for the provider field.
func (r *distanceProfileResolver) Provider(ctx context.Context, obj *distanceprofile.DistanceProfile) (string, error) {
	return string(obj.Provider), nil
}

// DistanceProfiles is the resolver for the distanceProfiles field.
func (r *queryResolver) DistanceProfiles(ctx context.Context, input gqlmodel.DataTableConnectionInput) (*gqlmodel.DistanceProfileConnection, error) {
	authCtx, err := r.requirePermission(ctx, permission.ResourceDistanceProfile, permission.OpRead)
	if err != nil {
		return nil, err
	}

	tableInput, err := dataTableConnectionFromGraphQL(&input, tenantInfo(authCtx))
	if err != nil {
		return nil, err
	}

	result, err := r.distanceProfileService.ListConnection(
		ctx,
		&repositories.ListDistanceProfileConnectionRequest{
			Filter:                 tableInput.Filter,
			Cursor:                 tableInput.Cursor,
			DistanceProfileColumns: distanceProfileColumns(ctx, "edges.node"),
		},
	)
	if err != nil {
		return nil, err
	}

	return distanceProfileConnectionToModel(result)
}

// DistanceProfile is the resolver for the distanceProfile field.
func (r *queryResolver) DistanceProfile(ctx context.Context, id string) (*distanceprofile.DistanceProfile, error) {
	authCtx, err := r.requirePermission(ctx, permission.ResourceDistanceProfile, permission.OpRead)
	if err != nil {
		return nil, err
	}

	profileID, err := pulid.MustParse(id)
	if err != nil {
		return nil, err
	}

	return r.distanceProfileService.Get(ctx, repositories.GetDistanceProfileByIDRequest{
		ID:         profileID,
		TenantInfo: tenantInfo(authCtx),
	})
}

// DistanceProfile returns generated.DistanceProfileResolver implementation.
func (r *Resolver) DistanceProfile() generated.DistanceProfileResolver {
	return &distanceProfileResolver{r}
}

type distanceProfileResolver struct{ *Resolver }
