package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"

	"github.com/emoss08/trenova/internal/api/graphql/generated"
	"github.com/emoss08/trenova/internal/api/graphql/gqlmodel"
	"github.com/emoss08/trenova/internal/core/domain/edi"
	"github.com/emoss08/trenova/internal/core/domain/permission"
	"github.com/emoss08/trenova/internal/core/ports/repositories"
	"github.com/emoss08/trenova/internal/core/services/ediservice"
	"github.com/emoss08/trenova/pkg/pagination"
	"github.com/emoss08/trenova/shared/pulid"
	"github.com/emoss08/trenova/shared/timeutils"
)

func (r *ediMessageResolver) TransactionSet(ctx context.Context, obj *edi.EDIMessage) (string, error) {
	return string(obj.TransactionSet), nil
}

func (r *ediPartnerDocumentProfileResolver) TransactionSet(ctx context.Context, obj *edi.EDIPartnerDocumentProfile) (string, error) {
	return string(obj.TransactionSet), nil
}

func (r *ediTemplateResolver) TransactionSet(ctx context.Context, obj *edi.EDITemplate) (string, error) {
	return string(obj.TransactionSet), nil
}

func (r *ediTransferResolver) TenderPayload(ctx context.Context, obj *edi.EDITransfer) (any, error) {
	return obj.TenderPayload, nil
}

func (r *ediTransferResolver) MappingSnapshot(ctx context.Context, obj *edi.EDITransfer) (any, error) {
	return obj.MappingSnapshot, nil
}

func (r *queryResolver) EDIPartners(ctx context.Context, input gqlmodel.DataTableConnectionInput) (*gqlmodel.EDIPartnerConnection, error) {
	authCtx, err := r.requirePermission(ctx, permission.ResourceEDI, permission.OpRead)
	if err != nil {
		return nil, err
	}

	tableInput, err := dataTableConnectionFromGraphQL(ctx, &input, tenantInfo(authCtx))
	if err != nil {
		return nil, err
	}

	result, err := r.ediService.ListPartnersCursor(ctx, &repositories.ListEDIPartnersRequest{
		Filter: tableInput.Filter,
		Cursor: tableInput.Cursor,
	})
	if err != nil {
		return nil, err
	}

	return ediPartnerConnectionToModel(result)
}

func (r *queryResolver) EDICommunicationProfiles(ctx context.Context, input gqlmodel.DataTableConnectionInput) (*gqlmodel.EDICommunicationProfileConnection, error) {
	authCtx, err := r.requirePermission(ctx, permission.ResourceEDI, permission.OpRead)
	if err != nil {
		return nil, err
	}

	tableInput, err := dataTableConnectionFromGraphQL(ctx, &input, tenantInfo(authCtx))
	if err != nil {
		return nil, err
	}

	result, err := r.ediService.ListCommunicationProfilesCursor(
		ctx,
		&repositories.ListEDICommunicationProfilesRequest{
			Filter: tableInput.Filter,
			Cursor: tableInput.Cursor,
		},
	)
	if err != nil {
		return nil, err
	}

	return ediCommunicationProfileConnectionToModel(result)
}

func (r *queryResolver) EDITransfers(ctx context.Context, input gqlmodel.DataTableConnectionInput, direction gqlmodel.EDITransferDirection) (*gqlmodel.EDITransferConnection, error) {
	authCtx, err := r.requirePermission(ctx, permission.ResourceEDI, permission.OpRead)
	if err != nil {
		return nil, err
	}

	tableInput, err := dataTableConnectionFromGraphQL(ctx, &input, tenantInfo(authCtx))
	if err != nil {
		return nil, err
	}

	req := &repositories.ListEDITransfersRequest{
		Filter: tableInput.Filter,
		Cursor: tableInput.Cursor,
	}
	var result *pagination.CursorListResult[*edi.EDITransfer]
	if direction == gqlmodel.EDITransferDirectionInbound {
		result, err = r.ediService.ListInboundTransfersCursor(ctx, req)
	} else {
		result, err = r.ediService.ListOutboundTransfersCursor(ctx, req)
	}
	if err != nil {
		return nil, err
	}

	return ediTransferConnectionToModel(result)
}

func (r *queryResolver) EDIMessages(ctx context.Context, input gqlmodel.DataTableConnectionInput, transactionSet *string, direction *edi.DocumentDirection, partnerID *string) (*gqlmodel.EDIMessageConnection, error) {
	authCtx, err := r.requirePermission(ctx, permission.ResourceEDI, permission.OpRead)
	if err != nil {
		return nil, err
	}

	tableInput, err := dataTableConnectionFromGraphQL(ctx, &input, tenantInfo(authCtx))
	if err != nil {
		return nil, err
	}

	req := &repositories.ListEDIMessagesRequest{
		Filter: tableInput.Filter,
		Cursor: tableInput.Cursor,
	}
	if transactionSet != nil {
		req.TransactionSet = edi.TransactionSet(*transactionSet)
	}
	if direction != nil {
		req.Direction = *direction
	}
	if partnerID != nil && *partnerID != "" {
		parsed, parseErr := pulid.MustParse(*partnerID)
		if parseErr != nil {
			return nil, parseErr
		}
		req.PartnerID = parsed
	}

	result, err := r.ediService.ListMessagesCursor(ctx, req)
	if err != nil {
		return nil, err
	}

	return ediMessageConnectionToModel(result)
}

func (r *queryResolver) EDIInboundFiles(ctx context.Context, input gqlmodel.DataTableConnectionInput, status *edi.InboundFileStatus, partnerID *string) (*gqlmodel.EDIInboundFileConnection, error) {
	authCtx, err := r.requirePermission(ctx, permission.ResourceEDI, permission.OpRead)
	if err != nil {
		return nil, err
	}

	tableInput, err := dataTableConnectionFromGraphQL(ctx, &input, tenantInfo(authCtx))
	if err != nil {
		return nil, err
	}

	req := &repositories.ListEDIInboundFilesRequest{
		Filter: tableInput.Filter,
		Cursor: tableInput.Cursor,
	}
	if status != nil {
		req.Status = *status
	}
	if partnerID != nil && *partnerID != "" {
		parsed, parseErr := pulid.MustParse(*partnerID)
		if parseErr != nil {
			return nil, parseErr
		}
		req.PartnerID = parsed
	}

	result, err := r.ediInboundService.ListInboundFilesCursor(ctx, req)
	if err != nil {
		return nil, err
	}

	return ediInboundFileConnectionToModel(result)
}

func (r *queryResolver) EDITemplates(ctx context.Context, input gqlmodel.DataTableConnectionInput, status *edi.TemplateStatus, transactionSet *string, direction *edi.DocumentDirection) (*gqlmodel.EDITemplateConnection, error) {
	authCtx, err := r.requirePermission(ctx, permission.ResourceEDI, permission.OpRead)
	if err != nil {
		return nil, err
	}

	tableInput, err := dataTableConnectionFromGraphQL(ctx, &input, tenantInfo(authCtx))
	if err != nil {
		return nil, err
	}

	req := &repositories.ListEDITemplatesRequest{
		Filter: tableInput.Filter,
		Cursor: tableInput.Cursor,
	}
	if status != nil {
		req.Status = *status
	}
	if transactionSet != nil && *transactionSet != "" {
		req.TransactionSet = edi.TransactionSet(*transactionSet)
	}
	if direction != nil {
		req.Direction = *direction
	}

	result, err := r.ediService.ListTemplatesCursor(ctx, req)
	if err != nil {
		return nil, err
	}

	return ediTemplateConnectionToModel(result)
}

func (r *queryResolver) EDIMappingProfiles(ctx context.Context, input gqlmodel.DataTableConnectionInput, partnerID *string) (*gqlmodel.EDIMappingProfileConnection, error) {
	authCtx, err := r.requirePermission(ctx, permission.ResourceEDI, permission.OpRead)
	if err != nil {
		return nil, err
	}

	tableInput, err := dataTableConnectionFromGraphQL(ctx, &input, tenantInfo(authCtx))
	if err != nil {
		return nil, err
	}

	req := &repositories.ListEDIMappingProfilesRequest{
		Filter: tableInput.Filter,
		Cursor: tableInput.Cursor,
	}
	if partnerID != nil && *partnerID != "" {
		parsed, parseErr := pulid.MustParse(*partnerID)
		if parseErr != nil {
			return nil, parseErr
		}
		req.PartnerID = parsed
	}

	result, err := r.ediService.ListMappingProfilesCursor(ctx, req)
	if err != nil {
		return nil, err
	}

	return ediMappingProfileConnectionToModel(result)
}

func (r *queryResolver) EDITestCases(ctx context.Context, input gqlmodel.DataTableConnectionInput, partnerDocumentProfileID *string) (*gqlmodel.EDITestCaseConnection, error) {
	authCtx, err := r.requirePermission(ctx, permission.ResourceEDI, permission.OpRead)
	if err != nil {
		return nil, err
	}

	tableInput, err := dataTableConnectionFromGraphQL(ctx, &input, tenantInfo(authCtx))
	if err != nil {
		return nil, err
	}

	req := &repositories.ListEDITestCasesRequest{
		Filter: tableInput.Filter,
		Cursor: tableInput.Cursor,
	}
	if partnerDocumentProfileID != nil && *partnerDocumentProfileID != "" {
		parsed, parseErr := pulid.MustParse(*partnerDocumentProfileID)
		if parseErr != nil {
			return nil, parseErr
		}
		req.PartnerDocumentProfileID = parsed
	}

	result, err := r.ediService.ListTestCasesCursor(ctx, req)
	if err != nil {
		return nil, err
	}

	return ediTestCaseConnectionToModel(result)
}

func (r *queryResolver) EDISummary(ctx context.Context, sinceHours *int) (*gqlmodel.EDISummary, error) {
	authCtx, err := r.requirePermission(ctx, permission.ResourceEDI, permission.OpRead)
	if err != nil {
		return nil, err
	}

	req := &ediservice.GetEDISummaryRequest{TenantInfo: tenantInfo(authCtx)}
	if sinceHours != nil && *sinceHours > 0 {
		req.Since = timeutils.NowUnix() - int64(*sinceHours)*3600
	}
	summary, err := r.ediService.GetEDISummary(ctx, req)
	if err != nil {
		return nil, err
	}

	return ediSummaryToModel(summary), nil
}

func (r *queryResolver) EDIPartnerScorecards(ctx context.Context, sinceHours *int) ([]*gqlmodel.EDIPartnerScorecard, error) {
	authCtx, err := r.requirePermission(ctx, permission.ResourceEDI, permission.OpRead)
	if err != nil {
		return nil, err
	}

	req := &ediservice.GetEDIPartnerScorecardsRequest{TenantInfo: tenantInfo(authCtx)}
	if sinceHours != nil && *sinceHours > 0 {
		req.Since = timeutils.NowUnix() - int64(*sinceHours)*3600
	}
	rows, err := r.ediService.GetEDIPartnerScorecards(ctx, req)
	if err != nil {
		return nil, err
	}
	return ediPartnerScorecardsToModel(rows), nil
}

func (r *queryResolver) EDIPartnerReadiness(ctx context.Context, partnerIds []string) ([]*gqlmodel.EDIPartnerReadinessState, error) {
	authCtx, err := r.requirePermission(ctx, permission.ResourceEDI, permission.OpRead)
	if err != nil {
		return nil, err
	}
	ids := make([]pulid.ID, 0, len(partnerIds))
	for _, raw := range partnerIds {
		id, parseErr := pulid.MustParse(raw)
		if parseErr != nil {
			continue
		}
		ids = append(ids, id)
	}
	states, err := r.ediService.GetPartnerReadiness(ctx, &ediservice.GetEDIPartnerReadinessRequest{
		TenantInfo: tenantInfo(authCtx),
		PartnerIDs: ids,
	})
	if err != nil {
		return nil, err
	}
	models := make([]*gqlmodel.EDIPartnerReadinessState, 0, len(states))
	for _, state := range states {
		models = append(models, &gqlmodel.EDIPartnerReadinessState{
			PartnerID:      state.PartnerID.String(),
			Ready:          state.Ready,
			CompletedCount: state.CompletedCount,
			TotalCount:     state.TotalCount,
		})
	}
	return models, nil
}

func (r *queryResolver) EDIVolumeSeries(ctx context.Context, sinceHours *int) ([]*gqlmodel.EDIVolumePoint, error) {
	authCtx, err := r.requirePermission(ctx, permission.ResourceEDI, permission.OpRead)
	if err != nil {
		return nil, err
	}

	req := &ediservice.GetEDIVolumeSeriesRequest{TenantInfo: tenantInfo(authCtx)}
	if sinceHours != nil && *sinceHours > 0 {
		req.Since = timeutils.NowUnix() - int64(*sinceHours)*3600
	}
	series, err := r.ediService.GetEDIVolumeSeries(ctx, req)
	if err != nil {
		return nil, err
	}
	return ediVolumeSeriesToModel(series), nil
}

func (r *Resolver) EdiMessage() generated.EdiMessageResolver { return &ediMessageResolver{r} }

func (r *Resolver) EdiPartnerDocumentProfile() generated.EdiPartnerDocumentProfileResolver {
	return &ediPartnerDocumentProfileResolver{r}
}

func (r *Resolver) EdiTemplate() generated.EdiTemplateResolver { return &ediTemplateResolver{r} }

func (r *Resolver) EdiTransfer() generated.EdiTransferResolver { return &ediTransferResolver{r} }

type (
	ediMessageResolver                struct{ *Resolver }
	ediPartnerDocumentProfileResolver struct{ *Resolver }
	ediTemplateResolver               struct{ *Resolver }
	ediTransferResolver               struct{ *Resolver }
)
