package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"

	"github.com/emoss08/trenova/internal/api/graphql/gqlmodel"
	"github.com/emoss08/trenova/internal/core/domain/permission"
	"github.com/emoss08/trenova/internal/core/domain/ratetable"
	"github.com/emoss08/trenova/internal/core/ports/repositories"
	"github.com/emoss08/trenova/shared/pulid"
)

// RateTables is the resolver for the rateTables field.
func (r *queryResolver) RateTables(ctx context.Context, input gqlmodel.DataTableConnectionInput) (*gqlmodel.RateTableConnection, error) {
	authCtx, err := r.requirePermission(ctx, permission.ResourceRateTable, permission.OpRead)
	if err != nil {
		return nil, err
	}

	tableInput, err := dataTableConnectionFromGraphQL(&input, tenantInfo(authCtx))
	if err != nil {
		return nil, err
	}

	result, err := r.rateTableService.ListConnection(
		ctx,
		&repositories.ListRateTableConnectionRequest{
			Filter:           tableInput.Filter,
			Cursor:           tableInput.Cursor,
			RateTableColumns: rateTableColumns(ctx, "edges.node"),
		},
	)
	if err != nil {
		return nil, err
	}

	return rateTableConnectionToModel(result)
}

// RateTable is the resolver for the rateTable field.
func (r *queryResolver) RateTable(ctx context.Context, id string) (*ratetable.RateTable, error) {
	authCtx, err := r.requirePermission(ctx, permission.ResourceRateTable, permission.OpRead)
	if err != nil {
		return nil, err
	}

	rateTableID, err := pulid.MustParse(id)
	if err != nil {
		return nil, err
	}

	return r.rateTableService.GetByID(ctx, &repositories.GetRateTableByIDRequest{
		RateTableID: rateTableID,
		TenantInfo:  tenantInfo(authCtx),
	})
}
