package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"

	"github.com/emoss08/trenova/internal/api/graphql/gqlmodel"
	"github.com/emoss08/trenova/internal/core/domain/permission"
	"github.com/emoss08/trenova/internal/core/domain/worker"
	"github.com/emoss08/trenova/internal/core/ports/repositories"
	"github.com/emoss08/trenova/internal/core/services/timesheetservice"
	"github.com/emoss08/trenova/shared/pulid"
)

func (r *mutationResolver) ClockIn(ctx context.Context, input gqlmodel.ClockInput) (*worker.TimeClockEntry, error) {
	authCtx, workerID, err := r.requireTimesheetWorkerScope(ctx, permission.OpCreate, input.WorkerID)
	if err != nil {
		return nil, err
	}

	return r.timesheetService.ClockIn(ctx, &timesheetservice.ClockRequest{
		WorkerID:   workerID,
		At:         int64Value(input.At),
		Source:     worker.TimeEntrySourceClock,
		PayCodeID:  mustOptionalID(input.PayCodeID),
		Note:       stringValue(input.Note),
		TenantInfo: tenantInfo(authCtx),
		UserID:     authCtx.UserID,
	})
}

func (r *mutationResolver) ClockOut(ctx context.Context, input gqlmodel.ClockInput) (*worker.TimeClockEntry, error) {
	authCtx, workerID, err := r.requireTimesheetWorkerScope(ctx, permission.OpCreate, input.WorkerID)
	if err != nil {
		return nil, err
	}

	return r.timesheetService.ClockOut(ctx, &timesheetservice.ClockRequest{
		WorkerID:     workerID,
		At:           int64Value(input.At),
		BreakMinutes: int32(intValue(input.BreakMinutes)), //nolint:gosec // validated on the entry
		Note:         stringValue(input.Note),
		TenantInfo:   tenantInfo(authCtx),
		UserID:       authCtx.UserID,
	})
}

func (r *mutationResolver) RecordTimeEntry(ctx context.Context, input gqlmodel.RecordTimeEntryInput) (*worker.TimeClockEntry, error) {
	authCtx, workerID, err := r.requireTimesheetWorkerScope(ctx, permission.OpUpdate, input.WorkerID)
	if err != nil {
		return nil, err
	}

	entryID, err := optionalID(input.ID)
	if err != nil {
		return nil, invalidIDError("id", "Entry is invalid")
	}

	return r.timesheetService.RecordEntry(ctx, &timesheetservice.RecordEntryRequest{
		ID:           entryID,
		WorkerID:     workerID,
		ClockedInAt:  int64(input.ClockedInAt),
		ClockedOutAt: int64(input.ClockedOutAt),
		BreakMinutes: int32(intValue(input.BreakMinutes)), //nolint:gosec // validated on the entry
		PayCodeID:    mustOptionalID(input.PayCodeID),
		Note:         stringValue(input.Note),
		Reason:       input.Reason,
		TenantInfo:   tenantInfo(authCtx),
		UserID:       authCtx.UserID,
	})
}

func (r *mutationResolver) DeleteTimeEntry(ctx context.Context, input gqlmodel.DeleteTimeEntryInput) (bool, error) {
	authCtx, err := r.requirePermission(ctx, permission.ResourceTimesheet, permission.OpDelete)
	if err != nil {
		return false, err
	}

	entryID, err := pulid.MustParse(input.ID)
	if err != nil {
		return false, invalidIDError("id", "Entry is invalid")
	}

	if err = r.timesheetService.DeleteEntry(ctx, &timesheetservice.DeleteEntryRequest{
		ID:         entryID,
		Reason:     input.Reason,
		TenantInfo: tenantInfo(authCtx),
		UserID:     authCtx.UserID,
	}); err != nil {
		return false, err
	}

	return true, nil
}

func (r *mutationResolver) TransitionTimesheet(ctx context.Context, input gqlmodel.TransitionTimesheetInput) (*worker.Timesheet, error) {
	sheetID, err := pulid.MustParse(input.ID)
	if err != nil {
		return nil, invalidIDError("id", "Timesheet is invalid")
	}

	authCtx, err := r.requireAuth(ctx)
	if err != nil {
		return nil, err
	}

	sheet, err := r.timesheetService.GetTimesheet(ctx, &repositories.GetTimesheetByIDRequest{
		ID:         sheetID,
		TenantInfo: tenantInfo(authCtx),
	})
	if err != nil {
		return nil, err
	}

	// Each answer is a different grant: handing a week over is not the same
	// act as signing it off. The worker is read off the sheet rather than
	// taken from the caller: an id supplied alongside the one being acted on
	// is an id somebody can lie about.
	if _, _, err = r.requireTeamScope(
		ctx,
		permission.ResourceTimesheet,
		timesheetPermissionFor(input.Status),
		worker.ApprovalScopeAll,
		sheet.WorkerID,
	); err != nil {
		return nil, err
	}

	return r.timesheetService.Transition(ctx, &timesheetservice.TransitionTimesheetRequest{
		ID:         sheetID,
		Status:     input.Status,
		Note:       stringValue(input.Note),
		TenantInfo: tenantInfo(authCtx),
		UserID:     authCtx.UserID,
	})
}

func (r *mutationResolver) GeneratePayrollExport(ctx context.Context, input gqlmodel.GeneratePayrollExportInput) (*worker.PayrollExport, error) {
	authCtx, err := r.requirePermission(ctx, permission.ResourceTimesheet, permission.OpExport)
	if err != nil {
		return nil, err
	}

	return r.timesheetService.GenerateExport(ctx, &timesheetservice.GenerateExportRequest{
		PeriodStart: int64(input.PeriodStart),
		PeriodEnd:   int64(input.PeriodEnd),
		Note:        stringValue(input.Note),
		TenantInfo:  tenantInfo(authCtx),
		UserID:      authCtx.UserID,
	})
}

func (r *mutationResolver) VoidPayrollExport(ctx context.Context, input gqlmodel.VoidPayrollExportInput) (*worker.PayrollExport, error) {
	authCtx, err := r.requirePermission(ctx, permission.ResourceTimesheet, permission.OpExport)
	if err != nil {
		return nil, err
	}

	exportID, err := pulid.MustParse(input.ID)
	if err != nil {
		return nil, invalidIDError("id", "Payroll run is invalid")
	}

	return r.timesheetService.VoidExport(ctx, &timesheetservice.VoidExportRequest{
		ID:         exportID,
		Reason:     input.Reason,
		TenantInfo: tenantInfo(authCtx),
		UserID:     authCtx.UserID,
	})
}

func (r *queryResolver) Timesheets(ctx context.Context, filter *gqlmodel.TimesheetFilterInput) ([]*worker.Timesheet, error) {
	authCtx, err := r.requirePermission(ctx, permission.ResourceTimesheet, permission.OpRead)
	if err != nil {
		return nil, err
	}

	req := &repositories.ListTimesheetsRequest{
		TenantInfo:    tenantInfo(authCtx),
		IncludeWorker: true,
	}
	if filter != nil {
		if req.WorkerID, err = optionalID(filter.WorkerID); err != nil {
			return nil, invalidIDError("workerId", "Worker is invalid")
		}
		req.Statuses = filter.Statuses
		req.From = int64Value(filter.From)
		req.To = int64Value(filter.To)
		req.UnexportedOnly = boolValue(filter.UnexportedOnly)
		req.Limit = intValue(filter.Limit)
		if boolValue(filter.TeamOnly) {
			if req.ManagerIDs, err = r.rotaManagerIDs(
				ctx,
				authCtx.UserID,
				tenantInfo(authCtx),
			); err != nil {
				return nil, err
			}
		}
	}

	return r.timesheetService.ListTimesheets(ctx, req)
}

func (r *queryResolver) Timesheet(ctx context.Context, id string) (*worker.Timesheet, error) {
	authCtx, err := r.requirePermission(ctx, permission.ResourceTimesheet, permission.OpRead)
	if err != nil {
		return nil, err
	}

	sheetID, err := pulid.MustParse(id)
	if err != nil {
		return nil, invalidIDError("id", "Timesheet is invalid")
	}

	return r.timesheetService.GetTimesheet(ctx, &repositories.GetTimesheetByIDRequest{
		ID:             sheetID,
		TenantInfo:     tenantInfo(authCtx),
		IncludeEntries: true,
		IncludeWorker:  true,
	})
}

func (r *queryResolver) TimeClockEntries(ctx context.Context, workerID string, from *int, to *int, limit *int) ([]*worker.TimeClockEntry, error) {
	authCtx, id, err := r.requireTimesheetWorkerScope(ctx, permission.OpRead, workerID)
	if err != nil {
		return nil, err
	}

	return r.timesheetService.ListEntries(ctx, &repositories.ListTimeClockEntriesRequest{
		TenantInfo: tenantInfo(authCtx),
		WorkerID:   id,
		From:       int64Value(from),
		To:         int64Value(to),
		Limit:      intValue(limit),
	})
}

func (r *queryResolver) OpenTimeClockEntry(ctx context.Context, workerID string) (*worker.TimeClockEntry, error) {
	authCtx, id, err := r.requireTimesheetWorkerScope(ctx, permission.OpRead, workerID)
	if err != nil {
		return nil, err
	}

	return r.timesheetService.OpenEntry(ctx, tenantInfo(authCtx), id)
}

func (r *queryResolver) OpenTimeClockEntries(ctx context.Context, teamOnly *bool, limit *int) ([]*worker.TimeClockEntry, error) {
	authCtx, err := r.requirePermission(ctx, permission.ResourceTimesheet, permission.OpRead)
	if err != nil {
		return nil, err
	}

	req := &repositories.ListTimeClockEntriesRequest{
		TenantInfo:    tenantInfo(authCtx),
		OpenOnly:      true,
		IncludeWorker: true,
		Limit:         intValue(limit),
	}
	if boolValue(teamOnly) {
		if req.ManagerIDs, err = r.rotaManagerIDs(ctx, authCtx.UserID, tenantInfo(authCtx)); err != nil {
			return nil, err
		}
	}

	return r.timesheetService.ListEntries(ctx, req)
}

func (r *queryResolver) PayrollExports(ctx context.Context, limit *int) ([]*worker.PayrollExport, error) {
	authCtx, err := r.requirePermission(ctx, permission.ResourceTimesheet, permission.OpExport)
	if err != nil {
		return nil, err
	}

	return r.timesheetService.ListExports(ctx, &repositories.ListPayrollExportsRequest{
		TenantInfo: tenantInfo(authCtx),
		Limit:      intValue(limit),
	})
}

func (r *queryResolver) PayrollExport(ctx context.Context, id string) (*worker.PayrollExport, error) {
	authCtx, err := r.requirePermission(ctx, permission.ResourceTimesheet, permission.OpExport)
	if err != nil {
		return nil, err
	}

	exportID, err := pulid.MustParse(id)
	if err != nil {
		return nil, invalidIDError("id", "Payroll run is invalid")
	}

	return r.timesheetService.GetExport(ctx, tenantInfo(authCtx), exportID)
}

func (r *queryResolver) PayrollExportRows(ctx context.Context, id string) ([]*timesheetservice.PayrollExportRow, error) {
	authCtx, err := r.requirePermission(ctx, permission.ResourceTimesheet, permission.OpExport)
	if err != nil {
		return nil, err
	}

	exportID, err := pulid.MustParse(id)
	if err != nil {
		return nil, invalidIDError("id", "Payroll run is invalid")
	}

	return r.timesheetService.ExportRows(ctx, tenantInfo(authCtx), exportID)
}
