const R4 = (() => { let x = 7; return () => (x = (x * 9301 + 49297) % 233280) / 233280; })();
const pick = a => a[Math.floor(R4() * a.length)];
const AG_ID = ["billing", "compliance", "dispatch", "fuel", "help", "recv", "report", "settle", "digest", "billev", "coverage", "inbox"];
const QUAL = [
  ["dispatch", 0.81, -6, 0.74, 61, 40, "Completed"], ["billing", 0.91, 2, 0.88, 34, 40, "Completed"], ["compliance", 0.89, 0, 0.9, 12, 30, "Skipped"], ["report", 0.86, 1, 0.8, 22, 25, "Completed"],
  ["recv", 0.84, -1, 0.83, 9, 25, "Completed"], ["settle", 0.9, 3, null, 0, 20, "Completed"], ["fuel", 0.78, 0, 0.71, 7, 15, "BudgetStopped"], ["help", 0.94, 1, 0.92, 48, 30, "Completed"], ["inbox", 0.83, 4, 0.79, 14, 30, "Running"],
].map(([id, s, d, sat, rt, cases, st], i) => ({ id, score: s, delta: d, sat, ratings: rt, cases, st, spark: Array.from({ length: 14 }, (_, k) => Math.max(0.6, Math.min(0.98, s - d / 100 * (k < 11 ? 1 : 0) + (R4() - 0.5) * 0.04))) }));
const RUN_ST = { Running: ["Running", "b"], Completed: ["Completed", "k"], Skipped: ["Skipped", ""], BudgetStopped: ["Budget stopped", "w"], Failed: ["Failed", "d"] };
const SUITE = Array.from({ length: 26 }, (_, i) => { const q = QUAL[i % QUAL.length]; const st = i < QUAL.length ? q.st : pick(["Completed", "Completed", "Completed", "Skipped", "Failed"]); const sc = st === "Skipped" || st === "Failed" ? null : Math.round((q.score + (R4() - 0.5) * 0.06) * 100); return { id: "sr" + i, ag: q.id, st, n: st === "Skipped" ? 0 : st === "BudgetStopped" ? Math.round(q.cases * 0.6) : q.cases, of: q.cases, score: sc, delta: i < QUAL.length ? q.delta : Math.round((R4() - 0.5) * 6), cost: st === "Skipped" ? 0 : +(q.cases * (0.004 + R4() * 0.004)).toFixed(2), when: i < QUAL.length ? "Today 2:00 AM" : ["Yesterday 2:00 AM", "Oct 5, 2:00 AM", "Oct 4, 2:00 AM"][Math.floor(i / QUAL.length) - 1] || "Oct 3, 2:00 AM" }; });
const WORST = [
  ["dispatch", "Assistant answer", "Marcus Reed is available for SHP-48302.", "He's on a 34-hour reset until tomorrow — it should have checked HOS.", "Dana Ortiz", "Today 9:12 AM"],
  ["dispatch", "Assistant answer", "Ridgeline Freight's insurance is current.", "It expired on the 30th. This almost went out.", "Mike Chen", "Yesterday 4:40 PM"],
  ["billing", "Answer from another agent", "INV-20877 can be released; the POD is attached.", "POD is for the wrong stop.", "Sarah Alvarez", "Yesterday 11:05 AM"],
  ["report", "Briefing section", "On-time delivery rose to 96% this week.", "That counts cancelled loads as on time.", "Jordan Lee", "Oct 5"],
  ["fuel", "Assistant answer", "Indiana miles for Q3 are 41,208.", "Missing the two loads from the Gary yard.", "Priya Shah", "Oct 4"],
  ["recv", "Insight", "Acme Foods is 12 days slow on average.", "They pay on net 45 — 12 days over net 30 is expected.", "Sarah Alvarez", "Oct 3"],
].map(([ag, where, a, why, who, when], i) => ({ id: "w" + i, ag, where, a, why, who, when }));
const SUBJ = ["SHP-48302", "SHP-48211", "INV-20931", "SHP-48190", "Acme Foods", "SHP-48315", "Ridgeline Freight", "Q3 IFTA", "INV-20877", "Marcus Reed", "SHP-48277", null];
const SUMS = { billing: ["Proposed releasing the hold on INV-20931", "Found a rate mismatch on SHP-48211", "Asked for the missing POD"], dispatch: ["Proposed Marcus Reed for SHP-48302", "Proposed tendering SHP-48315 to Ridgeline", "Answered where SHP-48190 is"], inbox: ["Filed a rate confirmation to SHP-48277", "Drafted a reply to a status question", "Matched an EDI 204 to a new load"], coverage: ["Reviewed 6 uncovered moves", "Proposed 2 driver assignments"], billev: ["Diagnosed a billing hold", "Flagged INV-20877 for review"], digest: ["Sent the morning digest to 8 people"], report: ["Built a lane margin report"], compliance: ["Listed 3 expiring medical cards"], help: ["Explained how to split a load"], recv: ["Ranked who to chase first"], settle: ["Drafted this week's settlements"], fuel: ["Matched 41 fuel card lines"] };
const TRIG_L = { Chat: "A person", Scheduled: "Schedule", Event: "Event", Delegated: "Another agent" };
const RUNS = Array.from({ length: 64 }, (_, i) => { const ag = i < 4 ? ["dispatch", "inbox", "billing", "coverage"][i] : pick(AG_ID); const a = AGENTS0.find(x => x.id === ag); const st = i === 0 ? "Running" : i === 2 || i === 9 ? "Failed" : i === 5 ? "Waiting" : "Completed"; const trig = i === 7 ? "Delegated" : a.trig; return { id: "run_" + (9000 - i).toString(36).toUpperCase().padStart(6, "0"), ag, trig, st, handed: trig === "Delegated" ? "Billing exceptions" : null, subj: pick(SUBJ), sum: st === "Failed" ? "Could not connect to Workstation vLLM" : pick(SUMS[ag] || ["Answered a question"]), model: st === "Failed" ? "meta-llama/Llama-3.3-70B-Instruct" : ag === "inbox" || ag === "billev" ? "qwen2.5:14b" : "meta-llama/Llama-3.3-70B-Instruct", t: i, dur: st === "Running" ? null : Math.round(2 + R4() * 40), tok: Math.round(1200 + R4() * 9000) }; });
const PROP_ST = { Pending: ["Awaiting decision", "w"], Approved: ["Approved", "k"], Modified: ["Approved with changes", "k"], Rejected: ["Rejected", "d"], Expired: ["Expired", ""], Executed: ["Done", "k"] };
const PROPS = [
  ...Object.entries(PROPOSALS).flatMap(([ag, xs]) => xs.map((p, i) => ({ ag, tool: { Assign: "assign_driver", Tender: "tender_to_carrier", Reschedule: "reschedule_appointment", "Swap trailer": "swap_trailer", "Release hold": "release_billing_hold", "Re-rate": "rerate_shipment", "Write off": "write_off_short_pay" }[p.k], st: "Pending", tier: "ActWithApproval", conf: 0.62 + R4() * 0.33, why: p.k + " " + p.t, ago: p.ago, taint: p.k === "Tender" }))),
  ...Array.from({ length: 30 }, (_, i) => ({ ag: pick(["billing", "dispatch", "inbox", "recv", "settle"]), tool: pick(["assign_driver", "release_billing_hold", "correct_charge_code", "attach_document_to_shipment", "send_customer_reply", "apply_customer_payment", "tender_to_carrier"]), st: pick(["Approved", "Approved", "Executed", "Modified", "Rejected", "Expired"]), tier: pick(["ActWithApproval", "Propose"]), conf: 0.5 + R4() * 0.48, why: pick(["POD attached and signature date matches delivery", "Closest driver with hours left, 14 mi out", "Contract lane rate is $2.18, invoice billed $2.41", "Customer asked for status; shipment is on time", "Payment of $4,120 matches INV-20811 exactly", "Carrier accepts this lane 92% of the time"]), ago: ["1h", "3h", "Yesterday", "Oct 5", "Oct 4"][Math.floor(i / 6)], taint: R4() < 0.2 })),
].map((p, i) => ({ ...p, id: "prop_" + i, run: RUNS[(i * 3) % RUNS.length].id }));
const EXC = [
  ["dispatch", "Tool failed", "assign_driver returned 409: driver already assigned to SHP-48299", "Open", "12 min ago"], ["inbox", "Budget reached", "Daily token budget used before the 9 AM batch finished", "Open", "1 h ago"],
  ["billing", "Model error", "Workstation vLLM: connection refused", "Resolved", "5:21 AM"], ["coverage", "Loop stopped", "Stopped after 12 tool calls without an answer", "Resolved", "Yesterday"], ["recv", "Tool failed", "apply_customer_payment: invoice version changed", "Resolved", "Oct 5"],
].map(([ag, kind, msg, st, when], i) => ({ id: "ex" + i, ag, kind, msg, st, when }));
const AUD_ACT = [["Proposal approved", "person"], ["Tool executed", "agent"], ["Proposal created", "agent"], ["Agent settings changed", "person"], ["Memory approved", "person"], ["Provider tested", "person"], ["Proposal rejected", "person"], ["Tier earned", "system"], ["Outside text read", "agent"]];
const AUDIT = Array.from({ length: 80 }, (_, i) => { const [act, kind] = AUD_ACT[i % AUD_ACT.length]; const ag = pick(AG_ID); const a = AGENTS0.find(x => x.id === ag); return { seq: 48211 - i, act, kind, who: kind === "person" ? pick(["Sarah Alvarez", "Mike Chen", "Dana Ortiz", "System Administrator"]) : kind === "system" ? "Trenova" : a.n, ag, subj: pick(SUBJ) || "—", when: i < 8 ? (i * 7 + 2) + " min ago" : i < 30 ? "Today " + (9 - Math.floor(i / 4)) + ":" + String((i * 13) % 60).padStart(2, "0") + " AM" : i < 55 ? "Yesterday" : "Oct 5", hash: Array.from({ length: 16 }, () => "0123456789abcdef"[Math.floor(R4() * 16)]).join(""), sealed: i > 6 }; });
const EXPORTS = [["ai-audit-2026-09.jsonl", "Sep 1 – Sep 30", 41208, "System Administrator", "Oct 1", "Ready"], ["ai-audit-2026-q3-billing.csv", "Jul 1 – Sep 30 · Billing", 9311, "Sarah Alvarez", "Oct 2", "Ready"], ["ai-audit-2026-08.jsonl", "Aug 1 – Aug 31", 38640, "System Administrator", "Sep 1", "Expired"]].map(([f, r, n, by, when, st]) => ({ f, r, n, by, when, st }));
Object.assign(window, { QUAL, RUN_ST, SUITE, WORST, RUNS, TRIG_L, PROP_ST, PROPS, EXC, AUDIT, EXPORTS });
