function QualityTab({ S, A, searchRef }) {
  const [v, setV] = React.useState("agents"); const [open, setOpen] = React.useState(null); const [set, setSet] = React.useState(false);
  const [cfg, setCfg] = React.useState({ on: true, hour: 2, cases: 40, nightly: 1, monthly: 20, judge: true, sample: 25, thr: 5 });
  const reg = QUAL.filter(q => q.delta <= -cfg.thr); const avg = QUAL.reduce((t, q) => t + q.score, 0) / QUAL.length;
  const spend = SUITE.reduce((t, s) => t + s.cost, 0);
  const rated = QUAL.filter(q => q.sat != null), sat = rated.reduce((t, q) => t + q.sat * q.ratings, 0) / rated.reduce((t, q) => t + q.ratings, 0), nr = QUAL.reduce((t, q) => t + q.ratings, 0);
  const worstAg = reg[0] && agOf(reg[0].id);
  return (
    <div className="tabp">
      <Nova ctx="Quality" ctl={worstAg && <><button className="btn ink lg" onClick={() => setOpen({ t: "agent", r: reg[0] })}>Look at {worstAg.n}</button><span>Last night's sweep · {cfg.hour}:00 AM</span></>}>
        Agents score <b>{Math.round(avg * 100)}%</b> against their golden sets, and people liked <b>{Math.round(sat * 100)}%</b> of the answers they rated.{worstAg && <> <span className="ref d" onClick={() => setOpen({ t: "agent", r: reg[0] })}>{worstAg.n}</span> dropped {Math.abs(reg[0].delta)} points after Tuesday's change — most low ratings are about hours of service.</>}
      </Nova>
      <Figs items={[["Satisfaction", Math.round(sat * 100) + "%", "last 30 days"], ["Ratings", nr, "thumbs up and down"], ["Quality score", Math.round(avg * 100) + "%", QUAL.length + " agents scored"], ["Regressions", reg.length, reg.length ? reg.length + " agent still regressed" : "none open", reg.length ? "t-d" : ""], ["Eval spend this month", "$" + spend.toFixed(2), "of $" + cfg.monthly.toFixed(2)]]}></Figs>
      <div className="vw"><Seg v={v} opts={[["agents", "Agents"], ["runs", "Suite runs"], ["ratings", "Worst rated"]]} onChange={setV}></Seg></div>
      {v === "agents" ? <DT key="a" rows={QUAL} searchRef={searchRef} ph="Search agents" find={q => agOf(q.id).n} onOpen={r => setOpen({ t: "agent", r })} sel={open && open.r}
        filters={[["all", "All", () => true], ["reg", "Regressed", q => q.delta <= -cfg.thr], ["low", "Low satisfaction", q => q.sat != null && q.sat < 0.8]]}
        tools={<button className="btn" onClick={() => setSet(true)}><Ic n="gear" s={13}></Ic>Sweep settings</button>}
        cols={[{ k: "a", l: "Agent", c: q => <AgCell id={q.id}></AgCell>, sv: q => agOf(q.id).n }, { k: "s", l: "Quality score", c: q => <span className="qs"><b className="mono">{Math.round(q.score * 100)}%</b><span className={q.delta < 0 ? "t-d" : "t-b"}><Line d={q.spark}></Line></span></span>, sv: q => q.score }, { k: "d", l: "Change", c: q => <Pts v={q.delta}></Pts>, sv: q => q.delta }, { k: "sat", l: "Satisfaction", c: q => q.sat == null ? <span className="dim">No ratings</span> : <span className="mono">{Math.round(q.sat * 100)}%</span>, sv: q => q.sat || 0, hide: 1 }, { k: "rt", l: "Ratings", r: true, c: q => <span className="mono">{q.ratings}</span>, sv: q => q.ratings, hide: 1 }, { k: "c", l: "Cases", r: true, c: q => <span className="mono">{q.cases}</span>, sv: q => q.cases, hide: 1 }, { k: "st", l: "Last run", c: q => <Bd m={RUN_ST[q.st]}></Bd> }]}></DT>
        : v === "runs" ? <DT key="r" rows={SUITE} searchRef={searchRef} ph="Search suite runs" find={s => agOf(s.ag).n + s.st} onOpen={r => setOpen({ t: "run", r })} sel={open && open.r}
          filters={[["all", "All", () => true], ["att", "Needs a look", s => s.st === "Failed" || s.st === "BudgetStopped" || s.delta <= -cfg.thr]]}
          cols={[{ k: "a", l: "Agent", c: s => <AgCell id={s.ag}></AgCell>, sv: s => agOf(s.ag).n }, { k: "st", l: "Status", c: s => <Bd m={RUN_ST[s.st]}></Bd>, sv: s => s.st }, { k: "n", l: "Cases asked", c: s => <span className="cs"><span className="ubar"><i style={{ width: s.n / s.of * 100 + "%" }}></i></span><span className="mono">{s.n}/{s.of}</span></span> }, { k: "sc", l: "Score", r: true, c: s => s.score == null ? <span className="dim">—</span> : <span className="mono">{s.score}%</span>, sv: s => s.score || 0 }, { k: "d", l: "Change", c: s => s.score == null ? <span className="dim">—</span> : <Pts v={s.delta}></Pts>, sv: s => s.delta, hide: 1 }, { k: "co", l: "Cost", r: true, c: s => <span className="mono">${s.cost.toFixed(2)}</span>, sv: s => s.cost, hide: 1 }, { k: "w", l: "Started", c: s => <span className="mu">{s.when}</span> }]}></DT>
          : <DT key="w" rows={WORST} searchRef={searchRef} ph="Search answers and comments" find={w => w.a + w.why + agOf(w.ag).n} onOpen={r => setOpen({ t: "worst", r })} sel={open && open.r}
            filters={[["all", "All", () => true], ...[...new Set(WORST.map(w => w.where))].slice(0, 3).map(x => [x, x, w => w.where === x])]}
            cols={[{ k: "a", l: "Answer", w: "38%", c: w => <div className="tl"><b className="q">“{w.a}”</b><span><Ic n="down" s={10}></Ic> {w.why}</span></div> }, { k: "ag", l: "Agent", c: w => <AgCell id={w.ag}></AgCell>, sv: w => agOf(w.ag).n }, { k: "wh", l: "Where", c: w => <span className="mu">{w.where}</span>, hide: 1 }, { k: "p", l: "Rated by", c: w => <span className="mu">{w.who}</span>, hide: 1 }, { k: "t", l: "When", c: w => <span className="mu">{w.when}</span> }]}></DT>}
      {open && open.t === "agent" && (() => { const q = open.r, a = agOf(q.id); return <Sheet onClose={() => setOpen(null)} head={<><Tile a={a} s={36}></Tile><div className="sh-t"><b>{a.n}</b><span>{q.cases} golden cases · last run {RUN_ST[q.st][0].toLowerCase()}</span></div></>}>
        <div className="sh-p"><h4 className="sh-k">Quality score, last 14 nights</h4><div className="bigl"><b className="mono">{Math.round(q.score * 100)}%</b><Pts v={q.delta}></Pts><span className={q.delta < 0 ? "t-d" : "t-b"}><Line d={q.spark} w={240} h={48}></Line></span></div></div>
        <KV items={[["Satisfaction", q.sat == null ? "No ratings yet" : Math.round(q.sat * 100) + "% of " + q.ratings], ["Regression threshold", cfg.thr + " points"], ["Judge", cfg.judge ? cfg.sample + "% of answers" : "Off"], ["Cases per night", "up to " + cfg.cases]]}></KV>
        <div className="sh-p"><h4 className="sh-k">Lowest rated</h4>{WORST.filter(w => w.ag === q.id).map(w => <div key={w.id} className="wq"><b>“{w.a}”</b><span>{w.why} — {w.who}</span></div>)}{!WORST.some(w => w.ag === q.id) && <p className="ad-h">Nothing rated down.</p>}</div>
        <div className="ad-bar sh-f"><button className="xa" onClick={() => A.toast("Re-running " + a.n + "'s suite")}><Ic n="refresh" s={13}></Ic>Run suite now</button><button className="xa" onClick={() => A.go("agents", a.id)}><Ic n="edit" s={13}></Ic>Open agent</button><span className="sp"></span><button className="xa" onClick={() => { setOpen(null); setV("runs"); }}>All runs</button></div>
      </Sheet>; })()}
      {open && open.t === "run" && (() => { const s = open.r, a = agOf(s.ag); return <Sheet onClose={() => setOpen(null)} head={<><Tile a={a} s={36}></Tile><div className="sh-t"><b>Suite run · {a.n}</b><span>{s.when}</span></div><Bd m={RUN_ST[s.st]}></Bd></>}>
        <KV items={[["Score", s.score == null ? "—" : s.score + "%"], ["Change", s.score == null ? "—" : <Pts v={s.delta}></Pts>], ["Cases asked", s.n + " of " + s.of], ["Cost", "$" + s.cost.toFixed(2)]]}></KV>
        <div className="sh-p"><h4 className="sh-k">Cases</h4><div className="cases">{Array.from({ length: s.of }).map((_, i) => <i key={i} className={i >= s.n ? "z" : i % 7 === 3 && (s.score || 100) < 88 ? "f" : ""} title={"Case " + (i + 1)}></i>)}</div><p className="ad-h">{s.st === "Skipped" ? "Nothing about the agent or its cases changed since its last run." : s.st === "BudgetStopped" ? "The evaluation budget ran out before every case was asked." : "Each square is a golden case; red ones scored below the bar."}</p></div>
      </Sheet>; })()}
      {open && open.t === "worst" && (() => { const w = open.r, a = agOf(w.ag); return <Sheet onClose={() => setOpen(null)} head={<><Tile a={a} s={36}></Tile><div className="sh-t"><b>{a.n}</b><span>{w.where} · {w.when}</span></div></>}>
        <div className="sh-p"><h4 className="sh-k">The answer</h4><p className="wq-a">“{w.a}”</p><h4 className="sh-k mt">What {w.who.split(" ")[0]} said</h4><p className="wq-a q">{w.why}</p></div>
        <div className="ad-bar sh-f"><button className="btn sm ink" onClick={() => { A.toast("Added to " + a.n + "'s golden set"); setOpen(null); }}><Ic n="plus" s={12}></Ic>Add to golden set</button><button className="xa" onClick={() => A.go("memory")}><Ic n="brain" s={13}></Ic>Write a memory</button><span className="sp"></span><button className="xa" onClick={() => A.go("activity")}>Open the run</button></div>
      </Sheet>; })()}
      {set && <Sheet onClose={() => setSet(false)} head={<div className="sh-t"><b>Sweep settings</b><span>The nightly replay of each agent's golden set</span></div>}>
        <div className="pol sh-pol">
          <div className="po"><div className="po-h"><b>Nightly sweep</b><span className="sp"></span><Switch on={cfg.on} onChange={x => setCfg({ ...cfg, on: x })}></Switch></div><p>Replays each agent's cases and scores the answers.</p>
            {cfg.on && <div className="po-o"><span>Start at</span><Seg v={cfg.hour} opts={[[0, "00:00"], [2, "02:00"], [4, "04:00"], [6, "06:00"]]} onChange={x => setCfg({ ...cfg, hour: x })} cls="sm"></Seg><span>Cases per agent</span><Seg v={cfg.cases} opts={[[20, "20"], [40, "40"], [100, "100"]]} onChange={x => setCfg({ ...cfg, cases: x })} cls="sm"></Seg></div>}</div>
          <div className="po"><div className="po-h"><b>Judge model</b><span className="sp"></span><Switch on={cfg.judge} onChange={x => setCfg({ ...cfg, judge: x })}></Switch></div><p>A second model grades a sample of live answers between sweeps.</p>
            {cfg.judge && <div className="po-o"><span>Share of answers</span><Seg v={cfg.sample} opts={[[10, "10%"], [25, "25%"], [50, "50%"], [100, "All"]]} onChange={x => setCfg({ ...cfg, sample: x })} cls="sm"></Seg></div>}</div>
          <div className="po"><div className="po-h"><b>Regression threshold</b></div><p>A drop this large flags the agent and tells its owners.</p><div className="po-o"><Seg v={cfg.thr} opts={[[3, "3 pts"], [5, "5 pts"], [10, "10 pts"]]} onChange={x => setCfg({ ...cfg, thr: x })} cls="sm"></Seg></div></div>
          <div className="po"><div className="po-h"><b>Budget</b></div><p>Stops a sweep when either is reached.</p><div className="po-o"><span>Per night</span><Seg v={cfg.nightly} opts={[[0.5, "$0.50"], [1, "$1"], [5, "$5"]]} onChange={x => setCfg({ ...cfg, nightly: x })} cls="sm"></Seg><span>Per month</span><Seg v={cfg.monthly} opts={[[10, "$10"], [20, "$20"], [100, "$100"]]} onChange={x => setCfg({ ...cfg, monthly: x })} cls="sm"></Seg></div></div>
        </div>
      </Sheet>}
    </div>
  );
}
function ActivityTab({ S, A, searchRef }) {
  const [v, setV] = React.useState("runs"); const [open, setOpen] = React.useState(null); const [props, setProps] = React.useState(PROPS);
  const today = RUNS.filter(r => r.t < 11), failed = today.filter(r => r.st === "Failed").length, pend = props.filter(p => p.st === "Pending").length, openEx = EXC.filter(e => e.st === "Open").length;
  const decide = (p, st) => { setProps(xs => xs.map(x => x === p ? { ...x, st } : x)); setOpen(null); A.toast(st === "Approved" ? "Approved · " + p.tool + " runs now" : "Rejected · the agent is told why"); };
  const ago = t => t === 0 ? "now" : t < 11 ? (t * 9 + 2) + " min ago" : t < 30 ? "Today" : "Yesterday";
  return (
    <div className="tabp">
      <Nova ctx="Activity" spin={RUNS.some(r => r.st === "Running")} ctl={pend > 0 && <><button className="btn ink lg" onClick={() => setV("proposals")}>Decide {pend} proposals</button><span>Oldest waiting 1 h</span></>}>
        <b>{today.length} runs</b> today{failed ? <>, <span className="ref d" onClick={() => setV("runs")}>{failed} failed</span> when Workstation vLLM couldn't connect</> : ""}. <span className="ref w" onClick={() => setV("proposals")}>{pend} proposals</span> wait on a person{openEx ? <>, and <span className="ref" onClick={() => setV("exc")}>{openEx} exceptions</span> are still open</> : ""}.
      </Nova>
      <Figs items={[["Runs today", today.length, "1 running now"], ["Failed", failed, "of today's runs", failed ? "t-d" : ""], ["Awaiting a decision", pend, "proposals", pend ? "t-w" : ""], ["Approved as proposed", Math.round(props.filter(p => p.st === "Approved" || p.st === "Executed").length / props.filter(p => p.st !== "Pending").length * 100) + "%", "last 7 days"]]}></Figs>
      <div className="vw"><Seg v={v} opts={[["runs", "Runs"], ["proposals", "Proposals" + (pend ? " · " + pend : "")], ["exc", "Exceptions" + (openEx ? " · " + openEx : "")]]} onChange={setV}></Seg></div>
      {v === "runs" ? <DT key="r" rows={RUNS} searchRef={searchRef} ph="Search runs" find={r => agOf(r.ag).n + r.sum + (r.subj || "") + r.id} onOpen={r => setOpen({ t: "run", r })} sel={open && open.r}
        filters={[["all", "All", () => true], ["fail", "Failed", r => r.st === "Failed"], ["live", "Running", r => r.st === "Running" || r.st === "Waiting"]]}
        cols={[{ k: "a", l: "Agent", c: r => <AgCell id={r.ag} sub={r.handed && "Handed by " + r.handed}></AgCell>, sv: r => agOf(r.ag).n }, { k: "tr", l: "Started by", c: r => <span className="mu">{TRIG_L[r.trig]}</span>, hide: 1 }, { k: "st", l: "Status", c: r => <Bd m={{ Running: ["Running", "b"], Completed: ["Completed", "k"], Failed: ["Failed", "d"], Waiting: ["Waiting on a person", "w"] }[r.st]}></Bd>, sv: r => r.st }, { k: "su", l: "Summary", w: "34%", c: r => <div className="tl"><b className="rg">{r.sum}</b>{r.subj && <span className="mono">{r.subj}</span>}</div> }, { k: "m", l: "Model", c: r => <span className="mono mu sm">{r.model.split("/").pop()}</span>, hide: 1 }, { k: "t", l: "Started", c: r => <span className="mu">{ago(r.t)}</span>, sv: r => r.t }]}></DT>
        : v === "proposals" ? <DT key="p" rows={props} searchRef={searchRef} ph="Search proposals" find={p => p.tool + p.why + agOf(p.ag).n} onOpen={r => setOpen({ t: "prop", r })} sel={open && open.r}
          filters={[["pend", "Awaiting", p => p.st === "Pending"], ["all", "All", () => true], ["rej", "Rejected", p => p.st === "Rejected"]]}
          cols={[{ k: "c", l: "Proposed change", w: "36%", c: p => <div className="tl"><b className="rg">{p.why}</b><span className="mono">{p.tool}{p.taint && <span className="tg w xs">Read outside text</span>}</span></div> }, { k: "a", l: "Agent", c: p => <AgCell id={p.ag}></AgCell>, sv: p => agOf(p.ag).n }, { k: "st", l: "Status", c: p => <Bd m={PROP_ST[p.st]}></Bd>, sv: p => p.st }, { k: "tier", l: "Autonomy", c: p => <span className="mu">{TIER_L[p.tier]}</span>, hide: 1 }, { k: "cf", l: "Confidence", c: p => <span className="cs"><span className="ubar"><i style={{ width: p.conf * 100 + "%" }}></i></span><span className="mono">{Math.round(p.conf * 100)}%</span></span>, sv: p => p.conf, hide: 1 }, { k: "t", l: "Proposed", c: p => <span className="mu">{p.ago}</span> }]}></DT>
          : <DT key="e" rows={EXC} searchRef={searchRef} ph="Search exceptions" find={e => e.msg + e.kind + agOf(e.ag).n} onOpen={r => setOpen({ t: "exc", r })} sel={open && open.r}
            filters={[["open", "Open", e => e.st === "Open"], ["all", "All", () => true]]}
            cols={[{ k: "k", l: "Exception", w: "44%", c: e => <div className="tl"><b className="rg">{e.kind}</b><span className="mono">{e.msg}</span></div> }, { k: "a", l: "Agent", c: e => <AgCell id={e.ag}></AgCell> }, { k: "st", l: "Status", c: e => <Bd m={e.st === "Open" ? ["Open", "w"] : ["Resolved", "k"]}></Bd> }, { k: "t", l: "When", c: e => <span className="mu">{e.when}</span> }]}></DT>}
      {open && open.t === "run" && (() => { const r = open.r, a = agOf(r.ag); return <Sheet onClose={() => setOpen(null)} head={<><Tile a={a} s={36}></Tile><div className="sh-t"><b>{r.sum}</b><span className="mono">{r.id}</span></div></>}>
        <KV items={[["Agent", a.n], ["Started by", TRIG_L[r.trig] + (r.handed ? " · " + r.handed : "")], ["Model", <span className="mono sm">{r.model}</span>], ["Took", r.dur ? r.dur + "s · " + r.tok.toLocaleString() + " tokens" : "Still running"]]}></KV>
        <div className="sh-p"><h4 className="sh-k">What it did</h4><ol className="trs">
          <li><i></i><div><b>Read the request</b><span>{r.subj ? "About " + r.subj : "From " + TRIG_L[r.trig].toLowerCase()}</span></div></li>
          <li><i></i><div><b className="mono">find_in_trenova</b><span>Looked up {r.subj || "the record"} · 0.4s</span></div></li>
          <li><i></i><div><b className="mono">recall_memory</b><span>Read 2 memories</span></div></li>
          {r.st === "Failed" ? <li className="f"><i></i><div><b>Model call failed</b><span className="mono">dial tcp 127.0.0.1:8000: connection refused</span></div></li> : r.st === "Running" ? <li className="n"><i></i><div><b>Thinking…</b><span>Deciding on the next step</span></div></li> : <li className="k"><i></i><div><b>{r.sum}</b><span>Finished in {r.dur}s</span></div></li>}
        </ol></div>
        <div className="ad-bar sh-f"><button className="xa" onClick={() => A.toast("Opening the trace")}><Ic n="ext" s={13}></Ic>Open trace</button>{r.st === "Failed" && <button className="xa" onClick={() => A.go("providers", "vllm")}><Ic n="plug" s={13}></Ic>Check provider</button>}</div>
      </Sheet>; })()}
      {open && open.t === "prop" && (() => { const p = open.r, a = agOf(p.ag); return <Sheet onClose={() => setOpen(null)} head={<><Tile a={a} s={36}></Tile><div className="sh-t"><b>{p.why}</b><span className="mono">{p.tool}</span></div><Bd m={PROP_ST[p.st]}></Bd></>}>
        <KV items={[["Agent", a.n], ["Autonomy", TIER_L[p.tier]], ["Confidence", Math.round(p.conf * 100) + "%"], ["Run", <span className="mono sm">{p.run}</span>]]}></KV>
        {p.taint && <div className="sh-p"><div className="ah-w nm"><Ic n="warn" s={13}></Ic><span>The run read an email or document written outside the organization before proposing this. Check the details before approving.</span></div></div>}
        <div className="ad-bar sh-f">{p.st === "Pending" ? <><button className="btn sm ink" onClick={() => decide(p, "Approved")}><Ic n="check" s={12} w={2.2}></Ic>Approve</button><button className="btn sm" onClick={() => decide(p, "Rejected")}>Reject</button><span className="sp"></span><button className="xa" onClick={() => A.toast("Opening in Desk")}>Change in Desk</button></> : <span className="ad-h">Decided {p.ago}.</span>}</div>
      </Sheet>; })()}
      {open && open.t === "exc" && (() => { const e = open.r, a = agOf(e.ag); return <Sheet onClose={() => setOpen(null)} head={<><Tile a={a} s={36}></Tile><div className="sh-t"><b>{e.kind}</b><span>{a.n} · {e.when}</span></div><Bd m={e.st === "Open" ? ["Open", "w"] : ["Resolved", "k"]}></Bd></>}>
        <div className="sh-p"><h4 className="sh-k">What happened</h4><code className="sh-code">{e.msg}</code></div>
        <div className="ad-bar sh-f"><button className="xa" onClick={() => { setOpen(null); setV("runs"); }}><Ic n="timeline" s={13}></Ic>Open the run</button><span className="sp"></span>{e.st === "Open" && <button className="btn sm" onClick={() => { e.st = "Resolved"; setOpen(null); A.toast("Marked resolved"); }}>Mark resolved</button>}</div>
      </Sheet>; })()}
    </div>
  );
}
function AuditTab({ S, A, searchRef }) {
  const [v, setV] = React.useState("trail"); const [open, setOpen] = React.useState(null); const [ver, setVer] = React.useState({ st: "Intact", when: "Today 3:00 AM", thr: 48204 }); const [exp, setExp] = React.useState(false); const [exps, setExps] = React.useState(EXPORTS); const [rng, setRng] = React.useState("30"); const [fmt, setFmt] = React.useState("jsonl");
  const verify = () => { setVer(x => ({ ...x, st: "Verifying" })); setTimeout(() => { setVer({ st: "Intact", when: "just now", thr: 48211 }); A.toast("Chain verified · intact through #48,211"); }, 2200); };
  const busy = ver.st === "Verifying";
  return (
    <div className="tabp">
      <Nova ctx="Audit trail" spin={busy} ctl={<><button className={"btn lg" + (busy ? "" : " ink")} disabled={busy} onClick={verify}><Ic n="shield" s={13}></Ic>{busy ? "Verifying…" : "Verify now"}</button><span>{busy ? "Checking every row's signature" : "Checked every night on its own"}</span></>}>
        {busy ? <>Checking the chain from the last sealed row…</> : <>Every agent action is written to a <b>signed chain</b>. It was last checked {ver.when} and is <b className="t-k">intact</b> through #{ver.thr.toLocaleString()}; the {48211 - 48204 > 0 && ver.thr < 48211 ? "7 newest rows are sealed at the next check" : "newest row is sealed"}.</>}
      </Nova>
      <Figs items={[["Chain", "Signed", "Key ed25519 · k_2026_07"], ["Sealed through", "#48,204", "of 48,211 recorded"], ["Last verified", busy ? "…" : ver.st, ver.when + ", through #" + ver.thr.toLocaleString(), busy ? "" : "t-k"]]}></Figs>
      <div className="vw"><Seg v={v} opts={[["trail", "Trail"], ["exports", "Exports"]]} onChange={setV}></Seg></div>
      {v === "trail" ? <DT key="t" rows={AUDIT} per={15} searchRef={searchRef} ph="Search the trail" find={r => r.act + r.who + r.subj + r.seq} onOpen={r => setOpen(r)} sel={open}
        filters={[["all", "All", () => true], ["agent", "By agents", r => r.kind === "agent"], ["person", "By people", r => r.kind === "person"]]}
        tools={<button className="btn" onClick={() => setExp(true)}><Ic n="download" s={13}></Ic>Export trail</button>}
        cols={[{ k: "s", l: "#", w: 80, c: r => <span className="mono mu">{r.seq.toLocaleString()}</span>, sv: r => r.seq }, { k: "a", l: "Action", c: r => <b className="rg">{r.act}</b>, sv: r => r.act }, { k: "w", l: "By", c: r => r.kind === "agent" ? <AgCell id={r.ag}></AgCell> : <span className="agc"><span className="me sm">{r.who.split(" ").map(x => x[0]).join("").slice(0, 2)}</span><span>{r.who}</span></span> }, { k: "sj", l: "Subject", c: r => <span className="mono mu sm">{r.subj}</span>, hide: 1 }, { k: "sl", l: "Seal", c: r => r.sealed ? <span className="seal"><Ic n="lock" s={11}></Ic>Sealed</span> : <span className="seal p">Next check</span>, hide: 1 }, { k: "t", l: "When", c: r => <span className="mu">{r.when}</span> }]}></DT>
        : <DT key="x" rows={exps} ph="Search exports" find={x => x.f + x.r} tools={<button className="btn ink" onClick={() => setExp(true)}><Ic n="download" s={13}></Ic>Export trail</button>}
          cols={[{ k: "f", l: "File", c: x => <div className="tl"><b className="mono rg">{x.f}</b><span>{x.r}</span></div> }, { k: "n", l: "Rows", r: true, c: x => <span className="mono">{x.n.toLocaleString()}</span> }, { k: "b", l: "By", c: x => <span className="mu">{x.by}</span>, hide: 1 }, { k: "w", l: "Made", c: x => <span className="mu">{x.when}</span> }, { k: "st", l: "", r: true, c: x => x.st === "Ready" ? <button className="btn sm" onClick={e => { e.stopPropagation(); A.toast("Downloading " + x.f); }}><Ic n="download" s={12}></Ic>Download</button> : x.st === "Building" ? <Bd m={["Building", "b"]}></Bd> : <span className="dim">Expired</span> }]}></DT>}
      {open && <Sheet onClose={() => setOpen(null)} head={<><span className="src-i"><Ic n="receipt" s={15}></Ic></span><div className="sh-t"><b>{open.act}</b><span className="mono">#{open.seq.toLocaleString()} · {open.when}</span></div>{open.sealed ? <span className="seal"><Ic n="lock" s={11}></Ic>Sealed</span> : <span className="seal p">Next check</span>}</>}>
        <KV items={[["By", open.who], ["Subject", <span className="mono sm">{open.subj}</span>], ["Agent", agOf(open.ag).n], ["Signed with", "k_2026_07"]]}></KV>
        <div className="sh-p"><h4 className="sh-k">Chain</h4><div className="chn"><span><em>Previous</em><code>{AUDIT.find(x => x.seq === open.seq - 1)?.hash || "—"}</code></span><span><em>This row</em><code>{open.hash}</code></span></div><p className="ad-h">Each row's hash covers the one before it, so changing any row breaks every row after.</p></div>
      </Sheet>}
      {exp && <Modal onClose={() => setExp(false)} title="Export the audit trail" sub="A signed file anyone can check against the chain. It's kept for 30 days." foot={<><span className="sp"></span><button className="btn sm ghost" onClick={() => setExp(false)}>Cancel</button><button className="btn sm ink" onClick={() => { const f = "ai-audit-" + (rng === "30" ? "last-30-days" : rng === "90" ? "last-90-days" : "all") + "." + fmt; setExps(x => [{ f, r: rng === "all" ? "Everything" : "Last " + rng + " days", n: rng === "30" ? 39102 : rng === "90" ? 118440 : 482110, by: "You", when: "Just now", st: "Building" }, ...x]); setExp(false); setV("exports"); A.toast("Building " + f + " · it appears in Exports when ready"); setTimeout(() => setExps(x => x.map(y => y.f === f ? { ...y, st: "Ready" } : y)), 2600); }}>Start export</button></>}>
        <div className="po-o nm"><span>Range</span><Seg v={rng} opts={[["30", "Last 30 days"], ["90", "Last 90 days"], ["all", "Everything"]]} onChange={setRng} cls="sm"></Seg><span>Format</span><Seg v={fmt} opts={[["jsonl", "JSON Lines"], ["csv", "CSV"]]} onChange={setFmt} cls="sm"></Seg></div>
      </Modal>}
    </div>
  );
}
Object.assign(window, { QualityTab, ActivityTab, AuditTab });
