import type { SidebarLink } from "@/components/sidebar-nav";
import { Operation, Resource } from "@/types/permission";
import {
  BarChart3Icon,
  CalculatorIcon,
  ContainerIcon,
  HomeIcon,
  Package,
  ReceiptTextIcon,
  SettingsIcon,
  TruckIcon,
  UsersIcon,
} from "lucide-react";
import type { ModuleId, NavigationConfig, NavModule } from "./navigation.types";

interface AppModuleGroup {
  id: string;
  label: string;
  moduleIds: ModuleId[];
}

const homeModule: NavModule = {
  id: "home",
  label: "Home",
  icon: HomeIcon,
  description: "Dashboard and overview",
  basePath: "/",
  hideSecondarySidebar: true,
  navigation: [],
};
const adminModule: NavModule = {
  id: "admin",
  label: "Administration",
  icon: SettingsIcon,
  description: "System administration",
  basePath: "/admin/organization-settings",
  hideSecondarySidebar: true,
  adminOnly: true,
  navigation: [],
};

const shipmentManagementModule: NavModule = {
  id: "shipment",
  label: "Shipment Management",
  icon: TruckIcon,
  description: "Shipments and related configuration",
  basePath: "#",
  navigation: [
    {
      id: "shipments",
      label: "Shipments",
      path: "/shipment-management/shipments",
      icon: Package,
      resource: Resource.Shipment,
    },
    {
      id: "config-files-group",
      label: "Configuration Files",
      defaultOpen: false,
      items: [
        {
          id: "shipment-types",
          label: "Shipment Types",
          path: "/shipment-management/configuration-files/shipment-types",
          resource: Resource.ShipmentType,
        },
        {
          id: "service-types",
          label: "Service Types",
          path: "/shipment-management/configuration-files/service-types",
          resource: Resource.ServiceType,
        },
        {
          id: "hazardous-materials",
          label: "Hazardous Materials",
          path: "/shipment-management/configuration-files/hazardous-materials",
          resource: Resource.HazardousMaterial,
        },
        {
          id: "commodities",
          label: "Commodities",
          path: "/shipment-management/configuration-files/commodities",
          resource: Resource.Commodity,
        },
      ],
    },
  ],
};

const dispatchModule: NavModule = {
  id: "dispatch",
  label: "Dispatch Management",
  icon: UsersIcon,
  description: "Workers, drivers, and dispatch operations",
  basePath: "/dispatch",
  navigation: [
    {
      id: "locations",
      label: "Locations",
      path: "/dispatch/locations",
      resource: Resource.Location,
    },
    {
      id: "workers",
      label: "Workers",
      path: "/dispatch/workers",
      resource: Resource.Worker,
    },
    {
      id: "dispatch-config-group",
      label: "Configuration Files",
      defaultOpen: false,
      items: [
        {
          id: "location-categories",
          label: "Location Categories",
          path: "/dispatch/configuration-files/location-categories",
          resource: Resource.LocationCategory,
        },
        {
          id: "fleet-codes",
          label: "Fleet Codes",
          path: "/dispatch/configuration-files/fleet-codes",
          resource: Resource.FleetCode,
        },
      ],
    },
  ],
};

const equipmentModule: NavModule = {
  id: "fleet",
  label: "Equipment Management",
  icon: ContainerIcon,
  description: "Tractors, trailers, and equipment",
  basePath: "/equipment",
  navigation: [
    {
      id: "tractors",
      label: "Tractors",
      path: "/equipment/tractors",
      resource: Resource.Tractor,
    },
    {
      id: "trailers",
      label: "Trailers",
      path: "/equipment/trailers",
      resource: Resource.Trailer,
    },
    {
      id: "equipment-config-group",
      label: "Configuration Files",
      defaultOpen: false,
      items: [
        {
          id: "equipment-manufacturers",
          label: "Equipment Manufacturers",
          path: "/equipment/configuration-files/equipment-manufacturers",
          resource: Resource.EquipmentManufacturer,
        },
        {
          id: "equipment-types",
          label: "Equipment Types",
          path: "/equipment/configuration-files/equipment-types",
          resource: Resource.EquipmentType,
        },
      ],
    },
  ],
};

const billingModule: NavModule = {
  id: "billing",
  label: "Billing Management",
  icon: ReceiptTextIcon,
  description: "Invoicing and financial management",
  basePath: "/billing",
  navigation: [
    {
      id: "invoices",
      label: "Invoices",
      path: "/billing/invoices",
      resource: Resource.Invoice,
    },
    {
      id: "billing-config-group",
      label: "Configuration Files",
      defaultOpen: false,
      items: [
        {
          id: "accessorial-charges",
          label: "Accessorial Charges",
          path: "/billing/configuration-files/accessorial-charges",
          resource: Resource.AccessorialCharge,
        },
        {
          id: "charge-types",
          label: "Charge Types",
          path: "/billing/configuration-files/charge-types",
          resource: Resource.ChargeType,
        },
        {
          id: "formula-templates",
          label: "Formula Templates",
          path: "/billing/configuration-files/formula-templates",
          resource: Resource.FormulaTemplate,
          includeBetaTag: true,
        },
        {
          id: "customers",
          label: "Customers",
          path: "/billing/configuration-files/customers",
          resource: Resource.Customer,
        },
        {
          id: "document-types",
          label: "Document Types",
          path: "/billing/configuration-files/document-types",
          resource: Resource.DocumentType,
        },
        {
          id: "document-packet-rules",
          label: "Packet Rules",
          path: "/billing/configuration-files/document-packet-rules",
          resource: Resource.DocumentType,
        },
      ],
    },
  ],
};

const accountingModule: NavModule = {
  id: "accounting",
  label: "Accounting Management",
  icon: CalculatorIcon,
  description: "Accounting management",
  basePath: "/accounting",
  navigation: [
    {
      id: "accounting-dashboard",
      label: "Accounting Dashboard",
      path: "/accounting",
    },
    {
      id: "configuration-files-group",
      label: "Configuration Files",
      defaultOpen: false,
      items: [
        {
          id: "account-types",
          label: "Account Types",
          path: "/accounting/configuration-files/account-types",
          resource: Resource.AccountType,
        },
        {
          id: "fiscal-years",
          label: "Fiscal Years",
          path: "/accounting/configuration-files/fiscal-years",
          resource: Resource.FiscalYear,
        },
      ],
    },
  ],
};

const reportsModule: NavModule = {
  id: "reports",
  label: "Reports",
  icon: BarChart3Icon,
  description: "Analytics and reporting",
  basePath: "/reports",
  navigation: [
    {
      id: "reports-dashboard",
      label: "Reports Dashboard",
      path: "/reports",
    },
  ],
};

export const navigationConfig: NavigationConfig = {
  modules: [
    homeModule,
    shipmentManagementModule,
    dispatchModule,
    equipmentModule,
    billingModule,
    reportsModule,
    accountingModule,
    adminModule,
  ],
  quickActions: [
    {
      id: "create-shipment",
      label: "Create Shipment",
      description: "Add a new shipment",
      path: "/shipment-management/shipments",
      resource: Resource.Shipment,
      requiredOperation: Operation.Create,
      query: { panelType: "create" },
      keywords: ["shipment"],
    },
    {
      id: "create-shipment-type",
      label: "Create Shipment Type",
      description: "Add a new shipment type",
      path: "/shipment-management/configuration-files/shipment-types",
      resource: Resource.ShipmentType,
      requiredOperation: Operation.Create,
      query: { panelType: "create" },
      keywords: ["shipment", "type"],
    },
    {
      id: "create-service-type",
      label: "Create Service Type",
      description: "Add a new service type",
      path: "/shipment-management/configuration-files/service-types",
      resource: Resource.ServiceType,
      requiredOperation: Operation.Create,
      query: { panelType: "create" },
      keywords: ["service", "type"],
    },
    {
      id: "create-hazardous-material",
      label: "Create Hazardous Material",
      description: "Add a new hazardous material",
      path: "/shipment-management/configuration-files/hazardous-materials",
      resource: Resource.HazardousMaterial,
      requiredOperation: Operation.Create,
      query: { panelType: "create" },
      keywords: ["hazmat", "dangerous goods", "material"],
    },
    {
      id: "create-commodity",
      label: "Create Commodity",
      description: "Add a new commodity",
      path: "/shipment-management/configuration-files/commodities",
      resource: Resource.Commodity,
      requiredOperation: Operation.Create,
      query: { panelType: "create" },
      keywords: ["commodity"],
    },
    {
      id: "create-accessorial-charge",
      label: "Create Accessorial Charge",
      description: "Add a new accessorial charge",
      path: "/billing/configuration-files/accessorial-charges",
      resource: Resource.AccessorialCharge,
      requiredOperation: Operation.Create,
      query: { panelType: "create" },
      keywords: ["accessorial", "charge"],
    },
    {
      id: "create-customer",
      label: "Create Customer",
      description: "Add a new customer",
      path: "/billing/configuration-files/customers",
      resource: Resource.Customer,
      requiredOperation: Operation.Create,
      query: { panelType: "create" },
      keywords: ["customer"],
    },
    {
      id: "create-document-type",
      label: "Create Document Type",
      description: "Add a new document type",
      path: "/billing/configuration-files/document-types",
      resource: Resource.DocumentType,
      requiredOperation: Operation.Create,
      query: { panelType: "create" },
      keywords: ["document", "type"],
    },
    {
      id: "create-formula-template",
      label: "Create Formula Template",
      description: "Add a new formula template",
      path: "/billing/configuration-files/formula-templates",
      resource: Resource.FormulaTemplate,
      requiredOperation: Operation.Create,
      query: { panelType: "create" },
      keywords: ["formula", "template"],
    },
    {
      id: "create-account-type",
      label: "Create Account Type",
      description: "Add a new account type",
      path: "/accounting/configuration-files/account-types",
      resource: Resource.AccountType,
      requiredOperation: Operation.Create,
      query: { panelType: "create" },
      keywords: ["account", "type"],
    },
    {
      id: "create-fiscal-year",
      label: "Create Fiscal Year",
      description: "Add a new fiscal year",
      path: "/accounting/configuration-files/fiscal-years",
      resource: Resource.FiscalYear,
      requiredOperation: Operation.Create,
      query: { panelType: "create" },
      keywords: ["fiscal", "year"],
    },
    {
      id: "create-tractor",
      label: "Create Tractor",
      description: "Add a new tractor",
      path: "/equipment/tractors",
      resource: Resource.Tractor,
      requiredOperation: Operation.Create,
      query: { panelType: "create" },
      keywords: ["tractor", "equipment"],
    },
    {
      id: "create-trailer",
      label: "Create Trailer",
      description: "Add a new trailer",
      path: "/equipment/trailers",
      resource: Resource.Trailer,
      requiredOperation: Operation.Create,
      query: { panelType: "create" },
      keywords: ["trailer", "equipment"],
    },
    {
      id: "create-equipment-type",
      label: "Create Equipment Type",
      description: "Add a new equipment type",
      path: "/equipment/configuration-files/equipment-types",
      resource: Resource.EquipmentType,
      requiredOperation: Operation.Create,
      query: { panelType: "create" },
      keywords: ["equipment", "type"],
    },
    {
      id: "create-equipment-manufacturer",
      label: "Create Equipment Manufacturer",
      description: "Add a new equipment manufacturer",
      path: "/equipment/configuration-files/equipment-manufacturers",
      resource: Resource.EquipmentManufacturer,
      requiredOperation: Operation.Create,
      query: { panelType: "create" },
      keywords: ["equipment", "manufacturer"],
    },
    {
      id: "create-location",
      label: "Create Location",
      description: "Add a new location",
      path: "/dispatch/locations",
      resource: Resource.Location,
      requiredOperation: Operation.Create,
      query: { panelType: "create" },
      keywords: ["location"],
    },
    {
      id: "create-worker",
      label: "Create Worker",
      description: "Add a new worker",
      path: "/dispatch/workers",
      resource: Resource.Worker,
      requiredOperation: Operation.Create,
      query: { pageTab: "workers", panelType: "create" },
      keywords: ["worker", "driver", "employee"],
    },
    {
      id: "create-location-category",
      label: "Create Location Category",
      description: "Add a new location category",
      path: "/dispatch/configuration-files/location-categories",
      resource: Resource.LocationCategory,
      requiredOperation: Operation.Create,
      query: { panelType: "create" },
      keywords: ["location", "category"],
    },
    {
      id: "create-fleet-code",
      label: "Create Fleet Code",
      description: "Add a new fleet code",
      path: "/dispatch/configuration-files/fleet-codes",
      resource: Resource.FleetCode,
      requiredOperation: Operation.Create,
      query: { panelType: "create" },
      keywords: ["fleet", "code"],
    },
    {
      id: "create-hold-reason",
      label: "Create Hold Reason",
      description: "Add a new hold reason",
      path: "/admin/hold-reasons",
      resource: Resource.HoldReason,
      requiredOperation: Operation.Create,
      query: { panelType: "create" },
      keywords: ["hold", "reason"],
    },
    {
      id: "create-hazmat-segregation-rule",
      label: "Create Hazmat Segregation Rule",
      description: "Add a new hazmat segregation rule",
      path: "/admin/hazmat-segregation-rules",
      resource: Resource.HazmatSegregationRule,
      requiredOperation: Operation.Create,
      query: { panelType: "create" },
      keywords: ["hazmat", "segregation", "rule"],
    },
    {
      id: "create-distance-override",
      label: "Create Distance Override",
      description: "Add a new distance override",
      path: "/admin/distance-overrides",
      resource: Resource.DistanceOverride,
      requiredOperation: Operation.Create,
      query: { panelType: "create" },
      keywords: ["distance", "override"],
    },
    {
      id: "create-user",
      label: "Create User",
      description: "Add a new user",
      path: "/admin/users",
      resource: Resource.User,
      requiredOperation: Operation.Create,
      query: { panelType: "create" },
      keywords: ["user"],
    },
    {
      id: "create-role",
      label: "Create Role",
      description: "Add a new role",
      path: "/admin/roles/new",
      resource: Resource.Role,
      requiredOperation: Operation.Create,
      keywords: ["role", "permissions"],
    },
    {
      id: "create-custom-field",
      label: "Create Custom Field",
      description: "Add a new custom field",
      path: "/admin/custom-fields",
      resource: Resource.CustomFieldDefinition,
      requiredOperation: Operation.Create,
      query: { panelType: "create" },
      keywords: ["custom", "field"],
    },
  ],
};

export const appModuleGroups: AppModuleGroup[] = [
  {
    id: "core",
    label: "Core",
    moduleIds: ["home"],
  },
  {
    id: "operations",
    label: "Operations",
    moduleIds: ["shipment", "dispatch", "fleet"],
  },
  {
    id: "financial",
    label: "Financial",
    moduleIds: ["billing", "reports", "accounting"],
  },
  {
    id: "admin",
    label: "Admin",
    moduleIds: ["admin"],
  },
];

export const adminLinks: SidebarLink[] = [
  {
    href: "/admin/organization-settings",
    title: "Organization Settings",
    group: "Organization",
    adminOnly: true,
    resource: Resource.Organization,
    requiredOperation: Operation.Read,
  },
  {
    href: "/admin/accounting-control",
    title: "Accounting Controls",
    group: "Organization",
    adminOnly: true,
    resource: Resource.AccountingControl,
    requiredOperation: Operation.Read,
  },
  {
    href: "/admin/billing-controls/",
    title: "Billing Controls",
    group: "Organization",
    adminOnly: true,
    resource: Resource.BillingControl,
  },
  {
    href: "/admin/data-entry-controls/",
    title: "Data Entry Controls",
    group: "Organization",
    adminOnly: true,
    resource: Resource.DataEntryControl,
    requiredOperation: Operation.Read,
  },
  {
    href: "/admin/dispatch-controls/",
    title: "Dispatch Controls",
    group: "Organization",
    adminOnly: true,
    resource: Resource.DispatchControl,
    requiredOperation: Operation.Read,
  },
  {
    href: "/admin/shipment-controls",
    title: "Shipment Controls",
    group: "Organization",
    adminOnly: true,
    resource: Resource.ShipmentControl,
    requiredOperation: Operation.Read,
  },
  {
    href: "/admin/document-intelligence",
    title: "Document Intelligence",
    group: "Document Management",
    adminOnly: true,
    resource: Resource.DocumentControl,
    requiredOperation: Operation.Read,
  },
  {
    href: "/admin/document-parsing-rules",
    title: "Parsing Rules",
    group: "Document Management",
    adminOnly: true,
    resource: Resource.DocumentParsingRule,
    requiredOperation: Operation.Read,
  },
  {
    href: "/admin/sequence-configs",
    title: "Sequence Configuration",
    group: "Organization",
    adminOnly: true,
    resource: Resource.SequenceConfig,
    requiredOperation: Operation.Read,
  },
  {
    href: "/admin/distance-overrides/",
    title: "Distance Overrides",
    group: "Organization",
    adminOnly: true,
    resource: Resource.DistanceOverride,
    requiredOperation: Operation.Read,
  },
  {
    href: "/organization/consolidation-settings/",
    title: "Consolidation Settings",
    group: "Organization",
    disabled: true,
  },
  {
    href: "/organization/route-controls/",
    title: "Route Controls",
    group: "Organization",
    disabled: true,
  },
  {
    href: "/organization/feasibility-controls/",
    title: "Feasibility Controls",
    group: "Organization",
    disabled: true,
  },
  {
    href: "/admin/hazmat-segregation-rules",
    title: "Hazmat Seg. Rules",
    group: "Organization",
    adminOnly: true,
    resource: Resource.HazmatSegregationRule,
    requiredOperation: Operation.Read,
  },
  {
    href: "/admin/hold-reasons/",
    title: "Hold Reasons",
    group: "Organization",
    adminOnly: true,
    resource: Resource.HoldReason,
    requiredOperation: Operation.Read,
  },
  {
    href: "/admin/users/",
    title: "Users & Roles",
    group: "Organization",
    adminOnly: true,
    resource: Resource.User,
    requiredOperation: Operation.Read,
  },
  {
    href: "#",
    title: "Custom Reports",
    group: "Reporting & Analytics",
    disabled: true,
  },
  {
    href: "#",
    title: "Scheduled Reports",
    group: "Reporting & Analytics",
    disabled: true,
  },
  {
    href: "/organization/email-controls/",
    title: "Email Controls",
    group: "Email & SMS",
    disabled: true,
  },
  {
    href: "#",
    title: "Email Logs",
    group: "Email & SMS",
    disabled: true,
  },
  {
    href: "/organization/email-profiles/",
    title: "Email Profile(s)",
    group: "Email & SMS",
    disabled: true,
  },
  {
    href: "#",
    title: "Notification Types",
    group: "Notifications",
    disabled: true,
  },
  {
    href: "/admin/audit-logs",
    title: "Audit Entries",
    includeBetaTag: true,
    group: "Data & Integrations",
    adminOnly: true,
    resource: Resource.AuditLog,
    requiredOperation: Operation.Read,
  },
  {
    href: "/admin/database-sessions",
    title: "DB Sessions",
    group: "Data & Integrations",
    adminOnly: true,
    platformAdminOnly: true,
  },
  {
    href: "/organization/ai-logs/",
    title: "AI Logs",
    group: "Data & Integrations",
    disabled: true,
  },
  {
    href: "/admin/integrations",
    title: "Integrations",
    group: "Data & Integrations",
    adminOnly: true,
    resource: Resource.Integration,
    requiredOperation: Operation.Read,
  },
  {
    href: "/admin/api-keys",
    title: "API Keys",
    group: "Data & Integrations",
    adminOnly: true,
    resource: Resource.Integration,
    requiredOperation: Operation.Read,
  },
  {
    href: "/organization/pattern-config/",
    title: "Pattern Detection",
    group: "Data & Integrations",
    disabled: true,
  },
  {
    href: "/admin/custom-fields",
    title: "Custom Fields",
    group: "Data & Integrations",
    adminOnly: true,
    resource: Resource.CustomFieldDefinition,
    requiredOperation: Operation.Read,
  },
  {
    href: "/organization/data-retention/",
    title: "Data Retention",
    group: "Data & Integrations",
    disabled: true,
  },
  {
    href: "/organization/docker/",
    title: "Docker Management",
    group: "Data & Integrations",
    disabled: true,
  },
  {
    href: "/organization/resource-editor/",
    title: "Resource Editor",
    group: "Data & Integrations",
    disabled: true,
  },
  {
    href: "/admin/table-change-alerts/",
    title: "Table Change Alerts",
    group: "Data & Integrations",
    adminOnly: true,
    resource: Resource.TableChangeAlert,
    requiredOperation: Operation.Read,
  },
  {
    href: "/admin/document-operations",
    title: "Document Operations",
    group: "Document Management",
    adminOnly: true,
    platformAdminOnly: true,
  },
  {
    href: "/organization/document-templates/",
    title: "Document Templates",
    group: "Document Management",
    disabled: true,
  },
];
