# Generated by Django 4.1.2 on 2022-11-06 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_user_organization"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="email_verified",
        ),
    ]
