package api

import (
	"github.com/emoss08/trenova/internal/api/handlers/accessorialchargehandler"
	"github.com/emoss08/trenova/internal/api/handlers/accountingcontrolhandler"
	"github.com/emoss08/trenova/internal/api/handlers/accounttypehandler"
	"github.com/emoss08/trenova/internal/api/handlers/analyticshandler"
	"github.com/emoss08/trenova/internal/api/handlers/apikeyhandler"
	"github.com/emoss08/trenova/internal/api/handlers/assignmenthandler"
	"github.com/emoss08/trenova/internal/api/handlers/audithandler"
	"github.com/emoss08/trenova/internal/api/handlers/authhandler"
	"github.com/emoss08/trenova/internal/api/handlers/billingcontrolhandler"
	"github.com/emoss08/trenova/internal/api/handlers/billingqueuehandler"
	"github.com/emoss08/trenova/internal/api/handlers/commodityhandler"
	"github.com/emoss08/trenova/internal/api/handlers/customerhandler"
	"github.com/emoss08/trenova/internal/api/handlers/customfieldhandler"
	"github.com/emoss08/trenova/internal/api/handlers/databasesessionhandler"
	"github.com/emoss08/trenova/internal/api/handlers/dataentrycontrolhandler"
	"github.com/emoss08/trenova/internal/api/handlers/dispatchcontrolhandler"
	"github.com/emoss08/trenova/internal/api/handlers/distanceoverridehandler"
	"github.com/emoss08/trenova/internal/api/handlers/docshandler"
	"github.com/emoss08/trenova/internal/api/handlers/documentcontrolhandler"
	"github.com/emoss08/trenova/internal/api/handlers/documenthandler"
	"github.com/emoss08/trenova/internal/api/handlers/documentoperationshandler"
	"github.com/emoss08/trenova/internal/api/handlers/documentpacketrulehandler"
	"github.com/emoss08/trenova/internal/api/handlers/documentparsingrulehandler"
	"github.com/emoss08/trenova/internal/api/handlers/documenttypehandler"
	"github.com/emoss08/trenova/internal/api/handlers/dothazmatreferencehandler"
	"github.com/emoss08/trenova/internal/api/handlers/equipmentmanufacturerhandler"
	"github.com/emoss08/trenova/internal/api/handlers/equipmenttypehandler"
	"github.com/emoss08/trenova/internal/api/handlers/fiscalperiodhandler"
	"github.com/emoss08/trenova/internal/api/handlers/fiscalyearhandler"
	"github.com/emoss08/trenova/internal/api/handlers/fleetcodehandler"
	"github.com/emoss08/trenova/internal/api/handlers/formulatemplatehandler"
	"github.com/emoss08/trenova/internal/api/handlers/glaccounthandler"
	"github.com/emoss08/trenova/internal/api/handlers/googlemapshandler"
	"github.com/emoss08/trenova/internal/api/handlers/hazardousmaterialhandler"
	"github.com/emoss08/trenova/internal/api/handlers/hazmatsegregationrulehandler"
	"github.com/emoss08/trenova/internal/api/handlers/holdreasonhandler"
	"github.com/emoss08/trenova/internal/api/handlers/integrationhandler"
	"github.com/emoss08/trenova/internal/api/handlers/locationcategoryhandler"
	"github.com/emoss08/trenova/internal/api/handlers/locationhandler"
	"github.com/emoss08/trenova/internal/api/handlers/notificationhandler"
	"github.com/emoss08/trenova/internal/api/handlers/organizationhandler"
	"github.com/emoss08/trenova/internal/api/handlers/pagefavoritehandler"
	"github.com/emoss08/trenova/internal/api/handlers/permissionhandler"
	"github.com/emoss08/trenova/internal/api/handlers/realtimehandler"
	"github.com/emoss08/trenova/internal/api/handlers/roleassignmenthandler"
	"github.com/emoss08/trenova/internal/api/handlers/rolehandler"
	"github.com/emoss08/trenova/internal/api/handlers/searchhandler"
	"github.com/emoss08/trenova/internal/api/handlers/sequenceconfighandler"
	"github.com/emoss08/trenova/internal/api/handlers/servicetypehandler"
	"github.com/emoss08/trenova/internal/api/handlers/shipmentcontrolhandler"
	"github.com/emoss08/trenova/internal/api/handlers/shipmenthandler"
	"github.com/emoss08/trenova/internal/api/handlers/shipmentmovehandler"
	"github.com/emoss08/trenova/internal/api/handlers/shipmenttypehandler"
	"github.com/emoss08/trenova/internal/api/handlers/tablechangealerthandler"
	"github.com/emoss08/trenova/internal/api/handlers/tableconfigurationhandler"
	"github.com/emoss08/trenova/internal/api/handlers/tractorhandler"
	"github.com/emoss08/trenova/internal/api/handlers/trailerhandler"
	"github.com/emoss08/trenova/internal/api/handlers/userhandler"
	"github.com/emoss08/trenova/internal/api/handlers/usstatehandler"
	"github.com/emoss08/trenova/internal/api/handlers/versionhandler"
	"github.com/emoss08/trenova/internal/api/handlers/workerhandler"
	"github.com/emoss08/trenova/internal/api/handlers/workerptohandler"
	"go.uber.org/fx"
)

var HandlersModule = fx.Module("api-handlers", fx.Provide(
	organizationhandler.New,
	userhandler.New,
	authhandler.New,
	audithandler.New,
	formulatemplatehandler.New,
	tableconfigurationhandler.New,
	pagefavoritehandler.New,
	equipmenttypehandler.New,
	fleetcodehandler.New,
	tractorhandler.New,
	trailerhandler.New,
	integrationhandler.New,
	workerhandler.New,
	permissionhandler.New,
	realtimehandler.New,
	rolehandler.New,
	roleassignmenthandler.New,
	searchhandler.New,
	usstatehandler.New,
	equipmentmanufacturerhandler.New,
	customfieldhandler.New,
	docshandler.New,
	databasesessionhandler.New,
	documenthandler.New,
	documentoperationshandler.New,
	documentpacketrulehandler.New,
	accessorialchargehandler.New,
	assignmenthandler.New,
	versionhandler.New,
	servicetypehandler.New,
	sequenceconfighandler.New,
	shipmentcontrolhandler.New,
	shipmentmovehandler.New,
	shipmenthandler.New,
	shipmenttypehandler.New,
	hazardousmaterialhandler.New,
	hazmatsegregationrulehandler.New,
	dothazmatreferencehandler.New,
	commodityhandler.New,
	customerhandler.New,
	googlemapshandler.New,
	accountingcontrolhandler.New,
	accounttypehandler.New,
	glaccounthandler.New,
	fiscalyearhandler.New,
	fiscalperiodhandler.New,
	locationcategoryhandler.New,
	locationhandler.New,
	documenttypehandler.New,
	holdreasonhandler.New,
	billingcontrolhandler.New,
	billingqueuehandler.New,
	dataentrycontrolhandler.New,
	dispatchcontrolhandler.New,
	documentcontrolhandler.New,
	documentparsingrulehandler.New,
	workerptohandler.New,
	distanceoverridehandler.New,
	analyticshandler.New,
	apikeyhandler.New,
	tablechangealerthandler.New,
	notificationhandler.New,
))
