package api

import (
	"github.com/emoss08/trenova/internal/api/handlers"
	"go.uber.org/fx"
)

var HandlerModule = fx.Module("api-handlers", fx.Provide(
	handlers.NewAuthHandler,
	handlers.NewAPITokenHandler,
	handlers.NewOrganizationHandler,
	handlers.NewUserHandler,
	handlers.NewUsStateHandler,
	handlers.NewAuditHandler,
	handlers.NewWebSocketHandler,
	handlers.NewNotificationHandler,
	handlers.NewPageFavoriteHandler,
	handlers.NewTableConfigurationHandler,
	handlers.NewHoldReasonHandler,
	handlers.NewHazardousMaterialHandler,
	handlers.NewHazmatSegregationRuleHandler,
	handlers.NewBillingControlHandler,
	handlers.NewShipmentControlHandler,
	handlers.NewDataRetentionHandler,
	handlers.NewLocationCategoryHandler,
	handlers.NewLocationHandler,
	handlers.NewFleetCodeHandler,
	handlers.NewEmailProfileHandler,
	handlers.NewDocumentTypeHandler,
	handlers.NewEquipmentTypeHandler,
	handlers.NewEquipmentManufacturerHandler,
	handlers.NewWorkerHandler,
	handlers.NewShipmentTypeHandler,
	handlers.NewServiceTypeHandler,
	handlers.NewTractorHandler,
	handlers.NewTrailerHandler,
	handlers.NewCommodityHandler,
	handlers.NewClassificationHandler,
	handlers.NewAILogHandler,
	handlers.NewGoogleMapsHandler,
	handlers.NewCustomerHandler,
	handlers.NewVariableHandler,
	handlers.NewPermissionHandler,
	handlers.NewAccessorialChargeHandler,
	handlers.NewShipmentHandler,
	handlers.NewDedicatedLaneHandler,
	handlers.NewDedicatedLaneSuggestionHandler,
	handlers.NewPatternConfigHandler,
	handlers.NewDispatchControlHandler,
	handlers.NewDistanceOverrideHandler,
	handlers.NewSearchHandler,
	handlers.NewAccountTypeHandler,
))
