//revive:disable-next-line:var-naming
package api

import (
	"github.com/emoss08/trenova/internal/api/handlers/accessorialchargehandler"
	"github.com/emoss08/trenova/internal/api/handlers/accountingcontrolhandler"
	"github.com/emoss08/trenova/internal/api/handlers/accountsreceivablehandler"
	"github.com/emoss08/trenova/internal/api/handlers/accounttypehandler"
	"github.com/emoss08/trenova/internal/api/handlers/analyticshandler"
	"github.com/emoss08/trenova/internal/api/handlers/apikeyhandler"
	"github.com/emoss08/trenova/internal/api/handlers/assignmenthandler"
	"github.com/emoss08/trenova/internal/api/handlers/audithandler"
	"github.com/emoss08/trenova/internal/api/handlers/authhandler"
	"github.com/emoss08/trenova/internal/api/handlers/bankreceiptbatchhandler"
	"github.com/emoss08/trenova/internal/api/handlers/bankreceipthandler"
	"github.com/emoss08/trenova/internal/api/handlers/bankreceiptworkitemhandler"
	"github.com/emoss08/trenova/internal/api/handlers/billingcontrolhandler"
	"github.com/emoss08/trenova/internal/api/handlers/billingqueuehandler"
	"github.com/emoss08/trenova/internal/api/handlers/commodityhandler"
	"github.com/emoss08/trenova/internal/api/handlers/controlplaneprovisioninghandler"
	"github.com/emoss08/trenova/internal/api/handlers/customerhandler"
	"github.com/emoss08/trenova/internal/api/handlers/customerpaymenthandler"
	"github.com/emoss08/trenova/internal/api/handlers/customfieldhandler"
	"github.com/emoss08/trenova/internal/api/handlers/databasesessionhandler"
	"github.com/emoss08/trenova/internal/api/handlers/dataentrycontrolhandler"
	"github.com/emoss08/trenova/internal/api/handlers/dataretentionhandler"
	"github.com/emoss08/trenova/internal/api/handlers/dispatchcontrolhandler"
	"github.com/emoss08/trenova/internal/api/handlers/distancecontrolhandler"
	"github.com/emoss08/trenova/internal/api/handlers/distanceoverridehandler"
	"github.com/emoss08/trenova/internal/api/handlers/distanceprofilehandler"
	"github.com/emoss08/trenova/internal/api/handlers/docshandler"
	"github.com/emoss08/trenova/internal/api/handlers/documentcontrolhandler"
	"github.com/emoss08/trenova/internal/api/handlers/documenthandler"
	"github.com/emoss08/trenova/internal/api/handlers/documentoperationshandler"
	"github.com/emoss08/trenova/internal/api/handlers/documentpacketrulehandler"
	"github.com/emoss08/trenova/internal/api/handlers/documentparsingrulehandler"
	"github.com/emoss08/trenova/internal/api/handlers/documenttypehandler"
	"github.com/emoss08/trenova/internal/api/handlers/dothazmatreferencehandler"
	"github.com/emoss08/trenova/internal/api/handlers/edihandler"
	"github.com/emoss08/trenova/internal/api/handlers/emailhandler"
	"github.com/emoss08/trenova/internal/api/handlers/equipmentmanufacturerhandler"
	"github.com/emoss08/trenova/internal/api/handlers/equipmenttypehandler"
	"github.com/emoss08/trenova/internal/api/handlers/exchangeratehandler"
	"github.com/emoss08/trenova/internal/api/handlers/fiscalperiodhandler"
	"github.com/emoss08/trenova/internal/api/handlers/fiscalyearhandler"
	"github.com/emoss08/trenova/internal/api/handlers/fleetcodehandler"
	"github.com/emoss08/trenova/internal/api/handlers/formulatemplatehandler"
	"github.com/emoss08/trenova/internal/api/handlers/glaccounthandler"
	"github.com/emoss08/trenova/internal/api/handlers/glbalancehandler"
	"github.com/emoss08/trenova/internal/api/handlers/googlemapshandler"
	"github.com/emoss08/trenova/internal/api/handlers/hazardousmaterialhandler"
	"github.com/emoss08/trenova/internal/api/handlers/hazmatsegregationrulehandler"
	"github.com/emoss08/trenova/internal/api/handlers/holdreasonhandler"
	"github.com/emoss08/trenova/internal/api/handlers/iamhandler"
	"github.com/emoss08/trenova/internal/api/handlers/integrationhandler"
	"github.com/emoss08/trenova/internal/api/handlers/invoiceadjustmentcontrolhandler"
	"github.com/emoss08/trenova/internal/api/handlers/invoiceadjustmenthandler"
	"github.com/emoss08/trenova/internal/api/handlers/invoicehandler"
	"github.com/emoss08/trenova/internal/api/handlers/journalentryhandler"
	"github.com/emoss08/trenova/internal/api/handlers/journalreversalhandler"
	"github.com/emoss08/trenova/internal/api/handlers/locationcategoryhandler"
	"github.com/emoss08/trenova/internal/api/handlers/locationhandler"
	"github.com/emoss08/trenova/internal/api/handlers/manualjournalhandler"
	"github.com/emoss08/trenova/internal/api/handlers/organizationhandler"
	"github.com/emoss08/trenova/internal/api/handlers/pagefavoritehandler"
	"github.com/emoss08/trenova/internal/api/handlers/permissionhandler"
	"github.com/emoss08/trenova/internal/api/handlers/platformcataloghandler"
	"github.com/emoss08/trenova/internal/api/handlers/ratetablehandler"
	"github.com/emoss08/trenova/internal/api/handlers/realtimehandler"
	"github.com/emoss08/trenova/internal/api/handlers/roleassignmenthandler"
	"github.com/emoss08/trenova/internal/api/handlers/rolehandler"
	"github.com/emoss08/trenova/internal/api/handlers/searchhandler"
	"github.com/emoss08/trenova/internal/api/handlers/sequenceconfighandler"
	"github.com/emoss08/trenova/internal/api/handlers/servicefailurehandler"
	"github.com/emoss08/trenova/internal/api/handlers/servicefailurereasoncodehandler"
	"github.com/emoss08/trenova/internal/api/handlers/servicetypehandler"
	"github.com/emoss08/trenova/internal/api/handlers/shipmentcontrolhandler"
	"github.com/emoss08/trenova/internal/api/handlers/shipmenteventhandler"
	"github.com/emoss08/trenova/internal/api/handlers/shipmenthandler"
	"github.com/emoss08/trenova/internal/api/handlers/shipmentmovehandler"
	"github.com/emoss08/trenova/internal/api/handlers/shipmenttypehandler"
	"github.com/emoss08/trenova/internal/api/handlers/storedmileagehandler"
	"github.com/emoss08/trenova/internal/api/handlers/tablechangealerthandler"
	"github.com/emoss08/trenova/internal/api/handlers/tractorhandler"
	"github.com/emoss08/trenova/internal/api/handlers/trailerhandler"
	"github.com/emoss08/trenova/internal/api/handlers/userhandler"
	"github.com/emoss08/trenova/internal/api/handlers/usstatehandler"
	"github.com/emoss08/trenova/internal/api/handlers/versionhandler"
	"github.com/emoss08/trenova/internal/api/handlers/weatheralerthandler"
	"github.com/emoss08/trenova/internal/api/handlers/workerhandler"
	"github.com/emoss08/trenova/internal/api/handlers/workerptohandler"
	"go.uber.org/fx"
)

var HandlersModule = fx.Module("api-handlers", fx.Provide(
	dataretentionhandler.New,
	organizationhandler.New,
	iamhandler.New,
	userhandler.New,
	authhandler.New,
	audithandler.New,
	formulatemplatehandler.New,
	pagefavoritehandler.New,
	equipmenttypehandler.New,
	fleetcodehandler.New,
	tractorhandler.New,
	trailerhandler.New,
	integrationhandler.New,
	invoicehandler.New,
	workerhandler.New,
	permissionhandler.New,
	platformcataloghandler.New,
	realtimehandler.New,
	rolehandler.New,
	roleassignmenthandler.New,
	searchhandler.New,
	usstatehandler.New,
	equipmentmanufacturerhandler.New,
	customfieldhandler.New,
	docshandler.New,
	databasesessionhandler.New,
	documenthandler.New,
	documentoperationshandler.New,
	documentpacketrulehandler.New,
	accessorialchargehandler.New,
	assignmenthandler.New,
	accountsreceivablehandler.New,
	bankreceiptbatchhandler.New,
	bankreceipthandler.New,
	bankreceiptworkitemhandler.New,
	versionhandler.New,
	controlplaneprovisioninghandler.New,
	servicetypehandler.New,
	servicefailurereasoncodehandler.New,
	servicefailurehandler.New,
	sequenceconfighandler.New,
	shipmentcontrolhandler.New,
	shipmenteventhandler.New,
	shipmentmovehandler.New,
	shipmenthandler.New,
	shipmenttypehandler.New,
	hazardousmaterialhandler.New,
	hazmatsegregationrulehandler.New,
	dothazmatreferencehandler.New,
	edihandler.New,
	emailhandler.New,
	commodityhandler.New,
	customerhandler.New,
	customerpaymenthandler.New,
	googlemapshandler.New,
	weatheralerthandler.New,
	accountingcontrolhandler.New,
	accounttypehandler.New,
	glaccounthandler.New,
	glbalancehandler.New,
	fiscalyearhandler.New,
	fiscalperiodhandler.New,
	locationcategoryhandler.New,
	locationhandler.New,
	documenttypehandler.New,
	holdreasonhandler.New,
	ratetablehandler.New,
	invoiceadjustmenthandler.New,
	invoiceadjustmentcontrolhandler.New,
	journalentryhandler.New,
	journalreversalhandler.New,
	manualjournalhandler.New,
	billingcontrolhandler.New,
	billingqueuehandler.New,
	dataentrycontrolhandler.New,
	dispatchcontrolhandler.New,
	documentcontrolhandler.New,
	documentparsingrulehandler.New,
	workerptohandler.New,
	distancecontrolhandler.New,
	distanceoverridehandler.New,
	distanceprofilehandler.New,
	storedmileagehandler.New,
	exchangeratehandler.New,
	analyticshandler.New,
	apikeyhandler.New,
	tablechangealerthandler.New,
))
