//revive:disable-next-line:var-naming
package api

import (
	permissiondomain "github.com/emoss08/trenova/internal/core/domain/permission"
	"github.com/emoss08/trenova/internal/core/domain/platformcatalog"
	"github.com/emoss08/trenova/internal/core/domain/shipmentstate"
	"github.com/emoss08/trenova/internal/core/ports/services"
	"github.com/emoss08/trenova/internal/core/services/accessorialchargeservice"
	"github.com/emoss08/trenova/internal/core/services/accountingcontrolpolicyservice"
	"github.com/emoss08/trenova/internal/core/services/accountingcontrolservice"
	"github.com/emoss08/trenova/internal/core/services/accountsreceivableservice"
	"github.com/emoss08/trenova/internal/core/services/accounttypeservice"
	"github.com/emoss08/trenova/internal/core/services/apikeyservice"
	"github.com/emoss08/trenova/internal/core/services/assignmentservice"
	"github.com/emoss08/trenova/internal/core/services/auditservice"
	"github.com/emoss08/trenova/internal/core/services/authservice"
	"github.com/emoss08/trenova/internal/core/services/bankreceiptbatchservice"
	"github.com/emoss08/trenova/internal/core/services/bankreceiptservice"
	"github.com/emoss08/trenova/internal/core/services/bankreceiptworkitemservice"
	"github.com/emoss08/trenova/internal/core/services/billingcontrolpolicyservice"
	"github.com/emoss08/trenova/internal/core/services/billingcontrolservice"
	"github.com/emoss08/trenova/internal/core/services/billingqueueservice"
	"github.com/emoss08/trenova/internal/core/services/commodityservice"
	"github.com/emoss08/trenova/internal/core/services/customerpaymentservice"
	"github.com/emoss08/trenova/internal/core/services/customerservice"
	"github.com/emoss08/trenova/internal/core/services/customfieldservice"
	"github.com/emoss08/trenova/internal/core/services/databasesessionservice"
	"github.com/emoss08/trenova/internal/core/services/dataentrycontrolservice"
	"github.com/emoss08/trenova/internal/core/services/datatransformer"
	"github.com/emoss08/trenova/internal/core/services/dispatchcontrolservice"
	"github.com/emoss08/trenova/internal/core/services/distancecalculationservice"
	"github.com/emoss08/trenova/internal/core/services/distancecontrolservice"
	"github.com/emoss08/trenova/internal/core/services/distanceoverrideservice"
	"github.com/emoss08/trenova/internal/core/services/distanceprofileservice"
	"github.com/emoss08/trenova/internal/core/services/documentcontrolservice"
	"github.com/emoss08/trenova/internal/core/services/documentintelligenceservice"
	"github.com/emoss08/trenova/internal/core/services/documentoperationsservice"
	"github.com/emoss08/trenova/internal/core/services/documentpacketruleservice"
	"github.com/emoss08/trenova/internal/core/services/documentparsingruleservice"
	"github.com/emoss08/trenova/internal/core/services/documentsearchprojectionservice"
	"github.com/emoss08/trenova/internal/core/services/documentservice"
	"github.com/emoss08/trenova/internal/core/services/documenttypeservice"
	"github.com/emoss08/trenova/internal/core/services/documentuploadservice"
	"github.com/emoss08/trenova/internal/core/services/dothazmatreferenceservice"
	"github.com/emoss08/trenova/internal/core/services/ediservice"
	"github.com/emoss08/trenova/internal/core/services/emailservice"
	"github.com/emoss08/trenova/internal/core/services/entitlementservice"
	"github.com/emoss08/trenova/internal/core/services/equipmentmanufacturerservice"
	"github.com/emoss08/trenova/internal/core/services/equipmenttypeservice"
	"github.com/emoss08/trenova/internal/core/services/exchangerateservice"
	"github.com/emoss08/trenova/internal/core/services/fiscalperiodservice"
	"github.com/emoss08/trenova/internal/core/services/fiscalyearservice"
	"github.com/emoss08/trenova/internal/core/services/fleetcodeservice"
	"github.com/emoss08/trenova/internal/core/services/glaccountservice"
	"github.com/emoss08/trenova/internal/core/services/glbalanceservice"
	"github.com/emoss08/trenova/internal/core/services/globalsearchservice"
	"github.com/emoss08/trenova/internal/core/services/googlemapsservice"
	"github.com/emoss08/trenova/internal/core/services/hazardousmaterialservice"
	"github.com/emoss08/trenova/internal/core/services/hazmatsegregationruleservice"
	"github.com/emoss08/trenova/internal/core/services/holdreasonservice"
	"github.com/emoss08/trenova/internal/core/services/iamservice"
	"github.com/emoss08/trenova/internal/core/services/invoiceadjustmentcontrolservice"
	"github.com/emoss08/trenova/internal/core/services/invoiceadjustmentservice"
	"github.com/emoss08/trenova/internal/core/services/invoiceservice"
	"github.com/emoss08/trenova/internal/core/services/journalentryservice"
	"github.com/emoss08/trenova/internal/core/services/journalreversalservice"
	"github.com/emoss08/trenova/internal/core/services/locationcategoryservice"
	"github.com/emoss08/trenova/internal/core/services/locationcodegenerator"
	"github.com/emoss08/trenova/internal/core/services/locationservice"
	"github.com/emoss08/trenova/internal/core/services/manualjournalservice"
	"github.com/emoss08/trenova/internal/core/services/notificationservice"
	"github.com/emoss08/trenova/internal/core/services/openaidocumentservice"
	"github.com/emoss08/trenova/internal/core/services/organizationservice"
	"github.com/emoss08/trenova/internal/core/services/pagefavoriteservice"
	"github.com/emoss08/trenova/internal/core/services/permission"
	"github.com/emoss08/trenova/internal/core/services/platformbillingservice"
	"github.com/emoss08/trenova/internal/core/services/realtimeservice"
	"github.com/emoss08/trenova/internal/core/services/roleassignmentservice"
	"github.com/emoss08/trenova/internal/core/services/roleservice"
	"github.com/emoss08/trenova/internal/core/services/sequenceconfigservice"
	"github.com/emoss08/trenova/internal/core/services/servicetypeservice"
	"github.com/emoss08/trenova/internal/core/services/shipmentcommentservice"
	"github.com/emoss08/trenova/internal/core/services/shipmentcommercial"
	"github.com/emoss08/trenova/internal/core/services/shipmentcontrolservice"
	"github.com/emoss08/trenova/internal/core/services/shipmenteventservice"
	"github.com/emoss08/trenova/internal/core/services/shipmentholdservice"
	"github.com/emoss08/trenova/internal/core/services/shipmentimportassistantservice"
	"github.com/emoss08/trenova/internal/core/services/shipmentmoveservice"
	"github.com/emoss08/trenova/internal/core/services/shipmentservice"
	"github.com/emoss08/trenova/internal/core/services/shipmenttypeservice"
	"github.com/emoss08/trenova/internal/core/services/storedmileageservice"
	"github.com/emoss08/trenova/internal/core/services/tablechangealertservice"
	"github.com/emoss08/trenova/internal/core/services/tableconfigurationservice"
	"github.com/emoss08/trenova/internal/core/services/tenantprovisioningservice"
	"github.com/emoss08/trenova/internal/core/services/thumbnailservice"
	"github.com/emoss08/trenova/internal/core/services/tractorservice"
	"github.com/emoss08/trenova/internal/core/services/trailerservice"
	"github.com/emoss08/trenova/internal/core/services/usageservice"
	"github.com/emoss08/trenova/internal/core/services/userservice"
	"github.com/emoss08/trenova/internal/core/services/usstateservice"
	"github.com/emoss08/trenova/internal/core/services/versionservice"
	"github.com/emoss08/trenova/internal/core/services/weatheralertservice"
	"github.com/emoss08/trenova/internal/core/services/workerptoservice"
	"github.com/emoss08/trenova/internal/core/services/workerservice"
	"github.com/emoss08/trenova/internal/core/services/workflowstarter"
	"github.com/emoss08/trenova/internal/infrastructure/controlplane"
	"github.com/emoss08/trenova/pkg/seqgen"

	"go.uber.org/fx"
)

var ServiceModule = fx.Module("api-services", fx.Provide(
	organizationservice.New,
	iamservice.New,
	userservice.New,
	authservice.New,
	tableconfigurationservice.New,
	pagefavoriteservice.New,
	equipmentmanufacturerservice.New,
	equipmenttypeservice.New,
	fleetcodeservice.New,
	tractorservice.New,
	trailerservice.New,
	workerservice.New,
	auditservice.New,
	datatransformer.New,
	workflowstarter.New,
	permission.NewEngine,
	roleservice.New,
	permissiondomain.NewRegistry,
	permissiondomain.NewRouteRegistry,
	fx.Annotate(
		platformcatalog.NewStaticProvider,
		fx.ResultTags(`group:"platform_catalog_providers"`),
		fx.As(new(platformcatalog.CatalogProvider)),
	),
	platformcatalog.NewRegistry,
	entitlementservice.NewLocalEntitlementProvider,
	platformbillingservice.NewLocalBillingProvider,
	usageservice.NewNoopUsageProvider,
	fx.Annotate(
		controlplane.NewHTTPControlPlaneClient,
		fx.As(new(controlplane.Client)),
	),
	controlplane.NewCloudEntitlementProvider,
	controlplane.NewCloudBillingProvider,
	controlplane.NewCloudUsageProvider,
	fx.Annotate(
		controlplane.NewCloudAccessAuthorizer,
		fx.As(new(services.AccessAuthorizer)),
	),
	controlplane.NewHeartbeatReporter,
	tenantprovisioningservice.New,
	SelectEntitlementProvider,
	SelectBillingProvider,
	SelectUsageProvider,
	roleassignmentservice.New,
	usstateservice.New,
	shipmentstate.NewCoordinator,
	shipmentcommercial.New,
	customfieldservice.New,
	customfieldservice.NewValuesService,
	databasesessionservice.New,
	realtimeservice.New,
	globalsearchservice.New,
	thumbnailservice.NewGenerator,
	documentintelligenceservice.New,
	documentoperationsservice.New,
	documentsearchprojectionservice.New,
	documentservice.New,
	documentuploadservice.New,
	accessorialchargeservice.New,
	assignmentservice.New,
	fx.Annotate(
		bankreceiptbatchservice.New,
		fx.As(new(services.BankReceiptBatchService)),
	),
	bankreceiptservice.New,
	func(s *bankreceiptservice.Service) services.BankReceiptService { return s },
	bankreceiptworkitemservice.New,
	versionservice.New,
	servicetypeservice.New,
	sequenceconfigservice.New,
	shipmentcontrolservice.New,
	shipmentcommentservice.New,
	shipmenteventservice.New,
	shipmentholdservice.New,
	shipmentmoveservice.New,
	shipmentservice.New,
	shipmenttypeservice.New,
	hazardousmaterialservice.New,
	hazmatsegregationruleservice.New,
	dothazmatreferenceservice.New,
	ediservice.New,
	emailservice.New,
	func(s *emailservice.Service) services.EmailService { return s },
	commodityservice.New,
	fx.Annotate(
		customerpaymentservice.New,
		fx.As(new(services.CustomerPaymentService)),
	),
	customerservice.New,
	googlemapsservice.NewAutoCompleteService,
	fx.Annotate(
		weatheralertservice.New,
		fx.As(new(services.WeatherAlertService)),
	),
	accountingcontrolservice.New,
	accountingcontrolpolicyservice.New,
	accountsreceivableservice.New,
	accounttypeservice.New,
	glaccountservice.New,
	glbalanceservice.New,
	fiscalyearservice.New,
	fiscalperiodservice.New,
	locationcodegenerator.New,
	locationcategoryservice.New,
	locationservice.New,
	documenttypeservice.New,
	holdreasonservice.New,
	invoiceadjustmentcontrolservice.New,
	fx.Annotate(
		func(g seqgen.Generator) services.InvoiceAdjustGenerator { return g },
	),
	invoiceadjustmentservice.New,
	invoiceservice.New,
	journalentryservice.New,
	journalreversalservice.New,
	manualjournalservice.New,
	billingcontrolservice.New,
	billingcontrolpolicyservice.New,
	billingqueueservice.New,
	dataentrycontrolservice.New,
	dispatchcontrolservice.New,
	documentcontrolservice.New,
	documentparsingruleservice.New,
	func(s *documentparsingruleservice.Service) services.DocumentParsingRuleRuntime { return s },
	func(s *documentparsingruleservice.Service) services.DocumentParsingRuleAdminService { return s },
	documentpacketruleservice.New,
	workerptoservice.New,
	distancecalculationservice.New,
	distancecontrolservice.New,
	distanceoverrideservice.New,
	distanceprofileservice.New,
	storedmileageservice.New,
	exchangerateservice.New,
	apikeyservice.New,
	notificationservice.New,
	openaidocumentservice.New,
	shipmentimportassistantservice.New,
	tablechangealertservice.New,
	tablechangealertservice.NewConsumer,
	fx.Annotate(
		apikeyservice.NewUsageBufferWithLifecycle,
		fx.As(new(services.UsageRecorder)),
	),
), fx.Invoke(
	func(*controlplane.HeartbeatReporter) {},
))
