package api

import (
	permissiondomain "github.com/emoss08/trenova/internal/core/domain/permission"
	"github.com/emoss08/trenova/internal/core/domain/shipmentstate"
	"github.com/emoss08/trenova/internal/core/ports/services"
	"github.com/emoss08/trenova/internal/core/services/accessorialchargeservice"
	"github.com/emoss08/trenova/internal/core/services/accountingcontrolservice"
	"github.com/emoss08/trenova/internal/core/services/accounttypeservice"
	"github.com/emoss08/trenova/internal/core/services/apikeyservice"
	"github.com/emoss08/trenova/internal/core/services/assignmentservice"
	"github.com/emoss08/trenova/internal/core/services/auditservice"
	"github.com/emoss08/trenova/internal/core/services/authservice"
	"github.com/emoss08/trenova/internal/core/services/billingcontrolservice"
	"github.com/emoss08/trenova/internal/core/services/commodityservice"
	"github.com/emoss08/trenova/internal/core/services/customerservice"
	"github.com/emoss08/trenova/internal/core/services/customfieldservice"
	"github.com/emoss08/trenova/internal/core/services/databasesessionservice"
	"github.com/emoss08/trenova/internal/core/services/dataentrycontrolservice"
	"github.com/emoss08/trenova/internal/core/services/datatransformer"
	"github.com/emoss08/trenova/internal/core/services/dispatchcontrolservice"
	"github.com/emoss08/trenova/internal/core/services/distanceoverrideservice"
	"github.com/emoss08/trenova/internal/core/services/documentcontrolservice"
	"github.com/emoss08/trenova/internal/core/services/documentintelligenceservice"
	"github.com/emoss08/trenova/internal/core/services/documentoperationsservice"
	"github.com/emoss08/trenova/internal/core/services/documentpacketruleservice"
	"github.com/emoss08/trenova/internal/core/services/documentparsingruleservice"
	"github.com/emoss08/trenova/internal/core/services/documentsearchprojectionservice"
	"github.com/emoss08/trenova/internal/core/services/documentservice"
	"github.com/emoss08/trenova/internal/core/services/documenttypeservice"
	"github.com/emoss08/trenova/internal/core/services/documentuploadservice"
	"github.com/emoss08/trenova/internal/core/services/dothazmatreferenceservice"
	"github.com/emoss08/trenova/internal/core/services/equipmentmanufacturerservice"
	"github.com/emoss08/trenova/internal/core/services/equipmenttypeservice"
	"github.com/emoss08/trenova/internal/core/services/fiscalperiodservice"
	"github.com/emoss08/trenova/internal/core/services/fiscalyearservice"
	"github.com/emoss08/trenova/internal/core/services/fleetcodeservice"
	"github.com/emoss08/trenova/internal/core/services/glaccountservice"
	"github.com/emoss08/trenova/internal/core/services/globalsearchservice"
	"github.com/emoss08/trenova/internal/core/services/googlemapsservice"
	"github.com/emoss08/trenova/internal/core/services/hazardousmaterialservice"
	"github.com/emoss08/trenova/internal/core/services/hazmatsegregationruleservice"
	"github.com/emoss08/trenova/internal/core/services/holdreasonservice"
	"github.com/emoss08/trenova/internal/core/services/locationcategoryservice"
	"github.com/emoss08/trenova/internal/core/services/locationservice"
	"github.com/emoss08/trenova/internal/core/services/notificationservice"
	"github.com/emoss08/trenova/internal/core/services/openaidocumentservice"
	"github.com/emoss08/trenova/internal/core/services/shipmentimportassistantservice"
	"github.com/emoss08/trenova/internal/core/services/organizationservice"
	"github.com/emoss08/trenova/internal/core/services/pagefavoriteservice"
	"github.com/emoss08/trenova/internal/core/services/permission"
	"github.com/emoss08/trenova/internal/core/services/realtimeservice"
	"github.com/emoss08/trenova/internal/core/services/roleassignmentservice"
	"github.com/emoss08/trenova/internal/core/services/roleservice"
	"github.com/emoss08/trenova/internal/core/services/sequenceconfigservice"
	"github.com/emoss08/trenova/internal/core/services/servicetypeservice"
	"github.com/emoss08/trenova/internal/core/services/shipmentcommentservice"
	"github.com/emoss08/trenova/internal/core/services/shipmentcommercial"
	"github.com/emoss08/trenova/internal/core/services/shipmentcontrolservice"
	"github.com/emoss08/trenova/internal/core/services/shipmentholdservice"
	"github.com/emoss08/trenova/internal/core/services/shipmentmoveservice"
	"github.com/emoss08/trenova/internal/core/services/shipmentservice"
	"github.com/emoss08/trenova/internal/core/services/shipmenttypeservice"
	"github.com/emoss08/trenova/internal/core/services/tablechangealertservice"
	"github.com/emoss08/trenova/internal/core/services/tableconfigurationservice"
	"github.com/emoss08/trenova/internal/core/services/thumbnailservice"
	"github.com/emoss08/trenova/internal/core/services/tractorservice"
	"github.com/emoss08/trenova/internal/core/services/trailerservice"
	"github.com/emoss08/trenova/internal/core/services/userservice"
	"github.com/emoss08/trenova/internal/core/services/usstateservice"
	"github.com/emoss08/trenova/internal/core/services/versionservice"
	"github.com/emoss08/trenova/internal/core/services/workerptoservice"
	"github.com/emoss08/trenova/internal/core/services/workerservice"
	"github.com/emoss08/trenova/internal/core/services/workflowstarter"

	"go.uber.org/fx"
)

var ServiceModule = fx.Module("api-services", fx.Provide(
	organizationservice.New,
	userservice.New,
	authservice.New,
	tableconfigurationservice.New,
	pagefavoriteservice.New,
	equipmentmanufacturerservice.New,
	equipmenttypeservice.New,
	fleetcodeservice.New,
	tractorservice.New,
	trailerservice.New,
	workerservice.New,
	auditservice.New,
	datatransformer.New,
	workflowstarter.New,
	permission.NewEngine,
	roleservice.New,
	permissiondomain.NewRegistry,
	permissiondomain.NewRouteRegistry,
	roleassignmentservice.New,
	usstateservice.New,
	shipmentstate.NewCoordinator,
	shipmentcommercial.New,
	customfieldservice.New,
	customfieldservice.NewValuesService,
	databasesessionservice.New,
	realtimeservice.New,
	globalsearchservice.New,
	thumbnailservice.NewGenerator,
	documentintelligenceservice.New,
	documentoperationsservice.New,
	documentsearchprojectionservice.New,
	documentservice.New,
	documentuploadservice.New,
	accessorialchargeservice.New,
	assignmentservice.New,
	versionservice.New,
	servicetypeservice.New,
	sequenceconfigservice.New,
	shipmentcontrolservice.New,
	shipmentcommentservice.New,
	shipmentholdservice.New,
	shipmentmoveservice.New,
	shipmentservice.New,
	shipmenttypeservice.New,
	hazardousmaterialservice.New,
	hazmatsegregationruleservice.New,
	dothazmatreferenceservice.New,
	commodityservice.New,
	customerservice.New,
	googlemapsservice.NewAutoCompleteService,
	accountingcontrolservice.New,
	accounttypeservice.New,
	glaccountservice.New,
	fiscalyearservice.New,
	fiscalperiodservice.New,
	locationcategoryservice.New,
	locationservice.New,
	documenttypeservice.New,
	holdreasonservice.New,
	billingcontrolservice.New,
	dataentrycontrolservice.New,
	dispatchcontrolservice.New,
	documentcontrolservice.New,
	documentparsingruleservice.New,
	func(s *documentparsingruleservice.Service) services.DocumentParsingRuleRuntime { return s },
	func(s *documentparsingruleservice.Service) services.DocumentParsingRuleAdminService { return s },
	documentpacketruleservice.New,
	workerptoservice.New,
	distanceoverrideservice.New,
	apikeyservice.New,
	notificationservice.New,
	openaidocumentservice.New,
	shipmentimportassistantservice.New,
	tablechangealertservice.New,
	tablechangealertservice.NewConsumer,
	fx.Annotate(
		apikeyservice.NewUsageBufferWithLifecycle,
		fx.As(new(services.UsageRecorder)),
	),
))
