listen_addresses = '*'
ssl = on
ssl_cert_file = '/var/lib/postgresql/server.crt'
ssl_key_file = '/var/lib/postgresql/server.key'
max_connections = 200

shared_buffers = 1GB
effective_cache_size = 3GB
work_mem = 16MB
maintenance_work_mem = 256MB
wal_buffers = 16MB

checkpoint_completion_target = 0.9
wal_level = replica
max_wal_size = 2GB
min_wal_size = 256MB

random_page_cost = 1.1
effective_io_concurrency = 200
default_statistics_target = 100

shared_preload_libraries = 'pg_stat_statements'
pg_stat_statements.track = all

autovacuum = on
autovacuum_max_workers = 4
autovacuum_naptime = 30s
autovacuum_vacuum_threshold = 50
autovacuum_analyze_threshold = 50
autovacuum_vacuum_scale_factor = 0.05
autovacuum_analyze_scale_factor = 0.02

jit = on

log_min_duration_statement = 1000
log_checkpoints = on
log_connections = on
log_disconnections = on
log_lock_waits = on
log_temp_files = 0
