kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: my-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: Role
  name: my-rule
  apiGroup: rbac.authorization.k8s.io