[tool.isort]
profile = "black"
skip = ["venv", ".git", "migrations", ".venv", "client", ".tox"]

[tool.black]
line-length = 88
target-version = ["py311"]
exclude = '''
/(
  | \.git
  | client
  | \.mypy_cache
  | \.pytest_cache
  | \.ruff_cache
  | \.vscode
  | \.tox
  | venv
  | \.docker
  | \.github
  | buck-out
  | build
  | dist
)/
'''
