[tool.isort]
profile = "black"
skip = ["venv", ".git", "migrations", ".venv", "client", ".tox"]

[tool.black]
line-length = 88
target-version = ["py311"]
exclude = '''
/(
  | \.git
  | client
  | \.mypy_cache
  | \.pytest_cache
  | \.ruff_cache
  | \.vscode
  | \.tox
  | venv
  | \.docker
  | \.github
  | buck-out
  | build
  | dist
  | migrations
)/
'''

[tool.ruff]
ignore = ["E501"]
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "client",
    "node_modules",
    "venv",
]

[tool.mypy]
plugins = ["mypy_django_plugin.main", "mypy_drf_plugin.main"]
enable_error_code = ["truthy-bool", "redundant-expr", "unused-awaitable"]
allow_redefinition = true
check_untyped_defs = true
disallow_untyped_decorators = true
disallow_any_explicit = false
disallow_any_generics = false
disable_error_code = ["var-annotated", "misc"]
disallow_untyped_calls = false
disallow_untyped_defs = false
ignore_errors = false
ignore_missing_imports = true
implicit_reexport = true
local_partial_types = true
strict_optional = true
strict_equality = true
no_implicit_optional = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true
warn_unreachable = true
warn_no_return = true
exclude = "venv"
strict = true
python_version = 3.11

[mypy-tests.'*']
ignore_errors = true

[tool.django-stubs]
django_settings_module = "backend.settings"

[tool.flake8]
show-source = true
statistics = false
doctests = true
enable-extensions = "G"
docstring-style = "google"
exclude = ["tests", "migrations", "__pycache__", "venv", ".venv"]
max-line-length = 100
max-complexity = 6
ignore = ["E501", "W503", "F721", "C901"]

[tool.autoflake]
imports = ["django", "requests", "urllib3"]
recursive = true
exclude = [
    "rvenv/*",
    "*/migrations/*",
    "*/tests/*",
    "*/settings/*",
    "*/urls.py",
    "*/wsgi.py",
    "*/asgi.py",
    "*/apps.py",
]
remove-all-unused-imports = true
remove-unused-variables = true
in-place = true

[tool.pytest]
DJANGO_SETTINGS_MODULE = "backend.settings"
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "serial: marks tests as serial (deselect with '-m \"not serial\"')",
    "unit: marks tests as unit (deselect with '-m \"not unit\"')",
]
python_files = ["tests.py", "test_*.py", "*_tests.py"]
filterwarnings = [
    "ignore::DeprecationWarning",
    "ignore::PendingDeprecationWarning",
    "ignore::ImportWarning",
    "ignore::ResourceWarning",
]

[tool.bandit]
exclude_dirs = [
    "venv",
    ".venv",
    "node_modules",
    "client",
    "migrations",
    ".tox",
    ".git",
    ".github",
    ".vscode",
    ".docker",
    "buck-out",
    "build",
    "dist",
    "tests",
    "management"
]