package detentionresolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"

	"github.com/emoss08/trenova/internal/api/graphql/gqlmodel"
	"github.com/emoss08/trenova/internal/api/graphql/resolver/base"
	"github.com/emoss08/trenova/internal/core/domain/permission"
	"github.com/emoss08/trenova/internal/core/ports/repositories"
	"github.com/emoss08/trenova/internal/core/services/detentionservice"
	"github.com/emoss08/trenova/shared/pulid"
)

func (r *MutationResolver) CreateDetentionPolicy(ctx context.Context, input gqlmodel.DetentionPolicyInput) (*gqlmodel.DetentionPolicy, error) {
	authCtx, err := r.RequirePermission(ctx, permission.ResourceDetentionPolicy, permission.OpCreate)
	if err != nil {
		return nil, err
	}

	entity, err := detentionPolicyFromInput(&input, pulid.Nil, base.TenantInfo(authCtx))
	if err != nil {
		return nil, err
	}

	created, err := r.DetentionPolicyService.Create(ctx, entity, authCtx.UserID)
	if err != nil {
		return nil, err
	}

	return detentionPolicyToModel(created), nil
}

func (r *MutationResolver) UpdateDetentionPolicy(ctx context.Context, id string, input gqlmodel.DetentionPolicyInput) (*gqlmodel.DetentionPolicy, error) {
	authCtx, err := r.RequirePermission(ctx, permission.ResourceDetentionPolicy, permission.OpUpdate)
	if err != nil {
		return nil, err
	}

	policyID, err := pulid.MustParse(id)
	if err != nil {
		return nil, err
	}

	entity, err := detentionPolicyFromInput(&input, policyID, base.TenantInfo(authCtx))
	if err != nil {
		return nil, err
	}

	updated, err := r.DetentionPolicyService.Update(ctx, entity, authCtx.UserID)
	if err != nil {
		return nil, err
	}

	return detentionPolicyToModel(updated), nil
}

func (r *MutationResolver) DeleteDetentionPolicy(ctx context.Context, id string) (bool, error) {
	authCtx, err := r.RequirePermission(ctx, permission.ResourceDetentionPolicy, permission.OpDelete)
	if err != nil {
		return false, err
	}

	policyID, err := pulid.MustParse(id)
	if err != nil {
		return false, err
	}

	if err = r.DetentionPolicyService.Delete(ctx, &repositories.GetDetentionPolicyByIDRequest{
		DetentionPolicyID: policyID,
		TenantInfo:        base.TenantInfo(authCtx),
	}, authCtx.UserID); err != nil {
		return false, err
	}

	return true, nil
}

func (r *MutationResolver) DetentionBacktest(ctx context.Context, input gqlmodel.DetentionBacktestInput) (*gqlmodel.DetentionBacktestResult, error) {
	authCtx, err := r.RequirePermission(ctx, permission.ResourceDetentionPolicy, permission.OpRead)
	if err != nil {
		return nil, err
	}

	policy, err := detentionPolicyFromInput(input.Policy, pulid.Nil, base.TenantInfo(authCtx))
	if err != nil {
		return nil, err
	}

	req := detentionservice.BacktestRequest{
		Policy:                 policy,
		From:                   int64(input.From),
		To:                     int64(input.To),
		DriverPayRate:          input.DriverPayRate,
		AssumeNoticeCompliance: input.AssumeNoticeCompliance,
	}
	if input.Limit != nil {
		req.Limit = *input.Limit
	}

	result, err := r.DetentionService.Backtest(ctx, req, base.TenantInfo(authCtx))
	if err != nil {
		return nil, err
	}

	return detentionBacktestResultToModel(result), nil
}

func (r *MutationResolver) WaiveDetentionOccurrence(ctx context.Context, input gqlmodel.DetentionWaiveInput) (*gqlmodel.DetentionOccurrence, error) {
	authCtx, err := r.RequirePermission(ctx, permission.ResourceDetentionPolicy, permission.OpUpdate)
	if err != nil {
		return nil, err
	}

	occurrenceID, err := pulid.MustParse(input.OccurrenceID)
	if err != nil {
		return nil, err
	}

	occurrence, err := r.DetentionService.Waive(ctx, detentionservice.WaiveParams{
		OccurrenceID: occurrenceID,
		TenantInfo:   base.TenantInfo(authCtx),
		Reason:       input.Reason,
		Note:         input.Note,
		UserID:       authCtx.UserID,
	})
	if err != nil {
		return nil, err
	}

	return detentionOccurrenceToModel(occurrence), nil
}

func (r *MutationResolver) ApproveDetentionOccurrence(ctx context.Context, occurrenceID string) (*gqlmodel.DetentionOccurrence, error) {
	authCtx, err := r.RequirePermission(ctx, permission.ResourceDetentionPolicy, permission.OpUpdate)
	if err != nil {
		return nil, err
	}

	id, err := pulid.MustParse(occurrenceID)
	if err != nil {
		return nil, err
	}

	occurrence, err := r.DetentionService.Approve(ctx, detentionservice.ApproveParams{
		OccurrenceID: id,
		TenantInfo:   base.TenantInfo(authCtx),
		UserID:       authCtx.UserID,
	})
	if err != nil {
		return nil, err
	}

	return detentionOccurrenceToModel(occurrence), nil
}

func (r *MutationResolver) DisputeDetentionOccurrence(ctx context.Context, input gqlmodel.DetentionDisputeInput) (*gqlmodel.DetentionOccurrence, error) {
	authCtx, err := r.RequirePermission(ctx, permission.ResourceDetentionPolicy, permission.OpUpdate)
	if err != nil {
		return nil, err
	}

	occurrenceID, err := pulid.MustParse(input.OccurrenceID)
	if err != nil {
		return nil, err
	}

	occurrence, err := r.DetentionService.Dispute(ctx, detentionservice.DisputeParams{
		OccurrenceID: occurrenceID,
		TenantInfo:   base.TenantInfo(authCtx),
		Note:         input.Note,
		UserID:       authCtx.UserID,
	})
	if err != nil {
		return nil, err
	}

	return detentionOccurrenceToModel(occurrence), nil
}

func (r *MutationResolver) SendDetentionNotice(ctx context.Context, occurrenceID string) (*gqlmodel.DetentionOccurrence, error) {
	authCtx, err := r.RequirePermission(ctx, permission.ResourceDetentionPolicy, permission.OpUpdate)
	if err != nil {
		return nil, err
	}

	id, err := pulid.MustParse(occurrenceID)
	if err != nil {
		return nil, err
	}

	occurrence, err := r.DetentionService.SendOccurrenceNotice(
		ctx,
		detentionservice.SendOccurrenceNoticeParams{
			OccurrenceID: id,
			TenantInfo:   base.TenantInfo(authCtx),
			UserID:       authCtx.UserID,
		},
	)
	if err != nil {
		return nil, err
	}

	return detentionOccurrenceToModel(occurrence), nil
}

func (r *QueryResolver) DetentionPolicies(ctx context.Context, input gqlmodel.DataTableConnectionInput) (*gqlmodel.DetentionPolicyConnection, error) {
	authCtx, err := r.RequirePermission(ctx, permission.ResourceDetentionPolicy, permission.OpRead)
	if err != nil {
		return nil, err
	}

	tableInput, err := base.DataTableConnectionFromGraphQL(ctx, &input, base.TenantInfo(authCtx))
	if err != nil {
		return nil, err
	}

	result, err := r.DetentionPolicyService.ListConnection(
		ctx,
		&repositories.ListDetentionPolicyConnectionRequest{
			Filter: tableInput.Filter,
			Cursor: tableInput.Cursor,
		},
	)
	if err != nil {
		return nil, err
	}

	return detentionPolicyConnectionToModel(result)
}

func (r *QueryResolver) DetentionPolicy(ctx context.Context, id string) (*gqlmodel.DetentionPolicy, error) {
	authCtx, err := r.RequirePermission(ctx, permission.ResourceDetentionPolicy, permission.OpRead)
	if err != nil {
		return nil, err
	}

	policyID, err := pulid.MustParse(id)
	if err != nil {
		return nil, err
	}

	entity, err := r.DetentionPolicyService.GetByID(ctx, &repositories.GetDetentionPolicyByIDRequest{
		DetentionPolicyID: policyID,
		TenantInfo:        base.TenantInfo(authCtx),
		IncludeTiers:      true,
	})
	if err != nil {
		return nil, err
	}

	return detentionPolicyToModel(entity), nil
}

func (r *QueryResolver) DetentionDesk(ctx context.Context) ([]*gqlmodel.DetentionDeskEntry, error) {
	authCtx, err := r.RequirePermission(ctx, permission.ResourceDetentionPolicy, permission.OpRead)
	if err != nil {
		return nil, err
	}

	entries, err := r.DetentionService.ListDesk(ctx, base.TenantInfo(authCtx))
	if err != nil {
		return nil, err
	}

	result := make([]*gqlmodel.DetentionDeskEntry, 0, len(entries))
	for _, entry := range entries {
		if entry == nil {
			continue
		}
		result = append(result, detentionDeskEntryToModel(entry))
	}

	return result, nil
}

func (r *QueryResolver) DetentionOccurrence(ctx context.Context, id string) (*gqlmodel.DetentionOccurrenceDetail, error) {
	authCtx, err := r.RequirePermission(ctx, permission.ResourceDetentionPolicy, permission.OpRead)
	if err != nil {
		return nil, err
	}

	occurrenceID, err := pulid.MustParse(id)
	if err != nil {
		return nil, err
	}

	detail, err := r.DetentionService.GetOccurrenceDetail(
		ctx,
		&repositories.GetDetentionOccurrenceByIDRequest{
			OccurrenceID: occurrenceID,
			TenantInfo:   base.TenantInfo(authCtx),
		},
	)
	if err != nil {
		return nil, err
	}

	return detentionOccurrenceDetailToModel(detail), nil
}

func (r *QueryResolver) ShipmentDetention(ctx context.Context, shipmentID string) ([]*gqlmodel.DetentionOccurrence, error) {
	authCtx, err := r.RequirePermission(ctx, permission.ResourceDetentionPolicy, permission.OpRead)
	if err != nil {
		return nil, err
	}

	id, err := pulid.MustParse(shipmentID)
	if err != nil {
		return nil, err
	}

	occurrences, err := r.DetentionService.ListByShipment(
		ctx,
		&repositories.GetOccurrencesByShipmentRequest{
			ShipmentID: id,
			TenantInfo: base.TenantInfo(authCtx),
		},
	)
	if err != nil {
		return nil, err
	}

	return detentionOccurrencesToModel(occurrences), nil
}

func (r *QueryResolver) DetentionDisputePacket(ctx context.Context, occurrenceID string) (*gqlmodel.DetentionDisputePacket, error) {
	authCtx, err := r.RequirePermission(ctx, permission.ResourceDetentionPolicy, permission.OpRead)
	if err != nil {
		return nil, err
	}

	id, err := pulid.MustParse(occurrenceID)
	if err != nil {
		return nil, err
	}

	packet, err := r.DetentionService.BuildDisputePacket(ctx, id, base.TenantInfo(authCtx))
	if err != nil {
		return nil, err
	}

	return detentionDisputePacketToModel(packet), nil
}

func (r *QueryResolver) DetentionFacilityStats(ctx context.Context, input gqlmodel.DetentionStatsInput) ([]*gqlmodel.FacilityDetentionStat, error) {
	authCtx, err := r.RequirePermission(ctx, permission.ResourceDetentionPolicy, permission.OpRead)
	if err != nil {
		return nil, err
	}

	stats, err := r.DetentionService.FacilityProfiles(
		ctx,
		detentionStatsRequest(&input, base.TenantInfo(authCtx)),
	)
	if err != nil {
		return nil, err
	}

	result := make([]*gqlmodel.FacilityDetentionStat, 0, len(stats))
	for _, stat := range stats {
		if stat == nil {
			continue
		}
		result = append(result, facilityDetentionStatToModel(stat))
	}

	return result, nil
}

func (r *QueryResolver) DetentionCustomerStats(ctx context.Context, input gqlmodel.DetentionStatsInput) ([]*gqlmodel.CustomerDetentionStat, error) {
	authCtx, err := r.RequirePermission(ctx, permission.ResourceDetentionPolicy, permission.OpRead)
	if err != nil {
		return nil, err
	}

	stats, err := r.DetentionService.CustomerProfiles(
		ctx,
		detentionStatsRequest(&input, base.TenantInfo(authCtx)),
	)
	if err != nil {
		return nil, err
	}

	result := make([]*gqlmodel.CustomerDetentionStat, 0, len(stats))
	for _, stat := range stats {
		if stat == nil {
			continue
		}
		result = append(result, customerDetentionStatToModel(stat))
	}

	return result, nil
}

func (r *QueryResolver) DetentionWaiverStats(ctx context.Context, input gqlmodel.DetentionStatsInput) ([]*gqlmodel.DetentionWaiverLeakageStat, error) {
	authCtx, err := r.RequirePermission(ctx, permission.ResourceDetentionPolicy, permission.OpRead)
	if err != nil {
		return nil, err
	}

	stats, err := r.DetentionService.WaiverLeakage(
		ctx,
		detentionStatsRequest(&input, base.TenantInfo(authCtx)),
	)
	if err != nil {
		return nil, err
	}

	result := make([]*gqlmodel.DetentionWaiverLeakageStat, 0, len(stats))
	for _, stat := range stats {
		if stat == nil {
			continue
		}
		result = append(result, detentionWaiverStatToModel(stat))
	}

	return result, nil
}

func (r *QueryResolver) DetentionPolicyPreview(ctx context.Context, policy gqlmodel.DetentionPolicyInput, scenario gqlmodel.DetentionPreviewScenarioInput) (*gqlmodel.DetentionPreviewResult, error) {
	authCtx, err := r.RequirePermission(ctx, permission.ResourceDetentionPolicy, permission.OpRead)
	if err != nil {
		return nil, err
	}

	entity, err := detentionPolicyFromInput(&policy, pulid.Nil, base.TenantInfo(authCtx))
	if err != nil {
		return nil, err
	}

	result, err := r.DetentionService.PreviewPolicy(
		ctx,
		entity,
		detentionPreviewScenarioFromInput(&scenario),
		base.TenantInfo(authCtx),
	)
	if err != nil {
		return nil, err
	}

	return detentionPreviewResultToModel(result), nil
}
