// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package workertrainingresolver

import (
	base "github.com/emoss08/trenova/internal/api/graphql/resolver/base"
	driverportalservice "github.com/emoss08/trenova/internal/core/services/driverportalservice"
	workertrainingservice "github.com/emoss08/trenova/internal/core/services/workertrainingservice"
)

type Deps struct {
	*base.Core
	WorkerTrainingService *workertrainingservice.Service
	DriverPortalService   *driverportalservice.Service
}

type MutationResolver struct{ *Deps }

type PortalTrainingResolver struct{ *Deps }

type QueryResolver struct{ *Deps }

type TrainingCourseResolver struct{ *Deps }

type WorkerTrainingRecordResolver struct{ *Deps }
