# Generated by Django 4.1.4 on 2022-12-19 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worker", "0002_worker_entered_by_alter_workerprofile_hire_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workercomment",
            name="worker",
            field=models.ForeignKey(
                help_text="Related worker.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                related_query_name="comment",
                to="worker.worker",
                verbose_name="worker",
            ),
        ),
    ]
