# Generated by Django 4.1.2 on 2022-11-03 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("control_file", "0003_commenttype"),
        ("worker", "0012_worker_manager_alter_worker_depot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workercomment",
            name="comment_type",
            field=models.ForeignKey(
                help_text="Related comment type.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                related_query_name="comments",
                to="control_file.commenttype",
                verbose_name="comment type",
            ),
        ),
        migrations.DeleteModel(
            name="WorkerCommentType",
        ),
    ]
