# Generated by Django 4.1.3 on 2022-11-15 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worker", "0020_alter_worker_address_line_1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worker",
            name="address_line_2",
            field=models.CharField(
                blank=True,
                default=1,
                help_text="The address line 2 of the worker.",
                max_length=255,
                verbose_name="Address line 2",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="worker",
            name="code",
            field=models.CharField(
                blank=True,
                default=1,
                editable=False,
                help_text="The code of the worker. This field is required and must be unique.",
                max_length=10,
                unique=True,
                verbose_name="Code",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="workercontact",
            name="email",
            field=models.EmailField(
                blank=True,
                default=1,
                help_text="Email address of the contact.",
                max_length=255,
                verbose_name="Email Address",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="workercontact",
            name="relationship",
            field=models.CharField(
                blank=True,
                default=1,
                help_text="Relationship to the worker.",
                max_length=255,
                verbose_name="Relationship",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="workerprofile",
            name="endorsements",
            field=models.CharField(
                blank=True,
                choices=[
                    ("n", "None"),
                    ("h", "Hazmat"),
                    ("t", "Tanker"),
                    ("x", "Tanker and Hazmat"),
                ],
                default="n",
                help_text="Endorsements.",
                max_length=1,
                verbose_name="Endorsements",
            ),
        ),
        migrations.AlterField(
            model_name="workerprofile",
            name="license_number",
            field=models.CharField(
                blank=True,
                default=1,
                help_text="License Number.",
                max_length=20,
                verbose_name="License Number",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="workerprofile",
            name="race",
            field=models.CharField(
                blank=True,
                default=1,
                help_text="Race/Ethnicity",
                max_length=100,
                verbose_name="Race/Ethnicity",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="workerprofile",
            name="sex",
            field=models.CharField(
                blank=True,
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("non-binary", "Non-binary"),
                    ("other", "Other"),
                ],
                default=1,
                help_text="Sex/Gender of the worker.",
                max_length=11,
                verbose_name="Sex/Gender",
            ),
            preserve_default=False,
        ),
    ]
