# Generated by Django 4.1.6 on 2023-02-13 06:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoicing", "0003_invoicecontrol_invoice_logo_width_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoicecontrol",
            name="credit_memo_number_prefix",
            field=models.CharField(
                default="CN-",
                help_text="Define a prefix for credit note numbers.",
                max_length=10,
                verbose_name="Credit Note Number Prefix",
            ),
        ),
    ]
