package repositories

import (
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/accessorialchargerepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/additionalchargerepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/ailogrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/auditrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/billingcontrolrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/commodityrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/customerrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/dataretentionrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/dedicatedlanerepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/dispatchcontrolrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/distanceoverriderepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/dlsuggestionrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/documenttyperepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/emailprofilerepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/equipmentmanufacturerrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/equipmenttyperepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/fleetcoderepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/formulatemplaterepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/hazardousmaterialrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/hazmatexpirationrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/hazmatsegregationrulerepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/holdreasonrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/locationcategoryrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/locationrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/m2msync"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/notificationrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/organizationrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/pagefavoriterepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/patternconfigrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/policyrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/rolerepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/servicetyperepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/shipmentcommentrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/shipmentcontrolrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/shipmentmoverepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/shipmentrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/shipmenttyperepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/stoprepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/tableconfigurationrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/tractorrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/trailerrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/userrepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/usstaterepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/variablerepository"
	"github.com/emoss08/trenova/internal/infrastructure/postgres/repositories/workerrepository"
	"go.uber.org/fx"
)

var Module = fx.Module("postgres-repositories",
	fx.Provide(
		m2msync.NewSyncer,
		userrepository.NewRepository,
		organizationrepository.NewRepository,
		usstaterepository.NewRepository,
		auditrepository.NewRepository,
		notificationrepository.NewRepository,
		pagefavoriterepository.NewRepository,
		tableconfigurationrepository.NewRepository,
		holdreasonrepository.NewRepository,
		hazardousmaterialrepository.NewRepository,
		hazmatsegregationrulerepository.NewRepository,
		billingcontrolrepository.NewRepository,
		shipmentcontrolrepository.NewRepository,
		dataretentionrepository.NewRepository,
		locationcategoryrepository.NewRepository,
		locationrepository.NewRepository,
		fleetcoderepository.NewRepository,
		emailprofilerepository.NewRepository,
		documenttyperepository.NewRepository,
		equipmenttyperepository.NewRepository,
		equipmentmanufacturerrepository.NewRepository,
		hazmatexpirationrepository.NewRepository,
		workerrepository.NewRepository,
		shipmenttyperepository.NewRepository,
		servicetyperepository.NewRepository,
		tractorrepository.NewRepository,
		trailerrepository.NewRepository,
		commodityrepository.NewRepository,
		ailogrepository.NewRepository,
		customerrepository.NewRepository,
		variablerepository.NewRepository,
		policyrepository.NewRepository,
		rolerepository.NewRepository,
		accessorialchargerepository.NewRepository,
		stoprepository.NewRepository,
		shipmentmoverepository.NewRepository,
		shipmentcommentrepository.NewRepository,
		formulatemplaterepository.NewRepository,
		additionalchargerepository.NewRepository,
		shipmentrepository.NewRepository,
		dedicatedlanerepository.NewRepository,
		dlsuggestionrepository.NewRepository,
		patternconfigrepository.NewRepository,
		dispatchcontrolrepository.NewRepository,
		distanceoverriderepository.NewRepository,
	),
)
