package repositories

type EDIDocumentRepository interface {
	EDIDocumentTypeRepository
	EDITransactionSetRepository
	EDISourceContextRepository
	EDIPartnerSettingRepository
	EDITemplateRepository
	EDIPartnerDocumentProfileRepository
	EDIControlNumberRepository
	EDIMessageRepository
	EDITestCaseRepository
}
