package domainregistry

import (
	"github.com/emoss08/trenova/internal/core/domain/accessorialcharge"
	"github.com/emoss08/trenova/internal/core/domain/ailog"
	"github.com/emoss08/trenova/internal/core/domain/audit"
	"github.com/emoss08/trenova/internal/core/domain/bankreceipt"
	"github.com/emoss08/trenova/internal/core/domain/customer"
	"github.com/emoss08/trenova/internal/core/domain/dispatchcontrol"
	"github.com/emoss08/trenova/internal/core/domain/distancecontrol"
	"github.com/emoss08/trenova/internal/core/domain/distanceoverride"
	"github.com/emoss08/trenova/internal/core/domain/edi"
	"github.com/emoss08/trenova/internal/core/domain/equipmentcontinuity"
	"github.com/emoss08/trenova/internal/core/domain/fleetcode"
	"github.com/emoss08/trenova/internal/core/domain/formulatemplate"
	"github.com/emoss08/trenova/internal/core/domain/invoice"
	"github.com/emoss08/trenova/internal/core/domain/permission"
	"github.com/emoss08/trenova/internal/core/domain/servicefailure"
	"github.com/emoss08/trenova/internal/core/domain/servicetype"
	"github.com/emoss08/trenova/internal/core/domain/shipment"
	"github.com/emoss08/trenova/internal/core/domain/shipmentimportchat"
	"github.com/emoss08/trenova/internal/core/domain/storedmileage"
	"github.com/emoss08/trenova/internal/core/domain/tenant"
	"github.com/emoss08/trenova/internal/core/domain/trailer"
	"github.com/emoss08/trenova/internal/core/domain/usstate"
)

func RegisterEntities() []any {
	return []any{
		&usstate.UsState{},
		&tenant.BusinessUnit{},
		&formulatemplate.FormulaTemplate{},
		&tenant.DocumentControl{},
		&ailog.Log{},
		&dispatchcontrol.DispatchControl{},
		&tenant.BillingControl{},
		&invoice.Invoice{},
		&invoice.InoviceLine{},
		&invoice.Attachment{},
		&invoice.EmailAttempt{},
		&invoice.EmailAttemptAttachment{},
		&invoice.DocumentShareToken{},
		&permission.Role{},
		&permission.ResourcePermission{},
		&permission.UserRoleAssignment{},
		&permission.RoleHierarchyEdge{},
		&permission.RoleConstraint{},
		&permission.RoleConstraintRole{},
		&tenant.ShipmentControl{},
		&fleetcode.FleetCode{},
		&trailer.Trailer{},
		&equipmentcontinuity.EquipmentContinuity{},
		&accessorialcharge.AccessorialCharge{},
		&servicetype.ServiceType{},
		&distancecontrol.DistanceControl{},
		&distanceoverride.DistanceOverride{},
		&storedmileage.StoredMileage{},
		&edi.EDIPartner{},
		&edi.EDIConnection{},
		&edi.EDICommunicationProfile{},
		&edi.EDIMappingProfile{},
		&edi.EDIMappingProfileItem{},
		&edi.EDITransfer{},
		&edi.EDIDocumentType{},
		&edi.EDIPartnerSettingSchema{},
		&edi.EDIPartnerSettingField{},
		&edi.EDITemplate{},
		&edi.EDITemplateVersion{},
		&edi.EDITemplateSegment{},
		&edi.EDIPartnerDocumentProfile{},
		&edi.EDIControlNumberSequence{},
		&edi.EDIMessage{},
		&edi.EDIInboundFile{},
		&edi.EDIMessageValidationError{},
		&edi.EDITestCase{},
		&audit.Entry{},
		&shipment.Assignment{},
		&shipment.Stop{},
		&shipment.ShipmentMove{},
		&shipment.AdditionalCharge{},
		&shipment.ShipmentCommodity{},
		&shipment.ShipmentComment{},
		&shipment.ShipmentCommentMention{},
		&shipment.ShipmentHold{},
		&servicefailure.ReasonCode{},
		&servicefailure.ServiceFailure{},
		&shipment.Shipment{},
		&shipmentimportchat.Conversation{},
		&shipmentimportchat.Turn{},
		&customer.CustomerBillingProfileDocumentType{},
		&bankreceipt.BankReceipt{},
	}
}

func RegisterManyToManyEntities() []any {
	return []any{
		&customer.CustomerBillingProfileDocumentType{},
		&permission.RoleConstraintRole{},
	}
}
