# # Copyright 2023-2025 Eric Moss
# # Licensed under FSL-1.1-ALv2 (Functional Source License 1.1, Apache 2.0 Future)
# # Full license: https://github.com/emoss08/trenova/blob/main/LICENSE.md

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 10s
          static_configs:
            - targets: ['0.0.0.0:8888']
        
        - job_name: 'postgres-exporter'
          scrape_interval: 15s
          static_configs:
            - targets: ['postgres-exporter:9187']
        
        - job_name: 'trenova-app'
          scrape_interval: 10s
          static_configs:
            - targets: ['host.docker.internal:2222']  # Dedicated metrics server
          metrics_path: '/metrics'

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024

  resource:
    attributes:
      - key: environment
        value: development
        action: upsert

  attributes/loki:
    actions:
      - key: loki.resource.labels
        value: service.name, service.namespace, service.instance.id
        action: insert

exporters:
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true

  prometheusremotewrite:
    endpoint: http://mimir:9009/api/v1/push
    tls:
      insecure: true
    headers:
      X-Scope-OrgID: "trenova"

  loki:
    endpoint: http://loki:3100/loki/api/v1/push

  debug:
    verbosity: detailed
    sampling_initial: 5
    sampling_thereafter: 200

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [otlp/tempo, debug]
    
    metrics:
      receivers: [otlp, prometheus]
      processors: [batch, resource]
      exporters: [prometheusremotewrite, debug]
    
    logs:
      receivers: [otlp]
      processors: [batch, resource, attributes/loki]
      exporters: [loki, debug]

  extensions: [health_check, pprof, zpages]
  
extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679