# Generated by Django 4.1.5 on 2023-01-12 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("location", "0003_alter_locationcontact_location"),
        ("stops", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stop",
            name="location",
            field=models.ForeignKey(
                blank=True,
                help_text="The location of the stop.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stops",
                related_query_name="stop",
                to="location.location",
                verbose_name="Location",
            ),
        ),
    ]
