// Code generated by buncolgen. DO NOT EDIT.

package ratezone

import "github.com/emoss08/trenova/pkg/buncolgen"

// GetStaticFieldMap returns the pre-computed JSON→database column mapping for [RateZone].
// This implements [querybuilder.StaticFieldMapper], allowing the QueryBuilder to use
// the generated [buncolgen.RateZoneFieldMap] instead of parsing struct tags via reflection.
func (e *RateZone) GetStaticFieldMap() map[string]string {
	return buncolgen.RateZoneFieldMap
}

// GetStaticFieldMap returns the pre-computed JSON→database column mapping for [RateZoneMember].
// This implements [querybuilder.StaticFieldMapper], allowing the QueryBuilder to use
// the generated [buncolgen.RateZoneMemberFieldMap] instead of parsing struct tags via reflection.
func (e *RateZoneMember) GetStaticFieldMap() map[string]string {
	return buncolgen.RateZoneMemberFieldMap
}
