package roleresolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"

	"github.com/emoss08/trenova/internal/api/graphql/gqlmodel"
	"github.com/emoss08/trenova/internal/api/graphql/resolver/base"
	"github.com/emoss08/trenova/internal/core/domain/agentdefinition"
	"github.com/emoss08/trenova/internal/core/domain/permission"
	"github.com/emoss08/trenova/internal/core/ports/repositories"
	"github.com/emoss08/trenova/shared/pulid"
)

func (r *QueryResolver) Roles(ctx context.Context, input gqlmodel.DataTableConnectionInput) (*gqlmodel.RoleConnection, error) {
	authCtx, err := r.RequirePermission(ctx, permission.ResourceRole, permission.OpRead)
	if err != nil {
		return nil, err
	}

	tableInput, err := base.DataTableConnectionFromGraphQL(ctx, &input, base.TenantInfo(authCtx))
	if err != nil {
		return nil, err
	}

	result, err := r.RoleService.ListConnection(
		ctx,
		&repositories.ListRoleConnectionRequest{
			Filter: tableInput.Filter,
			Cursor: tableInput.Cursor,
		},
	)
	if err != nil {
		return nil, err
	}

	return roleConnectionToModel(result)
}

func (r *QueryResolver) Role(ctx context.Context, id string) (*permission.Role, error) {
	authCtx, err := r.RequirePermission(ctx, permission.ResourceRole, permission.OpRead)
	if err != nil {
		return nil, err
	}

	roleID, err := pulid.MustParse(id)
	if err != nil {
		return nil, err
	}

	return r.RoleService.GetRoleByID(ctx, repositories.GetRoleByIDRequest{
		ID:         roleID,
		TenantInfo: base.TenantInfo(authCtx),
	})
}

func (r *RoleResolver) CoreResponsibility(ctx context.Context, obj *permission.Role) (*string, error) {
	if obj.CoreResponsibility == "" {
		return nil, nil
	}

	value := string(obj.CoreResponsibility)
	return &value, nil
}

func (r *RoleResolver) MaxSensitivity(ctx context.Context, obj *permission.Role) (string, error) {
	return obj.MaxSensitivity.String(), nil
}

func (r *RoleResolver) Agents(ctx context.Context, obj *permission.Role) ([]*agentdefinition.Definition, error) {
	return r.RoleAgents(ctx, obj)
}
