package agentdefinition

const (
	toolListCarriers        = "list_carriers"
	toolListLocations       = "list_locations"
	toolGetCarrier          = "get_carrier"
	toolListServiceFailures = "list_service_failures"
)

func (t Template) StarterTools() []string {
	switch t {
	case TemplateDispatchAssistant:
		return []string{
			"get_shipment",
			"search_shipments",
			"list_shipments",
			"get_worker",
			"search_worker",
			"list_workers",
			"list_tractors",
			"list_trailers",
			"list_expiring_credentials",
			"list_time_off",
			"list_hold_reasons",
			"rank_move_candidates",
			"shop_carriers",
			"assign_move",
			"add_shipment_comment",
			"place_shipment_hold",
			"release_shipment_hold",
			"update_tractor_status",
			"update_trailer_status",
			"list_insights",
			"get_insight",
			"unassign_moves",
			"update_move_status",
			"assign_move_to_carrier",
			"cancel_carrier_assignment",
			"list_shipment_tenders",
			"cancel_tender",
			"record_tender_response",
			"list_rate_confirmations",
			"generate_rate_confirmation",
			"send_rate_confirmation",
			"void_rate_confirmation",
			"record_rate_confirmation_confirmed",
			"list_edi_partners",  //nolint:goconst // a template names each tool by its wire name
			"list_edi_transfers", //nolint:goconst // a template names each tool by its wire name
			"get_edi_transfer",   //nolint:goconst // a template names each tool by its wire name
			"send_edi_tender",
			"cancel_edi_tender",
			"expire_edi_tender",
			"list_edi_transfer_changes",
			"review_edi_transfer_change",
			"list_edi_messages",
			"send_edi_status_update",
			"retry_edi_message_delivery",
			"replay_edi_message",
			"uncancel_shipment",
			"duplicate_shipment",
			"update_shipment_hold",
			"split_move_at_relay",
			"recalculate_shipment_distance",
			"transfer_shipment_ownership",
			"pin_shipment_comment",
			"resolve_shipment_comment",
			"list_recurring_shipments",
			"generate_recurring_shipment",
			"update_shipment",
		}
	case TemplateBillingAssistant:
		return []string{
			"get_shipment",
			"search_shipments",
			"list_shipments",
			"list_customers",
			"list_billing_transfer_candidates",
			"transfer_to_billing",
			"list_billing_queue_items",
			"get_billing_queue_item",
			"assign_billing_queue_biller",
			"transition_item_to_in_review",
			"hold_billing_queue_item",
			"move_billing_item_to_exception",
			"send_billing_item_back_to_ops",
			"approve_billing_queue_item",
			"approve_billing_queue_items",
			"cancel_billing_queue_item",
			"list_invoices", //nolint:goconst // a template names each tool by its wire name
			"get_invoice",
			"get_invoices",
			"post_invoice",
			"send_invoice",
			"post_invoices",
			"send_invoices",
			"list_reports",
			"describe_report",
			"preview_report",
			"run_report",
			"list_email_profiles",
			"request_missing_docs",
			"list_accessorial_charges",
			"add_shipment_comment",
			"create_invoice",
			"update_invoice_draft",
			"generate_invoice_pdf",
			"void_invoice",
			"create_invoice_memo",
			"send_invoice_edi",
			toolSearchDocuments,
			"list_invoice_adjustments",
			"get_invoice_adjustment",
			"save_invoice_adjustment_draft",
			"submit_invoice_adjustment",
			"approve_invoice_adjustment",
			"reject_invoice_adjustment",
			"list_open_statements",
			"list_invoice_runs",
			"get_invoice_run",
			"build_invoice_run",
			"adjust_invoice_run_membership",
			"commit_invoice_run",
			"cancel_invoice_run",
			"bill_statement_now",
			"list_invoice_share_candidates",
			"share_invoice",
			"reassign_billing_charge",
			"manage_billing_transfer_run",
		}
	case TemplateComplianceAssistant:
		return []string{
			"get_worker",
			"search_worker",
			"list_workers",
			"list_expiring_credentials",
			"list_time_off",
			"list_tractors",
			"list_trailers",
			"list_reports",
			"describe_report",
			"preview_report",
			"run_report",
			"get_report_run",
			"list_insights",
			"get_insight",
			"get_worker_schedule",
			"list_shift_templates",
			"assign_worker_shift",
			"end_worker_shift_assignment",
			"set_worker_availability_preference",
			"propose_shift_swap",
			"approve_shift_swap",
			"reject_shift_swap",
			"withdraw_shift_swap",
			toolListCarriers,
			toolGetCarrier,
			"vet_carrier",
			"set_carrier_monitoring",
			"mark_carrier_intel_reviewed",
			"apply_carrier_intel_suggestions",
			"import_sourced_carrier",
			"verify_carrier_equipment",
			"list_worker_credentials",
			"record_worker_credential",
			"update_worker_credential",
			"attach_worker_credential_document",
			"list_worker_training",
			"list_training_courses",
			"assign_worker_training",
			"assign_required_worker_training",
			"record_training_completion",
			"list_employment_verifications",
			"record_employment_verification",
			"update_employment_verification",
			"log_employment_verification_request",
			"list_worker_checklists",
			"update_worker_checklist_item",
			"list_worker_safety_events",
			"open_worker_safety_event",
			"record_safety_violation",
			"change_worker_safety_event_status",
			"list_dot_tests",
			"get_dot_random_draw",
			"schedule_dot_test",
			"update_dot_random_selection",
			"list_worker_leave_cases",
		}
	case TemplateCustomerAssistant:
		return []string{
			"get_shipment",
			"search_shipments",
			"list_shipments",
			"list_customers",
			"list_invoices",
			"add_shipment_comment",
			"list_insights",
			"get_insight",
			"list_edi_partners",
			"list_edi_transfers",
			"get_edi_transfer",
			"accept_edi_tender",
			"decline_edi_tender",
			"list_edi_tender_changes",
			"review_edi_tender_change",
			"send_edi_status_update",
			"list_orders",
			"get_order",
			"create_order",
			"update_order",
			"attach_order_shipments",
			"detach_order_shipment",
			"add_order_charge",
			"update_order_charge",
			"set_order_charge_allocations",
			"remove_order_charge",
			"close_order",
			"cancel_order",
			"list_recurring_shipments",
			"create_recurring_shipment",
			"update_recurring_shipment",
			"set_recurring_shipment_status",
			"generate_recurring_shipment",
			"rerate_shipment",
			"edit_shipment_comment",
			"unpin_shipment_comment",
			"delete_shipment_comment",
			toolListServiceFailures,
			"get_service_failure",
			"update_service_failure",
			"review_service_failure",
			"void_service_failure",
			"dispute_detention",
			"vet_customer_broker",
			"create_customer",
			"update_customer",
			"update_customer_status",
			toolListLocations,
			"update_location",
			"update_location_status",
			"list_commodities",
			"create_commodity",
			"update_commodity",
		}
	case TemplateLoadMonitor:
		return []string{
			"get_dispatch_board",
			"get_shipment_tracking",
			"get_shipment",
			"list_vehicle_positions",
			"get_worker_hos",
			"list_service_failures",
			"list_service_failure_reason_codes",
			"list_detention_desk",
			"list_weather_alerts",
			"evaluate_service_failures",
			"resolve_service_failure",
			"add_shipment_comment",
			"notify_driver",
			"list_email_profiles",
			"email_customer",
			"send_detention_notice",
			"record_stop_actual",
		}
	case TemplateGeneralAssistant:
		return nil
	case TemplateDetentionDesk:
		return []string{
			"get_detention_occurrence",
			"list_detention_desk",
			"get_shipment",
			"get_shipment_tracking",
			"get_customer",
			"list_email_profiles",
			"send_detention_notice",
			"escalate_detention",
			"approve_detention",
			"waive_detention",
			"add_shipment_comment",
			"dispute_detention",
		}
	case TemplateCredentialDesk:
		return []string{
			"get_worker",
			"get_worker_credential",
			"list_expiring_credentials",
			"list_workers",
			"request_credential_renewal",
			"place_worker_dispatch_hold",
			"notify_driver",
		}
	case TemplateCustomerUpdateDesk:
		return []string{
			"get_shipment",
			"get_shipment_tracking",
			"get_customer",
			"get_customer_update_preferences",
			"list_email_profiles",
			"email_customer",
			"add_shipment_comment",
		}
	case TemplateCarrierRiskDesk:
		return []string{
			"get_carrier_intel_event",
			"get_carrier",
			"list_carriers",
			"acknowledge_carrier_intel_event",
			"resolve_carrier_intel_event",
			"vet_carrier",
			"set_carrier_monitoring",
			"mark_carrier_intel_reviewed",
		}
	case TemplateIntakeDesk:
		return []string{
			"get_inbound_message",
			"list_inbound_messages",
			"search_inbound_messages",
			"get_shipment",
			"search_shipments",
			"get_shipment_tracking",
			"get_customer",
			"get_carrier",
			"get_document_summary",
			toolSearchDocuments,
			"get_shipment_draft",
			"list_customers",
			"list_carriers",
			"list_email_profiles",
			"link_inbound_message",
			"mark_inbound_message",
			"reply_to_inbound_message",
			"attach_document_to_shipment",
			"add_shipment_comment",
			"get_edi_inbound_file",
			"list_edi_transfers",
			"get_edi_transfer",
			"quote_shipment", //nolint:goconst // a template names each tool by its wire name
			"accept_edi_tender",
			"decline_edi_tender",
		}
	case TemplateCashApplication:
		return []string{
			"get_bank_receipt",
			"list_bank_receipt_exceptions",
			"list_customer_payments",
			"list_customers",
			"get_customer",
			"list_invoices",
			"get_invoice",
			"match_bank_receipt",
			"post_customer_payment",
			"resolve_bank_receipt_work_item",
			"triage_bank_receipt_work_item",
		}
	case TemplateBillingException:
		return []string{
			"get_shipment",
			"search_shipments",
			"list_billing_transfer_candidates",
			"list_billing_queue_items",
			"get_billing_queue_item",
			"transition_item_to_in_review",
			"hold_billing_queue_item",
			"move_billing_item_to_exception",
			"send_billing_item_back_to_ops",
			"correct_charge_code",
			"request_missing_docs",
			"attach_document_to_shipment",
			"get_accounting_sync_status",
			"check_accounting_connection",
		}
	case TemplateDispatchAssignment:
		return []string{
			"get_shipment",
			"search_shipments",
			"get_worker",
			"search_worker",
			"get_dispatch_board",
			"rank_move_candidates",
			"plan_dispatch",
			"list_carriers",
			"shop_carriers",
			"assign_move",
			"tender_move_to_routing_guide",
			"tender_move_to_carriers",
			"assign_move_to_carrier",
			"list_shipment_tenders",
			"list_rate_confirmations",
			"generate_rate_confirmation",
			"send_rate_confirmation",
		}
	case TemplateImportAssistant:
		return []string{
			"get_shipment_draft",
			"list_customers",
			"get_customer",
			"list_service_types",
			"list_shipment_types",
			"list_formula_templates",
			toolListLocations,
			"list_location_categories",
			"search_shipments",
			"accept_field",
			"accept_all_confident",
			"set_field_value",
			"set_required_field",
			"set_stop_location",
			"set_stop_schedule",
			"create_location",
		}
	case TemplateShipmentIntake:
		return []string{
			"get_shipment_draft",
			"list_customers",
			toolListLocations,
			"list_service_types",
			"list_shipment_types",
			"list_equipment_types",
			"list_formula_templates",
			"list_commodities",
			"list_accessorial_charges",
			"search_shipments",
			"quote_shipment",
			"create_shipment",
		}
	case TemplateLoadEntryCheck:
		return []string{
			"get_shipment",
			"search_shipments",
			"get_customer",
			"explain_rate",
			"quote_shipment",
			"list_hold_reasons",
			"add_shipment_comment",
			"place_shipment_hold",
		}
	case TemplateServiceFailureDesk:
		return []string{
			"list_service_failures",
			"get_service_failure",
			"list_service_failure_reason_codes",
			"get_shipment",
			"get_shipment_tracking",
			"get_customer_update_preferences",
			"list_email_profiles",
			"resolve_service_failure",
			"email_customer",
			"add_shipment_comment",
			"update_service_failure",
			"void_service_failure",
		}
	case TemplateInsightAnalyst:
		return []string{
			"get_insight",
			"list_insights",
			"list_reports",
			"describe_report",
			"preview_report",
			"run_report",
			"get_report_run",
			"list_shipments",
			"list_invoices",
			"dismiss_insight",
			"restore_insight",
		}
	case TemplateEDIDesk:
		return []string{
			"list_edi_inbound_files",
			"get_edi_inbound_file",
			"list_edi_transfers",
			"get_edi_partner",
			"list_edi_partners",
			"reprocess_edi_inbound_files",
		}
	case TemplateBooksKeeper:
		return []string{
			"get_accounting_sync_status",
			"list_accounting_sync_records",
			"get_accounting_sync_record",
			"get_record_accounting_sync_state",
			"retry_accounting_sync",
			"skip_accounting_sync",
			"list_accounting_mapping_gaps",
			"get_accounting_mapping",
			"set_accounting_mapping",
			"list_accounting_inbound_changes",
			"apply_accounting_inbound_change",
			"ignore_accounting_inbound_change",
			"list_accounting_drift_findings",
			"resolve_accounting_drift",
			"dismiss_accounting_drift",
			"check_accounting_drift",
			"confirm_accounting_mapping_proposals",
			"reject_accounting_mapping_proposal",
			"release_accounting_sync",
			"list_fiscal_periods",
			"get_fiscal_close_blockers",
			"lock_fiscal_period",
			"close_fiscal_period",
		}
	case TemplateFormulaAssistant:
		return []string{
			"describe_formula_schema",
			"test_formula_expression",
			"propose_formula",
			"list_formula_templates",
			"list_rate_agreements",
			"get_rate_agreement",
			"get_rate_matrix",
			"get_fuel_surcharge_rates",
			"list_accessorial_charges",
			"explain_rate",
			"list_customers",
			toolListCarriers,
			toolListLocations,
			"list_rate_imports",
			"list_fuel_index_prices",
			"draft_rate_agreement",
			"revise_rate_agreement_draft",
			"duplicate_rate_agreement",
			"submit_rate_agreement",
			"amend_rate_agreement_rules",
			"apply_rate_increase",
			"suspend_rate_agreement",
			"resume_rate_agreement",
			"archive_rate_agreement",
			"commit_rate_import",
			"discard_rate_import",
			"run_rate_simulation",
			"record_fuel_index_price",
			"correct_fuel_index_price",
		}
	case TemplateSettlementsClerk:
		return settlementsClerkTools()
	case TemplateReceivables:
		return receivablesTools()
	case TemplateMasterDataSteward:
		return masterDataStewardTools()
	case TemplateWorkforceCoordinator:
		return workforceCoordinatorTools()
	case TemplateFuelTaxClerk:
		return fuelTaxClerkTools()
	case TemplateReportAnalyst:
		return reportAnalystTools()
	default:
		return nil
	}
}

func settlementsClerkTools() []string {
	return []string{
		"search_worker",
		"list_carriers",
		"search_shipments",
		"get_shipment",
		"list_driver_settlements",
		"get_driver_settlement",
		"list_driver_pay_events",
		"get_worker_earnings_summary",
		"get_settlement_dispute",
		"start_settlement_dispute_review",
		"resolve_settlement_dispute",
		"generate_driver_settlement",
		"generate_driver_settlement_batch",
		"attach_pay_events_to_settlement",
		"detach_pay_event_from_settlement",
		"hold_driver_pay_event",
		"release_driver_pay_event",
		"add_driver_settlement_adjustment",
		"remove_driver_settlement_adjustment",
		"recalculate_driver_settlement",
		"submit_driver_settlement",
		"approve_driver_settlement",
		"reject_driver_settlement",
		"post_driver_settlement",
		"record_driver_settlement_payment",
		"void_driver_settlement",
		"pay_driver_now",
		"list_carrier_settlements",
		"get_carrier_settlement",
		"generate_carrier_settlement_batch",
		"add_carrier_settlement_adjustment",
		"remove_carrier_settlement_adjustment",
		"recalculate_carrier_settlement",
		"submit_carrier_settlement",
		"approve_carrier_settlement",
		"reject_carrier_settlement",
		"post_carrier_settlement",
		"record_carrier_settlement_payment",
		"void_carrier_settlement",
		"list_carrier_invoice_matches",
		"list_edi_carrier_invoices",
		"create_carrier_invoice_match",
		"accept_carrier_invoice_match",
		"accept_carrier_invoice_match_with_variance",
		"reject_carrier_invoice_match",
		"link_edi_carrier_invoice_to_carrier",
		"list_pay_advances",
		"issue_pay_advance",
		"write_off_pay_advance",
		"list_escrow_accounts",
		"adjust_escrow_account",
		"list_pay_codes",
		"list_pay_profiles",
		"list_pay_assignments",
		"list_recurring_deductions",
		"list_recurring_earnings",
	}
}

func receivablesTools() []string {
	return []string{
		"list_customers",
		"get_customer",
		"list_invoices",
		"get_invoice",
		"get_shipment",
		toolSearchDocuments,
		"get_document_summary",
		"get_ar_aging",
		"list_ar_open_items",
		"list_collections_worklist",
		"get_customer_statement",
		"list_customer_payments",
		"apply_customer_payment",
		"reverse_customer_payment",
		"list_credit_memo_applications",
		"apply_credit_memo",
		"unapply_credit_memo",
		"list_invoice_disputes",
		"open_invoice_dispute",
		"resolve_invoice_dispute",
		"withdraw_invoice_dispute",
		"list_invoice_adjustments",
		"get_invoice_adjustment",
		"assess_late_charges",
		"send_invoice",
		"list_invoice_share_candidates",
		"share_invoice",
	}
}
