# Generated by Django 4.1.5 on 2023-01-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fuel", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fuelvendor",
            name="email_address",
            field=models.EmailField(
                blank=True,
                default=1,
                help_text="Email address for the vendor",
                max_length=254,
                verbose_name="Email Address",
            ),
            preserve_default=False,
        ),
    ]
