package aiusageresolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"

	"github.com/emoss08/trenova/shared/timeutils"

	"github.com/emoss08/trenova/internal/api/graphql/gqlmodel"
	"github.com/emoss08/trenova/internal/api/graphql/resolver/base"
	"github.com/emoss08/trenova/internal/core/domain/permission"
	"github.com/emoss08/trenova/internal/core/ports/services"
)

func (r *QueryResolver) AiUsageSummary(ctx context.Context, since *int) (*services.AIUsageSummary, error) {
	// Spend and latency are the provider's business, so reading providers is
	// the permission that reads their usage.
	authCtx, err := r.RequirePermission(ctx, permission.ResourceAIProvider, permission.OpRead)
	if err != nil {
		return nil, err
	}

	return r.AiUsageService.Summary(ctx, base.TenantInfo(authCtx), int64(base.DerefInt(since)))
}

func (r *QueryResolver) AiUsageDaily(ctx context.Context, days *int, timezone *string, providerID *string) ([]*services.AIUsageDay, error) {
	authCtx, err := r.RequirePermission(ctx, permission.ResourceAIProvider, permission.OpRead)
	if err != nil {
		return nil, err
	}

	req := &services.AIUsageDailyRequest{
		TenantInfo: base.TenantInfo(authCtx),
		Days:       base.DerefInt(days),
	}
	if timezone != nil {
		req.Timezone = *timezone
	}
	if req.ProviderID, err = base.OptionalID(providerID); err != nil {
		return nil, err
	}

	usage, err := r.AiUsageService.Daily(ctx, req)
	if err != nil {
		return nil, err
	}

	out := make([]*services.AIUsageDay, len(usage))
	for idx := range usage {
		out[idx] = &usage[idx]
	}
	return out, nil
}

func (r *QueryResolver) AiUsageFeatures(ctx context.Context, input gqlmodel.DataTableConnectionInput, days *int) (*gqlmodel.AIUsageFeatureConnection, error) {
	authCtx, err := r.RequirePermission(ctx, permission.ResourceAIProvider, permission.OpRead)
	if err != nil {
		return nil, err
	}

	window := base.DerefInt(days)
	if window <= 0 {
		window = 7
	}
	since := timeutils.NowUnix() - int64(window)*24*60*60

	summary, err := r.AiUsageService.Summary(ctx, base.TenantInfo(authCtx), since)
	if err != nil {
		return nil, err
	}

	return featureConnection(&input, summary.ByFeature)
}
