# Generated by Django 4.1.2 on 2022-11-12 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0007_order"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Order",
        ),
    ]
