# Generated by Django 4.1.3 on 2022-11-21 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0034_alter_order_freight_charge_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordercontrol",
            name="auto_pop_address",
            field=models.BooleanField(
                default=True,
                help_text="Auto populate address from location ID when entering an order.",
                verbose_name="Auto Populate Address",
            ),
        ),
    ]
