// Code generated by buncolgen. DO NOT EDIT.

package pagefavorite

import "github.com/emoss08/trenova/pkg/buncolgen"

// GetStaticFieldMap returns the pre-computed JSON→database column mapping for [PageFavorite].
// This implements [querybuilder.StaticFieldMapper], allowing the QueryBuilder to use
// the generated [buncolgen.PageFavoriteFieldMap] instead of parsing struct tags via reflection.
func (e *PageFavorite) GetStaticFieldMap() map[string]string {
	return buncolgen.PageFavoriteFieldMap
}
