import { AccessorialChargeService } from "./accessorial-charge";
import { AssignmentService } from "./assignment";
import { AccountTypeService } from "./account-type";
import { AccountingControlService } from "./accounting-control";
import { AnalyticsService } from "./analytics";
import { APIKeyService } from "./api-key";
import { AuditService } from "./audit";
import { BillingControlService } from "./billing-control";
import { CommodityService } from "./commodity";
import { CustomFieldService } from "./custom-field";
import { CustomerService } from "./customer";
import { DataEntryControlService } from "./data-entry-control";
import { DatabaseSessionService } from "./database-session";
import { DispatchControlService } from "./dispatch-control";
import { DistanceOverrideService } from "./distance-override";
import { DocumentService } from "./document";
import { EquipmentManufacturerService } from "./equipment-manufacturer";
import { EquipmentTypeService } from "./equipment-type";
import { FiscalPeriodService } from "./fiscal-period";
import { FiscalYearService } from "./fiscal-year";
import { FleetCodeService } from "./fleet-code";
import { FormulaTemplateService } from "./formula-template";
import { GoogleMapsService } from "./google-maps";
import { GlobalSearchService } from "./global-search";
import { HazardousMaterialService } from "./hazardous-material";
import { HazmatSegregationRuleService } from "./hazmat-segregation-rule";
import { HoldReasonService } from "./hold-reason";
import { IntegrationService } from "./integration";
import { LocationService } from "./location";
import { OrganizationService } from "./organization";
import { PageFavoriteService } from "./page-favorite";
import { RealtimeService } from "./realtime";
import { SequenceConfigService } from "./sequence-config";
import { ServiceTypeService } from "./service-type";
import { ShipmentService } from "./shipment";
import { ShipmentCommentService } from "./shipment-comment";
import { ShipmentControlService } from "./shipment-control";
import { ShipmentTypeService } from "./shipment-type";
import { NotificationService } from "./notification";
import { TableChangeAlertService } from "./table-change-alert";
import { TableConfigurationService } from "./table-configuration";
import { TractorService } from "./tractor";
import { TrailerService } from "./trailer";
import { UserService } from "./user";
import { WorkerService } from "./worker";

class APIService {
  public organizationService: OrganizationService;
  public userService: UserService;
  public pageFavoriteService: PageFavoriteService;
  public tableConfigurationService: TableConfigurationService;
  public formulaTemplateService: FormulaTemplateService;
  public equipmentTypeService: EquipmentTypeService;
  public equipmentManufacturerService: EquipmentManufacturerService;
  public fleetCodeService: FleetCodeService;
  public trailerService: TrailerService;
  public tractorService: TractorService;
  public customFieldService: CustomFieldService;
  public documentService: DocumentService;
  public accessorialChargeService: AccessorialChargeService;
  public workerService: WorkerService;
  public serviceTypeService: ServiceTypeService;
  public sequenceConfigService: SequenceConfigService;
  public shipmentTypeService: ShipmentTypeService;
  public hazardousMaterialService: HazardousMaterialService;
  public hazmatSegregationRuleService: HazmatSegregationRuleService;
  public commodityService: CommodityService;
  public customerService: CustomerService;
  public databaseSessionService: DatabaseSessionService;
  public googleMapsService: GoogleMapsService;
  public globalSearchService: GlobalSearchService;
  public accountingControlService: AccountingControlService;
  public accountTypeService: AccountTypeService;
  public fiscalYearService: FiscalYearService;
  public fiscalPeriodService: FiscalPeriodService;
  public locationService: LocationService;
  public holdReasonService: HoldReasonService;
  public shipmentCommentService: ShipmentCommentService;
  public shipmentControlService: ShipmentControlService;
  public shipmentService: ShipmentService;
  public billingControlService: BillingControlService;
  public dataEntryControlService: DataEntryControlService;
  public dispatchControlService: DispatchControlService;
  public distanceOverrideService: DistanceOverrideService;
  public realtimeService: RealtimeService;
  public integrationService: IntegrationService;
  public analyticService: AnalyticsService;
  public auditService: AuditService;
  public apiKeyService: APIKeyService;
  public assignmentService: AssignmentService;
  public notificationService: NotificationService;
  public tableChangeAlertService: TableChangeAlertService;

  constructor() {
    this.fleetCodeService = new FleetCodeService();
    this.organizationService = new OrganizationService();
    this.pageFavoriteService = new PageFavoriteService();
    this.tableConfigurationService = new TableConfigurationService();
    this.userService = new UserService();
    this.formulaTemplateService = new FormulaTemplateService();
    this.equipmentTypeService = new EquipmentTypeService();
    this.equipmentManufacturerService = new EquipmentManufacturerService();
    this.trailerService = new TrailerService();
    this.tractorService = new TractorService();
    this.customFieldService = new CustomFieldService();
    this.documentService = new DocumentService();
    this.accessorialChargeService = new AccessorialChargeService();
    this.workerService = new WorkerService();
    this.serviceTypeService = new ServiceTypeService();
    this.sequenceConfigService = new SequenceConfigService();
    this.shipmentTypeService = new ShipmentTypeService();
    this.hazardousMaterialService = new HazardousMaterialService();
    this.hazmatSegregationRuleService = new HazmatSegregationRuleService();
    this.commodityService = new CommodityService();
    this.customerService = new CustomerService();
    this.databaseSessionService = new DatabaseSessionService();
    this.googleMapsService = new GoogleMapsService();
    this.globalSearchService = new GlobalSearchService();
    this.accountingControlService = new AccountingControlService();
    this.accountTypeService = new AccountTypeService();
    this.fiscalYearService = new FiscalYearService();
    this.fiscalPeriodService = new FiscalPeriodService();
    this.locationService = new LocationService();
    this.holdReasonService = new HoldReasonService();
    this.shipmentCommentService = new ShipmentCommentService();
    this.shipmentControlService = new ShipmentControlService();
    this.shipmentService = new ShipmentService();
    this.billingControlService = new BillingControlService();
    this.dataEntryControlService = new DataEntryControlService();
    this.dispatchControlService = new DispatchControlService();
    this.distanceOverrideService = new DistanceOverrideService();
    this.realtimeService = new RealtimeService();
    this.integrationService = new IntegrationService();
    this.apiKeyService = new APIKeyService();
    this.analyticService = new AnalyticsService();
    this.auditService = new AuditService();
    this.assignmentService = new AssignmentService();
    this.notificationService = new NotificationService();
    this.tableChangeAlertService = new TableChangeAlertService();
  }
}

export const apiService = new APIService();
