// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package schedulingresolver

import (
	base "github.com/emoss08/trenova/internal/api/graphql/resolver/base"
	schedulingservice "github.com/emoss08/trenova/internal/core/services/schedulingservice"
)

type Deps struct {
	*base.Core
	SchedulingService *schedulingservice.Service
}

type MutationResolver struct{ *Deps }

type QueryResolver struct{ *Deps }

type ShiftTemplateResolver struct{ *Deps }
