package mutate

import (
	"strconv"
	"strings"
	"time"
)

// MutHarnessFileName is the TestMain file injected into a covering test package
// through -overlay. It never touches the source tree.
const MutHarnessFileName = "assay_mut_harness_test.go"

// PlanEnvVar points the harness at its instruction file. Unset, the injected
// TestMain is a plain os.Exit(m.Run()) — which is what lets the same binary
// serve the env-selected fallback path with per-process semantics intact.
const PlanEnvVar = "ASSAY_MUT_PLAN"

const (
	mutHarnessPrefix  = "assay:mutharness "
	mutHarnessBegin   = "begin"
	mutHarnessVerdict = "verdict"
)

const (
	verdictKilled   = "killed"
	verdictSurvived = "survived"
	// verdictTainted means the mutant's site executed during package init, where
	// no in-process switch can reach it; the harness refuses to judge it and the
	// executor re-runs it env-selected, in a process of its own.
	verdictTainted = "tainted"
)

const mutHarnessHeader = `// Code generated by assay for mutation testing. DO NOT EDIT.
//
// assay injects this file into a covering test package through -overlay while
// mutants are judged; it is never written to the source tree. It runs the
// package's tests once per mutant, switching the active mutant between runs, so
// judging N mutants costs one process instead of N. With ` + PlanEnvVar + `
// unset it behaves exactly like a normal test binary.
`

// MutHarnessSource renders the injected TestMain for a covering test package.
//
// The protocol mirrors the index harness, with one addition: a begin line
// before each m.Run. The executor needs it to tell two deaths apart — a process
// that dies after announcing an instruction was killed by that mutant's tests,
// while a fresh process that dies before its first announcement has a broken
// harness, and the remaining mutants must fall back rather than be blamed.
func MutHarnessSource(testPackageName, mutatedPath string, samePackage bool) []byte {
	sel := "AssaySelect"
	initSites := "AssayInitSites"
	importBlock := ""
	if !samePackage {
		sel = "assaymut." + sel
		initSites = "assaymut." + initSites
		importBlock = "\n\tassaymut " + strconv.Quote(mutatedPath) + "\n"
	}

	return []byte(mutHarnessHeader + `
package ` + testPackageName + `

import (
	"bufio"
	"flag"
	"fmt"
	"os"
	"strconv"
	"strings"
	"testing"
	"time"
` + importBlock + `)

func TestMain(m *testing.M) {
	plan := os.Getenv("` + PlanEnvVar + `")
	if plan == "" {
		os.Exit(m.Run())
	}

	file, err := os.Open(plan)
	if err != nil {
		assayMutFail(err)
	}
	defer file.Close()

	tainted := make(map[int32]bool)
	for _, id := range ` + initSites + `() {
		tainted[id] = true
	}

	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" {
			continue
		}
		idField, pattern, ok := strings.Cut(line, "\t")
		if !ok {
			assayMutFail(fmt.Errorf("malformed instruction %q", line))
		}
		id64, parseErr := strconv.ParseInt(idField, 10, 32)
		if parseErr != nil {
			assayMutFail(fmt.Errorf("bad mutant id %q", idField))
		}
		id := int32(id64)

		if tainted[id] {
			fmt.Printf("` + mutHarnessPrefix + mutHarnessVerdict + ` %d ` + verdictTainted + ` ns=0\n", id)

			continue
		}

		if setErr := flag.Set("test.run", pattern); setErr != nil {
			assayMutFail(setErr)
		}

		fmt.Printf("` + mutHarnessPrefix + mutHarnessBegin + ` %d\n", id)
		` + sel + `(id)
		began := time.Now()
		code := m.Run()
		elapsed := time.Since(began)
		` + sel + `(0)

		verdict := "` + verdictSurvived + `"
		if code != 0 {
			verdict = "` + verdictKilled + `"
		}
		fmt.Printf("` + mutHarnessPrefix + mutHarnessVerdict + ` %d %s ns=%d\n", id, verdict, elapsed.Nanoseconds())
	}
	if scanErr := scanner.Err(); scanErr != nil {
		assayMutFail(scanErr)
	}

	os.Exit(0)
}

func assayMutFail(err error) {
	fmt.Fprintln(os.Stderr, "assay:mutharness-error", err)
	os.Exit(3)
}
`)
}

type mutHarnessEvent struct {
	kind     string
	id       int32
	verdict  string
	duration time.Duration
}

// parseMutHarnessLine accepts only lines about the expected mutant, so a test
// that prints something shaped like a harness line cannot desync the executor.
// The prefix is searched anywhere in the line, not only at its start, because a
// test printing without a trailing newline glues the harness's output onto its
// fragment.
func parseMutHarnessLine(line string, expected int32) (mutHarnessEvent, bool) {
	at := strings.LastIndex(line, mutHarnessPrefix)
	if at < 0 {
		return mutHarnessEvent{}, false
	}

	fields := strings.Fields(line[at+len(mutHarnessPrefix):])
	if len(fields) < 2 {
		return mutHarnessEvent{}, false
	}

	id64, err := strconv.ParseInt(fields[1], 10, 32)
	if err != nil || int32(id64) != expected {
		return mutHarnessEvent{}, false
	}

	switch fields[0] {
	case mutHarnessBegin:
		if len(fields) != 2 {
			return mutHarnessEvent{}, false
		}

		return mutHarnessEvent{kind: mutHarnessBegin, id: expected}, true
	case mutHarnessVerdict:
		if len(fields) != 4 {
			return mutHarnessEvent{}, false
		}
		verdict := fields[2]
		if verdict != verdictKilled && verdict != verdictSurvived && verdict != verdictTainted {
			return mutHarnessEvent{}, false
		}
		nsField, ok := strings.CutPrefix(fields[3], "ns=")
		if !ok {
			return mutHarnessEvent{}, false
		}
		ns, nsErr := strconv.ParseInt(nsField, 10, 64)
		if nsErr != nil || ns < 0 {
			return mutHarnessEvent{}, false
		}

		return mutHarnessEvent{
			kind:     mutHarnessVerdict,
			id:       expected,
			verdict:  verdict,
			duration: time.Duration(ns),
		}, true
	default:
		return mutHarnessEvent{}, false
	}
}
