// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/emoss08/trenova/internal/core/ports/services"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDispatchAutoAssignService creates a new instance of MockDispatchAutoAssignService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDispatchAutoAssignService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDispatchAutoAssignService {
	mock := &MockDispatchAutoAssignService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDispatchAutoAssignService is an autogenerated mock type for the DispatchAutoAssignService type
type MockDispatchAutoAssignService struct {
	mock.Mock
}

type MockDispatchAutoAssignService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDispatchAutoAssignService) EXPECT() *MockDispatchAutoAssignService_Expecter {
	return &MockDispatchAutoAssignService_Expecter{mock: &_m.Mock}
}

// Plan provides a mock function for the type MockDispatchAutoAssignService
func (_mock *MockDispatchAutoAssignService) Plan(ctx context.Context, req *services.DispatchPlanRequest) (*services.DispatchPlan, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Plan")
	}

	var r0 *services.DispatchPlan
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *services.DispatchPlanRequest) (*services.DispatchPlan, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *services.DispatchPlanRequest) *services.DispatchPlan); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.DispatchPlan)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *services.DispatchPlanRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDispatchAutoAssignService_Plan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Plan'
type MockDispatchAutoAssignService_Plan_Call struct {
	*mock.Call
}

// Plan is a helper method to define mock.On call
//   - ctx context.Context
//   - req *services.DispatchPlanRequest
func (_e *MockDispatchAutoAssignService_Expecter) Plan(ctx any, req any) *MockDispatchAutoAssignService_Plan_Call {
	return &MockDispatchAutoAssignService_Plan_Call{Call: _e.mock.On("Plan", ctx, req)}
}

func (_c *MockDispatchAutoAssignService_Plan_Call) Run(run func(ctx context.Context, req *services.DispatchPlanRequest)) *MockDispatchAutoAssignService_Plan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *services.DispatchPlanRequest
		if args[1] != nil {
			arg1 = args[1].(*services.DispatchPlanRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDispatchAutoAssignService_Plan_Call) Return(dispatchPlan *services.DispatchPlan, err error) *MockDispatchAutoAssignService_Plan_Call {
	_c.Call.Return(dispatchPlan, err)
	return _c
}

func (_c *MockDispatchAutoAssignService_Plan_Call) RunAndReturn(run func(ctx context.Context, req *services.DispatchPlanRequest) (*services.DispatchPlan, error)) *MockDispatchAutoAssignService_Plan_Call {
	_c.Call.Return(run)
	return _c
}
