// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/emoss08/trenova/internal/core/domain/documenttemplate"
	"github.com/emoss08/trenova/internal/core/ports/repositories"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDocumentTemplateVersionRepository creates a new instance of MockDocumentTemplateVersionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDocumentTemplateVersionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDocumentTemplateVersionRepository {
	mock := &MockDocumentTemplateVersionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDocumentTemplateVersionRepository is an autogenerated mock type for the DocumentTemplateVersionRepository type
type MockDocumentTemplateVersionRepository struct {
	mock.Mock
}

type MockDocumentTemplateVersionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDocumentTemplateVersionRepository) EXPECT() *MockDocumentTemplateVersionRepository_Expecter {
	return &MockDocumentTemplateVersionRepository_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function for the type MockDocumentTemplateVersionRepository
func (_mock *MockDocumentTemplateVersionRepository) GetByID(context1 context.Context, getDocumentTemplateVersionByIDRequest *repositories.GetDocumentTemplateVersionByIDRequest) (*documenttemplate.DocumentTemplateVersion, error) {
	ret := _mock.Called(context1, getDocumentTemplateVersionByIDRequest)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *documenttemplate.DocumentTemplateVersion
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *repositories.GetDocumentTemplateVersionByIDRequest) (*documenttemplate.DocumentTemplateVersion, error)); ok {
		return returnFunc(context1, getDocumentTemplateVersionByIDRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *repositories.GetDocumentTemplateVersionByIDRequest) *documenttemplate.DocumentTemplateVersion); ok {
		r0 = returnFunc(context1, getDocumentTemplateVersionByIDRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*documenttemplate.DocumentTemplateVersion)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *repositories.GetDocumentTemplateVersionByIDRequest) error); ok {
		r1 = returnFunc(context1, getDocumentTemplateVersionByIDRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDocumentTemplateVersionRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockDocumentTemplateVersionRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - context1 context.Context
//   - getDocumentTemplateVersionByIDRequest *repositories.GetDocumentTemplateVersionByIDRequest
func (_e *MockDocumentTemplateVersionRepository_Expecter) GetByID(context1 any, getDocumentTemplateVersionByIDRequest any) *MockDocumentTemplateVersionRepository_GetByID_Call {
	return &MockDocumentTemplateVersionRepository_GetByID_Call{Call: _e.mock.On("GetByID", context1, getDocumentTemplateVersionByIDRequest)}
}

func (_c *MockDocumentTemplateVersionRepository_GetByID_Call) Run(
	run func(context1 context.Context, getDocumentTemplateVersionByIDRequest *repositories.GetDocumentTemplateVersionByIDRequest),
) *MockDocumentTemplateVersionRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *repositories.GetDocumentTemplateVersionByIDRequest
		if args[1] != nil {
			arg1 = args[1].(*repositories.GetDocumentTemplateVersionByIDRequest)
		}
		run(arg0, arg1)
	})
	return _c
}

func (_c *MockDocumentTemplateVersionRepository_GetByID_Call) Return(documentTemplateVersion *documenttemplate.DocumentTemplateVersion, err error) *MockDocumentTemplateVersionRepository_GetByID_Call {
	_c.Call.Return(documentTemplateVersion, err)
	return _c
}

func (_c *MockDocumentTemplateVersionRepository_GetByID_Call) RunAndReturn(
	run func(context1 context.Context, getDocumentTemplateVersionByIDRequest *repositories.GetDocumentTemplateVersionByIDRequest) (*documenttemplate.DocumentTemplateVersion, error),
) *MockDocumentTemplateVersionRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockDocumentTemplateVersionRepository
func (_mock *MockDocumentTemplateVersionRepository) List(context1 context.Context, listDocumentTemplateVersionsRequest *repositories.ListDocumentTemplateVersionsRequest) ([]*documenttemplate.DocumentTemplateVersion, error) {
	ret := _mock.Called(context1, listDocumentTemplateVersionsRequest)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*documenttemplate.DocumentTemplateVersion
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *repositories.ListDocumentTemplateVersionsRequest) ([]*documenttemplate.DocumentTemplateVersion, error)); ok {
		return returnFunc(context1, listDocumentTemplateVersionsRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *repositories.ListDocumentTemplateVersionsRequest) []*documenttemplate.DocumentTemplateVersion); ok {
		r0 = returnFunc(context1, listDocumentTemplateVersionsRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*documenttemplate.DocumentTemplateVersion)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *repositories.ListDocumentTemplateVersionsRequest) error); ok {
		r1 = returnFunc(context1, listDocumentTemplateVersionsRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDocumentTemplateVersionRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockDocumentTemplateVersionRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - context1 context.Context
//   - listDocumentTemplateVersionsRequest *repositories.ListDocumentTemplateVersionsRequest
func (_e *MockDocumentTemplateVersionRepository_Expecter) List(context1 any, listDocumentTemplateVersionsRequest any) *MockDocumentTemplateVersionRepository_List_Call {
	return &MockDocumentTemplateVersionRepository_List_Call{Call: _e.mock.On("List", context1, listDocumentTemplateVersionsRequest)}
}

func (_c *MockDocumentTemplateVersionRepository_List_Call) Run(
	run func(context1 context.Context, listDocumentTemplateVersionsRequest *repositories.ListDocumentTemplateVersionsRequest),
) *MockDocumentTemplateVersionRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *repositories.ListDocumentTemplateVersionsRequest
		if args[1] != nil {
			arg1 = args[1].(*repositories.ListDocumentTemplateVersionsRequest)
		}
		run(arg0, arg1)
	})
	return _c
}

func (_c *MockDocumentTemplateVersionRepository_List_Call) Return(documentTemplateVersions []*documenttemplate.DocumentTemplateVersion, err error) *MockDocumentTemplateVersionRepository_List_Call {
	_c.Call.Return(documentTemplateVersions, err)
	return _c
}

func (_c *MockDocumentTemplateVersionRepository_List_Call) RunAndReturn(
	run func(context1 context.Context, listDocumentTemplateVersionsRequest *repositories.ListDocumentTemplateVersionsRequest) ([]*documenttemplate.DocumentTemplateVersion, error),
) *MockDocumentTemplateVersionRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockDocumentTemplateVersionRepository
func (_mock *MockDocumentTemplateVersionRepository) Create(context1 context.Context, createDocumentTemplateVersionRequest *repositories.CreateDocumentTemplateVersionRequest) (*documenttemplate.DocumentTemplateVersion, error) {
	ret := _mock.Called(context1, createDocumentTemplateVersionRequest)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *documenttemplate.DocumentTemplateVersion
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *repositories.CreateDocumentTemplateVersionRequest) (*documenttemplate.DocumentTemplateVersion, error)); ok {
		return returnFunc(context1, createDocumentTemplateVersionRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *repositories.CreateDocumentTemplateVersionRequest) *documenttemplate.DocumentTemplateVersion); ok {
		r0 = returnFunc(context1, createDocumentTemplateVersionRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*documenttemplate.DocumentTemplateVersion)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *repositories.CreateDocumentTemplateVersionRequest) error); ok {
		r1 = returnFunc(context1, createDocumentTemplateVersionRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDocumentTemplateVersionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockDocumentTemplateVersionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - context1 context.Context
//   - createDocumentTemplateVersionRequest *repositories.CreateDocumentTemplateVersionRequest
func (_e *MockDocumentTemplateVersionRepository_Expecter) Create(context1 any, createDocumentTemplateVersionRequest any) *MockDocumentTemplateVersionRepository_Create_Call {
	return &MockDocumentTemplateVersionRepository_Create_Call{Call: _e.mock.On("Create", context1, createDocumentTemplateVersionRequest)}
}

func (_c *MockDocumentTemplateVersionRepository_Create_Call) Run(
	run func(context1 context.Context, createDocumentTemplateVersionRequest *repositories.CreateDocumentTemplateVersionRequest),
) *MockDocumentTemplateVersionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *repositories.CreateDocumentTemplateVersionRequest
		if args[1] != nil {
			arg1 = args[1].(*repositories.CreateDocumentTemplateVersionRequest)
		}
		run(arg0, arg1)
	})
	return _c
}

func (_c *MockDocumentTemplateVersionRepository_Create_Call) Return(documentTemplateVersion *documenttemplate.DocumentTemplateVersion, err error) *MockDocumentTemplateVersionRepository_Create_Call {
	_c.Call.Return(documentTemplateVersion, err)
	return _c
}

func (_c *MockDocumentTemplateVersionRepository_Create_Call) RunAndReturn(
	run func(context1 context.Context, createDocumentTemplateVersionRequest *repositories.CreateDocumentTemplateVersionRequest) (*documenttemplate.DocumentTemplateVersion, error),
) *MockDocumentTemplateVersionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockDocumentTemplateVersionRepository
func (_mock *MockDocumentTemplateVersionRepository) Update(context1 context.Context, documentTemplateVersion *documenttemplate.DocumentTemplateVersion) (*documenttemplate.DocumentTemplateVersion, error) {
	ret := _mock.Called(context1, documentTemplateVersion)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *documenttemplate.DocumentTemplateVersion
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *documenttemplate.DocumentTemplateVersion) (*documenttemplate.DocumentTemplateVersion, error)); ok {
		return returnFunc(context1, documentTemplateVersion)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *documenttemplate.DocumentTemplateVersion) *documenttemplate.DocumentTemplateVersion); ok {
		r0 = returnFunc(context1, documentTemplateVersion)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*documenttemplate.DocumentTemplateVersion)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *documenttemplate.DocumentTemplateVersion) error); ok {
		r1 = returnFunc(context1, documentTemplateVersion)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDocumentTemplateVersionRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockDocumentTemplateVersionRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - context1 context.Context
//   - documentTemplateVersion *documenttemplate.DocumentTemplateVersion
func (_e *MockDocumentTemplateVersionRepository_Expecter) Update(context1 any, documentTemplateVersion any) *MockDocumentTemplateVersionRepository_Update_Call {
	return &MockDocumentTemplateVersionRepository_Update_Call{Call: _e.mock.On("Update", context1, documentTemplateVersion)}
}

func (_c *MockDocumentTemplateVersionRepository_Update_Call) Run(
	run func(context1 context.Context, documentTemplateVersion *documenttemplate.DocumentTemplateVersion),
) *MockDocumentTemplateVersionRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *documenttemplate.DocumentTemplateVersion
		if args[1] != nil {
			arg1 = args[1].(*documenttemplate.DocumentTemplateVersion)
		}
		run(arg0, arg1)
	})
	return _c
}

func (_c *MockDocumentTemplateVersionRepository_Update_Call) Return(documentTemplateVersion *documenttemplate.DocumentTemplateVersion, err error) *MockDocumentTemplateVersionRepository_Update_Call {
	_c.Call.Return(documentTemplateVersion, err)
	return _c
}

func (_c *MockDocumentTemplateVersionRepository_Update_Call) RunAndReturn(
	run func(context1 context.Context, documentTemplateVersion *documenttemplate.DocumentTemplateVersion) (*documenttemplate.DocumentTemplateVersion, error),
) *MockDocumentTemplateVersionRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// Publish provides a mock function for the type MockDocumentTemplateVersionRepository
func (_mock *MockDocumentTemplateVersionRepository) Publish(context1 context.Context, publishDocumentTemplateVersionRequest *repositories.PublishDocumentTemplateVersionRequest) (*documenttemplate.DocumentTemplateVersion, error) {
	ret := _mock.Called(context1, publishDocumentTemplateVersionRequest)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 *documenttemplate.DocumentTemplateVersion
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *repositories.PublishDocumentTemplateVersionRequest) (*documenttemplate.DocumentTemplateVersion, error)); ok {
		return returnFunc(context1, publishDocumentTemplateVersionRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *repositories.PublishDocumentTemplateVersionRequest) *documenttemplate.DocumentTemplateVersion); ok {
		r0 = returnFunc(context1, publishDocumentTemplateVersionRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*documenttemplate.DocumentTemplateVersion)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *repositories.PublishDocumentTemplateVersionRequest) error); ok {
		r1 = returnFunc(context1, publishDocumentTemplateVersionRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDocumentTemplateVersionRepository_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockDocumentTemplateVersionRepository_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - context1 context.Context
//   - publishDocumentTemplateVersionRequest *repositories.PublishDocumentTemplateVersionRequest
func (_e *MockDocumentTemplateVersionRepository_Expecter) Publish(context1 any, publishDocumentTemplateVersionRequest any) *MockDocumentTemplateVersionRepository_Publish_Call {
	return &MockDocumentTemplateVersionRepository_Publish_Call{Call: _e.mock.On("Publish", context1, publishDocumentTemplateVersionRequest)}
}

func (_c *MockDocumentTemplateVersionRepository_Publish_Call) Run(
	run func(context1 context.Context, publishDocumentTemplateVersionRequest *repositories.PublishDocumentTemplateVersionRequest),
) *MockDocumentTemplateVersionRepository_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *repositories.PublishDocumentTemplateVersionRequest
		if args[1] != nil {
			arg1 = args[1].(*repositories.PublishDocumentTemplateVersionRequest)
		}
		run(arg0, arg1)
	})
	return _c
}

func (_c *MockDocumentTemplateVersionRepository_Publish_Call) Return(documentTemplateVersion *documenttemplate.DocumentTemplateVersion, err error) *MockDocumentTemplateVersionRepository_Publish_Call {
	_c.Call.Return(documentTemplateVersion, err)
	return _c
}

func (_c *MockDocumentTemplateVersionRepository_Publish_Call) RunAndReturn(
	run func(context1 context.Context, publishDocumentTemplateVersionRequest *repositories.PublishDocumentTemplateVersionRequest) (*documenttemplate.DocumentTemplateVersion, error),
) *MockDocumentTemplateVersionRepository_Publish_Call {
	_c.Call.Return(run)
	return _c
}

// Archive provides a mock function for the type MockDocumentTemplateVersionRepository
func (_mock *MockDocumentTemplateVersionRepository) Archive(context1 context.Context, archiveDocumentTemplateVersionRequest *repositories.ArchiveDocumentTemplateVersionRequest) (*documenttemplate.DocumentTemplateVersion, error) {
	ret := _mock.Called(context1, archiveDocumentTemplateVersionRequest)

	if len(ret) == 0 {
		panic("no return value specified for Archive")
	}

	var r0 *documenttemplate.DocumentTemplateVersion
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *repositories.ArchiveDocumentTemplateVersionRequest) (*documenttemplate.DocumentTemplateVersion, error)); ok {
		return returnFunc(context1, archiveDocumentTemplateVersionRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *repositories.ArchiveDocumentTemplateVersionRequest) *documenttemplate.DocumentTemplateVersion); ok {
		r0 = returnFunc(context1, archiveDocumentTemplateVersionRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*documenttemplate.DocumentTemplateVersion)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *repositories.ArchiveDocumentTemplateVersionRequest) error); ok {
		r1 = returnFunc(context1, archiveDocumentTemplateVersionRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDocumentTemplateVersionRepository_Archive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Archive'
type MockDocumentTemplateVersionRepository_Archive_Call struct {
	*mock.Call
}

// Archive is a helper method to define mock.On call
//   - context1 context.Context
//   - archiveDocumentTemplateVersionRequest *repositories.ArchiveDocumentTemplateVersionRequest
func (_e *MockDocumentTemplateVersionRepository_Expecter) Archive(context1 any, archiveDocumentTemplateVersionRequest any) *MockDocumentTemplateVersionRepository_Archive_Call {
	return &MockDocumentTemplateVersionRepository_Archive_Call{Call: _e.mock.On("Archive", context1, archiveDocumentTemplateVersionRequest)}
}

func (_c *MockDocumentTemplateVersionRepository_Archive_Call) Run(
	run func(context1 context.Context, archiveDocumentTemplateVersionRequest *repositories.ArchiveDocumentTemplateVersionRequest),
) *MockDocumentTemplateVersionRepository_Archive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *repositories.ArchiveDocumentTemplateVersionRequest
		if args[1] != nil {
			arg1 = args[1].(*repositories.ArchiveDocumentTemplateVersionRequest)
		}
		run(arg0, arg1)
	})
	return _c
}

func (_c *MockDocumentTemplateVersionRepository_Archive_Call) Return(documentTemplateVersion *documenttemplate.DocumentTemplateVersion, err error) *MockDocumentTemplateVersionRepository_Archive_Call {
	_c.Call.Return(documentTemplateVersion, err)
	return _c
}

func (_c *MockDocumentTemplateVersionRepository_Archive_Call) RunAndReturn(
	run func(context1 context.Context, archiveDocumentTemplateVersionRequest *repositories.ArchiveDocumentTemplateVersionRequest) (*documenttemplate.DocumentTemplateVersion, error),
) *MockDocumentTemplateVersionRepository_Archive_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockDocumentTemplateVersionRepository
func (_mock *MockDocumentTemplateVersionRepository) Delete(context1 context.Context, getDocumentTemplateVersionByIDRequest *repositories.GetDocumentTemplateVersionByIDRequest) error {
	ret := _mock.Called(context1, getDocumentTemplateVersionByIDRequest)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *repositories.GetDocumentTemplateVersionByIDRequest) error); ok {
		r0 = returnFunc(context1, getDocumentTemplateVersionByIDRequest)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDocumentTemplateVersionRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockDocumentTemplateVersionRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - context1 context.Context
//   - getDocumentTemplateVersionByIDRequest *repositories.GetDocumentTemplateVersionByIDRequest
func (_e *MockDocumentTemplateVersionRepository_Expecter) Delete(context1 any, getDocumentTemplateVersionByIDRequest any) *MockDocumentTemplateVersionRepository_Delete_Call {
	return &MockDocumentTemplateVersionRepository_Delete_Call{Call: _e.mock.On("Delete", context1, getDocumentTemplateVersionByIDRequest)}
}

func (_c *MockDocumentTemplateVersionRepository_Delete_Call) Run(
	run func(context1 context.Context, getDocumentTemplateVersionByIDRequest *repositories.GetDocumentTemplateVersionByIDRequest),
) *MockDocumentTemplateVersionRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *repositories.GetDocumentTemplateVersionByIDRequest
		if args[1] != nil {
			arg1 = args[1].(*repositories.GetDocumentTemplateVersionByIDRequest)
		}
		run(arg0, arg1)
	})
	return _c
}

func (_c *MockDocumentTemplateVersionRepository_Delete_Call) Return(err error) *MockDocumentTemplateVersionRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDocumentTemplateVersionRepository_Delete_Call) RunAndReturn(
	run func(context1 context.Context, getDocumentTemplateVersionByIDRequest *repositories.GetDocumentTemplateVersionByIDRequest) error,
) *MockDocumentTemplateVersionRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}
