// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/emoss08/trenova/internal/core/domain/shipmentevent"
	"github.com/emoss08/trenova/internal/core/ports/repositories"
	"github.com/emoss08/trenova/internal/core/ports/services"
	mock "github.com/stretchr/testify/mock"
)

// NewMockShipmentEventService creates a new instance of MockShipmentEventService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockShipmentEventService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockShipmentEventService {
	mock := &MockShipmentEventService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockShipmentEventService is an autogenerated mock type for the ShipmentEventService type
type MockShipmentEventService struct {
	mock.Mock
}

type MockShipmentEventService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockShipmentEventService) EXPECT() *MockShipmentEventService_Expecter {
	return &MockShipmentEventService_Expecter{mock: &_m.Mock}
}

// List provides a mock function for the type MockShipmentEventService
func (_mock *MockShipmentEventService) List(ctx context.Context, req *repositories.ListShipmentEventsRequest) ([]*shipmentevent.Event, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*shipmentevent.Event
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *repositories.ListShipmentEventsRequest) ([]*shipmentevent.Event, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *repositories.ListShipmentEventsRequest) []*shipmentevent.Event); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*shipmentevent.Event)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *repositories.ListShipmentEventsRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockShipmentEventService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockShipmentEventService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - req *repositories.ListShipmentEventsRequest
func (_e *MockShipmentEventService_Expecter) List(ctx interface{}, req interface{}) *MockShipmentEventService_List_Call {
	return &MockShipmentEventService_List_Call{Call: _e.mock.On("List", ctx, req)}
}

func (_c *MockShipmentEventService_List_Call) Run(run func(ctx context.Context, req *repositories.ListShipmentEventsRequest)) *MockShipmentEventService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *repositories.ListShipmentEventsRequest
		if args[1] != nil {
			arg1 = args[1].(*repositories.ListShipmentEventsRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockShipmentEventService_List_Call) Return(events []*shipmentevent.Event, err error) *MockShipmentEventService_List_Call {
	_c.Call.Return(events, err)
	return _c
}

func (_c *MockShipmentEventService_List_Call) RunAndReturn(run func(ctx context.Context, req *repositories.ListShipmentEventsRequest) ([]*shipmentevent.Event, error)) *MockShipmentEventService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Record provides a mock function for the type MockShipmentEventService
func (_mock *MockShipmentEventService) Record(ctx context.Context, params *services.RecordShipmentEventParams) error {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Record")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *services.RecordShipmentEventParams) error); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockShipmentEventService_Record_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Record'
type MockShipmentEventService_Record_Call struct {
	*mock.Call
}

// Record is a helper method to define mock.On call
//   - ctx context.Context
//   - params *services.RecordShipmentEventParams
func (_e *MockShipmentEventService_Expecter) Record(ctx interface{}, params interface{}) *MockShipmentEventService_Record_Call {
	return &MockShipmentEventService_Record_Call{Call: _e.mock.On("Record", ctx, params)}
}

func (_c *MockShipmentEventService_Record_Call) Run(run func(ctx context.Context, params *services.RecordShipmentEventParams)) *MockShipmentEventService_Record_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *services.RecordShipmentEventParams
		if args[1] != nil {
			arg1 = args[1].(*services.RecordShipmentEventParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockShipmentEventService_Record_Call) Return(err error) *MockShipmentEventService_Record_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockShipmentEventService_Record_Call) RunAndReturn(run func(ctx context.Context, params *services.RecordShipmentEventParams) error) *MockShipmentEventService_Record_Call {
	_c.Call.Return(run)
	return _c
}
