// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/emoss08/trenova/internal/core/domain/carrier"
	"github.com/emoss08/trenova/internal/core/ports/repositories"
	"github.com/emoss08/trenova/pkg/pagination"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCarrierRepository creates a new instance of MockCarrierRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCarrierRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCarrierRepository {
	mock := &MockCarrierRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCarrierRepository is an autogenerated mock type for the CarrierRepository type
type MockCarrierRepository struct {
	mock.Mock
}

type MockCarrierRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCarrierRepository) EXPECT() *MockCarrierRepository_Expecter {
	return &MockCarrierRepository_Expecter{mock: &_m.Mock}
}

// BulkUpdateStatus provides a mock function for the type MockCarrierRepository
func (_mock *MockCarrierRepository) BulkUpdateStatus(ctx context.Context, req *repositories.BulkUpdateCarrierStatusRequest) ([]*carrier.Carrier, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for BulkUpdateStatus")
	}

	var r0 []*carrier.Carrier
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *repositories.BulkUpdateCarrierStatusRequest) ([]*carrier.Carrier, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *repositories.BulkUpdateCarrierStatusRequest) []*carrier.Carrier); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*carrier.Carrier)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *repositories.BulkUpdateCarrierStatusRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCarrierRepository_BulkUpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkUpdateStatus'
type MockCarrierRepository_BulkUpdateStatus_Call struct {
	*mock.Call
}

// BulkUpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - req *repositories.BulkUpdateCarrierStatusRequest
func (_e *MockCarrierRepository_Expecter) BulkUpdateStatus(ctx any, req any) *MockCarrierRepository_BulkUpdateStatus_Call {
	return &MockCarrierRepository_BulkUpdateStatus_Call{Call: _e.mock.On("BulkUpdateStatus", ctx, req)}
}

func (_c *MockCarrierRepository_BulkUpdateStatus_Call) Run(run func(ctx context.Context, req *repositories.BulkUpdateCarrierStatusRequest)) *MockCarrierRepository_BulkUpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *repositories.BulkUpdateCarrierStatusRequest
		if args[1] != nil {
			arg1 = args[1].(*repositories.BulkUpdateCarrierStatusRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCarrierRepository_BulkUpdateStatus_Call) Return(customers []*carrier.Carrier, err error) *MockCarrierRepository_BulkUpdateStatus_Call {
	_c.Call.Return(customers, err)
	return _c
}

func (_c *MockCarrierRepository_BulkUpdateStatus_Call) RunAndReturn(run func(ctx context.Context, req *repositories.BulkUpdateCarrierStatusRequest) ([]*carrier.Carrier, error)) *MockCarrierRepository_BulkUpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockCarrierRepository
func (_mock *MockCarrierRepository) Create(ctx context.Context, entity *carrier.Carrier) (*carrier.Carrier, error) {
	ret := _mock.Called(ctx, entity)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *carrier.Carrier
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *carrier.Carrier) (*carrier.Carrier, error)); ok {
		return returnFunc(ctx, entity)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *carrier.Carrier) *carrier.Carrier); ok {
		r0 = returnFunc(ctx, entity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*carrier.Carrier)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *carrier.Carrier) error); ok {
		r1 = returnFunc(ctx, entity)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCarrierRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCarrierRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - entity *carrier.Carrier
func (_e *MockCarrierRepository_Expecter) Create(ctx any, entity any) *MockCarrierRepository_Create_Call {
	return &MockCarrierRepository_Create_Call{Call: _e.mock.On("Create", ctx, entity)}
}

func (_c *MockCarrierRepository_Create_Call) Run(run func(ctx context.Context, entity *carrier.Carrier)) *MockCarrierRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *carrier.Carrier
		if args[1] != nil {
			arg1 = args[1].(*carrier.Carrier)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCarrierRepository_Create_Call) Return(customer1 *carrier.Carrier, err error) *MockCarrierRepository_Create_Call {
	_c.Call.Return(customer1, err)
	return _c
}

func (_c *MockCarrierRepository_Create_Call) RunAndReturn(run func(ctx context.Context, entity *carrier.Carrier) (*carrier.Carrier, error)) *MockCarrierRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockCarrierRepository
func (_mock *MockCarrierRepository) GetByID(ctx context.Context, req repositories.GetCarrierByIDRequest) (*carrier.Carrier, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *carrier.Carrier
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repositories.GetCarrierByIDRequest) (*carrier.Carrier, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repositories.GetCarrierByIDRequest) *carrier.Carrier); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*carrier.Carrier)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repositories.GetCarrierByIDRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCarrierRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockCarrierRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - req repositories.GetCarrierByIDRequest
func (_e *MockCarrierRepository_Expecter) GetByID(ctx any, req any) *MockCarrierRepository_GetByID_Call {
	return &MockCarrierRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, req)}
}

func (_c *MockCarrierRepository_GetByID_Call) Run(run func(ctx context.Context, req repositories.GetCarrierByIDRequest)) *MockCarrierRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repositories.GetCarrierByIDRequest
		if args[1] != nil {
			arg1 = args[1].(repositories.GetCarrierByIDRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCarrierRepository_GetByID_Call) Return(customer1 *carrier.Carrier, err error) *MockCarrierRepository_GetByID_Call {
	_c.Call.Return(customer1, err)
	return _c
}

func (_c *MockCarrierRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, req repositories.GetCarrierByIDRequest) (*carrier.Carrier, error)) *MockCarrierRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByIdentity provides a mock function for the type MockCarrierRepository
func (_mock *MockCarrierRepository) FindByIdentity(ctx context.Context, req *repositories.FindCarrierByIdentityRequest) (*carrier.Carrier, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for FindByIdentity")
	}

	var r0 *carrier.Carrier
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *repositories.FindCarrierByIdentityRequest) (*carrier.Carrier, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *repositories.FindCarrierByIdentityRequest) *carrier.Carrier); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*carrier.Carrier)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *repositories.FindCarrierByIdentityRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCarrierRepository_FindByIdentity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIdentity'
type MockCarrierRepository_FindByIdentity_Call struct {
	*mock.Call
}

// FindByIdentity is a helper method to define mock.On call
//   - ctx context.Context
//   - req *repositories.FindCarrierByIdentityRequest
func (_e *MockCarrierRepository_Expecter) FindByIdentity(ctx any, req any) *MockCarrierRepository_FindByIdentity_Call {
	return &MockCarrierRepository_FindByIdentity_Call{Call: _e.mock.On("FindByIdentity", ctx, req)}
}

func (_c *MockCarrierRepository_FindByIdentity_Call) Run(run func(ctx context.Context, req *repositories.FindCarrierByIdentityRequest)) *MockCarrierRepository_FindByIdentity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *repositories.FindCarrierByIdentityRequest
		if args[1] != nil {
			arg1 = args[1].(*repositories.FindCarrierByIdentityRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCarrierRepository_FindByIdentity_Call) Return(customer1 *carrier.Carrier, err error) *MockCarrierRepository_FindByIdentity_Call {
	_c.Call.Return(customer1, err)
	return _c
}

func (_c *MockCarrierRepository_FindByIdentity_Call) RunAndReturn(run func(ctx context.Context, req *repositories.FindCarrierByIdentityRequest) (*carrier.Carrier, error)) *MockCarrierRepository_FindByIdentity_Call {
	_c.Call.Return(run)
	return _c
}

// GetByIDs provides a mock function for the type MockCarrierRepository
func (_mock *MockCarrierRepository) GetByIDs(ctx context.Context, req repositories.GetCarriersByIDsRequest) ([]*carrier.Carrier, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetByIDs")
	}

	var r0 []*carrier.Carrier
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repositories.GetCarriersByIDsRequest) ([]*carrier.Carrier, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repositories.GetCarriersByIDsRequest) []*carrier.Carrier); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*carrier.Carrier)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repositories.GetCarriersByIDsRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCarrierRepository_GetByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByIDs'
type MockCarrierRepository_GetByIDs_Call struct {
	*mock.Call
}

// GetByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - req repositories.GetCarriersByIDsRequest
func (_e *MockCarrierRepository_Expecter) GetByIDs(ctx any, req any) *MockCarrierRepository_GetByIDs_Call {
	return &MockCarrierRepository_GetByIDs_Call{Call: _e.mock.On("GetByIDs", ctx, req)}
}

func (_c *MockCarrierRepository_GetByIDs_Call) Run(run func(ctx context.Context, req repositories.GetCarriersByIDsRequest)) *MockCarrierRepository_GetByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repositories.GetCarriersByIDsRequest
		if args[1] != nil {
			arg1 = args[1].(repositories.GetCarriersByIDsRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCarrierRepository_GetByIDs_Call) Return(customers []*carrier.Carrier, err error) *MockCarrierRepository_GetByIDs_Call {
	_c.Call.Return(customers, err)
	return _c
}

func (_c *MockCarrierRepository_GetByIDs_Call) RunAndReturn(run func(ctx context.Context, req repositories.GetCarriersByIDsRequest) ([]*carrier.Carrier, error)) *MockCarrierRepository_GetByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockCarrierRepository
func (_mock *MockCarrierRepository) List(ctx context.Context, req *repositories.ListCarrierRequest) (*pagination.ListResult[*carrier.Carrier], error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *pagination.ListResult[*carrier.Carrier]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *repositories.ListCarrierRequest) (*pagination.ListResult[*carrier.Carrier], error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *repositories.ListCarrierRequest) *pagination.ListResult[*carrier.Carrier]); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pagination.ListResult[*carrier.Carrier])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *repositories.ListCarrierRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCarrierRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockCarrierRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - req *repositories.ListCarrierRequest
func (_e *MockCarrierRepository_Expecter) List(ctx any, req any) *MockCarrierRepository_List_Call {
	return &MockCarrierRepository_List_Call{Call: _e.mock.On("List", ctx, req)}
}

func (_c *MockCarrierRepository_List_Call) Run(run func(ctx context.Context, req *repositories.ListCarrierRequest)) *MockCarrierRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *repositories.ListCarrierRequest
		if args[1] != nil {
			arg1 = args[1].(*repositories.ListCarrierRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCarrierRepository_List_Call) Return(listResult *pagination.ListResult[*carrier.Carrier], err error) *MockCarrierRepository_List_Call {
	_c.Call.Return(listResult, err)
	return _c
}

func (_c *MockCarrierRepository_List_Call) RunAndReturn(run func(ctx context.Context, req *repositories.ListCarrierRequest) (*pagination.ListResult[*carrier.Carrier], error)) *MockCarrierRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListConnection provides a mock function for the type MockCarrierRepository
func (_mock *MockCarrierRepository) ListConnection(ctx context.Context, req *repositories.ListCarrierConnectionRequest) (*pagination.CursorListResult[*carrier.Carrier], error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListConnection")
	}

	var r0 *pagination.CursorListResult[*carrier.Carrier]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *repositories.ListCarrierConnectionRequest) (*pagination.CursorListResult[*carrier.Carrier], error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *repositories.ListCarrierConnectionRequest) *pagination.CursorListResult[*carrier.Carrier]); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pagination.CursorListResult[*carrier.Carrier])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *repositories.ListCarrierConnectionRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCarrierRepository_ListConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListConnection'
type MockCarrierRepository_ListConnection_Call struct {
	*mock.Call
}

// ListConnection is a helper method to define mock.On call
//   - ctx context.Context
//   - req *repositories.ListCarrierConnectionRequest
func (_e *MockCarrierRepository_Expecter) ListConnection(ctx any, req any) *MockCarrierRepository_ListConnection_Call {
	return &MockCarrierRepository_ListConnection_Call{Call: _e.mock.On("ListConnection", ctx, req)}
}

func (_c *MockCarrierRepository_ListConnection_Call) Run(run func(ctx context.Context, req *repositories.ListCarrierConnectionRequest)) *MockCarrierRepository_ListConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *repositories.ListCarrierConnectionRequest
		if args[1] != nil {
			arg1 = args[1].(*repositories.ListCarrierConnectionRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCarrierRepository_ListConnection_Call) Return(cursorListResult *pagination.CursorListResult[*carrier.Carrier], err error) *MockCarrierRepository_ListConnection_Call {
	_c.Call.Return(cursorListResult, err)
	return _c
}

func (_c *MockCarrierRepository_ListConnection_Call) RunAndReturn(run func(ctx context.Context, req *repositories.ListCarrierConnectionRequest) (*pagination.CursorListResult[*carrier.Carrier], error)) *MockCarrierRepository_ListConnection_Call {
	_c.Call.Return(run)
	return _c
}

// SelectOptions provides a mock function for the type MockCarrierRepository
func (_mock *MockCarrierRepository) SelectOptions(ctx context.Context, req *repositories.CarrierSelectOptionsRequest) (*pagination.ListResult[*carrier.Carrier], error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for SelectOptions")
	}

	var r0 *pagination.ListResult[*carrier.Carrier]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *repositories.CarrierSelectOptionsRequest) (*pagination.ListResult[*carrier.Carrier], error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *repositories.CarrierSelectOptionsRequest) *pagination.ListResult[*carrier.Carrier]); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pagination.ListResult[*carrier.Carrier])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *repositories.CarrierSelectOptionsRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCarrierRepository_SelectOptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectOptions'
type MockCarrierRepository_SelectOptions_Call struct {
	*mock.Call
}

// SelectOptions is a helper method to define mock.On call
//   - ctx context.Context
//   - req *repositories.CarrierSelectOptionsRequest
func (_e *MockCarrierRepository_Expecter) SelectOptions(ctx any, req any) *MockCarrierRepository_SelectOptions_Call {
	return &MockCarrierRepository_SelectOptions_Call{Call: _e.mock.On("SelectOptions", ctx, req)}
}

func (_c *MockCarrierRepository_SelectOptions_Call) Run(run func(ctx context.Context, req *repositories.CarrierSelectOptionsRequest)) *MockCarrierRepository_SelectOptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *repositories.CarrierSelectOptionsRequest
		if args[1] != nil {
			arg1 = args[1].(*repositories.CarrierSelectOptionsRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCarrierRepository_SelectOptions_Call) Return(listResult *pagination.ListResult[*carrier.Carrier], err error) *MockCarrierRepository_SelectOptions_Call {
	_c.Call.Return(listResult, err)
	return _c
}

func (_c *MockCarrierRepository_SelectOptions_Call) RunAndReturn(run func(ctx context.Context, req *repositories.CarrierSelectOptionsRequest) (*pagination.ListResult[*carrier.Carrier], error)) *MockCarrierRepository_SelectOptions_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockCarrierRepository
func (_mock *MockCarrierRepository) Update(ctx context.Context, entity *carrier.Carrier) (*carrier.Carrier, error) {
	ret := _mock.Called(ctx, entity)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *carrier.Carrier
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *carrier.Carrier) (*carrier.Carrier, error)); ok {
		return returnFunc(ctx, entity)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *carrier.Carrier) *carrier.Carrier); ok {
		r0 = returnFunc(ctx, entity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*carrier.Carrier)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *carrier.Carrier) error); ok {
		r1 = returnFunc(ctx, entity)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCarrierRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockCarrierRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - entity *carrier.Carrier
func (_e *MockCarrierRepository_Expecter) Update(ctx any, entity any) *MockCarrierRepository_Update_Call {
	return &MockCarrierRepository_Update_Call{Call: _e.mock.On("Update", ctx, entity)}
}

func (_c *MockCarrierRepository_Update_Call) Run(run func(ctx context.Context, entity *carrier.Carrier)) *MockCarrierRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *carrier.Carrier
		if args[1] != nil {
			arg1 = args[1].(*carrier.Carrier)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCarrierRepository_Update_Call) Return(customer1 *carrier.Carrier, err error) *MockCarrierRepository_Update_Call {
	_c.Call.Return(customer1, err)
	return _c
}

func (_c *MockCarrierRepository_Update_Call) RunAndReturn(run func(ctx context.Context, entity *carrier.Carrier) (*carrier.Carrier, error)) *MockCarrierRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
