// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/emoss08/trenova/internal/core/ports/services"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUsageProvider creates a new instance of MockUsageProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsageProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsageProvider {
	mock := &MockUsageProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUsageProvider is an autogenerated mock type for the UsageProvider type
type MockUsageProvider struct {
	mock.Mock
}

type MockUsageProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsageProvider) EXPECT() *MockUsageProvider_Expecter {
	return &MockUsageProvider_Expecter{mock: &_m.Mock}
}

// CheckLimit provides a mock function for the type MockUsageProvider
func (_mock *MockUsageProvider) CheckLimit(context1 context.Context, usageLimitCheckRequest *services.UsageLimitCheckRequest) (*services.UsageLimitCheckResult, error) {
	ret := _mock.Called(context1, usageLimitCheckRequest)

	if len(ret) == 0 {
		panic("no return value specified for CheckLimit")
	}

	var r0 *services.UsageLimitCheckResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *services.UsageLimitCheckRequest) (*services.UsageLimitCheckResult, error)); ok {
		return returnFunc(context1, usageLimitCheckRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *services.UsageLimitCheckRequest) *services.UsageLimitCheckResult); ok {
		r0 = returnFunc(context1, usageLimitCheckRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.UsageLimitCheckResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *services.UsageLimitCheckRequest) error); ok {
		r1 = returnFunc(context1, usageLimitCheckRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsageProvider_CheckLimit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckLimit'
type MockUsageProvider_CheckLimit_Call struct {
	*mock.Call
}

// CheckLimit is a helper method to define mock.On call
//   - context1 context.Context
//   - usageLimitCheckRequest *services.UsageLimitCheckRequest
func (_e *MockUsageProvider_Expecter) CheckLimit(context1 interface{}, usageLimitCheckRequest interface{}) *MockUsageProvider_CheckLimit_Call {
	return &MockUsageProvider_CheckLimit_Call{Call: _e.mock.On("CheckLimit", context1, usageLimitCheckRequest)}
}

func (_c *MockUsageProvider_CheckLimit_Call) Run(run func(context1 context.Context, usageLimitCheckRequest *services.UsageLimitCheckRequest)) *MockUsageProvider_CheckLimit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *services.UsageLimitCheckRequest
		if args[1] != nil {
			arg1 = args[1].(*services.UsageLimitCheckRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsageProvider_CheckLimit_Call) Return(usageLimitCheckResult *services.UsageLimitCheckResult, err error) *MockUsageProvider_CheckLimit_Call {
	_c.Call.Return(usageLimitCheckResult, err)
	return _c
}

func (_c *MockUsageProvider_CheckLimit_Call) RunAndReturn(run func(context1 context.Context, usageLimitCheckRequest *services.UsageLimitCheckRequest) (*services.UsageLimitCheckResult, error)) *MockUsageProvider_CheckLimit_Call {
	_c.Call.Return(run)
	return _c
}

// RecordUsage provides a mock function for the type MockUsageProvider
func (_mock *MockUsageProvider) RecordUsage(context1 context.Context, usageRecordRequest *services.UsageRecordRequest) (*services.UsageRecordResult, error) {
	ret := _mock.Called(context1, usageRecordRequest)

	if len(ret) == 0 {
		panic("no return value specified for RecordUsage")
	}

	var r0 *services.UsageRecordResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *services.UsageRecordRequest) (*services.UsageRecordResult, error)); ok {
		return returnFunc(context1, usageRecordRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *services.UsageRecordRequest) *services.UsageRecordResult); ok {
		r0 = returnFunc(context1, usageRecordRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.UsageRecordResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *services.UsageRecordRequest) error); ok {
		r1 = returnFunc(context1, usageRecordRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsageProvider_RecordUsage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordUsage'
type MockUsageProvider_RecordUsage_Call struct {
	*mock.Call
}

// RecordUsage is a helper method to define mock.On call
//   - context1 context.Context
//   - usageRecordRequest *services.UsageRecordRequest
func (_e *MockUsageProvider_Expecter) RecordUsage(context1 interface{}, usageRecordRequest interface{}) *MockUsageProvider_RecordUsage_Call {
	return &MockUsageProvider_RecordUsage_Call{Call: _e.mock.On("RecordUsage", context1, usageRecordRequest)}
}

func (_c *MockUsageProvider_RecordUsage_Call) Run(run func(context1 context.Context, usageRecordRequest *services.UsageRecordRequest)) *MockUsageProvider_RecordUsage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *services.UsageRecordRequest
		if args[1] != nil {
			arg1 = args[1].(*services.UsageRecordRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsageProvider_RecordUsage_Call) Return(usageRecordResult *services.UsageRecordResult, err error) *MockUsageProvider_RecordUsage_Call {
	_c.Call.Return(usageRecordResult, err)
	return _c
}

func (_c *MockUsageProvider_RecordUsage_Call) RunAndReturn(run func(context1 context.Context, usageRecordRequest *services.UsageRecordRequest) (*services.UsageRecordResult, error)) *MockUsageProvider_RecordUsage_Call {
	_c.Call.Return(run)
	return _c
}
