# # Copyright 2023-2025 Eric Moss
# # Licensed under FSL-1.1-ALv2 (Functional Source License 1.1, Apache 2.0 Future)
# # Full license: https://github.com/emoss08/trenova/blob/main/LICENSE.md

server:
  port: 8084

database:
  dsn: postgres://routing:routing@localhost:5433/routing?sslmode=disable
  auto_migrate: true

redis:
  addr: localhost:6380

kafka:
  brokers:
    - localhost:9092
  producer:
    batch_size: 100
    batch_timeout: 1s
    async: true
    compression: snappy
  consumer:
    group_id: routing-service
    min_bytes: 10240
    max_bytes: 10485760
    max_wait: 500ms
    commit_interval: 1s
  topics:
    route_events: routing.events.route-calculated
    batch_requests: routing.requests.batch-calculate
    osm_updates: routing.data.osm-updates
    restriction_updates: routing.data.restriction-updates
    cache_invalidation: routing.cache.invalidation