-- Modify "business_units" table
ALTER TABLE "business_units" ALTER COLUMN "city" DROP NOT NULL, ALTER COLUMN "state" DROP NOT NULL, ALTER COLUMN "country" DROP NOT NULL, ALTER COLUMN "postal_code" DROP NOT NULL, ALTER COLUMN "tax_id" DROP NOT NULL, ALTER COLUMN "subscription_plan" DROP NOT NULL, ALTER COLUMN "legal_name" DROP NOT NULL;
-- Modify "organizations" table
ALTER TABLE "organizations" ADD COLUMN "organization_dispatch_control" uuid NOT NULL;
-- Create "dispatch_controls" table
CREATE TABLE "dispatch_controls" ("id" uuid NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "record_service_incident" character varying NOT NULL DEFAULT 'Never', "deadhead_target" double precision NOT NULL DEFAULT 0, "max_shipment_weight_limit" bigint NOT NULL DEFAULT 80000, "grace_period" smallint NOT NULL DEFAULT 0, "enforce_worker_assign" boolean NOT NULL DEFAULT true, "trailer_continuity" boolean NOT NULL DEFAULT false, "dupe_trailer_check" boolean NOT NULL DEFAULT false, "maintenance_compliance" boolean NOT NULL DEFAULT true, "regulatory_check" boolean NOT NULL DEFAULT false, "prev_shipment_on_hold" boolean NOT NULL DEFAULT false, "worker_time_away_restriction" boolean NOT NULL DEFAULT true, "tractor_worker_fleet_constraint" boolean NOT NULL DEFAULT false, "organization_id" uuid NOT NULL, "business_unit_id" uuid NOT NULL, PRIMARY KEY ("id"));
-- Modify "organizations" table
ALTER TABLE "organizations" ADD CONSTRAINT "organizations_dispatch_controls_dispatch_control" FOREIGN KEY ("organization_dispatch_control") REFERENCES "dispatch_controls" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
-- Modify "dispatch_controls" table
ALTER TABLE "dispatch_controls" ADD CONSTRAINT "dispatch_controls_business_units_business_unit" FOREIGN KEY ("business_unit_id") REFERENCES "business_units" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, ADD CONSTRAINT "dispatch_controls_organizations_organization" FOREIGN KEY ("organization_id") REFERENCES "organizations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
