package handlers

import (
	"github.com/emoss08/trenova/internal/api"
	"github.com/gofiber/fiber/v2"
)

// AttachAllRoutes attaches all the routes to the Fiber instance.
func AttachAllRoutes(s *api.Server, api fiber.Router) {
	NewAccessorialChargeHandler(s).RegisterRoutes(api)
	NewOrganizationHandler(s).RegisterRoutes(api)
	NewAccountingControlHandler(s).RegisterRoutes(api)
	NewDispatchControlHandler(s).RegisterRoutes(api)
	NewShipmentControlHandler(s).RegisterRoutes(api)
	NewBillingControlHandler(s).RegisterRoutes(api)
	NewInvoiceControlHandler(s).RegisterRoutes(api)
	NewRouteControlHandler(s).RegisterRoutes(api)
	NewFeasibilityToolControlHandler(s).RegisterRoutes(api)
	NewEmailControlHandler(s).RegisterRoutes(api)
	NewUserHandler(s).RegisterRoutes(api)
	NewUserFavoriteHandler(s).RegisterRoutes(api)
	NewHazardousMaterialSegregationHandler(s).RegisterRoutes(api)
	NewEmailProfileHandler(s).RegisterRoutes(api)
	NewTableChangeAlertHandler(s).RegisterRoutes(api)
	NewGoogleAPIHandler(s).RegisterRoutes(api)
	NewRevenueCodeHandler(s).RegisterRoutes(api)
	NewWorkerHandler(s).RegisterRoutes(api)
	NewChargeTypeHandler(s).RegisterRoutes(api)
	NewCommentTypeService(s).RegisterRoutes(api)
	NewCommodityHandler(s).RegisterRoutes(api)
	NewCustomerHandler(s).RegisterRoutes(api)
	NewDelayCodeHandler(s).RegisterRoutes(api)
	NewDivisionCodeHandler(s).RegisterRoutes(api)
	NewDocumentClassificationHandler(s).RegisterRoutes(api)
	NewEquipmentManufacturerHandler(s).RegisterRoutes(api)
	NewEquipmentTypeHandler(s).RegisterRoutes(api)
	NewFleetCodeHandler(s).RegisterRoutes(api)
	NewGeneralLedgerAccountHandler(s).RegisterRoutes(api)
	NewTagHandler(s).RegisterRoutes(api)
	NewHazardousMaterialHandler(s).RegisterRoutes(api)
	NewLocationHandler(s).RegisterRoutes(api)
	NewLocationCategoryHandler(s).RegisterRoutes(api)
	NewFeatureFlagHandler(s).RegisterRoutes(api)
	NewQualifierCodeHandler(s).RegisterRoutes(api)
	NewReasonCodeHandler(s).RegisterRoutes(api)
	NewServiceTypeHandler(s).RegisterRoutes(api)
	NewShipmentTypeHandler(s).RegisterRoutes(api)
	NewUSStateHandler(s).RegisterRoutes(api)
	NewTractorHandler(s).RegisterRoutes(api)
	NewTrailerHandler(s).RegisterRoutes(api)
	NewReportHandler(s).RegisterRoutes(api)
	NewUserNotificationHandler(s).RegisterRoutes(api)
	NewPermissionHandler(s).RegisterRoutes(api)
	NewRoleHandler(s).RegisterRoutes(api)
	NewResourceHandler(s).RegisterRoutes(api)
}
