package platformcatalog

const (
	ProductTMS                  = ProductKey("tms")
	ProductWorkforce            = ProductKey("workforce")
	ProductDocumentIntelligence = ProductKey("document_intelligence")
	ProductIntegrations         = ProductKey("integrations")
	ProductAnalytics            = ProductKey("analytics")
	ProductPlatform             = ProductKey("platform")
)

const (
	FeatureCoreTMS                 = FeatureKey("tms.core")
	FeatureDispatch                = FeatureKey("tms.dispatch")
	FeatureBilling                 = FeatureKey("tms.billing")
	FeatureAccounting              = FeatureKey("tms.accounting")
	FeatureFleetMaintenance        = FeatureKey("tms.fleet")
	FeatureSettlement              = FeatureKey("tms.settlement")
	FeatureDriverPortal            = FeatureKey("tms.driver_portal")
	FeatureWorkforceCore           = FeatureKey("workforce.core")
	FeatureWorkforceCompliance     = FeatureKey("workforce.compliance")
	FeatureWorkforceTimeOff        = FeatureKey("workforce.time_off")
	FeatureWorkforceTimeTracking   = FeatureKey("workforce.time_tracking")
	FeatureWorkforceTalent         = FeatureKey("workforce.talent")
	FeatureWorkforceSafety         = FeatureKey("workforce.safety")
	FeatureWorkforceBenefits       = FeatureKey("workforce.benefits")
	FeatureWorkforceSelfService    = FeatureKey("workforce.self_service")
	FeatureDocumentManagement      = FeatureKey("document_management")
	FeatureDocumentIntelligence    = FeatureKey("document_intelligence.ai")
	FeatureGlobalSearch            = FeatureKey("platform.global_search")
	FeatureAnalytics               = FeatureKey("analytics.workspace")
	FeatureAPIKeys                 = FeatureKey("platform.api_keys")
	FeatureTableChangeAlerts       = FeatureKey("platform.table_change_alerts")
	FeatureAgentAutomation         = FeatureKey("platform.agent_automation")
	FeatureAdministration          = FeatureKey("platform.administration")
	FeatureEDIIntegration          = FeatureKey("integrations.edi")
	FeatureExchangeRateIntegration = FeatureKey("integrations.exchange_rates")
	FeatureSamsaraIntegration      = FeatureKey("integrations.samsara")
	FeatureGoogleMapsIntegration   = FeatureKey("integrations.google_maps")
	FeatureRealtimeNotifications   = FeatureKey("platform.realtime_notifications")
)

const (
	MeterAPIRequests                = MeterKey("api.requests")
	MeterDocumentUploads            = MeterKey("documents.uploads")
	MeterDocumentAIClassifications  = MeterKey("document_intelligence.classifications")
	MeterDocumentAIExtractions      = MeterKey("document_intelligence.extractions")
	MeterGlobalSearchQueries        = MeterKey("platform.search_queries")
	MeterTableChangeEvents          = MeterKey("platform.table_change_events")
	MeterIntegrationSyncRuns        = MeterKey("integrations.sync_runs")
	MeterAnalyticsQueries           = MeterKey("analytics.queries")
	MeterWorkforceManagedWorkers    = MeterKey("workforce.managed_workers")
	MeterWorkforceComplianceScreens = MeterKey("workforce.compliance_screenings")
)
