# Generated by Django 4.1.5 on 2023-01-07 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0003_alter_revenuecode_expense_account_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="divisioncode",
            name="ap_account",
            field=models.ForeignKey(
                blank=True,
                help_text="The accounts payable account associated with the division code.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="division_code_ap_account",
                to="accounting.generalledgeraccount",
                verbose_name="Accounts Payable Account",
            ),
        ),
        migrations.AlterField(
            model_name="divisioncode",
            name="cash_account",
            field=models.ForeignKey(
                blank=True,
                help_text="The cash account associated with the division code.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="division_code_cash_account",
                to="accounting.generalledgeraccount",
                verbose_name="Cash Account",
            ),
        ),
        migrations.AlterField(
            model_name="divisioncode",
            name="expense_account",
            field=models.ForeignKey(
                blank=True,
                help_text="The expense account associated with the division code.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="division_code_expense_account",
                to="accounting.generalledgeraccount",
                verbose_name="Expense Account",
            ),
        ),
    ]
