package api

import (
	"github.com/emoss08/trenova/internal/api/handlers/accessorialcharge"
	"github.com/emoss08/trenova/internal/api/handlers/analytics"
	"github.com/emoss08/trenova/internal/api/handlers/assignment"
	"github.com/emoss08/trenova/internal/api/handlers/audit"
	"github.com/emoss08/trenova/internal/api/handlers/auth"
	"github.com/emoss08/trenova/internal/api/handlers/backup"
	"github.com/emoss08/trenova/internal/api/handlers/billingcontrol"
	"github.com/emoss08/trenova/internal/api/handlers/billingqueue"
	"github.com/emoss08/trenova/internal/api/handlers/commodity"
	"github.com/emoss08/trenova/internal/api/handlers/consolidation"
	"github.com/emoss08/trenova/internal/api/handlers/customer"
	"github.com/emoss08/trenova/internal/api/handlers/dedicatedlane"
	"github.com/emoss08/trenova/internal/api/handlers/dedicatedlanesuggestion"
	"github.com/emoss08/trenova/internal/api/handlers/document"
	"github.com/emoss08/trenova/internal/api/handlers/documentqualityconfig"
	"github.com/emoss08/trenova/internal/api/handlers/documenttype"
	"github.com/emoss08/trenova/internal/api/handlers/equipmentmanufacturer"
	"github.com/emoss08/trenova/internal/api/handlers/equipmenttype"
	"github.com/emoss08/trenova/internal/api/handlers/favorite"
	"github.com/emoss08/trenova/internal/api/handlers/fleetcode"
	"github.com/emoss08/trenova/internal/api/handlers/hazardousmaterial"
	"github.com/emoss08/trenova/internal/api/handlers/hazmatsegregationrule"
	"github.com/emoss08/trenova/internal/api/handlers/integration"
	"github.com/emoss08/trenova/internal/api/handlers/location"
	"github.com/emoss08/trenova/internal/api/handlers/locationcategory"
	"github.com/emoss08/trenova/internal/api/handlers/notification"
	"github.com/emoss08/trenova/internal/api/handlers/notificationpreference"
	"github.com/emoss08/trenova/internal/api/handlers/organization"
	"github.com/emoss08/trenova/internal/api/handlers/patternconfig"
	"github.com/emoss08/trenova/internal/api/handlers/permission"
	"github.com/emoss08/trenova/internal/api/handlers/reporting"
	"github.com/emoss08/trenova/internal/api/handlers/resourceeditor"
	"github.com/emoss08/trenova/internal/api/handlers/role"
	"github.com/emoss08/trenova/internal/api/handlers/routing"
	"github.com/emoss08/trenova/internal/api/handlers/servicetype"
	"github.com/emoss08/trenova/internal/api/handlers/session"
	"github.com/emoss08/trenova/internal/api/handlers/shipment"
	"github.com/emoss08/trenova/internal/api/handlers/shipmentcontrol"
	"github.com/emoss08/trenova/internal/api/handlers/shipmentmove"
	"github.com/emoss08/trenova/internal/api/handlers/shipmenttype"
	"github.com/emoss08/trenova/internal/api/handlers/stop"
	"github.com/emoss08/trenova/internal/api/handlers/tableconfiguration"
	"github.com/emoss08/trenova/internal/api/handlers/tractor"
	"github.com/emoss08/trenova/internal/api/handlers/trailer"
	"github.com/emoss08/trenova/internal/api/handlers/user"
	"github.com/emoss08/trenova/internal/api/handlers/usstate"
	"github.com/emoss08/trenova/internal/api/handlers/websocket"
	"github.com/emoss08/trenova/internal/api/handlers/worker"
	"github.com/emoss08/trenova/internal/api/handlers"
	"github.com/emoss08/trenova/internal/pkg/validator"
	"go.uber.org/fx"
)

var HandlersModule = fx.Module("api.Handlers", fx.Provide(
	validator.NewErrorHandler,
	auth.NewHandler,
	analytics.NewHandler,
	organization.NewHandler,
	usstate.NewHandler,
	user.NewHandler,
	session.NewHandler,
	worker.NewHandler,
	tableconfiguration.NewHandler,
	fleetcode.NewHandler,
	documentqualityconfig.NewHandler,
	equipmenttype.NewHandler,
	equipmentmanufacturer.NewHandler,
	shipmenttype.NewHandler,
	servicetype.NewHandler,
	hazardousmaterial.NewHandler,
	commodity.NewHandler,
	locationcategory.NewHandler,
	reporting.NewHandler,
	location.NewHandler,
	tractor.NewHandler,
	trailer.NewHandler,
	customer.NewHandler,
	consolidation.NewHandler,
	shipment.NewHandler,
	routing.NewHandler,
	assignment.NewHandler,
	shipmentmove.NewHandler,
	stop.NewHandler,
	shipmentcontrol.NewHandler,
	billingcontrol.NewHandler,
	backup.NewHandler,
	audit.NewHandler,
	hazmatsegregationrule.NewHandler,
	accessorialcharge.NewHandler,
	document.NewHandler,
	documenttype.NewHandler,
	integration.NewHandler,
	billingqueue.NewHandler,
	resourceeditor.NewHandler,
	favorite.NewHandler,
	permission.NewHandler,
	role.NewHandler,
	dedicatedlane.NewHandler,
	dedicatedlanesuggestion.NewHandler,
	patternconfig.NewHandler,
	websocket.NewHandler,
	notificationpreference.NewHandler,
	notification.NewHandler,
	handlers.NewMetricsHandler,
))
