enum PeriodType {
  Month
  Quarter
  Week
  Adjusting
}

enum FiscalPeriodStatus {
  Inactive
  Open
  Locked
  Closed
  PermanentlyClosed
}

type FiscalPeriod {
  id: ID!
  businessUnitId: ID!
  organizationId: ID!
  fiscalYearId: ID!
  periodNumber: Int!
  periodType: PeriodType!
  status: FiscalPeriodStatus!
  name: String!
  startDate: Timestamp!
  endDate: Timestamp!
  isAdjusting: Boolean!
  allowAdjustingEntries: Boolean!
  adjustmentDeadline: Timestamp
  lockedAt: Timestamp
  closedAt: Timestamp
  version: Int!
  createdAt: Timestamp!
  updatedAt: Timestamp!
}
