enum SelectOptionResource {
  ACCESSORIAL_CHARGE
  ACCOUNT_TYPE
  CARRIER
  COMMODITY
  CUSTOMER
  DETENTION_POLICY
  DISTANCE_PROFILE
  DOCUMENT_TYPE
  EDI_CONNECTION
  EDI_TRANSFER
  EQUIPMENT_MANUFACTURER
  EQUIPMENT_TYPE
  FLEET_CODE
  FORMULA_TEMPLATE
  FISCAL_PERIOD
  FISCAL_YEAR
  FUEL_INDEX
  FUEL_SURCHARGE_PROGRAM
  GL_ACCOUNT
  HAZARDOUS_MATERIAL
  LOCATION
  LOCATION_CATEGORY
  ORDER
  ORGANIZATION
  RATE_AGREEMENT
  RATE_MATRIX
  RATE_ZONE
  ROLE
  SERVICE_FAILURE_REASON_CODE
  SERVICE_TYPE
  SHIPMENT
  SHIPMENT_TYPE
  TRACTOR
  TRAILER
  US_STATE
  USER
  WORKER
  EDI_COMMUNICATION_PROFILE
  EDI_DOCUMENT_TYPE
  EDI_MAPPING_PROFILE
  EDI_PARTNER
  EDI_PARTNER_DOCUMENT_PROFILE
  EDI_TEMPLATE
  EMAIL_PROFILE
}

input SelectOptionsInput {
  resource: SelectOptionResource!
  query: String
  first: Int = 20
  offset: Int = 0
  ids: [ID!]
  filters: JSON
}

type SelectOption {
  id: ID!
  label: String!
  description: String
  meta: JSON
}

type SelectOptionEdge {
  node: SelectOption!
  cursor: String!
}

type SelectOptionConnection {
  edges: [SelectOptionEdge!]!
  pageInfo: PageInfo!
  totalCount: Int
}

extend type Query {
  selectOptions(input: SelectOptionsInput!): SelectOptionConnection!
}
