package registry

import (
	"github.com/emoss08/trenova/internal/core/domain/accessorialcharge"
	"github.com/emoss08/trenova/internal/core/domain/billing"
	"github.com/emoss08/trenova/internal/core/domain/businessunit"
	"github.com/emoss08/trenova/internal/core/domain/commodity"
	"github.com/emoss08/trenova/internal/core/domain/compliance"
	"github.com/emoss08/trenova/internal/core/domain/consolidation"
	"github.com/emoss08/trenova/internal/core/domain/customer"
	"github.com/emoss08/trenova/internal/core/domain/dedicatedlane"
	"github.com/emoss08/trenova/internal/core/domain/documentqualityconfig"
	"github.com/emoss08/trenova/internal/core/domain/documentqualityfeedback"
	"github.com/emoss08/trenova/internal/core/domain/equipmentmanufacturer"
	"github.com/emoss08/trenova/internal/core/domain/equipmenttype"
	"github.com/emoss08/trenova/internal/core/domain/fleetcode"
	"github.com/emoss08/trenova/internal/core/domain/hazardousmaterial"
	"github.com/emoss08/trenova/internal/core/domain/hazmatsegregationrule"
	"github.com/emoss08/trenova/internal/core/domain/integration"
	"github.com/emoss08/trenova/internal/core/domain/location"
	"github.com/emoss08/trenova/internal/core/domain/organization"
	"github.com/emoss08/trenova/internal/core/domain/pagefavorite"
	"github.com/emoss08/trenova/internal/core/domain/pcmilerconfiguration"
	"github.com/emoss08/trenova/internal/core/domain/permission"
	"github.com/emoss08/trenova/internal/core/domain/pretrainedmodels"
	"github.com/emoss08/trenova/internal/core/domain/pronumber"
	"github.com/emoss08/trenova/internal/core/domain/resource"
	"github.com/emoss08/trenova/internal/core/domain/servicetype"
	"github.com/emoss08/trenova/internal/core/domain/session"
	"github.com/emoss08/trenova/internal/core/domain/shipment"
	"github.com/emoss08/trenova/internal/core/domain/shipmenttype"
	"github.com/emoss08/trenova/internal/core/domain/tableconfiguration"
	"github.com/emoss08/trenova/internal/core/domain/tractor"
	"github.com/emoss08/trenova/internal/core/domain/trailer"
	"github.com/emoss08/trenova/internal/core/domain/user"
	"github.com/emoss08/trenova/internal/core/domain/usstate"
	"github.com/emoss08/trenova/internal/core/domain/worker"
)

func RegisterEntities() []any {
	return []any{
		&usstate.UsState{},
		&businessunit.BusinessUnit{},
		&organization.Organization{},
		&shipment.ShipmentControl{},
		&billing.BillingControl{},
		&resource.ResourceDefinition{},
		&session.Event{},
		&session.Session{},
		&permission.RolePermission{},
		&permission.Permission{},
		&permission.Role{},
		&user.UserRole{},
		&user.UserOrganization{},
		&user.User{},
		&worker.WorkerPTO{},
		&worker.Worker{},
		&worker.WorkerProfile{},
		&compliance.HazmatExpiration{},
		&tableconfiguration.ConfigurationShare{},
		&tableconfiguration.Configuration{},
		&fleetcode.FleetCode{},
		&documentqualityconfig.DocumentQualityConfig{},
		&documentqualityfeedback.DocumentQualityFeedback{},
		&pretrainedmodels.PretrainedModel{},
		&equipmenttype.EquipmentType{},
		&equipmentmanufacturer.EquipmentManufacturer{},
		&shipmenttype.ShipmentType{},
		&servicetype.ServiceType{},
		&hazardousmaterial.HazardousMaterial{},
		&commodity.Commodity{},
		&customer.CustomerEmailProfile{},
		&customer.BillingProfileDocumentType{},
		&customer.BillingProfile{},
		&customer.Customer{},
		&tractor.Tractor{},
		&trailer.Trailer{},
		&location.LocationCategory{},
		&location.Location{},
		&shipment.Stop{},
		&shipment.AdditionalCharge{},
		&shipment.ShipmentCommodity{},
		&shipment.ShipmentMove{},
		&shipment.Shipment{},
		&pcmilerconfiguration.PCMilerConfiguration{},
		&pronumber.Sequence{},
		&hazmatsegregationrule.HazmatSegregationRule{},
		&billing.DocumentType{},
		&accessorialcharge.AccessorialCharge{},
		&integration.Integration{},
		&pagefavorite.PageFavorite{},
		&dedicatedlane.DedicatedLane{},
		&dedicatedlane.PatternConfig{},
		&dedicatedlane.DedicatedLaneSuggestion{},
		&consolidation.ConsolidationSettings{},
	}
}
