# Generated by Django 4.1.5 on 2023-01-13 21:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0003_alter_order_commodity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reasoncode",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Is Active", verbose_name="Is Active"
            ),
        ),
    ]
