# Generated by Django 4.1.3 on 2022-11-16 20:12

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0022_alter_order_freight_charge_amount_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stop",
            options={
                "ordering": ["movement", "sequence"],
                "verbose_name": "Stop",
                "verbose_name_plural": "Stops",
            },
        ),
        migrations.AlterField(
            model_name="commodity",
            name="unit_of_measure",
            field=core.models.ChoiceField(
                blank=True,
                choices=[
                    ("PALLET", "Pallet"),
                    ("TOTE", "Tote"),
                    ("DRUM", "Drum"),
                    ("CYLINDER", "Cylinder"),
                    ("CASE", "Case"),
                    ("AMPULE", "Ampule"),
                    ("BAG", "Bag"),
                    ("BOTTLE", "Bottle"),
                    ("PAIL", "Pail"),
                    ("PIECES", "Pieces"),
                    ("ISO_TANK", "ISO Tank"),
                ],
                help_text="Unit of Measure of the Commodity",
                max_length=8,
                verbose_name="Unit of Measure",
            ),
        ),
    ]
