# Generated by Django 4.1.3 on 2022-11-24 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0050_remove_additionalcharge_charge_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="additionalcharge",
            name="charge_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Charge Amount",
                max_digits=10,
                null=True,
                verbose_name="Charge Amount",
            ),
        ),
    ]
