# Generated by Django 4.1.3 on 2022-11-25 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commodities", "0001_initial"),
        ("order", "0052_alter_ordercomment_comment_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hazardousmaterial",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="movement",
            name="equipment",
        ),
        migrations.RemoveField(
            model_name="movement",
            name="order",
        ),
        migrations.RemoveField(
            model_name="movement",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="movement",
            name="primary_worker",
        ),
        migrations.RemoveField(
            model_name="movement",
            name="secondary_worker",
        ),
        migrations.RemoveField(
            model_name="qualifiercode",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="serviceincident",
            name="delay_code",
        ),
        migrations.RemoveField(
            model_name="serviceincident",
            name="movement",
        ),
        migrations.RemoveField(
            model_name="serviceincident",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="serviceincident",
            name="stop",
        ),
        migrations.RemoveField(
            model_name="stop",
            name="location",
        ),
        migrations.RemoveField(
            model_name="stop",
            name="movement",
        ),
        migrations.RemoveField(
            model_name="stop",
            name="organization",
        ),
        migrations.AlterField(
            model_name="order",
            name="commodity",
            field=models.ForeignKey(
                help_text="Commodity",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                related_query_name="order",
                to="commodities.commodity",
                verbose_name="Commodity",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="hazmat_id",
            field=models.ForeignKey(
                blank=True,
                help_text="Hazardous Class",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                related_query_name="order",
                to="commodities.hazardousmaterial",
                verbose_name="Hazardous Class",
            ),
        ),
        migrations.DeleteModel(
            name="Commodity",
        ),
        migrations.DeleteModel(
            name="HazardousMaterial",
        ),
        migrations.DeleteModel(
            name="Movement",
        ),
        migrations.DeleteModel(
            name="QualifierCode",
        ),
        migrations.DeleteModel(
            name="ServiceIncident",
        ),
        migrations.DeleteModel(
            name="Stop",
        ),
    ]
